### ISSUE TITLE
Feature request: Make `ollama run` also launch `serve` as child process

### ISSUE THREAD

**Issue by Anrock** [jmorganca/ollama#1004]
I'm using ollama mostly for fun and occasional queries - couple of times per day.

Right now one have to run `ollama serve` in one terminal and then run `ollama run` in another terminal which is a bit clunky.
Another option is to constantly have `ollama serve` running in the background however running a model consumes substantial amount of RAM and VRAM. 

Would it be possible to make `ollama run` also run a `serve` as child process and shut it down when user exits from the prompt if some option is given to `run`?

**Comment by wrapss** [comment]
You can create a service to automatically start ollama as described in the Manual install instructions.

**Comment by Anrock** [comment]
@wrapss I know. As I've mentioned in second paragraph it will constanly occupy substantial amount of resources when running.

**Comment by Anrock** [comment]
Oh, I see. As soon as I exit prompt the server resource consumption drops to almost zero.
