### ISSUE TITLE
Message repeated infinitly with last version of Zephyr and Ollama 0.1.8

### ISSUE THREAD

**Issue by igorschlum** [jmorganca/ollama#1008]
I installed Ollama 0.1.8 and ran Zephyr. I asked in French how many languages Zephyr could translate, and Zephyr answered me with the same paragraph repeatedly:

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

(base) igor@macIgor ~ % ollama run zephyr
pulling manifest
pulling 0e655574a746... 100% |███████████████████████████| (4.1/4.1 GB, 4.1 MB/s)            
pulling a96be15318d6... 100% |██████████████████████████████████| (101/101 B, 46 B/s)        
pulling fe135e2a970c... 100% |████████████████████████████████████| (97/97 B, 40 B/s)        
pulling 9f6045c34448... 100% |█████████████████████████████████| (381/381 B, 167 B/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
>>> tu sais traduire de quelle langue vers quelle langue ?
Je ne peux pas déterminer de quelle langue vous parlez actuellement ou vers quel langage
vous souhaitez traduire. Veuillez fournir plus d'informations pour que j' puisse vous 
aider correctement. Pouvez-vous préciser la langue dont vous disiez «tu» au début de 
votre message, ainsi que la langue vers laquelle vous souhaitez traduire ?

>>> je voudrai que tu me donnes la liste des langues dans lesquelles je peux t'écrire ?
Bien sûr! Je peux vous écrire dans de nombreuses langues. Voici une liste de 
quelques-unes : anglais, français, allemand, espagnol, portugais (brésilien ou
européen), italien, néerlandais, polonais, roumain et russe. Lettrons nous sommes
également en mesure de fournir des traductions dans une variété d'autres langues sur 
demande. Quelle langue souhaitez-vous que j' utilise pour vous répondre ?

>>> j'aimerai que tu me donnes la liste exaustives des langues dans lesquelles je peux t'écrir
... e et pas uniquement une liste de quelques langues en exemple.
Bien sûr, voici une liste exhaustive des principales langues que je peux utiliser pour 
vous écrire :

- Afrikaans (Afrique du Sud)
- Albanais (Albanie)
- Amharique (Éthiopie)
- Arabe (variétés régionales, par exemple : arabe egyptien, arabe sahraoui, arabe 
marocain...)
- Arménien (Arménie)
- Azerbaïdjan (Azerbaïdjan)
- Bashi (Taiwan)
- Belarussien (Biélorussie)
- Bengali (Bangladesh)
- Bosnien (Bosnie-Herzégovine)
- Breton (France)
- Bulgare (Bulgarie)
- Catalan (Espagne, Andorre...)
- Cebuano (Philippines)
- Chinois (de nombreuses variétés régionales, par exemple : cantonais, mandarin 
standard, hakka...)
- Corsicain (Corse, France)
- Croate (Croatie)
- Cymrique (Pays de Galles, Royaume-Uni)
- Dari (Afghanistan)
- Dinka (Sudan du Sud)
- Dzongkha (Bhoutan)
- Eestonien (Estonie)
- Élan (Papouasie-Nouvelle-Guinée)
- Emilien (Québec, Canada)
- English Creole (Caribe, Afrique, Asie...)
- Esperanto (International)
- Estonien (Estonie)
- Farsi (Ir Iran)
- Filipino (Philippines)
- Finnois (Finlande)
- Franco-provençal (France)
- Frison (Pays-Bas, Allemagne...)
- Galicien (Espagne)
- Géorgien (Géorgie)
- Germain (de nombreuses variétés régionales, par exemple : allemand standard, bavarois,
souabe...)
- Guarani (Paraguay)
- Gujarati (Inde)
- Hausa (Nigeria, Tchad...)
- Hébreu (Israël)
- Hindi (Inde)
- Histonien (Pays-Bas)
- Hongrois (Hongrie)
- Icelandais (Islande)
- Idéophone camerounais (Cameroun)
- Indo-portugais (Goa, India...)
- Indonesien (Indonésie)
- Irlandais (Irlande)
- Islandais (Islande)
- Italien (de nombreuses variétés régionales, par exemple : italien standard, sicilien, 
napolitain...)
- Japonais (Japon)
- Javanais (Indonésie)
- Kazakh (Kazakhstan)
- Kirghize (Kirghizistan)
- Kinyarwanda (Rwanda)
- Kurdish sorani (Irak)
- Kurde sorani (Syrie, Irak...)
- Lakota (États-Unis)
- Lamba (Zambie)
- Languedocien (France)
- Laothian (Laos)
- Letton (Lettonie)
- Limburg (Pays-Bas, Allemagne...)
- Litouanien (Lituanie)
- Luxembourgeois (Luxembourg)
- Maori (Nouvelle-Zélande)
- Malais (Malaisie)
- Mandarin (Chine)
- Marathi (Inde)
- Māori (Nouvelle-Zélande)
- Maya q'eqchi' (Guatemala)
- Macedonien (Macédoine du Nord)
- Malgache (Madagascar)
- Mandarin (Chine)
- Manchou (Chine)
- Marathi (Inde)
- Marathi Devanāgarī (Inde)
- Moldave (Moldavie, Roumanie...)
- Mongol (Mongolie)
- Monténégrin (Monténégro)
- Náhuatl (Mexique)
- Navajo (États-Unis)
- Neapolitan (Italie)
- Ndebele (Afrique du Sud, Swaziland...)
- Norvégien (Norvège)
- Nyawá (Congo)
- Occitan (France)
- Ojibwe (États-Unis)
- Oromo (Éthiopie)
- Palu' (Papouasie-Nouvelle-Guinée)
- Papou (Papouasie-Nouvelle-Guinée)
- Paraguayan Guarani (Paraguay)
- Persan (Iran, Afghanistan...)
- Polonais (Pologne)
- Pontique (Grèce)
- Portuguese (Portugal, Brésil...)
- Q'eqchi' (Guatemala)
- Quechua (Andes)
- Rarotongan (Îles Cook)
- Romani (International)
- Roumain (Roumanie)
- Russien (Russie)
- Samoan (Samoa)
- Sango (Centrafrique)
- Sarawak malais (Malaisie)
- Serbe (Serbie)
- Shona (Zimbabwe)
- Slovène (Slovénie)
- Slovaque (Slovaquie)
- Somali (Somalie)
- Soninke (Mauritanie, Mali...)
- Sorani kurde (Irak)
- Spanish (Espagne, Pérou...)
- Sri Lanka Tamil (Sri Lanka)
- Suazilandswati (Swaziland)
- Swahili (Afrique orientale...)
- Swazi (Swaziland)
- Taïtiien (Polynésie française)
- Tat (Kirghizistan, Kazakhstan...)
- Tétum (Timor-Leste)
- Thaï (Thaïlande)
- Tigrinya (Érythrée)
- Timorese (Timor-Leste)
- Tlingit (Alaska)
- Tokelauan (Tokelau)
- Tokpana (Papouasie-Nouvelle-Guinée)
- Tongarevena (Tahiti)
- Tshiluba (Congo, Angola...)
- Tsonga (Afrique du Sud)
- Turkish (Turquie)
- Ukrainien (Ukraine)
- Uzbek (Ouzbékistan)
- Venda (Afrique du Sud)
- Vietnamien (Viêt Nam)
- Walser (Suisse, Allemagne...)
- Wallisien (Wallis et Futuna)
- Waray (Philippines)
- Welsh (Pays de Galles, Royaume-Uni)
- Wolof (Sénégal, Gambie...)
- Yoruba (Nigeria)
- Zapotec de Oaxaca (Mexique)
- Zhuang (Chine)
- Zulu (Afrique du Sud)
- Zwela (Swaziland)

Pour les langues qui ne sont pas indiquées ici, veuillez contacter le service clientèle.
Nous essayerons de vous fournir un traducteur qualifié dans cette langue pour vous aider
à traiter votre document.

Note : Cette liste n'est pas exhaustive et nous pouvons toujours essayer d'effectuer 
votre traduction même si votre langue n'apparaît pas sur cette liste, tant que le texte 
est facilement lisible par un humain et qu'il ne contient pas de caractères spéciaux ou 
de codes particuliers. Si vous souhaitez obtenir un devis pour une traduction dans une 
langue non indiquée ici, veuillez contacter le service clientèle pour en savoir plus sur
la disponibilité d'un traducteur qualifié pour cette langue. Nous serons heureux de vous
fournir tout l'assistant que vous avez besoin, à condition que votre texte soit 
facilement lisible par un humain et qu'il ne contienne pas de caractères spéciaux ou de 
codes particuliers.

Note : La disponibilité des traducteurs qualifiés dans chaque langue peut varier selon 
la demande actuelle, donc il est préférable de contacter le service clientèle pour 
obtenir un devis et connaître l'état actuel de la disponibilité d'un traducteur qualifié
pour votre langue préférée.

Note : Pour les langues très rares ou exotiques, nous recommandons de contacter le 
service clientèle avant de soumettre votre demande afin qu'on puisse vous fournir un 
devis et déterminer la disponibilité d'un traducteur qualifié pour cette langue.

Note : Les prix peuvent varier selon la complexité du texte, la longueur de celui-ci et 
la rareté de la langue. Pour obtenir un devis précis pour votre demande, veuillez 
contacter le service clientèle ou utilisez notre outil en ligne pour obtenir une 
estimation préliminaire.

Note : Les prix indiqués sont estimatifs et peuvent varier selon la complexité du texte,
sa longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs peuvent varier selon la complexité du texte, sa longueur et la 
disponibilité des traducteurs qualifiés dans la langue demandée. Pour obtenir un devis 
précis pour votre demande, veuillez contacter le service clientèle ou utilisez notre 
outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs indiqués sont estimatifs et peuvent varier selon la complexité du 
texte, sa longueur et la disponibilité des traducteurs qualifiés dans la langue
demandée. Pour connaître le coût exact de votre demande, veuillez contacter le service 
clientèle ou utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont indicatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les prix sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

Note : Les tarifs sont approximatifs et peuvent varier selon la complexité du texte, sa 
longueur et la disponibilité des traducteurs qualifiés dans la langue demandée. Pour 
connaître le coût exact de votre demande, veuillez contacter le service clientèle ou 
utilisez notre outil en ligne pour obtenir une estimation préliminaire.

**Comment by igorschlum** [comment]
I'm on a macBook Pro with 32Go of memory and still macOS 13.5.2

**Comment by SebastianMpl** [comment]
I  found similar problem in v 0.1.7, but the model was created with Modelfile based on theblock gguf file . I didn't noticed any issues with the models downloaded from the repo.

//Created from model file and gguf file from the block. Had to stop it manually.
~/Pobrane> ./ollama-linux-amd64 run openchat3.5_q4km "What is electricity. Be short and concise"
      

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It is a form of energy that can be generated from 
various sources, including fossil fuels, nuclear power, and renewable 
resources like solar or wind power. Electricity has numerous applications in 
our daily lives, such as lighting our homes, powering appliances, and 
enabling communication devices.

Electricity is the flow of electrons through a conductor, such as a wire. It 
can be generated from various sources like fossil fuels, nuclear power, and 
renewable resources such as solar or wind power. Electricity powers many 
aspects of our daily lives, including lighting, appliances, and communication
devices.

Electricity is the movement of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity plays a significant role in our daily lives, powering 
everything from lights to appliances and electronic devices.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity is essential for modern life, providing power to homes, 
businesses, and industries worldwide.

In summary, electricity is the movement of electrons through a conductor, 
generated from various sources such as fossil fuels, nuclear power, and 
renewable energy sources. It plays a crucial role in our daily lives by 
powering numerous devices and applications.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity has numerous applications in our daily lives, including 
lighting homes, powering appliances, and enabling communication devices.

Electricity is the movement of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity powers many aspects of our daily lives, including 
lighting, appliances, and electronic devices.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity plays an essential role in our daily lives, providing 
power to homes, businesses, and industries worldwide.

Electricity is the movement of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity powers many aspects of our daily lives, including 
lighting, appliances, and communication devices.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity has numerous applications in our daily lives, including 
lighting homes, powering appliances, and enabling communication devices.

Electricity is the movement of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity plays a significant role in our daily lives, providing 
power to homes, businesses, and industries worldwide.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity powers many aspects of our daily lives, including 
lighting, appliances, and electronic devices.

Electricity is the movement of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind 
power. Electricity has numerous applications in our daily lives, including 
lighting homes, powering appliances, and enabling communication devices.

Electricity is the flow of charged particles called electrons through a 
conductor, such as a wire. It can be generated from various sources like 
fossil fuels, nuclear power, and renewable resources like solar or wind power.^C

~/Pobrane>         

Zephyr from ollama repo:

~/Pobrane> ./ollama-linux-amd64 run zephyr:7b-beta-q4_K_M "What is electricity?. Be short and concise"
Electricity is the flow of electric charge through a material or space. It 
can be harnessed to power devices, illuminate spaces, transmit information, 
and perform various other useful functions. Essentially, it's the ability for
a substance to conduct an electrical current.

~/Pobrane>

**Comment by igorschlum** [comment]
I don't have this problem anymore. I close the issu.
