### ISSUE TITLE
How to stop a model aftering it's served?

### ISSUE THREAD

**Issue by paulwongx** [jmorganca/ollama#1025]
When the modelling is already being served, what is the command to stop it so that I can serve it again with different variables? I want to run `OLLAMA_ORIGINS=https://XXXXX ollama serve` but I'm getting an error that the address is already in use.

Running `ollama --help` doesn't show a command to unserve...?

tldr; how can I unserve?

**Comment by mxyng** [comment]
It looks like you're referring to overriding the default allowed origins. For setting `OLLAMA_ORIGINS`, see https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network
