### ISSUE TITLE
How to properly format Advanced Parameters / options in API calls?

### ISSUE THREAD

**Issue by tob-har** [jmorganca/ollama#1027]
API Documentation gives a proper example, how to use 
`POST /api/generate`

But how to properly format the JSON object to use Advanced Parameters?
Especially `options` and `system`.

I tried to request the following via `POST /api/generate`.
Everything behaves as expected, eg stream, but options is not workig:

`
{
  "model": "llama2:latest",
  "stream": false,
  "prompt": "Sing a song.",
  "options": {
    "temperature": 5}
 }
`

Happy about hints!!! Thanks a lot

**Comment by BruceMacD** [comment]
Hi @tob-har your request specifying system and temperature will look something like this:
```
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "llama2:latest",
  "prompt": "Sing a song",
  "system": "You are Beyoncé",
  "stream": false,
  "options": {
    "temperature": 0.8
    }
}'
```

**Comment by tob-har** [comment]
thanks! Yes, that I go so far. 
but setting advanced parameters like this as object as value of a key:value pair has no effect:

"options": {
    "temperature": 0.8
    }

even when using super extrem valus vor top_k or top_p...

But I also dont get errors... so I assume, it is somehow ignored when processing the request?!?    
Maybe do the parameters need to be set within the Modelfile befor when creating a model to be overwritable?

**Comment by BruceMacD** [comment]
I just tested the options and they are properly passed to the LLM in the most recent version. What behavior do you expect to see?
