### ISSUE TITLE
WizardCoder models lack a prompt template

### ISSUE THREAD

**Issue by Nan-Do** [jmorganca/ollama#1030]
I have been using the WizardCoder models and they do not use a template, this makes the quality of the output substantially worse, sometimes not writing python code and some others not offering an answer at all. 

I have been trying to see how to contribute this to the model but I haven't seen any feasible way to do it so here is a modelfile description that can be used to make the model use the proper template

```
FROM wizardcoder:13b-python

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 0.3

# set the system prompt
TEMPLATE """
{{ .System }}

### Instruction:
{{ .Prompt }}

### Response:
"""

SYSTEM """
Below is an instruction that describes a task. Write a response that appropriately completes the request.
"""
```

**Comment by mxyng** [comment]
This should be fixed now. Please pull the updated image with `ollama pull wizardcoder:13b-python`
