### ISSUE TITLE
Are these system specs good enough for any models?

### ISSUE THREAD

**Issue by simoovara** [jmorganca/ollama#1033]
Just a question, I have an old laptop that i turned into a server with Ubuntu LTS. It has an AMD E1-6015 APU and 8gb of ram. I would like to know if that's enough to run any of these models, thank you!

**Comment by SebastianMpl** [comment]
Not for any. Try those <= 7b parameters and q4 or lower (but it also lowers quality). I have 6 gb ram and have about 3 tokens per second. The speed is like an answer from a real person, not those flashing words...

**Comment by BruceMacD** [comment]
I don't know much about that AMD processor series so I cant really say for sure,but if you'd like to try the most lightweight model to see what you're system is capable I'd suggest giving orca-mini a try to see if it works: `ollama run orca-mini`

**Comment by easp** [comment]
That's a laptop chip from 2015. It may not be able to run any models at all if it lacks the needed vector instructions. If it can run models on the CPU, it'll be slow, but enough to get a taste.

**Comment by simoovara** [comment]
Alright, really helpful. Will try the lightest model orca-mini and I'll comment on this to let you know how it goes.

**Comment by simoovara** [comment]
Yeah, it's really really slow. It loads for about a minute and then types it out really slowly, approximately 1 word every second.
worth a try though

**Comment by simoovara** [comment]
thanks everyone for the help!
