### ISSUE TITLE
run a multi-file model 

### ISSUE THREAD

**Issue by eramax** [jmorganca/ollama#1037]
How to import a model which is multiple files like the image bellow
![image](https://github.com/jmorganca/ollama/assets/542413/56ed2ebc-a215-42f4-8699-b59d8d6866f4)

I tried but It gave me error
```parsing modelfile    
looking for model    
⠋ creating model layer  Error: invalid file magic```

**Comment by Nan-Do** [comment]
You need a quantized version of the model not the full precision weights. Check if there is a quantized (GGUF) version of the model you are interested in

**Comment by easp** [comment]
Check docs before opening an issue? In this case, 
https://github.com/jmorganca/ollama/blob/main/docs/import.md

**Comment by jmorganca** [comment]
Hi @eramax thanks for creating an issue. Currently the `Modelfile` and `ollama create` don't yet support importing from pytorch, but the plan is to eventually support this (see https://github.com/jmorganca/ollama/issues/1112)

For now you can import PyTorch models by following https://github.com/jmorganca/ollama/blob/main/docs/import.md to convert and quantize them first.
