### ISSUE TITLE
Add the deepseek model to the library

### ISSUE THREAD

**Issue by Nan-Do** [jmorganca/ollama#1040]
The deepseek model is currently the best coding open source model on the HumanEval dataset second only to ChatGPT4 by a little margin.
https://www.deepseek.com/
https://huggingface.co/deepseek-ai
https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-instruct
https://huggingface.co/deepseek-ai/deepseek-coder-33b-instruct
https://evalplus.github.io/leaderboard.html

There are 7b and 33b model variants, the quantized versions can be found here:
https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF
https://huggingface.co/TheBloke/deepseek-coder-33B-instruct-GGUF

This is a possible valid modelfile including a valid prompt template:
```
FROM ./deepseek-coder-33b-instruct.Q4_K_M.gguf

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 0.2

# set the system prompt
TEMPLATE """{{ .System }}

### Instruction:
{{ .Prompt }}

### Response:
"""

SYSTEM """You are an advanced AI programming assistant."""
```
The authors propose a longer version of this template, which is more restrictive, as well as other variants for other kinds of inference
https://github.com/deepseek-ai/deepseek-coder#3-chat-model-inference

**Comment by eramax** [comment]
Yes please add it.

**Comment by valentimarco** [comment]
+1

**Comment by daniel-a-diaz** [comment]
I was just about to write this feature request. Please add.

**Comment by kapral18** [comment]
+1

**Comment by gururise** [comment]
Any movement on this?  Would love to use deepseek coder as a coding assistant and Ollama as the server.  Would work great with the '[continue](https://continue.dev/docs/reference/Models/ollama)' vscode extension!

**Comment by Nan-Do** [comment]
Just a reminder for anyone interested in using this model, you can still download the model and use the ollama create command to add it to your local repository of models.
https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md.

This is a short recipe to run the 7B model:
```
wget https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF/resolve/main/deepseek-coder-6.7b-instruct.Q4_K_M.gguf
```
Create the modelfile, with the following contents, in the same directory you downloaded the model.
```
FROM ./deepseek-coder-6.7b-instruct.Q4_K_M.gguf

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 0.1

# set the system prompt
TEMPLATE """{{ .System }}

### Instruction:
{{ .Prompt }}

### Response:
"""

SYSTEM """You are an advanced AI programming assistant."""
```

Run the ollama create command.
```
ollama create deepseek-7B -f ./modelfile
```

Use the model.
```
ollama run deepseek-7B
```

**Comment by mxyng** [comment]
DeepSeek Coder is now [available](https://ollama.ai/library/deepseek-coder) in the Ollama library

**Comment by Nan-Do** [comment]
Just a comment for people interested in using this model, with the current configuration you'll need a graphic card with at least 16GB of VRAM (for the 6.7GB) in order to be able to use this model with GPU acceleration

**Comment by ex3ndr** [comment]
Base models are very interesting to have too
https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base
https://huggingface.co/deepseek-ai/deepseek-coder-33b-base
