### ISSUE TITLE
Update defect dolphin 2.2

### ISSUE THREAD

**Issue by vxld100** [jmorganca/ollama#1047]
I couldn't help but notice that the current [dolphin 2.2](https://ollama.ai/library/dolphin2.2-mistral) model on ollama points to version 2.2 and not 2.2.1. On the Huggingface [page](https://huggingface.co/ehartford/dolphin-2.2-mistral-7b) of dolphin 2.2 it says that the model has been overfit. On the [page](https://huggingface.co/ehartford/dolphin-2.2.1-mistral-7b) of version 2.2.1 Eric explains that "this is a checkpoint release, to fix overfit training. ie, it was responding with CoT even when I didn't request it, and also it was too compliant even when the request made no sense. This one should be better." This is also very noticeable in using the model.

**Comment by jmorganca** [comment]
`dolphin2.2-mistral` is now the 2.2.1 model – the URLs will soon be updated to a better naming scheme for `dolphin-mistral`

Will close this for now however feel free to re-open!
