### ISSUE TITLE
Where are the chat logs saved?

### ISSUE THREAD

**Issue by bitcoinmeetups** [jmorganca/ollama#1052]
Hi,

I'm Mr. Atom, a very friendly guy.

Where are the chat logs saved? I can't find the directory.

**Comment by pdevine** [comment]
Hello Mr. Atom,

We don't save the chat logs _per se_, however, you can find the history of the things you sent in `~/.ollama/history`.

**Comment by jmorganca** [comment]
Hi @bitcoinmeetups as @pdevine no logs are saved – will close this for now however feel free to re-open if needed

**Comment by Mingzefei** [comment]
Hello,

I have successfully deployed Ollama on a server running Windows 10 and have made the API available to other users within the local network. However, I've noticed that the chat records in the .ollama/history directory only include interactions made locally through the command line and do not contain any records of the chats initiated by other users over the network.

I'm curious to know whether the local server does not record network-initiated chat interactions at all, or if these records are stored in a different location that I'm not aware of.

**Comment by pdevine** [comment]
`.ollama/history` is the readline history for the client so you can use the up/down arrow when chatting. It's only saved on the client machine, not on the central server.

**Comment by YashasviMantha** [comment]
Same question as @Mingzefei, is it possible to see the history that different tools accessing Ollama over the network (like openweb-ui) send on the Ollama server (in my case docker container)? Or is it safe to assume this history is NOT saved?

**Comment by pdevine** [comment]
@YashasviMantha unless you had debug turned on, it's not saved anywhere. If you do have debug turned on the user prompts will be indirectly stored in the ollama server logs. You can find out how to view the logs in the [troubleshooting guide](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md) and in the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-view-the-logs)

**Comment by vavanade** [comment]
> [@YashasviMantha](https://github.com/YashasviMantha) If you do have debug turned on the user prompts will be indirectly stored in the ollama server logs.

What do you mean by indirectly stored? I don't see any prompts in the `server.log` file (on Windows). I see DEBUG level messages there though. Do they contain some ID that references the user prompt which is stored somewhere else?

**Comment by BananaAcid** [comment]
> `.ollama/history` is the readline history for the client so you can use the up/down arrow when chatting. It's only saved on the client machine, not on the central server.

1️⃣ ... I suspect this is for the CLI client only?

2️⃣ Can this be disabled? (GDPR)

3️⃣ (And why is this not stored only in the CLI clients memory?)
