### ISSUE TITLE
Error: mkdir permission denied

### ISSUE THREAD

**Issue by pepsiamir** [jmorganca/ollama#1066]
After installing Mistral and Sqlcoder models I got this error.
```
verifying sha256 digest
writing manifest
Error: mkdir /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/mistral: permission denied
```
I had to make the directory manually which then succeeded.
```
sudo mkdir /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/mistral
```

**Comment by BruceMacD** [comment]
Thanks for opening the issue, we have been having some issues with how we run the ollama runs as service on linux in relation to file access. The fix should be in soon in #898

**Comment by Luminous-seed** [comment]
Ubuntu22.04 拉取模型,多次遇到permission denied问题.

拉取模型的命令:
```ollama pull nomic-embed-text```

返回和报错:
pulling manifest 
pulling 970aa74c0a90... 100% ▕████████████████▏ 274 MB                         
pulling c71d239df917... 100% ▕████████████████▏  11 KB                         
pulling ce4a164fc046... 100% ▕████████████████▏   17 B                         
pulling 31df23ea7daa... 100% ▕████████████████▏  420 B                         
verifying sha256 digest 
writing manifest 
Error: mkdir /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/nomic-embed-text: permission denied

按照本问答方法自己手动生成路径
```sudo mkdir /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/nomic-embed-text```

重新拉取模型
```ollama pull nomic-embed-text```
返回和报错:
pulling manifest 
pulling 970aa74c0a90... 100% ▕████████████████▏ 274 MB                         
pulling c71d239df917... 100% ▕████████████████▏  11 KB                         
pulling ce4a164fc046... 100% ▕████████████████▏   17 B                         
pulling 31df23ea7daa... 100% ▕████████████████▏  420 B                         
verifying sha256 digest 
writing manifest 
Error: open /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/nomic-embed-text/latest: permission denied

担心是因为权限不足,使用sudo再次拉取模型
```sudo ollama pull nomic-embed-text```
报错:
pulling manifest 
pulling 970aa74c0a90... 100% ▕█▏ 274 MB                         
pulling c71d239df917... 100% █▏  11 KB                         
pulling ce4a164fc046... 100% ▕██▏   17 B                         
pulling 31df23ea7daa... 100% ▕█▏  420 B                         
verifying sha256 digest 
writing manifest 
Error: open /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/nomic-embed-text/latest: permission denied

求助了,不知道怎么个事...

**Comment by kkglow** [comment]
try change the owner or group of the file directory from root to ollama

sudo find /usr/share/ollama/.ollama/models/ -type f -exec chown ollama:ollama {} \;
sudo find /usr/share/ollama/.ollama/models/ -type d -exec chown ollama:ollama {} \;
sudo find /usr/share/ollama/.ollama/models/ -type f -exec chmod 644 {} \;
sudo find /usr/share/ollama/.ollama/models/ -type d -exec chmod 755 {} \;

hope this is helpful

**Comment by slamj1** [comment]
Small nitpick, for bash need \; at the end of each command.

**Comment by slamj1** [comment]
sorry backslashes don't come through, should be:

`sudo find /usr/share/ollama/.ollama/models/ -type f -exec chown ollama:ollama {} \;`

**Comment by dangarciahe** [comment]
I'm still getting this issue. The error I got in systemd logs was 

`Error: could not create directory mkdir /var/lib/ollama: permission denied
`

My workaround was to give the ollama's systemd entry permissions to  its /var/lib/ folder, modifying `etc/systemd/system/ollama.service` by adding the following lines:

```
StateDirectory=ollama
WorkingDirectory=/var/lib/ollama
```

After that simply restart the systemd config and module:

`sudo systemctl daemon-reload && sudo systemctl restart ollama.service`

This worked in my Manjaro install
