### ISSUE TITLE
Request: Tokenize endpoint

### ISSUE THREAD

**Issue by danemadsen** [jmorganca/ollama#1068]
I'm wanting to feed in example prompt / responses but there doesn't seem to be a way to do it without just attaching them to the system prompt? Is there a way we can have a /api/tokenize endpoint so example prompt / responses can be fed in as context?

**Comment by BruceMacD** [comment]
Hi @danemadsen thanks for opening the issue, we are working on a `messages` request parameter that will allow you to pass in request/responses directly, bypassing the need to set a tokenized context. Would that meet your needs?

https://github.com/jmorganca/ollama/pull/991

**Comment by danemadsen** [comment]
Yes i just saw the PR, that will work fine. Though i do think the encode /  decode endpoints could also be helpful in certain circumstances as well.

**Comment by jmorganca** [comment]
Closing this issue now that #991 is merged 🎊
