### ISSUE TITLE
FROM: command not found"

### ISSUE THREAD

**Issue by seyi33** [jmorganca/ollama#1069]
i installed ollama via WSL, but i keep getting "FROM: command not found", when i try to create a model file using a local model and this is the command i have been using "FROM /mistral-7b-instruct-v0.1.Q4_K_M.gguf".

**Comment by mxyng** [comment]
It seems you're running `FROM` from the command line interface. `FROM` is an instruction/command in the Modelfile so you'll need to create a file called Modelfile and add that line as the first time of the file. Then, you can create a model with `ollama create <name>` where `<name>` is the name you want the new model to be called. I hope this helps.

**Comment by seyi33** [comment]
> It seems you're running `FROM` from the command line interface. `FROM` is an instruction/command in the Modelfile so you'll need to create a file called Modelfile and add that line as the first time of the file. Then, you can create a model with `ollama create <name>` where `<name>` is the name you want the new model to be called. I hope this helps.

Yes, it did, Thanks . i saved it as a file in wsl and the rest was smooth
