### ISSUE TITLE
starcoder support (code models)

### ISSUE THREAD

**Issue by nathanleclaire** [jmorganca/ollama#107]
I wonder if https://github.com/bigcode-project/starcoder.cpp support could be added, I would be pretty curious to check out https://github.com/nlpxucan/WizardLM/tree/main/WizardCoder using ollama

**Comment by mchiang0610** [comment]
This is now available! 

1B: 
`ollama run starcoder` 

3B: 
`ollama run starcoder:3b` 

7B: 
`ollama run starcoder:7b` 

15B: 
`ollama run starcoder:15b`
