### ISSUE TITLE
Enhancement: Enable GPU Support for NVIDIA JetPack and the NVIDIA Jetson Lineup

### ISSUE THREAD

**Issue by bnodnarb** [jmorganca/ollama#1071]
Hi all,

I recently purchased an [NVIDIA Jetson Orin Developer Kit](https://store.nvidia.com/en-us/jetson/store/?page=1&limit=9&locale=en-us) and am hoping to get Ollama running on it.

These little powerhouses are specifically built for AI applications and they have a ton of capability crammed into a tiny form factor.

The Jetson devices run a flavor of Linux called [JetPack](https://developer.nvidia.com/embedded/jetpack), which is also packed with AI features. Description of JetPack below:

> NVIDIA JetPack SDK is the most comprehensive solution for building end-to-end accelerated AI applications. JetPack provides a full development environment for hardware-accelerated AI-at-the-edge development on Nvidia Jetson modules. JetPack includes [Jetson Linux](https://developer.nvidia.com/embedded/jetson-linux) with bootloader, Linux kernel, Ubuntu desktop environment, and a complete set of libraries for acceleration of GPU computing, multimedia, graphics, and computer vision.

Ollama works in a "CPU only" fashion when installed via the standard `curl https://ollama.ai/install.sh | sh` command when running on JetPack, but it seems to ignore all of the GPU power that is available on the Jetson board.

It would be awesome if we could get Ollama running at full speed on these devices.

Does anyone know where we could begin? I'm happy to help, but don't really know where to start.

**Comment by 65a** [comment]
Does it work in ggerganov/llama.cpp with acceleration?

**Comment by bnodnarb** [comment]
I know that @dusty-nv from NVIDIA got llama.cpp working and makes it available in a [Jetson Docker Container](https://github.com/dusty-nv/jetson-containers/tree/master/packages/llm/llama_cpp).

I'm not sure what tweaks needed to be made, but it does mean that llama.cpp can be made to run with CUDA enabled.

**Comment by bnodnarb** [comment]
This is the output that I get after running the Linux install script:

```
>>> Downloading ollama...
######################################################################## 100.0%##O=#  #                                                                      
>>> Installing ollama to /usr/local/bin...
>>> Creating ollama user...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
Created symlink /etc/systemd/system/default.target.wants/ollama.service → /etc/systemd/system/ollama.service.
>>> Installing NVIDIA repository...
curl: (22) The requested URL returned error: 404
```

This is likely because the install.sh script calls `    curl -fsSL -o $TEMP_DIR/cuda-keyring.deb https://developer.download.nvidia.com/compute/cuda/repos/$1$2/$(uname -m)/cuda-keyring_1.1-1_all.deb`

Running that `uname -m` command returns `aarch64` which causes the 404 as there is no page for that.

Ideally we can simply bypass this part because the CUDA drivers should already be installed via JetPack:

```
$ more /usr/local/cuda/version.json
{
   "cuda" : {
      "name" : "CUDA SDK",
      "version" : "11.4.19"
   },
   "cuda_compat" : {
      "name" : "CUDA Specific Libraries",
      "version" : "11.4.31478197"
   },
   "cuda_cudart" : {
      "name" : "CUDA Runtime (cudart)",
      "version" : "11.4.298"
   },
   "cuda_cuobjdump" : {
      "name" : "cuobjdump",
      "version" : "11.4.315"
   },
...
```

**Comment by bnodnarb** [comment]
Eureka! I was able to get this to work by combining a handful of tickets. I'll create a pull request with documented instructions on how to get it up and running :)

**Comment by jp2000** [comment]
Cant wait, just ran into this with mine. 
llama.cpp did work great for me with no changes, but yeah ollama is stuck in cpu-only mode.

**Comment by brandonironbirdlabscom** [comment]
@jp2000 - working on the PR now. Will send a note and link once it's submitted. Thanks!

**Comment by bnodnarb** [comment]
@jp2000 - working on the PR now. Will send a note and link once it's submitted. Thanks!

**Comment by bnodnarb** [comment]
> @jp2000 - working on the PR now. Will send a note and link once it's submitted. Thanks!

Hi all - please see submitted pull request here: https://github.com/jmorganca/ollama/pull/1098

Closing this issue :)

Thanks!

**Comment by mraiser** [comment]
> > @jp2000 - working on the PR now. Will send a note and link once it's submitted. Thanks!
> 
> Hi all - please see submitted pull request here: #1098
> 
> Closing this issue :)
> 
> Thanks!

Can confirm... This works great on 8GB Jetson Orin Nano with Jetpack 5.1.2 on Ubuntu 20.04. Thank you!!!
