### ISSUE TITLE
More fine-grained download speed

### ISSUE THREAD

**Issue by Dialga** [jmorganca/ollama#1073]
Currently when downloading large models, it shows downloading `16/19 GB`, it would be more helpful to show a float e.g. `16.22/19.3 GB`.

**Comment by technovangelist** [comment]
Hi @slarrauri, we recently updated the way we show this in the cli. We now show a float of downloading progress. Do you think that solves your issue?

![CleanShot 2024-01-02 at 17 58 43](https://github.com/jmorganca/ollama/assets/633681/291c88d3-2e95-4239-a2cf-eca34526ad18)

**Comment by mxyng** [comment]
The progress bar has been updated to display decimals when necessary
