### ISSUE TITLE
Error when attempted to download Ollama Mac/Linux version `Error fetching release`

### ISSUE THREAD

**Issue by abdulazizalmass** [jmorganca/ollama#1077]
Thank you for the amazing project. Kindly, close this once the download issue is resolved

**Comment by BruceMacD** [comment]
Thanks for the report, we are looking into it now.

**Comment by BruceMacD** [comment]
We had a caching issue, the problem should resolve soon, redeploying the website now.

**Comment by BruceMacD** [comment]
This should be resolved now, please let us know if anyone hits this again. Thanks!
