### ISSUE TITLE
Error after prompting Llama2 on M1.

### ISSUE THREAD

**Issue by aelder** [jmorganca/ollama#108]
After starting Ollama and running Llama2, any prompt results in:
`Error: Post "http://127.0.0.1:11434/api/generate": EOF
`
Installed on M1 Macbook Pro
Ollama reports that it is running.
'Ollama list' reports llama2:latest.

Is this a memory issue?

**Comment by pdevine** [comment]
How much memory do you have? It should work fine (albeit slow) on a 16GB laptop.

**Comment by mchiang0610** [comment]
@aelder may I ask what was the length of your prompt? I have seen this on longer prompts this morning.

**Comment by aelder** [comment]
@mchiang0610 it happens with any length. I’ve tried down to a single character.

Based on comments I imagine it’s lack of memory. I’m only using a base M1 with 8gb unified memory.

**Comment by chsasank** [comment]
Yep, it's out of memory. Reported logs at #118
