### ISSUE TITLE
Can't get it to use GPU in docker

### ISSUE THREAD

**Issue by pdavis68** [jmorganca/ollama#1089]
I have a RTX 3050...

I went through the install and it works from the command-line, but using the CPU. 

When I try running this last step, though (after shutting down the container):

docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama

I get: Error response from daemon: Conflict. The container name "/ollama" is already in use by container "60d73a071b8a28b47b2593dd459338fa9d6002b0f7ac041267e2c79114091e6f". You have to remove (or rename) that container to be able to reuse that name.

How do I get it to use the GPUs now that it's installed?

**Comment by orkutmuratyilmaz** [comment]
@pdavis68 which OS do you use?

**Comment by orkutmuratyilmaz** [comment]
also, if you want to use "ollama" name as your container name, you better delete the other container.

**Comment by pdavis68** [comment]
Sorry, I thought I closed this comment. I got confused in the install I'm running it in docker under windows. I posted a new issue after the install completed regarding some possible instruction clarifications.
