### ISSUE TITLE
build failure: `APPLE_IDENTITY: unbound variable`

### ISSUE THREAD

**Issue by jpmcb** [jmorganca/ollama#1092]
Attempting to build on the darwin platform using the `build/build_darwing.sh` script results in the following error:

```
./scripts/build_darwin.sh: line 17: APPLE_IDENTITY: unbound variable
```

This is after go generate (with `cmake` for th llama.cpp targets) and the `ollama` binary have completed building:

```
❯ ls -la dist
total 71664
drwxr-xr-x@  3 jpmcb  staff        96 Nov 11 10:52 .
drwxr-xr-x@ 28 jpmcb  staff       896 Nov 11 10:46 ..
-rwxr-xr-x@  1 jpmcb  staff  36688338 Nov 11 10:52 ollama
```

There appear to be a few unbound variables: `APPLE_IDENTITY`, `APPLE_ID`, `APPLE_PASSWORD`, `APPLE_TEAM_ID` which my guess are used to sign/authenticate the binaries so they run smoothly on macs without

I more or less just want a way to build and run locally without having to sign any binaries. `go generate ./... && go build-o dist/ollama-dev` would probably work fine but wondering if there's a more official way.

---

Some additional details on my system:

```
❯ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.3 (22E252)
      Kernel Version: Darwin 22.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Chip: Apple M2 Max
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 8422.100.650
      OS Loader Version: 8422.100.650
```

**Comment by mxyng** [comment]
The build script is intended to build release binaries. For local use, you should use `go generate ./... && go build .` instead
