### ISSUE TITLE
OLLAMA with openchat

### ISSUE THREAD

**Issue by aniketmoha9** [jmorganca/ollama#1093]
Can you add openchat3.5 model also with ollama, it would be great to test it as they are claiming to better than most of the models? It is answering the question but it is not stopping.

`FROM ./openchat_3.5.Q6_K.gguf
`

**Comment by ktsi** [comment]
Would be great if we could have this model in ollama.

**Comment by ageorgios** [comment]
+1 plz support

**Comment by eramax** [comment]
+1 plz support

**Comment by TanvirOnGH** [comment]
+1 plz support

**Comment by nickanderson** [comment]
This happened. https://ollama.ai/library/openchat

**Comment by technovangelist** [comment]
Looks like this is resolved so I will go ahead and close the issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
