### ISSUE TITLE
Exploring Multimodal LLMs: Incorporating Image as Input in ModelFile.

### ISSUE THREAD

**Issue by saifullah-N** [jmorganca/ollama#1109]
Hi, I'd like to experiment with multimodal language models that can handle both images and text as input. Is there a way to input an image.

My ModelFile looks like this
```
FROM ./my_model.gguf
PARAMERTER..
SYSTEM You are An Artist describe the image
```

I'm trying to run this on macos.
M1 chip

**Comment by jmorganca** [comment]
Hi there! Thanks for creating an issue. I'll merge it with https://github.com/jmorganca/ollama/issues/746
