### ISSUE TITLE
Error trying to create custom model, fresh install

### ISSUE THREAD

**Issue by austinhale** [jmorganca/ollama#111]
First off, this is awesome. Thank you for creating this. Running into a `Error: 400 Bad Request` when trying to follow the README and create a custom model. 

Steps:
1. Download Apple Silicon app from `https://ollama.ai/download` & install to CLI
2. Run `ollama run llama2` successfully
3. Create a `Modelfile` and copy/paste the README example verbatim
4. Run `ollama create mario -f ./Modelfile`
5. Receive the `Error: 400 Bad Request`

Attempted a few of the other examples as well, etc. but couldn't get it to run.

**Comment by mchiang0610** [comment]
Thanks for this bug report. There is currently a bug with using relative paths. If you use an absolute path eg.) `ollama create mario -f ~/Downloads/ollama/Modelfile` it should work.

**Comment by james-see** [comment]
I was having the same issue, thanks for the workaround!

**Comment by mchiang0610** [comment]
@james-see @austinhale This issue should be fixed in the latest version (0.0.7) just released. If you have Ollama installed, it'll prompt to update. 

Thanks! 

The specific PR is: https://github.com/jmorganca/ollama/pull/112
