### ISSUE TITLE
Problems pushing a new model to ollama

### ISSUE THREAD

**Issue by matthewchung74** [jmorganca/ollama#1111]
Having problems pushing a new model to ollama

```
ollama push matthewchung74/medmistral
retrieving manifest
pushing 9f302ba97745...  99% |████████████ | (4.1/4.1 GB, 3.4 MB/s) [19m54s:0s]Error: max retries exceeded
```
Is this the right cli command? I've tried about 3 times now.

**Comment by jmorganca** [comment]
Hi @matthewchung74 sorry you hit this. Will look into the cause

**Comment by mxyng** [comment]
This is very like caused by the authenticated URL expiring which shouldn't be an issue anymore after the timeout was increased
