### ISSUE TITLE
I am trying to Create Model File But I am getting permission Denied Error. 

### ISSUE THREAD

**Issue by Sridatta0808** [jmorganca/ollama#1113]
Project Structure :

bin/
src/
models/
requirements.txt
Readme.md

Steps Followed:
$ nano Modelfile  - > Inserted -> FROM ./models/mistral-7b-instruct-v0.1.Q3_K_M.gguf
$ ollama create example -f Modelfile

-> Returns Following Error :
couldn't open modelfile '/home/sridatta/projects/basic_llm/langchain/Modelfile'  Error: failed to open file: open /home/sridatta/projects/basic_llm/langchain/Modelfile: permission denied
 
Tried the below approach Approache : 
->  chmod -R o+rx Modelfile path (DIDNT WORK)

For any one please let me know how to load GGUF model to ollama chat. 
Thanks in advance.

**Comment by BruceMacD** [comment]
Hey @Sridatta0808, thanks for opening the issue. The way we install Ollama on linux has some file permissions issues, a fix is underway in #898.

A workaround in the meantime will be to move the Modelfile and gguf file to `/usr/share/ollama` so that the Ollama service user can access them.

**Comment by MostlyKIGuess** [comment]
You can also trying adding it to tmp dir or the dir where ollama can access it, it might just work out..

or give perms to Ollama using

```
usermod -aG ollama $USER
```
