### ISSUE TITLE
vicuna33b not executing on GPU

### ISSUE THREAD

**Issue by nshern** [jmorganca/ollama#1116]
I am using Debian with an A4000. Vicuna13b will execute on GPU just fine but Vicuna33b will not.

Is this a bug or am I misunderstanding something in the documentation or configuration?

**Comment by BruceMacD** [comment]
Vicuna-33b is too big to entirely offload to an A4000 GPU (quick Google search says that its got 16GB of VRAM) so the load will be shared between CPU and GPU. If you are only seeing CPU usage try checking the ollama service logs:
`sudo journalctl -u ollama.service > ollama_logs.txt`

Happy to help with any errors you may see in there.

**Comment by jmorganca** [comment]
Hi @nshern thanks for the issue. I'll close this one for now if it's answered, but feel free to re-open it otherwise!
