### ISSUE TITLE
Change Default 11434 Port & fw question

### ISSUE THREAD

**Issue by jjsarf** [jmorganca/ollama#1117]
Does anyone know how to change Ollama's default port?

Also how do we allow other computers to hit the /generate api? 

Thanks,
John

**Comment by jmorganca** [comment]
Hi @jjsarf you can use the `OLLAMA_HOST` environment variable in combination with `ollama serve`

E.g. to expose Ollama externally on port 8080 you can use:

```
OLLAMA_HOST=0.0.0.0:8080 ollama serve
```

Feel free to post another issue! Will close this one for now

**Comment by jjsarf** [comment]
That did not work. 
super@mario:/var/www/html$ curl -X POST http://ai:8080/api/generate -d '{
  "model": "llama2",
  "prompt": "How are you?",
  "stream": true,
  "options": {
    "top_k": 20,
    "top_p": 0.9,
    "typical_p": 0.7,
    "temperature": 0.8,
    "repeat_penalty": 1.2,
    "presence_penalty": 1.5,
    "frequency_penalty": 1.0
    }
}'
curl: (7) Failed to connect to ai port 8080 after 230 ms: Connection refused

I also tried with the IPs
C:\usb\laragon-portable\se>curl -X POST http://10.0.0.252:8080/api/generate -d "{\"model\": \"llama2\", \"prompt\": \"Why is the sky blue?\", \"stream\": true, \"options\": { \"top_k\": 20, \"top_p\": 0.9, \"typical_p\": 0.7, \"temperature\": 0.8, \"repeat_penalty\": 1.2, \"presence_penalty\": 1.5, \"frequency_penalty\": 1.0 }}"
curl: (7) Failed to connect to 10.0.0.252 port 8080: Connection refused

**Comment by jjsarf** [comment]
But it did help if I run it locally were the ollama is installed  (to the "ai" host) not for the external IP.
