### ISSUE TITLE
please support neural-chat-7b-v3-1

### ISSUE THREAD

**Issue by eramax** [jmorganca/ollama#1136]
Definitely one the most amazing models I've ever seen [neural-chat-7b-v3-1 ](https://huggingface.co/Intel/neural-chat-7b-v3-1)
please include it to the models page.
I used it thorugh this command 
```bash
ollama run fakezeta/neural-chat-7b-v3-1:Q5_K_M
```

**Comment by mxyng** [comment]
Thanks for the model request, this model is now available in the Ollama library: https://ollama.ai/library/neural-chat
