### ISSUE TITLE
pls Wizard Uncensored 

### ISSUE THREAD

**Issue by nathanleclaire** [jmorganca/ollama#114]
https://huggingface.co/TheBloke/WizardLM-13B-Uncensored-GGML good performance ime

**Comment by mchiang0610** [comment]
@nathanleclaire we just added it. Haven't added it to the readme yet. 

Try it: 

```
ollama run wizard-vicuna 
```

**Comment by mchiang0610** [comment]
@nathanleclaire closing this now, since it's on the readme now. Let me know if this is not what you want, and we can pick it up again. 

Thank you so much for submitting this!
