### ISSUE TITLE
Model push is not working

### ISSUE THREAD

**Issue by eramax** [jmorganca/ollama#1140]
I tried many times to push my models to ollama but always I get this error
```
retrieving manifest
Error: max retries exceeded
```

**Comment by BruceMacD** [comment]
Hey @eramax, I've hit this exact issue. I've got a fix for it in #1131. 

It's either you're pushing to the base namespace (which is what I was doing) or you need to create the namespace before pushing. Here's the steps to success:
1. Sign-up for ollama.ai
https://www.ollama.ai/signup
2. Create a new model
https://www.ollama.ai/new
3. Create the model locally with your username as the namespace
```
ollama create <ollama-username>/<model-name> -f /path/to/Modelfile
```
4. Push the model
```
ollama push <ollama-username>/<model-name>
```

**Comment by eramax** [comment]
I guess still there is an issue in the push function

this is my repo https://ollama.ai/eramax/nous-capybara-7b-1.9
the ssh pub key shown at `cat ~/.ollama/id_ed25519.pub` is already set and added to my profile
*md is the directory 

```bash
➜  md llm -v
ollama version 0.1.10


➜  md l
.0644 root root 4.8 GB Wed Nov 15 17:32:01 2023 🗋 Capybara-7B-V1.9-Q5_K_M.gguf
.0644 root root 139 B  Sat Nov 18 01:31:40 2023 🗋 Modelfile

➜  md llm create eramax/nous-capybara-7b-1.9:Q5_K_M -f Modelfile
transferring context
creating model layer
creating template layer
creating parameters layer
creating config layer
using already created layer sha256:08323667b50ceb4ddf208f475b6101857c26688cf413e80329f174fe34f53e9a
using already created layer sha256:a8ac3515452d80041d2c3ed2ebf79f2b9a1ac4468e201a1b661ceb90c20c1a93
writing layer sha256:f4c99b0ffe2c4d82a82fcc83294c8603984598f5a77d2e1ddaedabc50bbf9ad6
writing layer sha256:e6d5ee0679e5d1afe5b2b66a38ebc0f8475801b210aea9734e626bb63f00f9bf
writing manifest
success

➜  md llm ls
NAME                                    ID              SIZE    MODIFIED
eramax/nous-capybara-7b-1.9:Q5_K_M      6a898ba40903    5.1 GB  3 seconds ago

➜  md llm run eramax/nous-capybara-7b-1.9:Q5_K_M
>>> who are you
 I am a helpful AI-powered digital assistant.

➜  md llm push eramax/nous-capybara-7b-1.9:Q5_K_M
retrieving manifest
Error: unable to push eramax/nous-capybara-7b-1.9, make sure this namespace exists and you are authorized to push to it
```

**Comment by ssghost** [comment]
I have the same problem I tried to add my ollama-username before the model name, but unfortunately it is still not working, and the error message is the same,
`Error: file does not exist` I don't know which "file" is missing here?

> Hey @eramax, I've hit this exact issue. I've got a fix for it in #1131.
> 
> It's either you're pushing to the base namespace (which is what I was doing) or you need to create the namespace before pushing. Here's the steps to success:
> 
> 1. Sign-up for ollama.ai
>    https://www.ollama.ai/signup
> 2. Create a new model
>    https://www.ollama.ai/new
> 3. Create the model locally with your username as the namespace
> 
> ```
> ollama create <ollama-username>/<model-name> -f /path/to/Modelfile
> ```
> 
> 4. Push the model
> 
> ```
> ollama push <ollama-username>/<model-name>
> ```

**Comment by konsumer** [comment]
I have similar issue with [konsumer/weather](https://ollama.com/konsumer/weather).

I added ` ~/.ollama/id_ed25519.pub` to my ollama account's keys.

```
$ ollama create konsumer/weather -f weather.Modelfile

transferring model data 
reading model metadata 
creating system layer 
using already created layer sha256:5eacc46e5b0ec08858572de8dc6fd8be34cc2246a13a756858b0abed6ea78fe4 
using already created layer sha256:a47b02e00552cd7022ea700b1abf8c572bb26c9bc8c1a37e01b566f2344df5dc 
using already created layer sha256:f02dd72bb2423204352eabc5637b44d79d17f109fdb510a7c51455892aa2d216 
using already created layer sha256:d1b61d566986671c9bea56b690c1f31c79346b8e8d94b7807a64ba5a52132113 
using already created layer sha256:63a5174447d20977e22b3cf064ca9501f047d919d8ae4bc7141eb2c3775076c0 
writing manifest 
success 

$ ollama push konsumer/weather

retrieving manifest 
Error: unable to push konsumer/weather, make sure this namespace exists and you are authorized to push to it
```

I am on latest PopOS (similar to Ubuntu.)

**Comment by maxtheman** [comment]
I got this issue but was able to resolve by creating with a new model name on MacOS.

**Comment by kzos** [comment]
model push error still present , why to close?

**Comment by sovit-123** [comment]
Hello. As understood at the moment, we have to set the public key from `/usr/share/ollama/.ollama/id_ed25519.pub`. However, while creating the model, the set of commands on the website pointt to `.ollama/id_ed25519.pub`. I recommend opening this issue untl the website is updated with the correct command.

**Comment by BruceMacD** [comment]
Hi @sovit-123, where is the command you saw with the incorrect path for the key? There was an update to ollama.com/settings/keys recently that should have the correct default path now.

**Comment by sovit-123** [comment]
Hi @BruceMacD Just checked a few things now. On the **Settings** page, all commands are correct. However, I remember, just two days back when I tried to push my first model and no public keys were set, then after entering the model name, it suggested adding the public key (Note: this is the first time when someone creates a model/public key is not present). On the model creation page, there was a set of commands along with the command to print the public key on the terminal. That's where the wrong command was present.

**Comment by BruceMacD** [comment]
Thanks @sovit-123, I see it now. I'll get this fixed.

**Comment by sctrueew** [comment]
Hi, I'm trying to push from Google Colab, and I’ve generated a public key and added it to my Ollama account. However, when I attempt to push the model, I encounter the following error:

```
!ollama list
NAME                      	ID          	SIZE  	MODIFIED       
zpm/mehrdadllm:latest     	650326dced94	4.9 GB	35 minutes ago

!ssh-keygen -t ed25519 -N ""
!sudo cp ~/.ssh/id_ed25519.pub /usr/share/ollama/.ollama/id_ed25519.pub
!cat /usr/share/ollama/.ollama/id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwPOb/wYjqgxJ........

!ollama push zpm/mehrdadllm
Error: you are not authorized to push to this namespace. Please create the model under a namespace you own.
```

It seems I’m not authorized to push to this namespace. Could you advise on how to resolve this issue?

**Comment by sovit-123** [comment]
@sctrueew You need to go **Settings > Ollama Keys** in your Ollama account and then paste the SSH key that you get via 
`cat /usr/share/ollama/.ollama/id_ed25519.pub`. Execute the command in your own (local) terminal to get the key.

**Comment by sctrueew** [comment]
@sovit-123 Thanks for your reply. I did and set the SSH key in Ollama account but still get this error:

> Error: you are not authorized to push to this namespace. Please create the model under a namespace you own.

**Comment by sovit-123** [comment]
@sctrueew So, at the moment you have added your API key here?
![image](https://github.com/user-attachments/assets/6c4c58ac-cbee-496c-9c30-913f9379f18e)

Oh. So, you are executing in Colab, right? I guess in that case, you need to get the SSH key from colab. Can you try that?

**Comment by sovit-123** [comment]
@sctrueew Can you skip this step:
`!sudo cp ~/.ssh/id_ed25519.pub /usr/share/ollama/.ollama/id_ed25519.pub`

And directly do `!cat /usr/share/ollama/.ollama/id_ed25519.pub` to get the SSH key?

**Comment by sctrueew** [comment]
it was the same key and I still get this

> Error: you are not authorized to push to this namespace. Please create the model under a namespace you own.

**Comment by sovit-123** [comment]
That's odd. Hopefully, you restarted the Colab system, and re-installed Ollama before trying that.

**Comment by yilengyao** [comment]
I am using Ubuntu/Linux
Adding keys from /usr/share/ollama/.ollama/id_ed25519.pub doesn't allow me to push.

While adding keys from
~/.ollama/id_ed25519.pub 
works.

**Comment by cstp55** [comment]
ollama create -f Modelfile chandancstp/aprilo
ollama push chandancstp/aprilo
I have follow the above way but getting following error
Error: you are not authorized to push to this namespace, create the model under a namespace you own

**Comment by cstp55** [comment]
working for me also
https://ollama.com/chandancstp/aprilo[https://ollama.com/chandancstp/aprilo](url)
add your public key at ollama keys sections
1. create or copy the  model
ollama create -f Modelfile chandancstp/aprilo

>ollama push chandancstp/aprilo

![Image](https://github.com/user-attachments/assets/605c1178-3e80-4b71-932e-925b4b016555)

**Comment by Byte-Maste** [comment]
1.ssh-keygen -t ed25519 -f C:\Users\<YOUR_PC_NAME>\.ssh\id_ed25519
2.go to your C:\Users\<YOUR_PC_NAME>\.ollama\id_ed25519.pub add this key to ollama key section
3.ollama create ollama_user_name/your_model_name -f Modelfile
4.ollama push ollama_user_name/your_model_name

**Comment by AcidicSoil** [comment]
just fixed by uninstalling and cleaning up leftover dirs from windows and ubuntu wsl. I think it was a version mismatch that caused this. client version didnt match the cli version. So probably getting those versions to match would fix it. easy way for me was just to uninstall on both and reinstall. currently pushing w/o issues ATM
