### ISSUE TITLE
running any model crashes my Ubuntu 22.04 LTS system  with 2 nvidia GPUs RTX 3060

### ISSUE THREAD

**Issue by pexus** [jmorganca/ollama#1148]
It used to work before. The latest version just crashes my system. I tried running xwinlm, mistral and llama2.
I have an AMD FX 830, 2 nvidia GPU RTX 3060 with 12GB each and CPU mem of 32GB. Running on Ubuntu 22.04 LTS. 
I am using the latest CUDA toolkit 12.3

**Comment by jmorganca** [comment]
Hi @pexus – sorry to hear. Let's get this fixed. Would it be possible to share the Ollama logs? `journalctl -u ollama` should show an error as to why it's crashing

**Comment by pexus** [comment]
Here is the last log files before the crash. I will upload the full log files also.
----
Nov 15 21:48:38 ai-desktop ollama[1315]: gs     0x0
Nov 15 21:48:40 ai-desktop systemd[1]: ollama.service: Failed with result 'exit-code'.
Nov 15 21:48:40 ai-desktop systemd[1]: ollama.service: Consumed 1min 36.511s CPU time.
Nov 15 21:48:43 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 1.
Nov 15 21:48:43 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:43 ai-desktop systemd[1]: ollama.service: Consumed 1min 36.511s CPU time.
Nov 15 21:48:43 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:48:43 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:48:43 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:48:46 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 2.
Nov 15 21:48:46 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:46 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:48:46 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:48:46 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:48:49 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 3.
Nov 15 21:48:49 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:49 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:48:50 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:48:50 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:48:53 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 4.
Nov 15 21:48:53 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:53 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:48:53 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:48:53 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:48:56 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 5.
Nov 15 21:48:56 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:56 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:48:56 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:48:56 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:48:59 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 6.
Nov 15 21:48:59 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:48:59 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:03 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:03 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:06 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 7.
Nov 15 21:49:06 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:06 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:06 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:06 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:09 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 8.
Nov 15 21:49:09 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:09 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:18 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:18 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:22 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 9.
Nov 15 21:49:22 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:22 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:22 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:22 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:25 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 10.
Nov 15 21:49:25 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:25 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:25 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:25 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:28 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 11.
Nov 15 21:49:28 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:28 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:28 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:28 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:31 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 12.
Nov 15 21:49:31 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:31 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:32 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:32 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:35 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 13.
Nov 15 21:49:35 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:35 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:35 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:35 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.
Nov 15 21:49:38 ai-desktop systemd[1]: ollama.service: Scheduled restart job, restart counter is at 14.
Nov 15 21:49:38 ai-desktop systemd[1]: Stopped Ollama Service.
Nov 15 21:49:38 ai-desktop systemd[1]: Started Ollama Service.
Nov 15 21:49:38 ai-desktop systemd[1]: ollama.service: Main process exited, code=dumped, status=11/SEGV
Nov 15 21:49:38 ai-desktop systemd[1]: ollama.service: Failed with result 'core-dump'.

**Comment by pexus** [comment]
The full log file attached.. 
[ollama.log](https://github.com/jmorganca/ollama/files/13378341/ollama.log)

**Comment by pexus** [comment]
I wanted to make sure my multi-gpu system is good. So I did run the gpu-burn to exercise both the cards and it seem to work ok without any issues:
---
sing compare file: compare.ptx
Burning for 60 seconds.
GPU 0: NVIDIA GeForce RTX 3060 (UUID: GPU-5a7e6ca0-cffd-c851-ccab-841a563cb01f)
GPU 1: NVIDIA GeForce RTX 3060 (UUID: GPU-ead06433-da1b-b94a-e443-90fcba03b220)
Initialized device 0 with 11831 MB of memory (11508 MB available, using 10357 MB of it), using FLOATS
Results are 268435456 bytes each, thus performing 38 iterations
Initialized device 1 with 11834 MB of memory (11693 MB available, using 10524 MB of it), using FLOATS
Results are 268435456 bytes each, thus performing 39 iterations
15.0%  proc'd: 38 (8230 Gflop/s) - 78 (10117 Gflop/s)   errors: 0 - 0   temps: 52 C - 46 C 
	Summary at:   Thu Nov 16 07:59:11 AM MST 2023

30.0%  proc'd: 114 (9460 Gflop/s) - 156 (10119 Gflop/s)   errors: 0 - 0   temps: 57 C - 53 C 
	Summary at:   Thu Nov 16 07:59:20 AM MST 2023

41.7%  proc'd: 190 (9440 Gflop/s) - 195 (10122 Gflop/s)   errors: 0 - 0   temps: 60 C - 55 C 
	Summary at:   Thu Nov 16 07:59:27 AM MST 2023

58.3%  proc'd: 266 (9403 Gflop/s) - 312 (10039 Gflop/s)   errors: 0 - 0   temps: 62 C - 59 C 
	Summary at:   Thu Nov 16 07:59:37 AM MST 2023

71.7%  proc'd: 342 (9332 Gflop/s) - 390 (10021 Gflop/s)   errors: 0 - 0   temps: 63 C - 62 C 
	Summary at:   Thu Nov 16 07:59:45 AM MST 2023

83.3%  proc'd: 418 (9236 Gflop/s) - 429 (10005 Gflop/s)   errors: 0 - 0   temps: 64 C - 63 C 
	Summary at:   Thu Nov 16 07:59:52 AM MST 2023

93.3%  proc'd: 456 (9226 Gflop/s) - 507 (9980 Gflop/s)   errors: 0 - 0   temps: 65 C - 65 C  
	Summary at:   Thu Nov 16 07:59:58 AM MST 2023

100.0%  proc'd: 532 (9365 Gflop/s) - 546 (9973 Gflop/s)   errors: 0 - 0   temps: 65 C - 66 C 
Killing processes with SIGTERM (soft kill)
Freed memory for dev 1
Uninitted cublas
Freed memory for dev 0
Uninitted cublas

**Comment by orlyandico** [comment]
Is that an FX 8300?  it is a fairly old CPU. May not be related, but I ran into some problems running Kubernetes on an old AMD processor (granted, older than the FX 8300) due to incomplete/missing SSE4.2 implementation.

**Comment by pexus** [comment]
I have AMD FX-8350 Eight Core Processor. I have run models through ollama and other LLM runners successfully before. I had to reconfigure my system lately and with the latest re-install I am seeing this behavior, so I believe it may have been something to do with recent updates to Ollama. Let me know if you need any additional information.

**Comment by pexus** [comment]
I have an update to this issue. I switched my nVidia drivers on Ubuntu from nvidia-driver-545 which seems to still in beta  To nvidia-driver-535 and now I don't see the issue. i can load the models and interact without crashing.  So it is not an ollama issue, hence I am closing this issue.
