### ISSUE TITLE
No such host no matter what model I pull

### ISSUE THREAD

**Issue by chnsh** [jmorganca/ollama#1149]
Hello 👋 

Thank you so much for developing this project. I am excited to use it in my day-to-day work and when I pull any model - as an example `ollama pull codellama:7b-instruct` I get an error like so. This is true for all models. I am wondering if I am missing any steps. 

I installed this app from https://ollama.ai/download

```
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/3a/3a43f93b78ec50f7c4e4dc8bd1cb3fff5a900e7d574c51a6f7495e48486e0dac/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20231116%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20231116T045920Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=173709c13b6930d42a44fb994a03ce05da90590a40150253ae5240158c43ce84": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host
```

**Comment by BruceMacD** [comment]
I'm looking in this now. @chnsh was this a model you had downloaded previously, and you see the error when pulling it again, or is it your first time downloading?

**Comment by nairaditya99** [comment]
Hi,
Same issue here.
First-time download on MacOS using the client on the website. Tried to reinstall but that didn't work. For some reason, its not able to connect at all?

When I run ollama serve I get this

`Error: listen tcp 127.0.0.1:11434: bind: address already in use`

Then I ran 

`lsof -i :1134` and found ollama listening on the port so I killed it and ran ollama serve again. Still facing the same issue.

**Comment by chnsh** [comment]
@BruceMacD Thanks for looking into it. Its not running inside Docker and its the first time I downloaded any models.

**Comment by nairaditya99** [comment]
Btw @chnsh @BruceMacD, I think it's some sort of issue with my internet. I switched to mobile hotspot and it started downloading the models right away

**Comment by BruceMacD** [comment]
Thanks for the update @nairaditya99, I think this might be a DNS issue so that would make sense.

**Comment by chnsh** [comment]
It must have been transient - it worked when I tried it today. Thanks for the help!
