### ISSUE TITLE
How to stop the ollama?

### ISSUE THREAD

**Issue by kmkarakaya** [jmorganca/ollama#1152]
I try to kill the service but it keeps restarting!

kmkarakaya@DESKTOP-AMT61DR:~$ sudo kill 9493
kmkarakaya@DESKTOP-AMT61DR:~$ ps aux | grep ollama
ollama    9516  0.1  0.2 2370868 21388 ?       Ssl  12:11   0:00 /usr/local/bin/ollama serve
kmkarak+  9531  0.0  0.0   4024  2128 pts/7    S+   12:11   0:00 grep --color=auto ollama

**Comment by horw** [comment]
Hi, @kmkarakaya , have you tried `systemctl stop ollama`?

**Comment by kmkarakaya** [comment]
@horw Yes, It stopped OLLAMA. Thanks

**Comment by igorschlum** [comment]
@kmkarakaya can you close the issue?
