### ISSUE TITLE
CodeGPT extension cannot connect to locally served ollama Error: connect ECONNREFUSED ::1:11434

### ISSUE THREAD

**Issue by wahreChrist** [jmorganca/ollama#1153]
Im trying to make CodeGPT extension work, to interact with Ollama in VS code, but it gives me this error in devtools console:
```
[Extension Host] No active text editor found.
log.ts:441   ERR [Extension Host] Error: Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```
Ollama itself works fine in CLI, http://127.0.0.1:11434/ also works and says that its up and running. Can't seem to figure out why Ollama refuses the connection. Can it have something to do with it not being able to locate default ssh key? It creates one every time when I run `ollama serve`, but then just exits with an error that port 11434 is already taken

**Comment by wahreChrist** [comment]
Hello @horw, I know that its possible I just don't understand what might be causing this issue in my particular case

**Comment by orkutmuratyilmaz** [comment]
@wahreChrist, have you checked [this issue](https://github.com/davila7/code-gpt-docs/issues/192)?

**Comment by wahreChrist** [comment]
@orkutmuratyilmaz just checked now, unfortunately mentioned solutions there didn't help me, promptLayer.js wasn't mentioned in my logs though, its only complaining about the connection being refused on that port

**Comment by mxyng** [comment]
> ECONNREFUSED ::1:11434

> http://127.0.0.1:11434/

These addresses are not the same. Ensure CodeGPT is configured correctly with 127.0.0.1:11434. Alternatively, configure ollama with `OLLAMA_HOST=0.0.0.0`
