### ISSUE TITLE
[Linux] - Instructions for exposing Ollama doesn't work

### ISSUE THREAD

**Issue by SoloBSD** [jmorganca/ollama#1157]
Instructions for Linux on how to expose ollama doesn't work.

https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

For some reason when Ollama gets installed on Linux it creates:
/etc/systemd/system/ollama.service

So it seems it never processes 
/etc/systemd/system/ollama.service.d/environment.conf file

I tried to add:
Environment=OLLAMA_HOST=0.0.0.0:11434
under the [Service] section of /etc/systemd/system/ollama.service
but still doesn't take it.
There is already there an "Environment" statement which contains some paths. Didn't try to append the OLLAMA_HOST variable at the end, but created a new line down the existing one.

I only made it work issuing manually:
export OLLAMA_HOST=0.0.0.0:11434

**Comment by mxyng** [comment]
Did you run `systemctl daemon-reload` and `systemctl restart ollama` after creating the `environment.conf` file? Without these commands, systemd will not see the new configurations or restart ollama with the changes.

```
$ ss -tlnp | grep ollama
LISTEN 0      4096                                   127.0.0.1:11434      0.0.0.0:*    users:(("ollama",pid=7864,fd=3))
$ mkdir -p /etc/systemd/system/ollama.service.d
$ cat <<EOF >/etc/systemd/system/ollama.service.d/environment.conf
> [Service]
> Environment=OLLAMA_HOST=0.0.0.0
> EOF
$ ss -tlnp  | grep ollama
LISTEN 0      4096                                   127.0.0.1:11434      0.0.0.0:*    users:(("ollama",pid=7864,fd=3))
root@orac:/home/ollama# systemctl daemon-reload
root@orac:/home/ollama# systemctl restart ollama
root@orac:/home/ollama# ss -tlnp  | grep ollama
LISTEN 0      4096                                           *:11434            *:*    users:(("ollama",pid=7998,fd=3))
```

> There is already there an "Environment" statement which contains some paths.

You can have multiple `Environment` statements in systemd service configurations.

**Comment by SoloBSD** [comment]
Yes I ran both commands and for some reason I don't get the variable exported.
Only if I do it manually.

**Comment by mxyng** [comment]
What does `systemctl cat ollama` return? It will display the merged configuration. If `Environment=OLLAMA_HOST` is not in the outputs, it hasn't been configured correctly

**Comment by johnm-starling** [comment]
**Instructions for Configuring the `ollama` Service in Ubuntu**

*Note: These instructions have been tested on Ubuntu variants.*

1. **Edit Service Configuration**
   - Run the following command to edit the service configuration:
     ```bash
     sudo systemctl edit ollama.service
     ```
   - This command opens an editor for the `ollama.service.d/override.conf` file.

2. **Add Environment Variables**
   - In the opened editor, add the following lines under the `[Service]` section:
     ```ini
     [Service]
     Environment="OLLAMA_HOST=0.0.0.0:11434"
     Environment="OLLAMA_ORIGINS='*'"
     ```
   - *Important:* Do not omit the quotes around the environment variable values.

3. **Effect of Configuration**
   - These settings will configure the `ollama` service to listen on all interfaces on port 11434 and allow connections from any IP.

4. **Reload and Restart Service**
   - After editing the configuration, reload the systemd daemon and restart the `ollama` service:
     ```bash
     sudo systemctl daemon-reload
     sudo systemctl restart ollama.service
     ```

5. **Verify Service Status**
   - To check that the service is using the additional configuration file:
     ```bash
     sudo systemctl status ollama.service
     ```

6. **Check Open Ports**
   - Use the following command to view open ports and confirm if port 11434 is listening for communications:
     ```bash
     sudo ss -tuln
     ```
   - You should see port 11434 open and ready for communications on any interface and to any remote IP.

---

I have just tested this on my Ubuntu 23.10.1 but have also done the same in 22.04 variants including PopOS!.

**Comment by mxyng** [comment]
Yes, those are the instructions described in the [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network)

**Comment by johnm-starling** [comment]
The Environment statements are echo'd differently between the FAQ and what I have posted.

https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Environment=

"If you need to assign a value containing spaces or the equals sign to a variable, put quotes around the whole assignment. "

Environment="VAR1=word1 word2" VAR2=word3 "VAR3=$word 5 6"

**Comment by SoloBSD** [comment]
Hi, yeah,
Seems that the quotes are making the magic. 
Now it is working. 
Thanks!

**Comment by mxyng** [comment]
Good call. Updated the FAQ
