### ISSUE TITLE
Update the model name in the api doc

### ISSUE THREAD

**Issue by shenli** [jmorganca/ollama#1169]
Hi, I am new to Ollama. 

I followed the [Quickstart](https://github.com/jmorganca/ollama/tree/main#quickstart) to try Ollama with model Llama2. It is very easy to run and a very interesting project.

When I explored further in the [API doc](https://github.com/jmorganca/ollama/blob/main/docs/api.md), I found that the model names are not consistent. There are `llama2` and `llama2:7b` in the API doc. I met the issue like `{"error":"model 'llama2:7b' not found, try pulling it first"}% `.  From the [model library section](https://github.com/jmorganca/ollama/tree/main#model-library), I think `llama2` is the same as `llama2:7b`. But from [here](https://ollama.ai/library/llama2) I notice that `llama2` is actually `llam2:latest`. 
For the [API doc](https://github.com/jmorganca/ollama/blob/main/docs/api.md), do you think it is better to change all the `llama2:7b` to `llama2`? It is good for the people who are following the Quickstart.

**Comment by jmorganca** [comment]
Thanks for creating an issue! This has been updated on `main` 😊
