### ISSUE TITLE
Command line tool not getting registered

### ISSUE THREAD

**Issue by chsasank** [jmorganca/ollama#117]
Just downloaded mac package and running it is not registering command to command line.

**Comment by mchiang0610** [comment]
@chsasank This is a bug that we're fixing right now. 

In the meantime, you can manually add it to path via: 

```
sudo ln -s /Applications/Ollama.app/Contents/Resources/ollama /usr/local/bin/ollama
```

**Comment by mchiang0610** [comment]
If you don't mind, I'll close this issue and merge it with the previous one that's already open to keep it on one issue. 

https://github.com/jmorganca/ollama/issues/113
