### ISSUE TITLE
Update installed models

### ISSUE THREAD

**Issue by Bodo-von-Greif** [jmorganca/ollama#1171]
Hi all,

i wrote a small bash script to update the installed models.
Maybe its useful for some of you:

`
#/bin/bash

#Based on: ollama run codellama 'show me how to send the first colum named "name" of the list which is produced with ollama list with xargs to "ollama pull"'
echo "Actual models"
ollama list
echo
ollama list | grep -v "NAME" | awk '{print $1}' | xargs -I{} ollama pull {}
echo
echo "Updated models"
ollama list
`

**Comment by BruceMacD** [comment]
Thanks for the contribution @Bodo-von-Greif, resolving this for now as there doesn't seem to be any more work required here, but people will still be able to reference this in the future when they're searching.
