### ISSUE TITLE
error: invalid cross-device link

### ISSUE THREAD

**Issue by 0xRavenBlack** [jmorganca/ollama#1181]
Description:
When attempting to create a new model using the provided Hugging Face model (https://huggingface.co/TheBloke/Leo-Mistral-Hessianai-7B-Chat-GGUF) with the following command:

    ollama create game-mistral-7b -f ./Modelfile

an error occurs during the process, resulting in the following error message:

    transferring context Error: rename /tmp/sha256:9fa68a1621f99d387fe0c7f70b47cfecda9be0e7a02255499beb13d240a092104036603730 /usr/share/ollam/.ollama
    /models/blobs/sha256:9fa68a1621f99d387fe0c7f70b47cfecda9be0e7a02255499beb13d240a09210: invalid cross-device link`

Modelfile Contents:

```
FROM ./leo-mistral-hessianai-7b-chat.Q5_K_M.gguf

TEMPLATE """{{- if .System }}
<|im_start|>system {{ .System }}<|im_end|>
{{- end }}
<|im_start|>user
{{ .Prompt }}<|im_end|>
<|im_start|>assistant
"""

PARAMETER stop <|im_start|>
PARAMETER stop <|im_end|>

# set the system prompt
SYSTEM """
"""
```

Additional Information:
* Model Used: [Leo-Mistral-Hessianai-7B-Chat-GGUF](https://huggingface.co/TheBloke/Leo-Mistral-Hessianai-7B-Chat-GGUF)
* Ollama Version: v0.1.10
* Operating System: Arch Linux

Steps to Reproduce:
* Execute the command: ollama create game-mistral-7b -f ./Modelfile
* Observe the error mentioned above.

**Comment by jmorganca** [comment]
For any folks hitting this, the next release which will be out soon will include a fix for this. Sorry you received an error when creating models
