### ISSUE TITLE
Where is the model file stored?

### ISSUE THREAD

**Issue by happy15** [jmorganca/ollama#119]
Hi, first thanks for the awesome work.

Just wondering, where is the model file located?

**Comment by mchiang0610** [comment]
@happy15 it's hosted on a model registry via CloudFlare.

**Comment by mchiang0610** [comment]
Let me know if this answers your question. Feel free to join our discord: 

[Discord](https://discord.gg/MrfB5FbNWN)

**Comment by happy15** [comment]
I saw the pulling of large files (possibly docker layers?), I wonder where these files are located in my local disk. Thanks.

**Comment by happy15** [comment]
> Let me know if this answers your question. Feel free to join our discord:
> 
> [Discord](https://discord.gg/MrfB5FbNWN)

unable to accept the invitation

**Comment by mchiang0610** [comment]
@happy15, just tried the Discord invitation. It should work. 

The files once pulled are in layers, and are stored in: 
`~/.ollama/models`

**Comment by etareduction** [comment]
> I am using windows and built from source. When doing ./ollama pull _model_, I see a download progress bar. The folder C:\users*USER*.ollama\models gains in size (the same as is being downloaded). However no files with this size are being created. I have never seen something like this. The folder has the correct size, but it contains absolutely no files with relevant size. Just an empty directory "blobs".

Most probably it's just a hidden file/directory (name starts with dot)

**Comment by krisgesling** [comment]
For future visitors directed here via a web search - this is now answered in the FAQ:
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by CodeYoda** [comment]
Is there a way to have ollama store the models it downloads to a specified location?  I want to store them on a different, data drive

**Comment by amit-yaduwanshi-amla** [comment]
you can find the model at below folder paste the command on windows Run (Window key + R) 
C:\Users\%username%\.ollama\models
