### ISSUE TITLE
JSON mode when used from LangChain RAG

### ISSUE THREAD

**Issue by abaranovskis-redsamurai** [jmorganca/ollama#1191]
Hello,

I would like to ask if there are any plans to support JSON mode response, when Ollama is called from LangChain RAG?

Thanks.

**Comment by abaranovskis-redsamurai** [comment]
I found example of using Ollama JSON output here - https://github.com/jacoblee93/oss-model-extraction-evals/blob/main/run_evals.py, didn't had chance to run this code yet. But it looks like tightly coupled with OpenAI functions. I wonder if its possible to get JSON output through LangChain without using these functions?

**Comment by BruceMacD** [comment]
Hi @abaranovskis-redsamurai, the Langchain libraries are maintained by the Langchain team. At the moment I do see that the JavaScript library support JSON mode through their `OllamaFunctions` interface.
https://js.langchain.com/docs/integrations/chat/ollama_functions

**Comment by abaranovskis-redsamurai** [comment]
Thanks, I will check with Langchain team. I found sample Python notebook with OllamaFunctions (not in master branch): https://github.com/langchain-ai/langchain/blob/d84bb3899369d57f5c8dd081edc87ff75ecd79e1/docs/docs/integrations/chat/ollama_functions.ipynb
