### ISSUE TITLE
Are the models quantizated?

### ISSUE THREAD

**Issue by chsasank** [jmorganca/ollama#120]
Can you give more details on quantization level the models are running and if they can be changed?

**Comment by mchiang0610** [comment]
Right now, we curate models using 4-bit quantization. We do want to support changing quantizations in the future -- whether this is submitted by users or we curate them are to be decided. 

Hope this answers your question. 

Feel free to join our Discord to chat more! 

[Discord](https://discord.gg/MrfB5FbNWN)

Thanks
