### ISSUE TITLE
/admin Page Auth Key not working

### ISSUE THREAD

**Issue by Asher9971** [jmorganca/ollama#1205]
After a fresh install i need to input an Auth Key on the admin page.
![image](https://github.com/jmorganca/ollama/assets/11883647/a36825fe-27e7-4153-b8d3-be886fc7bcb9)

I generated one and pasted it in the compose-file.

`cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    #depends_on:
    #  - cheshire-cat-vector-memory
    #  - embedder
    #  - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - API_KEY=${API_KEY:-9da0f457-cecd-459e-********}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
      - ${CORE_PORT:-1865}:80
    volumes:
      - cheshire_cat_core_static:/app/cat/static
      - cheshire_cat_core_public:/app/cat/public
      - cheshire_cat_core_plugins:/app/cat/plugins
    restart: unless-stopped`

also tried without any API_KEY Variable in compose-file also didn't worked and i got the attempt to input an auth key on the /admin page

**Comment by BruceMacD** [comment]
Matt is correct, this looks like an issue with [Cheshire Cat](https://github.com/cheshire-cat-ai/core), please open the issue over there and they should be able to help you out.
