### ISSUE TITLE
Performance question?

### ISSUE THREAD

**Issue by kosecki123** [jmorganca/ollama#121]
This is just request for info rather than a bug.

What's kind of performance / latency on prompts we should expect running on M2 Pro ? Seems like takes up to 10s to generate the answers using `llama2` model. Is that something that can improve in the future?

**Comment by jmorganca** [comment]
Hi @kosecki123 . Absolutely. That 10 seconds is loading in the model, and we're working on making that much shorter!

Thanks for the issue!

**Comment by zhiyun-deng** [comment]
Why not keep the model loaded in between prompts? Providing such option would make the user experience much smoother.

**Comment by jmorganca** [comment]
@zhiyun-deng 💯 – the next release will do this! You can also test this out on `main`

**Comment by jmorganca** [comment]
Closing for now as the same model will stay loaded between prompts
