### ISSUE TITLE
\n Modelfile and path deprecated?

### ISSUE THREAD

**Issue by Luxadevi** [jmorganca/ollama#1217]
Hi, 

Could you tell me why you removed the "path" parameter from the /api/create endpoint?

And why the replacement of parsing the whole modelfile in the curl command?
Really struggeling to set up some python logic where \n is the escape character for a new line and it goes completly mental on it.
Would it be possible to have different syntaxing for this?

**Comment by BruceMacD** [comment]
Hey @Luxadevi sorry for the confusion. We switched over to using the `modelfile` parameter directly but `path` will continue to be supported for now (might get deprecated at some point in the future). 

I noticed that our python client didn't get updated, Im working on that now in this PR:
https://github.com/jmorganca/ollama/pull/1227
I think this could be of use to you.

**Comment by jmorganca** [comment]
Hi @Luxadevi. This totally makes sense. I've marked the `path` parameter as no longer deprecated
