### ISSUE TITLE
show ollama version

### ISSUE THREAD

**Issue by mchiang0610** [jmorganca/ollama#122]

**Comment by alivardar** [comment]
it is necessary for following release number

**Comment by BruceMacD** [comment]
Workaround for the moment is to check the "get info" on the Mac app

<img width="262" alt="image" src="https://github.com/jmorganca/ollama/assets/5853428/c74a6607-7391-45d4-9867-7a9b952cd0fe">

**Comment by alivardar** [comment]
I understand thank you for answer, I am using as a daemon user. I will check location that version information and i can add to app.

**Comment by foldfree** [comment]
Would be great to be able to run `ollama -v` or `ollama --version` and have the version number of the software being displayed as well as the version of the models installed.

**Comment by GitHubJobutex** [comment]
> Would be great to be able to run `ollama -v` or `ollama --version` and have the version number of the software being displayed as well as the version of the models installed.

I concur with this. I run the program exclusively from the Mac terminal screen and would like to be able to check and validate the version I run in that manner.

**Comment by mxyng** [comment]
`ollama -v` and `ollama --version` is implemented in #392.
