### ISSUE TITLE
Access ollama output directly on streamlit screen

### ISSUE THREAD

**Issue by arnram** [jmorganca/ollama#1220]
Hi,
I am in the process of developing a chatbot application using the RAG (Retrieval-Augmented Generation) technique alongside Ollama and LangChain. Initially, I successfully constructed the application using LangChain and achieved accurate responses displayed on the command-line interface (CLI). Subsequently, I attempted to create a graphical user interface (GUI) for the application. However, I encountered an issue where Ollama initially displays its output on the CLI before storing the string in a variable to provide it to Streamlit.

My concern pertains to accessing the direct output stream of Ollama within Streamlit, bypassing the CLI altogether. This direct access to the output stream of Ollama within the Streamlit interface would be more efficient and beneficial for my application's functionality.

Would you like guidance on how to redirect Ollama's output stream directly to Streamlit within your application?

**Comment by BruceMacD** [comment]
Hi @arnram, it sounds like the [Ollama API](https://github.com/jmorganca/ollama/blob/main/docs/api.md) is what you are looking for. You can call this to get responses from the LLM directly without using the CLI.

**Comment by marcellodesales** [comment]
@arnram I've been writing a Streamlit-based framework so that it can talk to any Ollama server using the API described by @BruceMacD... Maybe someone wants to help out :)

**Comment by arnram** [comment]
@BruceMacD, it is possible to directly get the feed o/p of ollama to any variable and without displaying it on the screen

**Comment by technovangelist** [comment]
Not sure exactly what you are asking here. With the Ollama API you can make a request to the /api/generate endpoint, and then process the json response and set that to any variable.

**Comment by arnram** [comment]
from langchain.document_loaders import WebBaseLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
data = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
all_splits = text_splitter.split_documents(data)

# Embed and store
from langchain.embeddings import (
    GPT4AllEmbeddings,
    OllamaEmbeddings,  # We can also try Ollama embeddings
)
from langchain.vectorstores import Chroma

vectorstore = Chroma.from_documents(documents=all_splits, embedding=GPT4AllEmbeddings()

# RAG prompt
from langchain import hub

QA_CHAIN_PROMPT = hub.pull("rlm/rag-prompt-llama")


# LLM
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.llms import Ollama

llm = Ollama(
    model="llama2",
    verbose=True,
    callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),
)

# QA chain
from langchain.chains import RetrievalQA

qa_chain = RetrievalQA.from_chain_type(
    llm,
    retriever=vectorstore.as_retriever(),
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
)

question = "What are the various approaches to Task Decomposition for AI Agents?"
result = qa_chain({"query": question})


I am using code for designing the chabot using RAG and ollama via langchain. As you can see langchain use Ollama() api for requestion the server. By using this method the respone is first print on cli and then store in the "result" variable. So my question is can you some method where I can use  ollama post request with langchain or any examples.

**Comment by mxyng** [comment]
>  callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),

This is explicitly streaming the response to stdout. If you want to save the output to a variable, you should use a different callback manager. Moreover, this appears to be an issue more fit for [langchain](https://github.com/langchain-ai/langchain) than ollama.

**Comment by technovangelist** [comment]
Since you are using langchain there are many examples in their documentation
