### ISSUE TITLE
Support for Intel Macs

### ISSUE THREAD

**Issue by VicariousVision** [jmorganca/ollama#123]
Hi When can we expect to hear feedback regadring the future of this? Maybe I could help out?

**Comment by mchiang0610** [comment]
@VicariousVision We are currently working on a universal binary for mac.

**Comment by jmorganca** [comment]
Update: The latest version of Ollama now runs on Intel Macs. There are some performance improvements to be had and a few errors that may occur on machines running macOS older than Big Sur.

**Comment by jmorganca** [comment]
Closing for now as this was shipped
