### ISSUE TITLE
 Incorrect Version Displayed with Command: ollama --version 

### ISSUE THREAD

**Issue by Samk13** [jmorganca/ollama#1230]
When running the version command, the output incorrectly displays ollama version 0.0.0 instead of the expected version:

```bash
ollama --version 
ollama version 0.0.0
```

expected behavior:
```bash
ollama --version 
ollama version  0.1.11
```

Current Ollama version: `V0.1.11`
Running on `WSL2 Ubuntu 22.04.3 LTS`

**Comment by jmorganca** [comment]
Sorry about the hiccup. This should be fixed now – you'll need to [Download Ollama](https://ollama.ai/download/linux)
