### ISSUE TITLE
Running multimodal models

### ISSUE THREAD

**Issue by austin-starks** [jmorganca/ollama#1235]
Hello! I don't know if this is a feature request or already possible using ollama, but I was wondering how can I easily run a multimodal model (such as [minigpt-4](https://minigpt-4.github.io)) I'm happy to assist in whatever way I can, but I'm very much new to this type of development.

**Comment by dimfeld** [comment]
There’s a PR open for supporting multimodal, so it should be supported soon-ish :)

https://github.com/jmorganca/ollama/pull/1216

**Comment by austin-starks** [comment]
Awesome! I'll very much be on the lookout. Thank you for your response! This project is literally amazing
