### ISSUE TITLE
Multi-line prompting from CLI issue - not waiting for closing """

### ISSUE THREAD

**Issue by ken-vat** [jmorganca/ollama#1241]
THe engine started to spew out code before ending the multi-line with closing """. as an example -

>>> """
... can you give python code to use this API using the python requests package/library
... curl -X POST \
...      --url "localhost:5000/v1/..." \
...      --header "Content-Type: application/json" \
...      --data '
... {
...   "chat": "string"
... }
... '
    
Here is an example of how you can use the `requests` package in Python to make a POST request to the `/v1/completions` 
endpoint ...

It started response right after this curl command before giving closing """

**Comment by mxyng** [comment]
This should be fixed by #1614
