### ISSUE TITLE
Set system prompt in `ollama run`

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1243]
We can see the system prompt with /show system, but have no way to set it. I would be nice to be able to set it from the command line.

**Comment by jmorganca** [comment]
Thanks for creating an issue. @pdevine is the mastermind behind much of the `ollama run` experience, but I would presume we'll most likely want `/set system "<system>"`

**Comment by pdevine** [comment]
Great suggestion! I actually had this working, but had forgotten to send out a PR. I'll see if I can find the code again.

**Comment by iplayfast** [comment]
Glad it's in the queue. (waiting patiently)

**Comment by iplayfast** [comment]
Thanks, I'm using it!
