### ISSUE TITLE
"Model" not found, try pulling it first

### ISSUE THREAD

**Issue by rehberim360** [jmorganca/ollama#1254]
Hello everyone. I host Ollama in google VM. All firewall settings etc. have been made. I am connecting remotely via API.

![1](https://github.com/jmorganca/ollama/assets/144798027/7c3ff8ed-aefd-44e9-978a-de48b9e8774d)

I pulled my models while in Ollama service start.

![2](https://github.com/jmorganca/ollama/assets/144798027/414266cd-fae5-4033-9265-ce2d30f6ae7f)

But no matter which model I pulled,

![3](https://github.com/jmorganca/ollama/assets/144798027/89f8a02b-3866-4acd-a161-6b9eb3e18c44)

**Comment by easp** [comment]
What do you get if you

```
curl http://GOOGLEVMIP:11434/api/show -d '{
  "name": "llama2-uncensored"
}'
```

**Comment by rehberim360** [comment]
![4](https://github.com/jmorganca/ollama/assets/144798027/840d2997-8c3c-481b-be78-8e28aef79d08)
``

**Comment by BruceMacD** [comment]
Hi @rehberim360, if you're behind a firewall you probably need to configure the `HTTPS_PROXY` environment variable.
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

Have you tried that?

**Comment by technovangelist** [comment]
did you try the proxy env var??

**Comment by mxyng** [comment]
It looks like you're trying to use `llama2-uncensored` but you pulled `llama2`. These are different models. Please pull `llama2-uncensored`

**Comment by technovangelist** [comment]
Hi @rehberim360, we haven't heard back from you. Did the solution proposed by @BruceMacD work for you? I'll go ahead and, assuming it's solved, close the issue for now. If you see this, and it didn't work, feel free to reopen the issue, and we can try to solve it again. Thanks so much for being a great part of this community.

**Comment by shivaprasadyanala** [comment]
@technovangelist 
when i try to do ollama serve 
i'm getting Error: listen tcp 127.0.0.1:11434: bind: address already in use
but how can i use ollama outside of the instance by calling it from postman
