### ISSUE TITLE
ollama listreg

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1255]
We can pull from the registry with ollama pull,
We can push to the registry with ollama push,
we don't have any way (that I can see) of seeing what's in the registry.
I propose ollama listreg

**Comment by easp** [comment]
a way to search the library from the cli would also be useful, perhaps moreso, as the library grows

**Comment by mchiang0610** [comment]
@iplayfast thank you for submitting this! Currently, there is search feature on the website, but still need to expose others' models that are public. 

Now, we definitely should have an API for the library for others to search and see what's in the library.

**Comment by iplayfast** [comment]
So If I'm working with cli how do I search the website? My proposal is to extend the existing command set by one command so it is consistant with the push and pull commands.  (I also feel this was closed prematurely).
