### ISSUE TITLE
Quantizated models availability in the default library

### ISSUE THREAD

**Issue by guinanet** [jmorganca/ollama#1269]
I've being using [text-generation-webui](https://github.com/oobabooga/text-generation-webui) to load 3 bit quantized models to fit my GPU memory (a GTX 1650, 4GB dedicated memory). I usually go to the user [TheBloke hugging Face](https://huggingface.co/TheBloke) page and check if there is a compatible model. It is a straightforward process, very easy to acomplish requiring just the path and the models name (mostly GGUF format). Most the times they provide the template for instruction tasks, and I practically don't have to touch a single line in any configuration file to work. I'm satisfied with the inference process, and I get stable results that range from 10 to 15 tokens / s.

About your project, the ollama, when I saw the available library, I couldn't load practically any model because anything >= 4 bit precision is too much for my GPU memory.

I'm here to ask, if it's not a difficult task, and if you trust users like TheBloke, to make these quantized models available to use by a simple "one click" install in your UI. These models are already available and free to use. I'm asking a practial UI to use them with few steps without the need to write configuration files for them to work.

Thanks!

**Comment by guinanet** [comment]
I'm very sorry, I'm writing this without testing the new updates (I tested long time ago). I see that there are some quantized models now.

Maybe I'm asking just a better integration with Hugging Face.

Anyway, thank you so much. Now I can test some models with your app!

**Comment by jmorganca** [comment]
Thanks @guinanet, I really appreciate you creating an issue. Keep an eye on https://github.com/jmorganca/ollama/issues/1267!
