### ISSUE TITLE
Specify where to download and look for models

### ISSUE THREAD

**Issue by Talleyrand-34** [jmorganca/ollama#1270]

**Comment by igorschlum** [comment]
Hi @Talleyrand-34 could you provide a description or close this Issu?
If your question is related on where your models are stored on you computer, on mac they are store in this folder.
/Users/igor/.ollama/models/manifests/registry.ollama.ai/library

**Comment by Talleyrand-34** [comment]
Sorry for not being accurate enough. When pulling and running models add the option (flag in cli) to specify where to download temporary and final files

**Comment by technovangelist** [comment]
All models are saved to the directory @igorschlum mentioned on mac, or to /usr/share/ollama/.ollama/models on Linux. Or if you set OLLAMA_HOME, then you can put them anywhere.

**Comment by igorschlum** [comment]
@technovangelist Is it possible to share LLM files between different users on MacOS? They could be put in

/Users/Shared/Library/Application\ Support

**Comment by Talleyrand-34** [comment]
(1)(deck@steamdeck test)$ OLLAMA_HOME=~/.ollama/models/
(deck@steamdeck test)$ ollama pull orca-mini
pulling manifest 
pulling 66002b78c70a...  39% ▕███████████████████████████████                                                 ▏(780 MB/2.0 GB, 3.6 MB/s)        [5m8s:1m8s]
Error: write /usr/share/ollama/.ollama/models/blobs/sha256:66002b78c70a22ab25e16cc9a1736c6cc6335398c7312e3eb33db202350afe66-partial: no space left on device

**Comment by technovangelist** [comment]
You included the solution in your example. You need to set OLLAMA_MODELS. But you need to set it for the `serve` process. I assume you are on Linux, so check out https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models

**Comment by Talleyrand-34** [comment]
> You included the solution in your example. You need to set OLLAMA_MODELS. But you need to set it for the `serve` process. I assume you are on Linux, so check out https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models

It is not the solution, i want to specify where to download models and where the temporary folder should be place. As it is seen in my previous message the process fails due to i cannot specify the temporal folder. When i revised the code i saw that the temporary folder could not be modified by any chance, it is a string embedded in the code
