### ISSUE TITLE
Install clobbers /etc/systemd/system/ollama.service file destroying any custom configurations like specifying IP or PORT being served or preventing cors errors

### ISSUE THREAD

**Issue by Dougie777** [jmorganca/ollama#1278]
Upgrading to the latest version clobbers my /etc/systemd/system/ollama.service file. If the file exists it should not be overwritten. Or the distro should only include a sample file like so /etc/systemd/system/ollama.service.sample

To Reproduce

1 Install ollama as a service using docs.
2 Customize /etc/systemd/system/ollama.service like adding:
Environment=OLLAMA_HOST=0.0.0.0
Environment=OLLAMA_ORIGINS=*
3 Upgrade to the latest ollama version

Expected behavior

/etc/systemd/system/ollama.service is overwritten, destroying any customizations to this file.

**Comment by jmorganca** [comment]
Sorry this happened. Will look into it what can be done to avoid losing any customizations!

**Comment by wrapss** [comment]
As specified in the faq, you can enter your environment variables in /etc/systemd/system/ollama.service.d/environment.conf and they will not be overwritten

**Comment by Dougie777** [comment]
I will move my customations to etc/systemd/system/ollama.service.d/environment.conf

Thanks all!
