### ISSUE TITLE
Auto Shutdown/kill

### ISSUE THREAD

**Issue by borisnachtsheim** [jmorganca/ollama#1290]
Hi guys,

i just managed to run a zephyr model with ollama on my small ubuntu server and call the model from my home computer. Everything works fine but after couple of minutes i get this auto kill:

2023/11/27 22:28:29 llama.go:435: signal: killed
2023/11/27 22:28:29 llama.go:509: llama runner stopped successfully

Then I have to manually redo ollama serve. 

How can I prevent this auto shutdown?

BJ

**Comment by mchiang0610** [comment]
@borisnachtsheim were there other logs? Wanted to track this down so we can fix it

**Comment by mxyng** [comment]
Closing this since there hasn't been an update in some time and the original issue looks normal
