### ISSUE TITLE
ollama runpod serverless template

### ISSUE THREAD

**Issue by devsaturn** [jmorganca/ollama#1291]
is there an example of deploy a model using an ollama in a runpod serverless ?

**Comment by pooyahrtn** [comment]
@devsaturn I created [this](https://medium.com/@pooya.haratian/running-ollama-with-runpod-serverless-and-langchain-6657763f400d) blog about doing that.

**Comment by devsaturn** [comment]
thank you for your article which really helped me . But cold start is very slow, it downloads the manifest at each request.

**Comment by pooyahrtn** [comment]
> thank you for your article which really helped me . But cold start is very slow, it downloads the manifest at each request.

@devsaturn glad to hear. That’s true, however, with their “FlashBoot” option on, I found consecutive requests pretty fast.

**Comment by devsaturn** [comment]
@pooyahrtn yep very fast! do you have a stream version ?

**Comment by devsaturn** [comment]
@pooyahrtn can we caching model in volume to improve model loading ?

**Comment by devsaturn** [comment]
@pooyahrtn i get sometime this error: OCI runtime pause failed: unable to freeze: unknown
