### ISSUE TITLE
All models gone?

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1296]
I have no idea what happened. Started working ran 
ollama run alfred
Error: could not connect to ollama server, run 'ollama serve' to start it
(alfred was previously installed)

ollama serve &
ollama run alfred
started downloading it!

Olama list
all the models are gone.
in /usr/share/ollama/.ollama/models/blobs there are a lot of files some are large. so I think that's them. 

but ollama doesn't know about them.

**Comment by technovangelist** [comment]
In the FAQ under docs in the repo is a look at how we store models. Also, based on your description you were running as two different users. The systemctl command runs ollama as the user ollama, but running ollama serve runs ollama as you. And the ollama run as you knows nothing about the models downloaded by the user ollama. Based on your description, it seems to be working as expected. I'll close this issue. Thanks so much for being a great Ollama user.
