### ISSUE TITLE
new good models

### ISSUE THREAD

**Issue by eramax** [jmorganca/ollama#1300]
Hi,
Please publish these new models 
https://huggingface.co/TheBloke/Starling-LM-7B-alpha-GGUF
https://huggingface.co/TheBloke/MergeMonster-13B-20231124-GGUF

**Comment by jmorganca** [comment]
Starling LM is now available here: https://ollama.ai/library/starling-lm

**Comment by eramax** [comment]
> Starling LM is now available here: https://ollama.ai/library/starling-lm

Great, Thanks
