### ISSUE TITLE
Wrong Prompt on Library Starling-lm Modelfile

### ISSUE THREAD

**Issue by fakezeta** [jmorganca/ollama#1314]
Hi,

prompt in library model [starling-lm](https://ollama.ai/library/starling-lm:latest) is wrong.
Later has been fixed ([in this thread](https://huggingface.co/TheBloke/Starling-LM-7B-alpha-GGUF/discussions/1#6566093f8556065b5238eeb2)) that it must be:

`GPT4 User: {prompt}<|end_of_turn|>GPT4 Assistant:`

I've tested locally with the following Modelfile:
```
FROM starling.gguf
TEMPLATE """{{ .System }} GPT4 User: {{ .Prompt }}<|end_of_turn|>GPT4 Assistant:"""
PARAMETER num_ctx 4096
PARAMETER stop "<|endoftext|>"
PARAMETER stop "<|end_of_turn|>"
```

Naturally, `num_ctx` can be omitted.

**Comment by jmorganca** [comment]
Thanks! This is fixed now
