### ISSUE TITLE
Installation fails on Fedora 39 (38+)

### ISSUE THREAD

**Issue by cephalization** [jmorganca/ollama#1326]
Nvidia hasn't uploaded specific cuda drivers for later versions of fedora here https://developer.download.nvidia.com/compute/cuda/repos/

So, installation fails when trying to install them for 38 and 39.

To fix, you can follow the steps for Fedora 35 and later here https://rpmfusion.org/Howto/CUDA

```sh
sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/cuda-fedora35.repo
sudo dnf clean all
sudo dnf module disable nvidia-driver
sudo dnf -y install cuda
```

And then redo the ollama install.

Everything seems to work afterwards

**Comment by supercheetah** [comment]
The installer really shouldn't be using NVidia's repo for this.  It's generally recommended to use RPMfusion for these drivers, which are kept up-to-date with the NVidia repo, but ensure they work on later versions.
