### ISSUE TITLE
Modelfile prompt should support chat / multiturn.

### ISSUE THREAD

**Issue by ehartford** [jmorganca/ollama#1327]
https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#template

So basically all that's coming in is .Prompt which is just a string.

But that can't handle chat and multi turn.

What's coming in should look a messages array. then this template should format that into a prompt.
```
[
  { "role": "system", "content": "You are a helpful AI assistant" },
  { "role": "user", "content": "Hello AI, How are you today?" },
  { "role": "assistant", "content": "I have no notion of time.  State your question?" },
  { "role": "user", "content": "Oh ok then, tell me the 38th state" }
]
```

then the template in the modelfile would look something like

```
{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}<|im_start|>assistant

```

Basically the idea that a prompt consists of a single system message and a single user message, isn't how most models actually work.

**Comment by BruceMacD** [comment]
Hey Eric, I just merged a `/chat` API that will be in the next release which should cover this.

Here's the doc:
https://github.com/jmorganca/ollama/blob/main/docs/api.md#send-chat-messages

It uses messages in the same format that you've suggested here. The template in the Modelfile is still the same right now, but the behavior matches what you suggested here too (templating for each set of messages).

Thanks for the feedback let us know if you notice anything else that doesn't seem right.
