### ISSUE TITLE
build issue server/routes.go:70:20: undefined: llama.New

### ISSUE THREAD

**Issue by nona00** [jmorganca/ollama#133]
I'm not able to build from git source:

root@debian:~/Downloads/ollama# go build .
# github.com/jmorganca/ollama/server
server/routes.go:70:20: undefined: llama.New

root@debian:~/Downloads/ollama# cat /etc/debian_version 
12.0

root@debian:~/Downloads/ollama# go version
go version go1.20.6 linux/amd64

**Comment by jmorganca** [comment]
Hi @nona00 

We'll look into why this is happening!

In the meantime, try running with:

```
CGO_ENABLED=1 go build .
```

**Comment by nona00** [comment]
Thank you very much, with this command I was able to build successfully.

**Comment by BruceMacD** [comment]
Related, and also resolved:
https://github.com/jmorganca/ollama/issues/158
