### ISSUE TITLE
Set conversation or chat history/context in CLI

### ISSUE THREAD

**Issue by Maharshi-Pandya** [jmorganca/ollama#1346]
Thank you for making this!

I tried the `/set history` command within the CLI and expected it to work.
I would like to use the CLI as a chatbot itself having access to conversation history (a window of messages if not whole).

What is the process to set the conversation history as context in `Openhermes-mistral` specifically?

Here is the bug:
<img width="1070" alt="image" src="https://github.com/jmorganca/ollama/assets/53078775/c6033c8b-5054-41a8-9977-9a0e0ab8b130">

**Comment by BruceMacD** [comment]
Hi @Maharshi-Pandya, this should work, here is my test for reference:
<img width="750" alt="image" src="https://github.com/jmorganca/ollama/assets/5853428/c1b363d5-3135-492f-8dea-829a43459424">

I'd suggest making sure you're on the latest ollama release, it could also have been some weirdness with the model so it is worth another shot.
