### ISSUE TITLE
starcoder not running

### ISSUE THREAD

**Issue by Darkseid1981** [jmorganca/ollama#1353]
I don't know how to fix this, every time I try to run "ollama run starcoder" it starts up and then gives me this error "Error: llama runner process has terminated" is there any particular reason this is happening?

I'm running
Debian 12 bookworm
with the LXQT Desktop 
on a Levnovo G-585
with 4gb ram
and about 30gb free disk space.

**Comment by technovangelist** [comment]
The starcoder:3b model should be able to load in 4gb of ram. But its possible you have other stuff running. can you try using ollama without the desktop running, just using the terminal and ensure nothing else is running?

**Comment by technovangelist** [comment]
Hi @Darkseid1981 are you still experiencing this issue? I am assuming you figured it out, so I will go ahead and close the issue for now. If you see this and are still experiencing the issue, please go ahead and reopen it so we can figure out what is going on here. Thanks so much for being an incredible part of this fantastic community.
