### ISSUE TITLE
Running inside a docker. Need -ip or --host parameter to change the interface.

### ISSUE THREAD

**Issue by phalexo** [jmorganca/ollama#1355]
something like 

ollama serve --ip 0.0.0.0

It defaults to the localhost 127.0.0.1 which is not usable for my setup.

Is there some way to specify an interface and a port?

**Comment by oliverbob** [comment]
Start ollama by:

`OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve`

and not with:

`ollama serve`

Or when you are using docker, do it this way:

docker run -d -v ./ollama -p 11434:11434 -e OLLAMA_ORIGINS="*" --name ollama ollama/ollama

Please check available docs in this repo or refer to this [Thread on this repo](https://github.com/jmorganca/ollama/issues/1179#issuecomment-1817099547).

**Comment by technovangelist** [comment]
It looks like oliverbob's comment solves your issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
