### ISSUE TITLE
Can't clone repo on Windows directly: invalid path library/modelfiles/llama2:13b

### ISSUE THREAD

**Issue by nathanleclaire** [jmorganca/ollama#137]
Weird result trying to clone repo on my Windows computer. 

```
error: invalid path 'library/modelfiles/llama2:13b'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by BruceMacD** [comment]
I think this was caused by file names not being allowed to contain `:` on windows. Might be fixed now on main:
https://github.com/jmorganca/ollama/pull/146

As a workaround using the WSL shell might work.

**Comment by nathanleclaire** [comment]
Ah got it yea this issue is more specifically about cloning the repo itself, I bet https://github.com/jmorganca/ollama/commit/6a19724d5f48b593a2519293b8485d528796ef7c fixed that 

Do have it running on WSL :)
