### ISSUE TITLE
Is it possible to add model and prompt params like max_tokens or temperature?

### ISSUE THREAD

**Issue by TumblerWarren** [jmorganca/ollama#1380]
It would be great if I could set params like temperature and max_tokens.
Also is it possible to turn of streaming?

**Comment by technovangelist** [comment]
Yes, you can add custom models and set parameters like temperature and others. take a look at https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md for more about setting parameters and adding models, and then https://ollama.ai/signup to signup to push models. I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by davidsyoung** [comment]
Now that we have openai external api usage (woo) to use other backends (notably I am using TabbyAPI for ExLlamav2), it would be great to be able to set max_tokens in the settings. 

Or, alternatively, add a model from the external API /models endpoint. I tried to create a modelfile, but it doesn’t seem that I can as it tries to pull a model with that name. 

Thanks again, awesome work lately.
