### ISSUE TITLE
litellm leaves defunct processes behind

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1382]
I'm not sure who's at fault here. 
https://github.com/BerriAI/litellm/issues/992

litellm -m ollama/alfred
litellm -m ollama/mistral
run an autogen application that uses these guys
The autogen get's stuck, so you must ctrl-c out.
The ollama models you started are now defunct

If on a linux system you do
ps aux | grep ollama
it will show things like:
ps aux | grep ollama
ollama 1581 0.0 0.0 4365940 17680 ? Ssl Dec01 0:47 /usr/local/bin/ollama serve
chris 735058 0.1 0.0 2740828 16376 pts/6 Sl+ Dec03 1:46 ollama run starling-lm
chris 1237946 0.4 0.0 2814560 16280 pts/8 Sl+ 12:11 1:25 ollama run orca2:13b
chris 1290228 0.2 0.0 299108 123796 pts/9 Sl 17:14 0:04 /home/chris/anaconda3/envs/autogen/bin/python /home/chris/anaconda3/envs/autogen/bin/litellm -m ollama/alfred --port 9000
chris 1290229 0.2 0.0 371844 123444 pts/9 Sl 17:14 0:04 /home/chris/anaconda3/envs/autogen/bin/python /home/chris/anaconda3/envs/autogen/bin/litellm -m ollama/DeepSeek-Coder --port 9001
chris 1290230 0.2 0.0 224088 123660 pts/9 S 17:14 0:04 /home/chris/anaconda3/envs/autogen/bin/python /home/chris/anaconda3/envs/autogen/bin/litellm -m ollama/starling-lm --port 9002
chris 1290243 0.0 0.0 0 0 pts/9 Z 17:14 0:00 [ollama]
chris 1290244 0.0 0.0 0 0 pts/9 Z 17:14 0:00 [ollama]
chris 1290245 0.0 0.0 0 0 pts/9 Z 17:14 0:00 [ollama]
chris 1290540 0.4 0.1 1501464 155380 pts/12 Sl+ 17:18 0:05 /home/chris/anaconda3/envs/panel/bin/python3.11 /home/chris/anaconda3/envs/panel/bin/panel serve panel_autogenollama.py
ollama 1291438 1592 3.9 5711180 5139892 ? S<l 17:24 246:30 /tmp/ollama236051357/llama.cpp/gguf/build/cpu/bin/ollama-runner --model /usr/share/ollama/.ollama/models/blobs/sha256:92da6238854f2fa902d8b2ad79d548536af1d3ab06821f323bd5bbcea2013276 --ctx-size 2048 --batch-size 512 --n-gpu-layers 110 --embedding --port 54099
chris 1367452 0.0 0.0 9528 2400 pts/13 S+ 17:40 0:00 grep --color=auto ollama

**Comment by technovangelist** [comment]
I am not sure what the problem is. Are you seeing different copies of ollama running? This must be a feature of litellm because we will only have a single server. So i think you need to ask litellm.

**Comment by iplayfast** [comment]
Git hub is hiding the defunct processes. (angle brackets), The porcesses 1290243,4,5 are zombie processes. This occurs when the child process is kill but the parent process lives on. I'm not sure of the resolution, but I think the parent process isn't spawning the child process correctly so it's an independent process.

**Comment by krrishdholakia** [comment]
@mxyng what's a good fix we can implement on our end to prevent this from happening?

**Comment by mxyng** [comment]
Subprocesses started with `Popen` should be cleaned up. This is usually done with `subproc.communicate()` but that's a blocking call. In Python 3, I would normally suggest using `asyncio` to manage processes but you can also `threading` or `multiprocessing`
