### ISSUE TITLE
ollama push {model} - 401 Couldn't Authorize

### ISSUE THREAD

**Issue by josiahbryan** [jmorganca/ollama#1387]
Even after adding the contents of ` ~/.ollama/id_ed25519.pub` to the SSH keys section of my Ollama `josiahbryan` account, I still got:
```
% ollama push josiahbryan/dragon-mistral-7b-v0-q4
retrieving manifest 
Error: on pull registry responded with code 401: {"message":"Couldn't authorize"}
```

Suggestions?

**Comment by mxyng** [comment]
This has been fixed. Sorry for the inconvenience
