### ISSUE TITLE
Description of models in the ollama page

### ISSUE THREAD

**Issue by lfoppiano** [jmorganca/ollama#1388]
I cannot find the meaning part of the naming convention of the models. For example: 

https://ollama.ai/library/starling-lm:7b-alpha-q4_K_M

It's clear that q4 indicate the bit of quantization, but what do K and M mean? 

Thanks

**Comment by easp** [comment]
S, M & L stand for small, medium and large. K refers, I think, to the quantization method, which, I think, uses K-means clustering.

**Comment by lfoppiano** [comment]
Thanks! but I'm wondering, for such models, what small, medium and large mean? I though that the number of parameters was the scale indication 🤔

**Comment by easp** [comment]
Good question. I should have been more clear. The sizes are relevant to the quantization. So, within the 4-bit K-quantization there are the option of Small and Medium variants. For the 3-bit, there are S, M & L,

From: https://github.com/ggerganov/llama.cpp/blob/5f6e0c0dff1e7a89331e6b25eca9a9fd71324069/examples/make-ggml.py#L16C1-L37C51
```
Old quant types (some base model types require these):
- Q4_0: small, very high quality loss - legacy, prefer using Q3_K_M
- Q4_1: small, substantial quality loss - legacy, prefer using Q3_K_L
- Q5_0: medium, balanced quality - legacy, prefer using Q4_K_M
- Q5_1: medium, low quality loss - legacy, prefer using Q5_K_M

New quant types (recommended):
- Q2_K: smallest, extreme quality loss - not recommended
- Q3_K: alias for Q3_K_M
- Q3_K_S: very small, very high quality loss
- Q3_K_M: very small, very high quality loss
- Q3_K_L: small, substantial quality loss
- Q4_K: alias for Q4_K_M
- Q4_K_S: small, significant quality loss
- Q4_K_M: medium, balanced quality - recommended
- Q5_K: alias for Q5_K_M
- Q5_K_S: large, low quality loss - recommended
- Q5_K_M: large, very low quality loss - recommended
- Q6_K: very large, extremely low quality loss
- Q8_0: very large, extremely low quality loss - not recommended
- F16: extremely large, virtually no quality loss - not recommended
- F32: absolutely huge, lossless - not recommended
```

**Comment by lfoppiano** [comment]
I understand, thanks.

**Comment by b-a0** [comment]
And is there a difference between upper and lower case letters?

![image](https://github.com/user-attachments/assets/b8a450e5-8cfe-447e-8a56-a9b68eeaa74d)

**Comment by github12101** [comment]
Good question!
