### ISSUE TITLE
`ollama create` not working

### ISSUE THREAD

**Issue by almonk** [jmorganca/ollama#1390]
Following the `Modelfile` tutorial in the readme, I can't get `ollama create` to work.

My modelfile is as follows:
```
FROM codellama:13b-instruct 

SYSTEM """
You are Mario from super mario bros, acting as an assistant.
"""
```

When I attempt to create from the modelfile, I get the following error:

```
transferring model data
pulling model
pulling manifest
Error: pull model manifest: file does not exist
```

I have pulled the `codellama:13b-instruct` model to my machine and succesfully run it.

I'm using a M2 Macbook running ollama `0.1.13`

**Comment by phalexo** [comment]
I think "create" is used for models you have already downloaded, i.e. it is a file you specify, not model name.

otherwise you just do

ollama run codellama2

with whatever name on Hugging Face.

**Comment by almonk** [comment]
@phalexo the docs imply that you can reference a model in this way https://github.com/jmorganca/ollama#customize-a-prompt

**Comment by mxyng** [comment]
This is a bug. There appears to be a space in the FROM line so it's looking for `codellama:13b-instruct<space>`. As a workaround, removing the space should work as expected.
