### ISSUE TITLE
Model filenames (are incompatible with other programs)

### ISSUE THREAD

**Issue by marco-trovato** [jmorganca/ollama#1395]
I already have a folder with several LLM models, each one can be 20-40 GB.

ollama is unable to load them, i have to pull them again one by one, and they will so they will get saved by ollama according to their HASH, i.e.:

`.../ollama_models/blobs/sha256:843d506c69eed7ece9a1584965be88421d9774a82bffd59e992d5a73eac2dee0`

Of course I could run (it works): 
`python3 ./koboldcpp.py --useclblast 0 0 --gpulayers 20 --model /mypath/ollama_models/blobs/sha256:843d506c69eed7ece9a1584965be88421d9774a82bffd59e992d5a73eac2dee0`

But am I am supposed to save a second copy of all those 200 GB files just because the filename are expected like this by ollama?

PROPOSED SOLUTION:
**Please save the filenames as their model name, i.e.: "wizardcoder_34b-python-q4_K_M.bin"** since everyone has a "LLM-models" folder already full of huge files

**Comment by mchiang0610** [comment]
Thanks for submitting this! This is related to the model export and import feature request on #335. Closing this so we don't have duplicates, and definitely happy to continue the conversation there.
