### ISSUE TITLE
No concurrent query. Error: unexpected end of response

### ISSUE THREAD

**Issue by fxrobin** [jmorganca/ollama#1397]
Trying to simultaneously quering Ollama results in a failure :

The first query is "served" but the second is ignore.

First request : 

![image](https://github.com/jmorganca/ollama/assets/16342334/70140b70-84ba-42d0-8755-79684a506ac3)

Second request in parallel : 

![image](https://github.com/jmorganca/ollama/assets/16342334/600b1753-9912-4bbd-b9dc-84d390d3f143)

Is it a limitation of Ollama ?

**Comment by contextcompanion** [comment]
I'm working on an app which makes parallel requests. As of the latest version (0.1.13) I am seeing this issue as well. Prior to this version (though I don't know exactly which version I was using before this), issuing parallel requests would eventually yield a result for all outstanding requests (even if the processing was handled serially internally by the ollama service). This appears to be a regression in a recent version.

**Comment by pdevine** [comment]
should be fixed with #1445
