### ISSUE TITLE
Bug: API - Chat docs examples are using `api/generate` in URL instead of `api/chat`

### ISSUE THREAD

**Issue by calderonsamuel** [jmorganca/ollama#1398]
https://github.com/jmorganca/ollama/blob/32f62fbb8e0b1ecb4ec8369586562abce86c8e50/docs/api.md?plain=1#L317-L327

https://github.com/jmorganca/ollama/blob/32f62fbb8e0b1ecb4ec8369586562abce86c8e50/docs/api.md?plain=1#L366-L384

**Comment by jmorganca** [comment]
Thanks for the issue and sorry about this – should be fixed now!

**Comment by Joao-Pimenta** [comment]
I actually get <Response [404]> when I try to use the chat API. I was using:

url = "http://127.0.0.1:11434/api/generate"
data = {
        "model": "wizard",
        "stream": False,
        "prompt": prompt,
        "options":{
            "num_predict":50
        }
    }

And getting great results.
I was just now reading the documentation, trying to switch to a chat with history, and was still not able to make it work.
I now have:
url = "http://127.0.0.1:11434/api/chat"
data = {
        "model": "wizard",
        "stream": False,
        "messages": chats,
        "options":{
            "num_predict":50
        }
    }
where chats is [{'role': 'user', 'content': 'Test 1'}]. And I get <Response [404]>

**Comment by calderonsamuel** [comment]
I get the same when I use the docker ollama:latest image. I think we just need to wait until they sync it.

> I actually get <Response [404]> when I try to use the chat API. I was using:
> 
> url = "http://127.0.0.1:11434/api/generate" data = { "model": "wizard", "stream": False, "prompt": prompt, "options":{ "num_predict":50 } }
> 
> And getting great results. I was just now reading the documentation, trying to switch to a chat with history, and was still not able to make it work. I now have: url = "http://127.0.0.1:11434/api/chat" data = { "model": "wizard", "stream": False, "messages": chats, "options":{ "num_predict":50 } } where chats is [{'role': 'user', 'content': 'Test 1'}]. And I get <Response [404]>

**Comment by tbirand** [comment]
I'm also getting the same 404 api error with the docker container.
