### ISSUE TITLE
Optimum-NVIDIA - Unlock blazingly fast LLM inference in just 1 line of code

### ISSUE THREAD

**Issue by iplayfast** [jmorganca/ollama#1402]
This article looks like it would be worth while to implement a check to see if nvidia is installed and add that line of code. Looks like it's quantizing an 8 bit float. 

https://huggingface.co/blog/optimum-nvidia

**Comment by easp** [comment]
As always, it's important to understand the conditions under which the claimed speedup was achieved. In this case:

- High end GPU
- fp8 model weights
- Batch size of 4
- Using tansformers python package

Ollama doesn't use the transformers python package, so this isn't going to be a single line of code to implement.
It uses a batch size of 1, already uses quantized model weights, and uses other optimizations (through llama.cpp). The quantization alone probably accounts for a significant part of of the 2.6x speedup they reported on the 4090 GPU.
