### ISSUE TITLE
`ollama run` fails on start

### ISSUE THREAD

**Issue by j-sneh** [jmorganca/ollama#1405]
```
➜  ~ ollama run llama2
⠋   Error: template: :2:11: executing "" at <.Context>: can't evaluate field Context in type struct { First bool; System string; Prompt string }

➜  ~ ollama --version
ollama version 0.1.13
```

Ran into this issue after running `ollama run llama2`. Occurs if server is running or if not & issue persisted after updating the server.

**Comment by technovangelist** [comment]
Can you provide some more info on your setup? How did you install ollama? What platform are you on?

**Comment by pdevine** [comment]
Hey @j-sneh can you try `ollama pull llama2` and then try running it again?

**Comment by pdevine** [comment]
I think #1244 will partially fix this, but I think you're running a really old model that needs to be updated.

**Comment by j-sneh** [comment]
I'm on an M1 Mac, macOS Moneterey — re-pulling the model fixed the issue. My old copy of the model was a couple of months old.
