### ISSUE TITLE
404 error for api requests (docker llama/latest)

### ISSUE THREAD

**Issue by tbirand** [jmorganca/ollama#1408]
I wanted to make a separate issue here as this was mentioned by a few in another issue that is closed.

Step 1. Spin up a container from the ollama/latest docker image
Step 2. Run 
```
curl http://localhost:11434/api/chat -d '{
  "model": "mistral",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```
Step 3. See the 404 error

**Comment by mxyng** [comment]
The chat api hasn't been released yet so the latest docker image will not support it. A release is scheduled for the next couple of days at which time the docker image will be updated.

In the mean time, `/api/chat` is only available when building from source

**Comment by tbirand** [comment]
Amazing, thanks @mxyng
