### ISSUE TITLE
"debug" or full visibility mode

### ISSUE THREAD

**Issue by nathanleclaire** [jmorganca/ollama#141]
It can be difficult to figure out what is happening behind the scenes in convos. Would be nice to have a mode where the generated text passed to the LLM for prediction displayed fully inline for troubleshooting

**Comment by BruceMacD** [comment]
Seems like this might be resolved now:
https://github.com/jmorganca/ollama/commit/05e08d231032640efb3ffb46983165f0f924f1d0
