### ISSUE TITLE
Issue connecting to 11434 for local model query following sample

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [jmorganca/ollama#1411]
I'm following this example as a basis for getting started:
https://www.youtube.com/watch?v=tvs350imHLY
https://gist.github.com/mneedham/eec9246a5ce95dc792f2e73b16dfe78e

Everything is working good except for actually running the query:
`response = query_engine.query("What is my question?")`

Which throws an error connecting to the Ollama service that was started:
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa201bb77f0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Also tried this instead of query_engine.query - but same error:
```
url = "http://localhost:11434/api/generate"
data = {
    "model": "llama2",
    "prompt": "What is my question?"
}
response = requests.post(url, json=data)
```

Running:
WSL  -  Ubuntu 22.04.3 LTS
Python 3.10

Any help appreciated!!!!

**Comment by ayttop** [comment]
curl http://localhost:11434/api/chat -d "{\"model\": \"llama3.1:8b\", \"stream\": false, \"messages\": [{\"role\": \"user\", \"content\": \"Why is the sky green?\"}]}"

**Comment by Mugane** [comment]
> http://localhost:11434/api/chat -d "{"model": "llama3.1:8b", "stream": false, "messages": [{"role": "user", "content": "Why is the sky green?"}]}"

How to do this using the url only? Is it possible?
