### ISSUE TITLE
Windows install runs into errors

### ISSUE THREAD

**Issue by csaben** [jmorganca/ollama#1414]
after manual install instructions and
```go build```
I receive the following errors:
```
# github.com/jmorganca/ollama/readline
readline\readline.go:199:12: undefined: syscall.Kill
readline\readline.go:199:28: undefined: syscall.SIGSTOP
```
After messing with readline.go I just manage to get a .exe file that doesn't work

@deadcoder0904 or anyone who compiled on windows and got a working executable, could you describe how you did it?

**Comment by csaben** [comment]
> i didn't try to install it. didn't do it manually either.

Did you use wsl on windows?

**Comment by BruceMacD** [comment]
@csaben there was a change that added some unix specific system calls so the development build of windows broke. Just opened a fix.

**Comment by deadcoder0904** [comment]
> Did you use wsl on windows?

no. couldn't get wsl working for sometime so i dropped it. dont know why i need it as terminal opens fast enough nowadays.
