### ISSUE TITLE
Cant pull model manifest

### ISSUE THREAD

**Issue by bw-Deejee** [jmorganca/ollama#1417]
I just installed ollama on a Azure VM.
Running `ollama run llama2` results in

`pulling manifest ⠴` for a couple minutes and eventually:

Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp 34.120.132.20:443: connect: connection timed out

Also visiting the link, results in this response:
`{
    "errors": [
        {
            "code": "MANIFEST_INVALID",
            "message": "manifest invalid",
            "detail": {}
        }
    ]
}`

I've tried a lot of things seen in other issues, as im operating behind a proxy. But nothing seems to work even though my proxy works for other all other stuff. And the invalid Json response above leads me to believe that I might not be the problem. Please help

**Comment by BruceMacD** [comment]
Hi @bw-Deejee, try giving these steps from the FAQ a try. Pulling from behind a proxy may cause issues.
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

**Comment by mxyng** [comment]
The FAQ might be unclear but the ENVIRONMENT line is preceded by creating the directory and adding a section header. The complete step should be

```
$ mkdir -p /etc/systemd/system/ollama.service.d
$ echo '[Service]' >/etc/systemd/system/ollama.service.d/environment.conf
$ echo 'Environment="HTTPS_PROXY=https://proxy.example.com"' >>/etc/systemd/system/ollama.service.d/environment.conf
```

The `[Service]` header is missing so systemd is actually ignoring the environment configuration

**Comment by bw-Deejee** [comment]
Working now thanks to that. Thank you!

**Comment by RockportTigger** [comment]
> The FAQ might be unclear but the ENVIRONMENT line is preceded by creating the directory and adding a section header. The complete step should be
> 
> ```
> $ mkdir -p /etc/systemd/system/ollama.service.d
> $ echo '[Service]' >/etc/systemd/system/ollama.service.d/environment.conf
> $ echo 'Environment="HTTPS_PROXY=https://proxy.example.com"' >>/etc/systemd/system/ollama.service.d/environment.conf
> ```
> 
> The `[Service]` header is missing so systemd is actually ignoring the environment configuration

Worked! Perfect! Thanks!

**Comment by datalee** [comment]
> The FAQ might be unclear but the ENVIRONMENT line is preceded by creating the directory and adding a section header. The complete step should be
> 
> ```
> $ mkdir -p /etc/systemd/system/ollama.service.d
> $ echo '[Service]' >/etc/systemd/system/ollama.service.d/environment.conf
> $ echo 'Environment="HTTPS_PROXY=https://proxy.example.com"' >>/etc/systemd/system/ollama.service.d/environment.conf
> ```
> 
> The `[Service]` header is missing so systemd is actually ignoring the environment configuration

Based on the above solution, I encountered the following issue:
`Error: pull model manifest: Get https://registry.ollama.ai/v2/library/qwen/manifests/110b-chat-v1.5- q4_0 proxyconnect tcp: dial tcp: lookup http: no such host`

**Comment by SleeplessBegonia** [comment]
> I just installed ollama on a Azure VM. Running `ollama run llama2` results in
> 
> `pulling manifest ⠴` for a couple minutes and eventually:
> 
> Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp 34.120.132.20:443: connect: connection timed out
> 
> Also visiting the link, results in this response: `{ "errors": [ { "code": "MANIFEST_INVALID", "message": "manifest invalid", "detail": {} } ] }`
> 
> I've tried a lot of things seen in other issues, as im operating behind a proxy. But nothing seems to work even though my proxy works for other all other stuff. And the invalid Json response above leads me to believe that I might not be the problem. Please help

how did you solve that?

**Comment by SleeplessBegonia** [comment]
> > The FAQ might be unclear but the ENVIRONMENT line is preceded by creating the directory and adding a section header. The complete step should be
> > ```
> > $ mkdir -p /etc/systemd/system/ollama.service.d
> > $ echo '[Service]' >/etc/systemd/system/ollama.service.d/environment.conf
> > $ echo 'Environment="HTTPS_PROXY=https://proxy.example.com"' >>/etc/systemd/system/ollama.service.d/environment.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `[Service]` header is missing so systemd is actually ignoring the environment configuration
> 
> Based on the above solution, I encountered the following issue: `Error: pull model manifest: Get https://registry.ollama.ai/v2/library/qwen/manifests/110b-chat-v1.5- q4_0 proxyconnect tcp: dial tcp: lookup http: no such host`

hey,did you solve that?

**Comment by rumitsa** [comment]
In my case the issue was related with bad internet connection. After getting stable connect, pulling the manifest started to work.
