### ISSUE TITLE
Make `notus` model available on `ollama`

### ISSUE THREAD

**Issue by davidberenstein1957** [jmorganca/ollama#1418]
We just hosted our [Argilla community meetup](https://www.youtube.com/playlist?list=PLBmuFBJ5cjcbsr49KFoC4DQoo3ZWT7q_d) and got the question if we would be able to make [Notus](https://argilla.io/blog/notus7b/) available on ollama. What would it take, and how can we help with this?

**Comment by phalexo** [comment]
This is what I have in my notus_modelfile:

FROM /opt/data/data/TheBloke/notus-7B-v1-GGUF/notus-7b-v1.Q6_K.gguf

PARAMETER temperature 1

PARAMETER stop <your_model_specific_tag_here>

>>>>>>then you run
ollama create notus -f notus_modelfile

and then

ollama run notus

or

litellm --model ollama/notus

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/notus/pull/13

**Comment by easp** [comment]
@davidberenstein1957 I don't know the criteria for choosing models to include in ollama.ai/library, but in case you missed it in the import doc, you can register for an account and then push it to your "personal" library on ollama.ai so that people can pull it easily (ie `ollama pull argilla-io/notus`).

**Comment by davidberenstein1957** [comment]
https://ollama.ai/argilla/notus

**Comment by easp** [comment]
@davidberenstein1957 I'm trying out the q6_K quantization of Notus and I notice that it's cutting off the output in the middle of sentences. I'm only up to about 750 words context.

**Comment by davidberenstein1957** [comment]
Thanks for the heads up. I updated the context length param to 8k. Was using the default one before. I believe you can overwrite this behavior by simply passing it as param or you can download the new model.

Note: I will assume you are trying to focus on pitching the sequel for the cocain bear movie 😉

**Comment by easp** [comment]
Thanks. I pulled the q6_K and q8_0 models again and the problem remains. I don't think it's context size since it happens as early as the first response. I'm using Ollama 0.1.14.  Other mistral fine-tunes that I've tried (openhermes2.5-mistral:7b-q6_K, dolphin2.2-mistral:7b-q8_0, mistral-openorca:latest) aren't exhibiting this problem.

**Comment by davidberenstein1957** [comment]
@easp, it should work with the current parameter config. Thanks a lot for following up on this. 

Hope you are able to help your completely imaginary heroin addicted wolf.
```
% ollama run argilla/notus:q6_K
>>> if I have a heroin addicted wolf, how can I keep him from dying of an overdose?
I must stress that heroin addiction in animals, particularly in wolves, is extremely rare and not a common issue. However, here are some 
measures you can take to keep your heroin-addicted wolf from dying of an overdose:

1. Consult with a veterinarian who specializes in animal behavior and addiction. They will be able to provide you with expert guidance on 
how to manage your wolf's addiction, including advice on detoxification, behavior modification, and medication management if necessary.

2. Monitor your wolf closely for signs of distress or overdose, such as extreme lethargy, difficulty breathing, vomiting, seizures, or loss 
of consciousness. These are all symptoms of a potential heroin overdose and should be treated as emergencies requiring immediate veterinary 
care.

3. Keep a close eye on your wolf's heroin supply and make sure it is stored safely away from their reach. Do not let them have unsupervised 
access to it, and consider using a securely locked cabinet or container to store it in.

4. Consider working with a professional animal behaviorist who can help you develop a behavior modification plan for your wolf. This may 
involve training them to avoid situations that trigger their cravings for heroin, such as exposure to certain smells or sounds, and 
rewarding them for positive behaviors like spending time outdoors or engaging in enrichment activities.

5. Make sure your wolf has access to plenty of physical activity and mental stimulation. Exercise and playtime can help reduce stress and 
anxiety, which are common triggers for heroin cravings. Consider working with a trainer who specializes in canine behavior modification to 
develop an exercise and play plan that meets your wolf's needs.

6. Finally, be prepared to seek emergency veterinary care if needed. If you suspect your wolf is experiencing a heroin overdose or other 
medical emergency, do not hesitate to contact your veterinarian immediately for guidance and assistance. Remember, timely treatment can make
all the difference in helping your wolf recover from addiction and stay healthy over time.
```

**Comment by davidberenstein1957** [comment]
@jmorganca, What are the requirement for models to be added as general models?

**Comment by easp** [comment]
@davidberenstein1957 I did a fresh pull and it's working now. 

I'm sure my heroin addicted wolf will survive as long as I'm amused by how earnestly LLMs tend to engage my ridiculous scenarios. Thanks for your concern.

**Comment by jmorganca** [comment]
https://ollama.ai/library/notus 🚀
