### ISSUE TITLE
original Unraid container gone?

### ISSUE THREAD

**Issue by ktfcaptain** [jmorganca/ollama#1422]
I installed a version(for lack of better words) of Ollama on an Unraid server a couple weeks ago and now it's gone from the community store.  There was a replacement titled "Chatbot-Ollama" but I have not been able to get that version running correctly on Unraid.  

So on one of my Unraid servers I have this(i think, dockerhub still points here) build, with "ollama-webui" working great.  My other Unraid server with the replacement "Chatbot-Ollama" and "ollama-webui" will not work so far.  I attempted manually installing this build with the same settings that are working on my original server, but can't get the webui to respond to the server.

I'll keep troubleshooting, was just dumbfounded the version that worked perfect on the first attempt vanished.  I'm afraid to make any changes now lol.   

Documenting my thoughts more than anything:

first install: https://i.imgur.com/knl7zSm.png

manual reproduction: https://i.imgur.com/EH0P4ki.png

replacement:  https://i.imgur.com/dLH1IMo.png

**Comment by mxyng** [comment]
Ollama does not maintain any Unraid related projects. You might find better luck asking in the Unraid forums?
