### ISSUE TITLE
Llama2-chat : what's the best way to implement?

### ISSUE THREAD

**Issue by itscvenk** [jmorganca/ollama#1447]
Hello folks

I tried openchat and it is kind of ok. Nowhere  near GPT4 in terms of richness in conversation.

I'd like to try using Llama2-chat. I have seen the page at https://github.com/jmorganca/ollama/blob/main/docs/import.md for importing new models into Ollama.

Question is if I should use the Llama2-chat from Meta or use the one from Huggingface?

many thanks for your replies, in advance

**Comment by igorschlum** [comment]
Hi @itscvenk

llama2 chat is already supported by Ollama

You can use one of those:
ollama run llama2:chat
ollama run llama2:7b-chat
ollama run llama2:13b-chat
ollama run llama2:70b-chat

And others chat models here:

https://ollama.ai/library/llama2/tags

Please close the Issue and use Discord for general questions, more than issues.
