### ISSUE TITLE
Use hard link to import GGUF on the same host to save disk space

### ISSUE THREAD

**Issue by xleven** [jmorganca/ollama#1450]
If I understand it correctly, first step of a GGUF import is copying the binary to model dir with a hashed name. When the number of models (mainly GGUF) grows, duplicated binaries may take a lot of disk space.
Thinking hard links, or the raw GGUFs if possible, will do the work of space saving, though it only makes sense when client & server are on the same host and GGUF & model dir are on the same disk.

**Comment by technovangelist** [comment]
Thanks for the comment. There is no duplication of files. If you have something like llama2 and then two models that are based on llama2 with different prompts and parameters, you will only have a single copy of the llama2 weights file. The other 2 leverage that file.

**Comment by xleven** [comment]
Hi @technovangelist thanks for your clarification. Good to know model files don't duplicate when you create a new Ollama model, maybe with different prompt, from an existing Ollama one. However what I was suggesting is that the raw GGUF files, which are built by llama.cpp or downloaded from HF and haven't been imported as Ollama models, get duplicated during [imports](https://github.com/jmorganca/ollama/blob/main/docs/import.md#importing-gguf). Tell me if there is anything unclear.

**Comment by phalexo** [comment]
> Hi @technovangelist thanks for your clarification. Good to know model files don't duplicate when you create a new Ollama model, maybe with different prompt, from an existing Ollama one. However what I was suggesting is that the raw GGUF files, which are built by llama.cpp or downloaded from HF and haven't been imported as Ollama models, get duplicated during [imports](https://github.com/jmorganca/ollama/blob/main/docs/import.md#importing-gguf). Tell me if there is anything unclear.

Yes, I have been meaning to ask about it too. When one creates a model, it appears that the model weights get duplicated into ollama repo, if simply judging by how long it takes. Simply writing some meta data would not take this long.

**Comment by mxyng** [comment]
Yes, importing binary model weights requires copying the file. This is necessary because the server might be remote or in another context that makes the source file inaccessible.
