### ISSUE TITLE
REST API : /api/chat endpoint not working

### ISSUE THREAD

**Issue by slovanos** [jmorganca/ollama#1467]
Refering to the the examples of the main page:

## Generate a response: Works perfectly
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama2",
  "prompt":"Why is the sky blue?"
}'
```

### Response is "404 page not found"
```
curl http://localhost:11434/api/chat -d '{
  "model": "llama2",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```
I tried restarting the server and also with mistral model and I am getting the same result.

**Comment by jmorganca** [comment]
Hi @slovanos! Which version of Ollama are you on? (you can check with `ollama -v`)

The chat api is available in 0.1.14 or later (just released yesterday :-). To upgrade simply re-download Ollama: https://ollama.ai/ on Linux or macOS. Hope this helps!

**Comment by slovanos** [comment]
Thank you very much for the fast response. ollama version 0.1.13. So that may be the issue. Thanks!

**Comment by ghassett** [comment]
I see this issue consistently when using the "mistral" model, but all works ok when using the "llama2."  My installed version is "ollama version is 0.1.17" running on MacOS, Mac M1.  With Ollama serving, I also get a 404 at http://localhost:11434/api/chat when trying to hit that URL in a browser.

**Comment by boldranet** [comment]
@ghassett read the error.message, and not just the status line. 404 means you haven't installed that model. use "ollama run mistral" first.

And GET requests, which you're sending in your browser, are routed differently. See also /Ollama/server.log
