### ISSUE TITLE
Will it be possible to run the new mixtral model quantized?

### ISSUE THREAD

**Issue by ManuXD32** [jmorganca/ollama#1470]
Hello, I know llama.cpp still doesn't support it, but this PR does https://github.com/ggerganov/llama.cpp/pull/4406
Is there a way to use it in ollama?

**Comment by r7l** [comment]
The [PR has been merged](https://github.com/ggerganov/llama.cpp/releases/tag/b1629). This is a huge release. Ollama probably needs to update their vendor dependency to get Mixtral support.

**Comment by ManuXD32** [comment]
Okay, thanks!
