### ISSUE TITLE
Publishing model fails with "Error: unable to push ..."

### ISSUE THREAD

**Issue by stephenwithav** [jmorganca/ollama#1471]
I followed the [import doc](https://github.com/jmorganca/ollama/blob/7a1b37ac64f0fb0585e279a0a840707843511ed3/docs/import.md?plain=1#L108) steps, but I'm getting the error in the title.

I've:

1. Created an account.
2. Copied my `id_ed25519.pub` file to `~/.ollama/` and `/usr/share/ollama/.ollama`.
3. Added the public key to my account.
4. Copied the model to my username's namespace.
5. Attempted `ollama push stephenwithav/book-summary`

```
Error: unable to push stephenwithav/book-summary, make sure this namespace exists and you are authorized to push to it
```

**Comment by mxyng** [comment]
To clarify, you copied your public key into `~/.ollama` and `/usr/share/ollama/.ollama` but you're not using the public key already in those directories?

Ollama create an application specific Ed25519 key pair and stores both the public and private keys in those directories. Copying a public key into that directory does not import the key to use for push. Instead, you should copy the public key from those directories and import them into ollama.ai.

**Comment by stephenwithav** [comment]
I copied them to those directories _and_ added it to my account on ollama.ai.

**Comment by mxyng** [comment]
Right, you should _not_ copy your key to those directories. You should use the `id_ed25519.pub` that already exist in those directory and import it to ollama.ai.

When you start ollama, it will create a keypair used specifically for ollama and save it into either `~/.ollama` or `/usr/share/ollama/.ollama` as `id_ed25519` (private key) and `id_ed25519.pub` (public key). When you want to publish, you take this `id_ed25519.pub` and import into ollama.ai, not another key.

**Comment by mxyng** [comment]
Closing this since it hasn't been updated for a while. Please reopen it if it's still an issue

**Comment by omegaT4224** [comment]
ollama cp llama3.2 dingo/yo-yo
ollama push dingo/yo-yo
