### ISSUE TITLE
Support for fully airgapped environment

### ISSUE THREAD

**Issue by yyefet** [jmorganca/ollama#1472]
Feature Request to support fully air-gapped environments to ensure no calls/requests leave the server externally if user desires.

Proposing --airgap or --no-external flag to disable all telemetry, pull from public repos, and phoning home of any sorts.

**Comment by mchiang0610** [comment]
@yyefet Thank you! Ollama should work for fully air-gapped environments already today. If the users' devices have no internet, it just won't pull or auto-update. 

Please let me know if there is anything missing in this feature. 

Again, thank you for bringing this up!
