### ISSUE TITLE
Add parameters for continuous batching and parallel flags

### ISSUE THREAD

**Issue by YourTechBud** [jmorganca/ollama#1476]
Llama.cpp server supports [continuous batching and running requests in parallel](https://github.com/ggerganov/llama.cpp/tree/master/examples/server) which can be super effective to make things way more efficient specifically when running smaller models.

I can contribute this feature if the project maintainers think it's a good addition.

**Comment by jmorganca** [comment]
Hi @YourTechBud , thanks so much for the issue! Absolutely 😊 . Will merge this with https://github.com/jmorganca/ollama/issues/358
