### ISSUE TITLE
Mixtral 8X7B

### ISSUE THREAD

**Issue by pdavis68** [jmorganca/ollama#1477]
I have read that Mixtral 8X7B requires a PR from llama.cpp (https://github.com/ggerganov/llama.cpp/pull/4406) according to this source: (https://huggingface.co/TheBloke/Mixtral-8x7B-v0.1-GGUF).

Are there any plans yet to incorporate these changes? Is there a timeline? Mixtral 8X7B looks very impressive (appears to outperform LLaMA 2 70B in most benchmarks.) and I'd love to get it into Ollama!

Here's Mistral's page on it: https://mistral.ai/news/mixtral-of-experts/

**Comment by tmc** [comment]
Until upstream (llama.cpp) support lands this isn't possible.
