### ISSUE TITLE
Permanently changing System prompt

### ISSUE THREAD

**Issue by luvchurchill** [jmorganca/ollama#1482]
I want to change the system prompt, after I write my own ``/set system`` and I check it ``/show system`` it is what I changed it to.
The problem is that when I quit, it changes back to the default boring prompt.
Is there a way to change it permanently?
Thanks

**Comment by phalexo** [comment]
You can put an input template into a model file, with the system prompt and then do

ollama create "YourModelName" -f YourModelFie.

**Comment by luvchurchill** [comment]
That creates a completely new model tho, right?

**Comment by mxyng** [comment]
Yes in the sense that it's a new model in `ollama list`. However, if you're using existing model templates, it will reuse the model weights and the only additional disk is a file for the system prompt.

You can also give the new model the same name to update it:

e.g.

```
$ ollama pull mistral
$ cat <<EOF >Modelfile
FROM mistral
SYSTEM "You are a good language model."
EOF
$ ollama create mistral
```

**Comment by luvchurchill** [comment]
Oh, ok that's what I was wondering about (disk space, etc.) thanks

**Comment by phalexo** [comment]
One thing to note though. If you have created a model entry from a local
gguf file, you would be duplicating data.

**Comment by SuperiorDigital** [comment]
how do you delete a <NEWMODELNAME>:latest once you want to remove?

**Comment by Ayush-Singh-31** [comment]
`with open("modelfile", "r") as file:`
`    modelfile = file.read()`
 `ollama.create(model = "modelname", modelfile = modelfile, stream = True)`
    
Somehow this altered the original model instead of creating a new one. I don't get what I did wrong, any help would be appreciated :)
