### ISSUE TITLE
suggestion: download models to home directory instead of `/usr/share/`  on linux ?

### ISSUE THREAD

**Issue by hualet** [jmorganca/ollama#1494]
I suggest that models should be downloaded to home directory like `~/.ollama/models` instead of `/usr/share/ollama/.ollama/models`,  since I think it's a conviention that data should be in home not root.

I didn't create root with a copacity big enough and encounter this :joy: 

![image](https://github.com/jmorganca/ollama/assets/2023967/5017e347-32ce-4da2-a6a5-df75cf711700)

**Comment by rgaidot** [comment]
This should be the case ($HOME) https://github.com/jmorganca/ollama/blob/main/server/modelpath.go#L108C18-L108C29

**Comment by BruceMacD** [comment]
Hey y'all, thanks for the feedback. There is actually an environment variable you can set to change the location the Ollama models are stored, here's the doc:
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models

Hope that helps.

**Comment by hualet** [comment]
> Hey y'all, thanks for the feedback. There is actually an environment variable you can set to change the location the Ollama models are stored, here's the doc: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models
> 
> Hope that helps.

It's not working here, any more information I should provide ?

**Comment by maxim-sermin** [comment]
Setting `OLLAMA_MODELS` also didn't work for me. However, I could get a similar result by changing the User/Group of the ollama systemd unit to be my user:

```
Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=<YOUR USERNAME GOES HERE>
Group=<YOUR GROUPNAME GOES HERE>
...
```

Then run `systemctl daemon-reload && systemctl restart ollama` to apply the changes

**Comment by wenxichen** [comment]
> Setting `OLLAMA_MODELS` also didn't work for me. However, I could get a similar result by changing the User/Group of the ollama systemd unit to be my user:
> 
> ```
> Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve
> User=<YOUR USERNAME GOES HERE>
> Group=<YOUR GROUPNAME GOES HERE>
> ...
> ```
> 
> Then run `systemctl daemon-reload && systemctl restart ollama` to apply the changes

This works for me. After setting the User and Group, I was able to add the following line under [Service]
`Environment="OLLAMA_MODELS=<my_custom_folder_full_path>"`
And now my models are downloaded to my custom folder.

**Comment by hualet** [comment]
Ah, I see. The environment should be set to the daemon, not the cli client. Thanks @maxim-sermin @wenxichen
