### ISSUE TITLE
Add Phi-2 model

### ISSUE THREAD

**Issue by hunnble** [jmorganca/ollama#1496]
The Phi-2 model performs well. Should we consider adding it to Ollama?

**Comment by easp** [comment]
It appears to use the same model architecture as Phi-1.5. That [model architecure is not supported by Llama.cpp](https://github.com/ggerganov/llama.cpp/issues/3146).

In addition, the model weights are not licensed for redistribution, at least not currently. You have to log-in to Azure with an account that has a credit card on file.

**Comment by izard** [comment]
The model weights can be downloaded by anyone from official https://huggingface.co/microsoft/phi-2/tree/main MSFT page. The license is quite permissive.

**Comment by easp** [comment]
They've loosened things up in the last 10hr. The fact remains though that support for the model architecture in Llama.cpp hasn't progressed much (at least not visibly) since September.

**Comment by HardKothari** [comment]
Not sure if this can help but there is a model card with GGUF format file and if they can be used. I tried locally creating Modelfile and it had internal error in the server.

https://huggingface.co/radames/phi-2-quantized

**Comment by jingfelix** [comment]
Seems like Phi-2 will be supported by llama.cpp in forseeeable future 👀
https://github.com/ggerganov/llama.cpp/pull/4490

**Comment by vaclcer** [comment]
it is now. Fingers crossed for Ollama :)

**Comment by Jbollenbacher** [comment]
> Seems like Phi-2 will be supported by llama.cpp in forseeeable future 👀
> https://github.com/ggerganov/llama.cpp/pull/4490

This just merged. llama.cpp now supports phi-2.

**Comment by brianjking** [comment]
Now that this has been merged what is required to get this working in ollama?

**Comment by HardKothari** [comment]
I believe Ollama has already added the support and is already available in pre-release 0.0.17
Check this out..
https://ollama.ai/jmorgan/phi/tags

**Comment by ibnbd** [comment]
https://ollama.ai/library/phi

**Comment by oliverbob** [comment]
Yes, its lightning fast. Its already supported by ollama.

**Comment by snajjar** [comment]
Not working on my machine, :(
(Lenovo Thinkpad P14S, Linux 6.5.7 Arch)

```
$ ollama run phi
⠙   Error: llama runner: failed to load model '/usr/share/ollama/.ollama/models/blobs/sha256:bd608f9545597ea3278b78038943059d1c29c62f3ca02c86523014f3a8c7a7f1': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull phi:latest
```

I tried different tags for the phi model, but none of them works.

**Comment by bgokden** [comment]
> Not working on my machine, :( (Lenovo Thinkpad P14S, Linux 6.5.7 Arch)
> 
> ```
> $ ollama run phi
> ⠙   Error: llama runner: failed to load model '/usr/share/ollama/.ollama/models/blobs/sha256:bd608f9545597ea3278b78038943059d1c29c62f3ca02c86523014f3a8c7a7f1': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull phi:latest
> ```
> 
> I tried different tags for the phi model, but none of them work. Do I need to install ollama from git?

Which version of ollama are you using? It worked for me with v0.1.17.
I have installed ollama from git with cloning this tag.

**Comment by snajjar** [comment]
Indeed. Even though the package version stated 1.0.17, `ollama --version` gave 1.0.9...

Re-installed from git, it works in 1.0.17

**Comment by oliverbob** [comment]
> Not working on my machine, :( (Lenovo Thinkpad P14S, Linux 6.5.7 Arch)
> 
> ```
> $ ollama run phi
> ⠙   Error: llama runner: failed to load model '/usr/share/ollama/.ollama/models/blobs/sha256:bd608f9545597ea3278b78038943059d1c29c62f3ca02c86523014f3a8c7a7f1': this model may be incompatible with your version of Ollama. If you previously pulled this model, try updating it by running `ollama pull phi:latest
> ```
> 
> I tried different tags for the phi model, but none of them work. Do I need to install ollama from git?

You clearly need an update if that's the case. Just run the installer via `curl https://ollama.ai/install.sh | sh` to update it once more.

**Comment by oliverbob** [comment]
> Indeed. Even though the package version stated 1.0.17, `ollama --version` gave 1.0.9...
> 
> Re-installed from git, it works in 1.0.17

You could be running two versions of Ollama. One via docker and one via the install script.

Run sudo lsof -i :11434 to find out. Or `docker ps`. If its on docker, you need to rebuild docker, but only when you have don a fresh `git pull` to update the local repo. Either remove docker ollama or stop it in docker before installing the `curl https://ollama.ai/install.sh | sh`. Then redownload Phi-2.

**Comment by trickster** [comment]
Is there any plan to add dolphin phi-2 as well? https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2/tree/main

**Comment by jmorganca** [comment]
@trickster yes! It's here https://ollama.ai/library/dolphin-phi 😊

**Comment by jmorganca** [comment]
Closing this as Phi has been added!
