### ISSUE TITLE
Add mistral's new 7B-instruct-v0.2

### ISSUE THREAD

**Issue by tarek-ayed** [jmorganca/ollama#1499]
Along with many releases, Mistral vastly improved their existing 7B model with a version named `v0.2`.

It has 32k context instead of 8k and better benchmark scores: https://x.com/dchaplot/status/1734198245067243629?s=20
More can be found here: https://docs.mistral.ai/platform/endpoints (see "Mistral Tiny")

The weights are published on HuggingFace:

https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2

I don't know if anything needs to be implemented on the llama.cpp front, given that it's the same architecture as before.

Let me know how I can contribute to make this happen ;)

**Comment by justinh-rahb** [comment]
No changes needed, was already uploaded yesterday, just repull Mistral

```
ollama pull mistral
```

**Comment by mchiang0610** [comment]
Closing since this is available now. Sorry about that. It means that we'll have to really improve the Ollama library to make those changes much more visible.

**Comment by Liuxyly** [comment]
What about this version on HuggingFace? 
https://huggingface.co/mistralai/Mixtral-8x7B-v0.1

**Comment by justinh-rahb** [comment]
The PR for that model support is merged to main but a new release hasn't been created yet. I'm sure it will be soon, and the model image to go with it.
