### ISSUE TITLE
Add Solar model

### ISSUE THREAD

**Issue by niknoproblems** [jmorganca/ollama#1522]
The Solar(instruct) model performs well https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard.
Should we consider adding it to Ollama?

**Comment by vaclcer** [comment]
Pls dont, its a joke 

https://www.reddit.com/r/LocalLLaMA/comments/18hnzzn/a_107b_model_is_now_on_the_top_of_the_llm/

**Comment by BruceMacD** [comment]
Thanks for the request, you can pull Solar here:
https://www.ollama.ai/library/solar
