### ISSUE TITLE
docs: generate chat response `loadDuration` missing

### ISSUE THREAD

**Issue by mthongvanh** [jmorganca/ollama#1523]
in the documentation https://github.com/jmorganca/ollama/blob/main/docs/api.md#response-6 loadDuration is listed as a return value but does not get returned by the api

<img width="981" alt="image" src="https://github.com/jmorganca/ollama/assets/4961248/bb0dbc37-c2cf-48ff-8c8d-be2ffcfa5115">

**Comment by BruceMacD** [comment]
Thanks for the report, this is a bug and load_duration should be getting set. We will have this fixed in the next release.
