### ISSUE TITLE
Mixtral 8x7B support

### ISSUE THREAD

**Issue by Baughn** [jmorganca/ollama#1525]
Following up on #1477 - llama.cpp now supports Mixtral.

I'd reopen the previous issue, but well, I can't.

**Comment by Titaniumtown** [comment]
Does the latest pre-release not support it? It says that it is supported.

**Comment by easp** [comment]
@Titaniumtown it is. Some people just aren't inclined to do any searching.
https://github.com/jmorganca/ollama/releases/tag/v0.1.16

**Comment by Titaniumtown** [comment]
Ah, thought I missed something, seems I wasn't the one missing something. lol

**Comment by Baughn** [comment]
That's five hours old. I swear the model didn't exist when I wrote the issue. :D
