### ISSUE TITLE
Control model cache location (set ollama directory to something other than ~/.ollama) 

### ISSUE THREAD

**Issue by weaversam8** [jmorganca/ollama#153]
It would be useful to configure the location where models are cached, so models could be downloaded and stored on external storage.

**Comment by abulka** [comment]
See my workaround in #155, for now.

**Comment by tspike** [comment]
For what it's worth, that workaround causes a kernel panic on my Mac. Keeping it on the internal disk works ok, but takes up a ton of space.

**Comment by xyproto** [comment]
Anyone had luck caching `~/.ollama` across runs in a GitHub action?

**Comment by jikkuatwork** [comment]
Any help on this would be great! I would like to configure where I can download the models to

**Comment by BruceMacD** [comment]
resolved by #897
