### ISSUE TITLE
CMake Error at CMakeLists.txt:491 (get_flags): get_flags Function invoked with incorrect arguments for function named: get_flags

### ISSUE THREAD

**Issue by 0xdevalias** [jmorganca/ollama#1539]
It seems that there is an issue when trying to build on linux, at least in our runner environment:

```
-- Could not find nvcc, please set CUDAToolkit_ROOT.
  CMake Warning at CMakeLists.txt:318 (message):
    cuBLAS not found
  
  
  -- CUDA host compiler is GNU 
  CMake Error at CMakeLists.txt:491 (get_flags):
    get_flags Function invoked with incorrect arguments for function named:
    get_flags
  
  
  -- CMAKE_SYSTEM_PROCESSOR: x86_64
  -- x86 detected
  -- Configuring incomplete, errors occurred!
  llm/llama.cpp/generate_linux.go:24: running "cmake": exit status 1
```

See the following issue for more details:

- https://github.com/Homebrew/homebrew-core/pull/157426

If this is an issue in our environment, that's fair enough. I mostly wanted to make sure there was an issue captured here for the error message to assist others in future.

**Comment by mamccorm** [comment]
+1 also encountering this

**Comment by jrgleason** [comment]
Encountering this when using WSL2
