### ISSUE TITLE
API endpoint to query models supported by ollama

### ISSUE THREAD

**Issue by gmaijoe** [jmorganca/ollama#1542]
https://github.com/ollama-webui/ollama-webui is looking to support a deeper integration with ollama. is there any way to expose an api of all model names supported by ollama? could manually scrape but an API would be easier for ingestion

**Comment by adriens** [comment]
I've linked your issue to mine as from my point of view it covers the same topic family
- https://github.com/jmorganca/ollama/issues/1473

**Comment by adriens** [comment]
BtW, when you talk about this API : are you talking about:

- **Public**: API hosted by ollama
- **Local** : needs to have a locally running ollama instance

**Comment by jmorganca** [comment]
Thanks so much for creating an issue! Will close this for #1473 so we can continue the convo there 😊
