### ISSUE TITLE
Is running behind a proxy fully supported?

### ISSUE THREAD

**Issue by pardeike** [jmorganca/ollama#1546]
Hi,

when I run with a configured proxy, I get the error `lookup registry.ollama.ai: no such host`:
```
> HTTPS_PROXY=http://REDACTED.XXX:10000 ollama run llama2
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai: no such host
```

I then added a manual dns entry to /etc/hosts and ran the command again, but this time after trying to fetch the manifest, I get

```
> HTTPS_PROXY=http://REDACTED.XXX:10000 ollama run llama2
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp 34.120.132.20:443: connect: network is unreachable
```  
  
Going to those urls in Safari works just fine so it seems that the proxy support isn't fully working.

**Comment by mxyng** [comment]
`HTTPS_PROXY` must be applied to `ollama serve` since that's the process actually reaching out to get the models. setting it with `ollama run` has no effect. Please see the [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy) for more details.

**Comment by pardeike** [comment]
My bad, I did not realise that the Ollama app had put itself in my menu bar. After quitting it, then running the proxied ollama serve from command line I could run `ollama run llama2` as intended.

**Comment by GuiZhaoyang** [comment]
@mxyng hi, I run the  ollama run llama2 in terminal,but still meet the error:

pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp 34.120.132.20:443: connect: network is unreachable

The ollama server logs:
2023/12/28 11:38:48 images.go:1066: request failed: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp 34.120.132.20:443: connect: network is unreachable
[GIN] 2023/12/28 - 11:38:48 | 200 |  267.776118ms |       127.0.0.1 | POST     "/api/pull"

**Comment by pardeike** [comment]
Did you run `ollama serve` with proxy settings @GuiZhaoyang ?
