### ISSUE TITLE
`OLLAMA_MODELS` environment variable ignored by Mac app

### ISSUE THREAD

**Issue by Crypto69** [jmorganca/ollama#1560]
Documentation FAQ says the following:

### How can I change where Ollama stores models?

To modify where models are stored, you can use the `OLLAMA_MODELS` environment variable. Note that on Linux this means defining `OLLAMA_MODELS` in a drop-in `/etc/systemd/system/ollama.service.d` service file, reloading systemd, and restarting the ollama service.

I have made the changes but it doesn't seem to work when using the ollama Mac app
```
~ ollama list
NAME                            	ID          	SIZE  	MODIFIED
deepseek-coder:33b              	2941d6ab92f3	18 GB 	3 weeks ago
deepseek-coder:33b-instruct-q2_K	92b1e8ffe46e	14 GB 	3 weeks ago
deepseek-coder:6.7b             	72be2442d736	3.8 GB	3 weeks ago
deepseek-coder:latest           	140a485970a6	776 MB	3 weeks ago
llama2:latest                   	fe938a131f40	3.8 GB	3 weeks ago
llama2-uncensored:latest        	44040b922233	3.8 GB	3 weeks ago
mistral:latest                  	1ab49bc0b6a8	4.1 GB	14 minutes ago
wizard-vicuna-uncensored:13b    	6887722b6618	7.4 GB	3 weeks ago
wizardlm-uncensored:13b-llama2  	886a369d74fc	7.4 GB	3 weeks ago
~ echo $OLLAMA_MODELS
/Volumes/ExternalHD/ollama-models
~ ollama run codellama
pulling manifest
pulling manifest
pulling manifest
pulling manifest
pulling manifest
``` I
However the model is still getting downloaded to ~/.ollama/models

**Comment by easp** [comment]
Try this.  Quit the menu bar app. From a Terminal window `OLLAMA_MODELS=THE_PATH_YOU_WANT open /Applications/Ollama.app`. I tried it on my computer and Ollama seems to pick up the environment variables.

You'll want to keep the Ollama.app from starting automatically.

**Comment by Crypto69** [comment]
Thanks that worked. Are there any plans to update the app so that you can have the app auto start?

> As a work-around, try this. Quit the menu bar app. From a Terminal window `OLLAMA_MODELS=THE_PATH_YOU_WANT open /Applications/Ollama.app`. I tried it on my computer and Ollama seems to pick up the environment variables.
> 
> You'll want to keep the Ollama.app from starting automatically.

**Comment by sandorvasas** [comment]
This is a major issue for me too, I need the models to be stored on another partition on my Ubuntu.

**Comment by easp** [comment]
@sandorvass https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models

**Comment by sandorvasas** [comment]
@easp it doesn't work, that's the issue.

**Comment by sandorvasas** [comment]
@easp 
 /etc/systemd/system/ollama.service.d
```
[Service]
Environment="OLLAMA_MODELS=/w/ollama/models/"
```
then
```
sudo systemctl daemon-reload 
sudo systemctl restart ollama
```
still downloads to `~/.ollama/models`

**Comment by technovangelist** [comment]
What OS are you on? You seem to be following the instructions for linux, but the models are being downloaded to the path used on MacOS. If you are using MacOS, use will need to quit Ollama from the menu bar, then in a new terminal window, run `OLLAMA_MODELS=/w/ollama/models/ ollama serve`. We are looking to update our Mac app to make this better.

**Comment by sandorvasas** [comment]
@technovangelist Thanks, that works flawlessly. I'm on Ubuntu, OP is on Mac. Could you update the docs? Docs only explain how to add an env var to ollama when it is run as a service, and that doesn't recognize the OLLAMA_MODELS env var. 
I stopped the service and just running `OLLAMA_MODELS=/w/ollama/models/ ollama serve` and that does work. :100:

**Comment by technovangelist** [comment]
It looks like all the issues in this have been solved. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by Crypto69** [comment]
> What OS are you on? You seem to be following the instructions for linux, but the models are being downloaded to the path used on MacOS. If you are using MacOS, use will need to quit Ollama from the menu bar, then in a new terminal window, run `OLLAMA_MODELS=/w/ollama/models/ ollama serve`. We are looking to update our Mac app to make this better.

I am on macOS. No I'm not following the instructions for linux. On macOS you need to stop the service on the menu bar and then run OLLAMA_MODELS=THE_PATH_YOU_WANT open /Applications/Ollama.app in order to get the models downloaded to your directory. This works but it would be great if the menu bar app Took into account environment variable when it started by the system

**Comment by zboyles** [comment]
@Crypto69 as a clean workaround you can add an alias to your shell config ie. `.zshrc`, `.bashrc`, etc. 

I wanted the models stored in `/Volumes/T9/models` so these are the steps I took to make the environmental variable work as expected; **Note: obviously change destination to your preferred path**
1. Quit Ollama from menu bar
2. Add the following lines to your shell configuration; I changed mine to ZSH so `~/.zshrc` but your Mac might be using `~/.bashrc`:

```shell
# .zshrc

export OLLAMA_MODELS="/Volumes/T9/models"
alias ollama="OLLAMA_MODELS=/Volumes/T9/models ollama $@"
```
3. Run commands normally, ie `ollama pull dolphin-mixtral` or `ollama run dolphin-mistral`


### Revert Configuration to Ollama Defaults

In order to change it back, I had to quit Ollama from the menu bar again and specify the original location for `OLLAMA_MODELS`. This might have resolved itself automatically after a reboot.
```shell
# .zshrc
# revert configuration back to Ollama defaults:

# alias ollama="OLLAMA_MODELS=/Volumes/T9/models ollama $@"
export OLLAMA_MODELS="~/.ollama/models"
```

**Comment by JohnnyLeuthard** [comment]
Why is this such a difficult thing to do. It is very buggy. I had it working with the environment variable on my Mac and it just stoped working. Would it be so hard to have a config file in Ollama to specify where to store Models rather than have to do work arounds. I have been fighting this for some time now because it keeps reverting to my local drive that is very limited on space. I'm close to abandoning Ollama and going with other tools.

**Comment by aricnappi** [comment]
> Why is this such a difficult thing to do. It is very buggy. I had it working with the environment variable on my Mac and it just stoped working. Would it be so hard to have a config file in Ollama to specify where to store Models rather than have to do work arounds. I have been fighting this for some time now because it keeps reverting to my local drive that is very limited on space. I'm close to abandoning Ollama and going with other tools.

On my machine at least (MacOS), I couldn't see my models anymore when I ran `ollama ps`. However, if I do `ollama run <model>` it still somehow finds and uses my local copy without pulling it. If I run `ollama ps` again, I somehow magically see that model in the list (but still not the others).

**Comment by easp** [comment]
@aricnappi `ollama ps` shows models that are currently loaded into memory. If you want to see the models you've downloaded, use `ollama list`

**Comment by michalliu** [comment]
not working, I just create a softlink to ~/.ollama
