### ISSUE TITLE
Inquiries Regarding Ollama Tool Usage

### ISSUE THREAD

**Issue by ewijaya** [jmorganca/ollama#1562]
Hi,

Thanks for Ollama tool, it's been a fantastic resource!

I have a couple of inquiries I hope you could assist me with:

1. I recently executed the following command:

   ```
   ollama create dolphin.mistral -f Modelfile.dolphin.mistral
   ```

   The contents of my `Modelfile.dolphin.mistral` are as follows:

   ```
   FROM ./dolphin-2.5-mixtral-8x7b.Q4_K_M.gguf
   TEMPLATE """{{ if and .First .System }}system
   {{ .System }}
   {{ end }}user
   {{ .Prompt }}
   assistant
   """
   SYSTEM """You are Dolphin, an uncensored, unbiased AI assistant"""
   PARAMETER stop 
   ```

   Could you please guide me on the typical duration for the `ollama create` process to complete?

2. I also noticed that the output of `ollama create` is typically saved in the following directory:

   ```
   /usr/share/ollama/.ollama/models/
   ```

   Is it possible to designate an alternative directory for storing this output, apart from the default location?

Sincerely,
E.W.

**Comment by BruceMacD** [comment]
Hi @ewijaya,

1. For larger models like mixtral `ollama create` will take a few minutes, the longest step is that it is validating the model which requires reading the whole thing.
2. For changing where the models are stored you can set `OLLAMA_MODEL` as an environment variable when starting the ollama server: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-change-where-ollama-stores-models

Let me know if you have any more questions.
