### ISSUE TITLE
Release: llava 13b

### ISSUE THREAD

**Issue by webmastermario** [jmorganca/ollama#1563]
Hello,

does somebody know when the model llava v2 13b is beeing added. Currently its only llava 7b.

Thanks

**Comment by easp** [comment]
Check the tags for llava in the library. The 13b version is there.
https://ollama.ai/library/llava/tags

**Comment by igorschlum** [comment]
Hi @webmastermario It's shorter to type
ollama run llava:13b
I just made it and it works well.
Could you please close the issue if it works for you too?
