### ISSUE TITLE
ollama in Powershell using WSL2

### ISSUE THREAD

**Issue by BananaAcid** [jmorganca/ollama#1568]
Just an info for others trying to trigger ollama from powershell:

Either use `wsl ollama run llama2` (prefix with wsl) 

- or -

enable a `ollama` command in powershell:

1. `notepad $PROFILE`
2. add as last line:  `function ollama() { $cmd = @("ollama") + $args ; &wsl.exe $cmd }`

Note: setting `OLLAMA_MODELS=/mnt/...DRIVELETTER...` will kill the performance!

**Comment by BruceMacD** [comment]
Thanks for documenting this @BananaAcid, marking this as resolved for now as there are no changes for Ollama outstanding here, but I appreciate adding this for future searchers.
