### ISSUE TITLE
I'm using ollama to run via API on Debian (WSL). When I give the command "ollama serve" the terminal is busy

### ISSUE THREAD

**Issue by EliasPereirah** [jmorganca/ollama#1581]
![Captura de tela 2023-12-18 100155](https://github.com/jmorganca/ollama/assets/16616409/73f036eb-6c06-4b30-966a-bf6df75aeb29)

**Comment by Cybervet** [comment]
Yes you can run it either with & at the end ,"Ollama serve &" , you can use screen or tmux or alternatively you can open another terminal.

**Comment by technovangelist** [comment]
It looks like @Cybervet has solved your issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
