### ISSUE TITLE
ollama crashes when calling /api/generate with invalid duration message

### ISSUE THREAD

**Issue by michaelgloeckner** [jmorganca/ollama#1582]
Hi,

i run ollama in k8s cluster and i upgraded from 0.1.9 to 0.1.16 to get mixtral fix.

the error occurred first time with version 0.1.14.

But when i call /api/generate ollama stops. 
Looking into ollama logs i see the following messages:
panic: time: invalid duration "-6414107897391086.000000ms"

More logs are attached:
[error_ollama_0.1.16.txt](https://github.com/jmorganca/ollama/files/13704366/error_ollama_0.1.16.txt)

**Comment by BruceMacD** [comment]
Hi @michaelgloeckner, thanks for opening the issue. Which distro is running on the nodes in your kube cluster? Im wondering if this has something to do with the library used to get the timestamps.

**Comment by michaelgloeckner** [comment]
Hi,

it is running on an Amazon node with gpu support (g5.8xlarge):

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
SUPPORT_END="2025-06-30"
Amazon Linux release 2 (Karoo)

If you have an idea how to check the library, let me know and I can test it on the system.

**Comment by BruceMacD** [comment]
Thanks for the details @michaelgloeckner, still looking at this. In the meantime, the way you are using `template` seems a bit off from my expectations. Normally it would be used along a prompt parameter, I'd suggest this request body instead:
```
{
    "model": "llama2",
    "raw": true,
    "prompt": "<|im_start|>system\nYou are an assistant for question-answering tasks.<|im_end|>\n<|im_start|>user\nQuestion: What are the advantages for Aladin??\nContext: Some context here<|im_end|>\n<|im_start|>assistant Answer:",
    "stream": false,
    "options": {
        "stop": [
            "<|im_start|>",
            "<|im_end|>"
        ]
    }
}
```
