### ISSUE TITLE
Missingn "ollama avail" command to show available models

### ISSUE THREAD

**Issue by dennisorlando** [jmorganca/ollama#1587]
Self descriptory; I have to go to this github page to look at what models are available, which appear to not be all of them

**Comment by rgaidot** [comment]
You can use `ollama list` or check in website https://ollama.ai/library ? 🤔

**Comment by technovangelist** [comment]
@rgaidot answer solves this issue. looking at the library page on ollama.ai is your best bet. I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by dennisorlando** [comment]
> You can use `ollama list` or check in website https://ollama.ai/library ? 🤔

Nope, "ollama list" only lists images that you locally downloaded on your machine; my idea was to have a CLI option to read from ollama.ai's library page, in order to not have to browse the web when wanting to view the available models. 
It would be cool to have a "ollama search" option that replicates what the library page does

**Comment by kyoh86** [comment]
💭 #1473 will solve this.
