### ISSUE TITLE
Wont run on amd or intel gpu's?

### ISSUE THREAD

**Issue by srgantmoomoo** [jmorganca/ollama#1594]
it seems that I cannot get this to run on my amd or my intel machine... does it only support nvidia gpu's?

keep getting this...
```
2023/12/18 21:59:15 images.go:737: total blobs: 0
2023/12/18 21:59:15 images.go:744: total unused blobs removed: 0
2023/12/18 21:59:15 routes.go:871: Listening on 127.0.0.1:11434 (version 0.1.16)
2023/12/18 21:59:15 routes.go:891: warning: gpu support may not be enabled, check that you have installed GPU drivers: nvidia-smi command failed
```

**Comment by Redhawk18** [comment]
bump, I know theres rocm for amd but would that actually fix it?

**Comment by Redhawk18** [comment]
#814

**Comment by srgantmoomoo** [comment]
better question, can i force it to just run on my cpu?

**Comment by srgantmoomoo** [comment]
or simply, how can i run this on an intel or amd system.

**Comment by technovangelist** [comment]
If you don't have an nVidia GPU we will just use CPU. Are you saying its not running? What OS, CPU, and how much ram do you have?

**Comment by srgantmoomoo** [comment]
yes, it is not running. it's giving the error i showed in my first message. tried it on linux mint, ryzen 3 5000 series cpu, 20 gb ram. As well as on a different, newer machine with an intel core i5, through debian on wsl. got the same error for both.

**Comment by Leo512bit** [comment]
>If you don't have an nVidia GPU we will just use CPU.

I get same error on Intel Arc on WSL, I didn't see any flags to force ollama to run on the CPU, I also tried to disable GPU acceleration in WSL but I still got the same error. (Mot sure if GPU acceleration was in fact disabled on WSL but I did set it in the 
`.wslconfig` file.)

**Comment by technovangelist** [comment]
What model are you trying to run?

**Comment by srgantmoomoo** [comment]
> What model are you trying to run?

i get the error after running `ollama serve`. my intention is to run mistral... but i haven't even gotten to a point where i can run anything.

**Comment by srgantmoomoo** [comment]
i installed it using `curl https://ollama.ai/install.sh | sh`

**Comment by technovangelist** [comment]
so `ollama serve` should already be running and you don't need to run it yourself. Aslo, i don't see an error. What happens when you run `ollama run mistral`?

**Comment by srgantmoomoo** [comment]
> so `ollama serve` should already be running and you don't need to run it yourself. Aslo, i don't see an error. What happens when you run `ollama run mistral`?

i do have to run `ollama serve`, if i run `ollama run mistral` i get `Error: could not connect to ollama server, run 'ollama serve' to start it`.

**Comment by technovangelist** [comment]
so what happens when you run `ollama run mistral` in a different terminal?

**Comment by srgantmoomoo** [comment]
> so what happens when you run `ollama run mistral` in a different terminal?

umm... same error? why would that change with the terminal im using?

**Comment by technovangelist** [comment]
what error?

**Comment by srgantmoomoo** [comment]
are you trolling me? the error in my original comment - 
https://github.com/jmorganca/ollama/issues/1594#issue-2047830033

**Comment by srgantmoomoo** [comment]
when i run ollama serve i get the following -
```2023/12/18 21:59:15 images.go:737: total blobs: 0
2023/12/18 21:59:15 images.go:744: total unused blobs removed: 0
2023/12/18 21:59:15 routes.go:871: Listening on 127.0.0.1:11434 (version 0.1.16)
2023/12/18 21:59:15 routes.go:891: warning: gpu support may not be enabled, check that you have installed GPU drivers: nvidia-smi command failed
```

when i run `ollama run mistral` i get the following -
`Error: could not connect to ollama server, run 'ollama serve' to start it`

**Comment by technovangelist** [comment]
would you be open to joining a zoom session so i can see whats going on?

**Comment by srgantmoomoo** [comment]
i could if that is easier for you, discord would be easier for me though if you want to add me srgantmoomoo#1052. but i dont mind zoom if thats what you prefer

**Comment by technovangelist** [comment]
discord would be best

**Comment by technovangelist** [comment]
I don't see you in the discord. Are you there?

**Comment by technovangelist** [comment]
I am mattw there

**Comment by technovangelist** [comment]
@srgantmoomoo and I worked through the issue on a Discord DM. `ollama serve` outputted what looks like an error message and they quit the program. The solution was to let it run and then in a new terminal window, run `ollama run <modelname>`

I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
