### ISSUE TITLE
Delete partially downloaded models.

### ISSUE THREAD

**Issue by luckydonald** [jmorganca/ollama#1599]
So, I accidentally started downloading a 118 GB file.
I could see that it would add files to `~/.ollama/models/blobs`, however they are not picked up by the rm command.

The only way to do it is to download it completely, just to then instantly delete it (`$ ollama rm …`).

That's quite wasteful for you guys bandwidth and actually my slow internet connection as well.
As I am running other model downloads, the timestamps don't really help in figuring out which files to delete.

Probably the first and easiest solution to this could be writing the `manifests` file with the start of the download.

**Comment by easp** [comment]
FWIW, restarting the backend server cleans up partial downloads.

**Comment by technovangelist** [comment]
Exactly. We have a pruning process that will automatically remove incomplete files. That occurs the next time the server starts. If you want to force it to run, quit Ollama from the menubar icon, then run Ollama again.

**Comment by jmorganca** [comment]
Hi there @luckydonald – Ollama will automatically "prune" all partially downloaded files when you restart it, so you can do this to purge all partial downloads. Let us know if that helps!

**Comment by luckydonald** [comment]
Thanks!

**Comment by Zeus-Eternal** [comment]
This might also be helpful for anyone else with similar issues...

Just type `history` in the command terminal to see all your previous command entries ie. `1. ollama pull previous-model-pull-attempt`,`2. ollama run previous-model-run-attempt`, `4. ollama pull...`, this should allow you to re-trace your steps.

**Comment by gaardhus** [comment]
I +1 an `ollama prune` command to call the  [PruneLayers function](https://github.com/ollama/ollama/blob/8645076a71941d78a996e52cff65c794df6cdbcb/server/images.go#L796-L827).

**Comment by Asimoedeus** [comment]
I clicked "Quit ollama" and those partial files are removed!😃

**Comment by mafonya** [comment]
`rm -rf ~/.ollama/models/blobs/*partial*`

**Comment by ogmkp** [comment]
Restarting ollama server or rebooting dont prune partials blobs here.
I did:
rm /usr/share/ollama/.ollama/models/blobs/*
