### ISSUE TITLE
Error: 403 on pulling manifest

### ISSUE THREAD

**Issue by honggyukim** [jmorganca/ollama#1601]
Hi,

Thanks very much for building this great project!

I would like to set up ollama in the internal Linux server of my office but it fails pulling pre-trained models as follows.
```
# installation
$ curl https://ollama.ai/install.sh | sh 

# run
$ ollama run llama2 
pulling manifest 
Error: 403:
```
I've tested it before and it was fine in my home, but it only fails in the office internal server maybe due to security policy.

Could anyone please let me know where ollama downloads the pre-trained models? I need to know its URL to make a firewall exception.

Thanks.

**Comment by honggyukim** [comment]
Otherwise, is there any way manually download the models?

If possible, then I can put the models under `/usr/share/ollama/.ollama/models` manually.

**Comment by tuelle** [comment]
I have the same problem (also trying to deploy in the office). We have a proxy installed. Does ollama use proxy settings when downloading a model?

**Comment by mxyng** [comment]
Ollama uses your system proxy settings if they're set. See the [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy) for more details

**Comment by honggyukim** [comment]
Thanks for the reply but I haven't configured `HTTP_PROXY` nor `HTTPS_PROXY`.

My question is this. Where does ollama downloads pre-trained models?
