### ISSUE TITLE
Error: llama runner process has terminated

### ISSUE THREAD

**Issue by BrandonDR** [jmorganca/ollama#1603]
Cannot seem to run any model - I tried 3B and 7B models and no luck. They all fail immediately - I wonder if I am missing a dependency.

`ollama run orca-mini --verbose`
> Error: llama runner process has terminated

Does not appear to be a RAM issue, this VM has 64GB. The process fails immediately.
![image](https://github.com/jmorganca/ollama/assets/30581808/f2b624b6-b9ca-435c-a463-d73ae0fcf04d)

From `journalctl -u ollama` :
> Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:403: skipping accelerated runner because num_gpu=0
Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:436: starting llama runner
Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:494: waiting for llama runner to start responding
Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:451: signal: illegal instruction
Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:459: error starting llama runner: llama runner process has terminated
Dec 19 10:46:26 wt-chatbot-v1 ollama[639]: 2023/12/19 10:46:26 llama.go:525: llama runner stopped successfully

The `ollama serve` service daemon seems to be running
> ● ollama.service - Ollama Service
     Loaded: loaded (/etc/systemd/system/ollama.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-12-19 11:17:39 UTC; 3s ago
   Main PID: 901 (ollama)
      Tasks: 7 (limit: 77155)
     Memory: 8.9M
        CPU: 6ms
     CGroup: /system.slice/ollama.service
             └─901 /usr/local/bin/ollama serve
>
> Dec 19 11:17:39 wt-chatbot-v1 systemd[1]: Started ollama.service - Ollama Service.
Dec 19 11:17:39 wt-chatbot-v1 ollama[901]: 2023/12/19 11:17:39 images.go:737: total blobs: 16
Dec 19 11:17:39 wt-chatbot-v1 ollama[901]: 2023/12/19 11:17:39 images.go:744: total unused blobs removed: 0
Dec 19 11:17:39 wt-chatbot-v1 ollama[901]: 2023/12/19 11:17:39 routes.go:871: Listening on 127.0.0.1:11434 (version 0.1.16)
Dec 19 11:17:39 wt-chatbot-v1 ollama[901]: 2023/12/19 11:17:39 routes.go:891: warning: gpu support may not be enabled, check that you have installed GPU drivers: nvidia-smi command failed

## Environment

ollama version is 0.1.16
Installed via `curl https://ollama.ai/install.sh | sh`

Running in a Proxmox VM, with 12 threads and 64GB ram.

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by sudo-logic** [comment]
Facing the same error

**Comment by BrandonDR** [comment]
I stopped the daemon, and tried the official docker container. Same result.

![image](https://github.com/jmorganca/ollama/assets/30581808/03d244ac-1668-44c5-9089-ed8b18125c01)

**Comment by BrandonDR** [comment]
I set the VM's CPU 'type' to 'host' in Proxmox. From this issue it seems to be related to missing CPU instructions such as AVX.

https://github.com/jmorganca/ollama/issues/1503

![image](https://github.com/jmorganca/ollama/assets/30581808/c3739a0e-980a-4fce-a958-66c289611ec3)
