### ISSUE TITLE
Is it possible to use ollama to generate embeddings?

### ISSUE THREAD

**Issue by almosnow** [jmorganca/ollama#1608]
Sorry about the noob-ish question but am not familiar with how ollama does things.

I have a bunch of text snippets that I'd like to generate embeddings for, could ollama (any model, idc at tje moment) be used for this?

**Comment by easp** [comment]
There is an embeddings endpoint in the API: https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings

Note that Ollama (and llama.cpp) doesn't support many/most models _designed for_ embedding use.
