### ISSUE TITLE
Asking Llama 2 to read a local text file

### ISSUE THREAD

**Issue by wwavess** [jmorganca/ollama#161]
Has anyone been able to get Llama 2 to read a txt file for analysis?

**Comment by BruceMacD** [comment]
You can pass a text file into the prompt using command substitution, this just adds the content of the file to the prompt. This will be limited by context size in our default models at the moment, which isn't very large. 

Here is an example where I have some of the wikipedia article on llamas in a text file:
```
ollama run llama2 "$(cat llama.txt)" please summarize this article
Sure, I'd be happy to summarize the article for you! Here is a brief summary of the main points:
* Llamas are domesticated South American camelids that have been used as meat and pack animals by Andean cultures since the Pre-Columbian era.
* Llamas are social animals that live in herds and their wool is soft and contains a small amount of lanolin. They can learn simple tasks after a few repetitions and can carry about 25-30% of their body weight for 8-13 km (5-8 miles) when using a pack.
```

**Comment by mchiang0610** [comment]
Thank you for submitting this! This should be resolved. 

There is also a demo of this with privateGPT: https://github.com/jmorganca/ollama/tree/main/examples/privategpt 

Please let me know if it's not solving your use case. 

Thank you!

**Comment by dhowe** [comment]
> You can pass a text file into the prompt using command substitution, this just adds the content of the file to the prompt. This will be limited by context size in our default models at the moment, which isn't very large.
> 
> Here is an example where I have some of the wikipedia article on llamas in a text file:
> 
> ```
> $ ollama run llama2 "$(cat llama.txt)" please summarize this article
> Sure, I'd be happy to summarize the article for you! Here is a brief summary of the main points:
> * Llamas are domesticated South American camelids that have been used as meat and pack animals by Andean cultures since the Pre-Columbian era.
> * Llamas are social animals that live in herds and their wool is soft and contains a small amount of lanolin. They can learn simple tasks after a few repetitions and can carry about 25-30% of their body weight for 8-13 km (5-8 miles) when using a pack.
> ```

Is there a way to do this where one is back at the model prompt after ?
