### ISSUE TITLE
Linux Mint ollama pull model

### ISSUE THREAD

**Issue by dwk601** [jmorganca/ollama#1610]
I'm using Linux mint and after pulling model using ollama pull mistral I don't see any downloaded model in ollama folder in the usr directory.
Anyone knows where the model downloaded?

**Comment by technovangelist** [comment]
On linux, the models download to `/usr/share/ollama/.ollama`

**Comment by technovangelist** [comment]
I think this solves the issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by dwk601** [comment]
/usr/share/ollama/.ollama/models/blobs there are sha... files those are the models?
