### ISSUE TITLE
Test_Routes Version Handler assertion fails

### ISSUE THREAD

**Issue by alinanorakari** [jmorganca/ollama#1613]
this assertion fails when I try to build the project:

https://github.com/jmorganca/ollama/blame/1ca484f67e6f607114496211004942013e5595eb/server/routes_test.go#L74

Error:
```
[GIN] 2023/12/19 - 19:11:41 | 200 |      56.659µs |       127.0.0.1 | GET      "/api/version"
```
[...]
```
--- FAIL: Test_Routes (0.00s)
    routes_test.go:185: Running Test: [Version Handler]
    routes_test.go:74: 
                Error Trace:    /build/source/server/routes_test.go:74
                                                        /build/source/server/routes_test.go:199
                Error:          Not equal: 
                                expected: "{\"version\":\"0.0.0\"}"
                                actual  : "{\"version\":\"0.1.17\"}"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -{"version":"0.0.0"}
                                +{"version":"0.1.17"}
                Test:           Test_Routes
```

Either I don't fully understand how the assertion is supposed to work and I am doing something wrong or the version string `"0.0.0"` in this assertion should be `"0.1.17"`.

**Comment by mxyng** [comment]
How are you running the unit tests? The version string is set to 0.0.0 statically and modified during build time for releases. The expected value is 0.0.0 for this case.

**Comment by alinanorakari** [comment]
I'm building it as a Nix package via Nix' built in `buildGoPackage`, which automatically runs the tests. I'm not very deep into how Nix handles this behind the scenes. This is the implementation https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/go/package.nix

To me it looks like lines 238-240 in th checkPhase are responsible for running the tests:
```
      for pkg in $(getGoDirs test); do
        buildGoDir test "$pkg"
      done
```

I can manually disable the checkPhase, but I'd rather have it run the tests as intended

**Comment by mxyng** [comment]
I see. It looks like it passes the same build flags to `go test` as `go build` thereby changing the Version value.
