### ISSUE TITLE
llava (and llava:13b) requires to add an image (though the image path has been given)

### ISSUE THREAD

**Issue by yuan2ai** [jmorganca/ollama#1620]
The issue is as described in Title, and more details are as follows:

        (base) vncer@jx8122:/buffer1/codes$ sudo docker exec -it ollama ollama run llava        
        >>> what is in this image? /home/vncer/Documents/d2.png
        This model requires you to add a jpeg, png, or svg image.
        >>> what is in this image? '/home/vncer/Documents/d2.png'
        This model requires you to add a jpeg, png, or svg image.
        >>> what is in this image? "/home/vncer/Documents/d2.png"
        This model requires you to add a jpeg, png, or svg image.
        >>> "/home/vncer/Documents/d2.png"
        This model requires you to add a jpeg, png, or svg image.
        >>> '/home/vncer/Documents/d2.png'
        This model requires you to add a jpeg, png, or svg image.
        >>> /home/vncer/Documents/d2.png
        Unknown command '/home/vncer/Documents/d2.png'. Type /? for help
        >>> /home/vncer/Documents/d2.png what is in this image
        Unknown command '/home/vncer/Documents/d2.png'. Type /? for help

        *the image path is correct.

System Info:
        ollama version is 0.1.17
        ollama installation: docker (sudo docker exec -it ollama ollama run llava)
        operating system: Ubuntu 22

Extra Info:
        I have used ollama to run dolphin-mixtral, and it works well. No problem at all.

Can anyone help? Thanks so much!

**Comment by igorschlum** [comment]
Try using a colon (:)

Describe rhis image:  /home/vncer/Documents/d2.png

**Comment by yuan2ai** [comment]
> Hi @yuan2ai , Try using a colon (:)
> 
> Describe this image: /home/vncer/Documents/d2.png

Thanks for your reply, while it still doesn't work from my side.
>>> Describe this image: /home/vncer/Documents/d2.png
This model requires you to add a jpeg, png, or svg image.

**Comment by igorschlum** [comment]
What computer and OS are you using? How much memory is available?
Could you share the log?

**Comment by yuan2ai** [comment]
> What computer and OS are you using? How much memory is available? Could you share the log?

Hi, issue resolved. Thanks.
I need to mount the folder of the container, with the -v option: sudo docker run -d --gpus=all -v ollama:/root/.ollama -v /home/vncer/Documents:/home/vncer/Documents -p 11434:11434 --name ollama ollama/ollama

**Comment by yuan2ai** [comment]
Always mount the correct folder when using docker.

**Comment by dhenson02** [comment]
> > What computer and OS are you using? How much memory is available? Could you share the log?
> 
> Hi, issue resolved. Thanks. I need to mount the folder of the container, with the -v option: sudo docker run -d --gpus=all -v ollama:/root/.ollama -v /home/vncer/Documents:/home/vncer/Documents -p 11434:11434 --name ollama ollama/ollama

lol yeah the error is useless.  this fixed it for me too (wasn't targeting the right dir)
