### ISSUE TITLE
Get error when run ```ollama run mixtral:8x7b-text-v0.1-q6_K    ```

### ISSUE THREAD

**Issue by yunfengsay** [jmorganca/ollama#1633]
~ ❯ ollama run mixtral:8x7b-text-v0.1-q6_K       ✘ INT  base  system 23:39:41
⠋   Error: invalid version

ollama version: 0.1.1
system:  Ubuntu 23.10 mantic

**Comment by phalexo** [comment]
Doesn't the name have the suffix ":latest"?

**Comment by mattbisme** [comment]
> Doesn't the name have the suffix ":latest"?

Depends on what tag is being used.

**Comment by easp** [comment]
Ollama version? Update to the latest available.

System configuration? [Logfile entries](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-view-the-logs)?

**Comment by easp** [comment]
@phalexo 
>Doesn't the name have the suffix ":latest"?

No. It's not necessary to specify :latest if you want to use the default  (ie mixtral) and latest isn't appropriate if you are specifying another tag, like ":8x7b-text-v0.1-q6_K."

**Comment by yunfengsay** [comment]
> Ollama version? Update to the latest available.
> 
> System configuration? [Logfile entries](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-view-the-logs)?
![image](https://github.com/jmorganca/ollama/assets/15527378/7ff40c8b-30c6-4a4f-9665-463c91042774)
![image](https://github.com/jmorganca/ollama/assets/15527378/40fddbda-aae1-48b1-8698-c1ab7ccf1833)

**Comment by yunfengsay** [comment]
It works after upgrade ollama to 0.1.17

**Comment by jmorganca** [comment]
@yunfengsay fantastic! Sorry the error isn't clearer RE requiring an upgrade. Will improve this!
