### ISSUE TITLE
gpu issues 

### ISSUE THREAD

**Issue by RootnuII** [jmorganca/ollama#1648]
warning: gpu support may not be enabled, check that you have installed GPU drivers: nvidia-smi command failed

i have installed all drivers for my gpu:1070ti 

still nothing maybe i installed the wrong drivers can someone point me in the right direction

**Comment by jmorganca** [comment]
Hi @RootnuII , may I ask which drivers you have installed - and what `nvidia-smi` outputs in the terminal? Thanks so much and sorry you're hitting an issue!

**Comment by SCOL-Leo** [comment]
@RootnuII Did you install nvidia-smi? If you install drivers this package is not always included in every distro.

**Comment by zanovis** [comment]
@RootnuII Is this happening in WSL?

**Comment by RootnuII** [comment]
all fixed with wsl 2 :)

**Comment by zanovis** [comment]
> all fixed with wsl 2 :)

Which drivers are you using? Still having this issue in WSL2 on 1080Ti. Thanks!
