### ISSUE TITLE
Make it simple to add new models from Huggingface

### ISSUE THREAD

**Issue by joshlewis** [jmorganca/ollama#165]
I love ollama! This is sweet.

I'm a beginner with LLM stuff. I see ollama has built-in support for several models like Nous-Hermes, Orca Mini, and a couple varieties of Llama2. I'd love it if it were just as easy (or at least almost as easy?) to add support for other models we find on huggingface.co with a simple command. Then once I had done that, I could run `ollama pull whatevermodel` and it would just do what it was supposed to do.

**Comment by mchiang0610** [comment]
@joshlewis Thank you! There is a workaround right now in that you can create a modelfile for the custom GGML models. 

In the modelfile, you can specify `FROM ./custom_model_name.bin`  and then create a model from there.

**Comment by joshlewis** [comment]
I don't agree this is completed. There's a workaround that sometimes works if you known enough to figure out how to set everything up, but it's not "simple". What I'm asking for is to make it simple.
