### ISSUE TITLE
GPU not in use?

### ISSUE THREAD

**Issue by Y2K350** [jmorganca/ollama#1651]
I am running Ollama which was installed on an arch linux system using "sudo pacman -S ollama" I am using a RTX 4090 with Nvidia's latest drivers. I also installed cuda using "sudo pacman -S cuda"

I run the LLM using the command "ollama run dolphin-mixtral:latest"

it does not appear to use the GPU based on GPU usage provided by GreenWithEnvy (GWE), but I am unsure how to verify that information.

Is there a specific command I need to run to ensure it uses the GPU instead of the CPU?

nvidia-smi returns:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0  On |                  Off |
|  0%   42C    P8              37W / 450W |  20102MiB / 24564MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3261      G   /usr/lib/Xorg                               632MiB |
|    0   N/A  N/A      3360      G   /usr/bin/gnome-shell                        327MiB |
|    0   N/A  N/A      3778      G   /usr/lib/xdg-desktop-portal-gnome            14MiB |
|    0   N/A  N/A      3973      G   gjs                                          99MiB |
|    0   N/A  N/A      4337      G   /app/lib/librewolf/librewolf                219MiB |
|    0   N/A  N/A      5088      G   ...,WinRetrieveSuggestionsOnlyOnDemand      167MiB |
|    0   N/A  N/A     67846      G   /usr/bin/gnome-text-editor                   13MiB |
|    0   N/A  N/A     69685      C   ...p/gguf/build/cuda/bin/ollama-runner    18000MiB |
|    0   N/A  N/A    101455      G   /usr/bin/nautilus                            32MiB |
|    0   N/A  N/A    101815      G   /usr/bin/kgx                                549MiB |
+---------------------------------------------------------------------------------------+

**Comment by xyproto** [comment]
Hi @Y2K350, maintainer of the `ollama` and `ollama-cuda` for Arch here.

The `ollama` package only uses the CPU, while the `ollama-cuda` package has support for CUDA.

**Comment by Y2K350** [comment]
> Hi @Y2K350, maintainer of the `ollama` and `ollama-cuda` for Arch here.
> 
> The `ollama` package only uses the CPU, while the `ollama-cuda` package has support for CUDA.

Thank you so much!

**Comment by misaligar** [comment]
> Hi @Y2K350, maintainer of the `ollama` and `ollama-cuda` for Arch here.
> 
> The `ollama` package only uses the CPU, while the `ollama-cuda` package has support for CUDA.

Is there a ROCm package for AMD GPUs?

**Comment by xyproto** [comment]
Not yet, but I think the ollama executable does quite a bit of auto-detection at runtime, and that the ollama-cuda package might not be needed anymore.

**Comment by misaligar** [comment]
> Not yet, but I think the ollama executable does quite a bit of auto-detection at runtime, and that the ollama-cuda package might not be needed anymore. 

Thanks. I asked because the executable did not recognize my GPU. Had to compile from source with amdgpu_targets parameter. Also opened an issue to document my experience.

**Comment by ioquatix** [comment]
Do we still need to use `ollama-cuda`? Even thought `ollama` shows that my GPU is detected (4090), it still uses the CPU.

**Comment by rs38** [comment]
same here (windows)

**Comment by ioquatix** [comment]
In the end, I tried `ollama-cuda` and it worked using my GPU. So, something is not quite right with the official distribution (on Arch).

**Comment by rs38** [comment]
I somehow retried it with the localhost server and checked the logs.
after 1-2 retries it was using the GPU even with the "standard" llama2

**Comment by casidiablo** [comment]
I am using Manjaro, so not too different from Arch, and I encounter two weird behaviors:

1. Even though the GPU is detected, and the models are started using the cuda LLM server, the GPU usage is 0% all the time, while the CPU is always 100% used (all 16 cores).

![image](https://github.com/ollama/ollama/assets/144458/0232ca85-6065-48cf-abd5-bf16410f3993)


2. Sometimes when ollama server loads the model with the GPU LLM Server (cuda_v12 in my case), it generates gibberish. If I force ollama to use cpu_avix2 instead, the responses are ok.

![image](https://github.com/ollama/ollama/assets/144458/9e1a5842-8f0a-4baf-9719-93455633e086)


Any ideas of what I could be doing wrong?

My card is is NVIDIA RTX A2000.

**Comment by rs38** [comment]
I think 4GB VRAM is not enough to hold an operating 7G model.
I have a 6 GB VRAM Nvidia Laptop that takes ~5 GB

`+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.65                 Driver Version: 546.65       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 ...  WDDM  | 00000000:02:00.0 Off |                  N/A |
|  0%   41C    P8               3W /  49W |   5030MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+`

**Comment by casidiablo** [comment]
Ok, yeah, I get it know. I tried orca-mini which is a 3b params model, and I see what I was expecting (no cpu usage, and the model responds super fast)

**Comment by eruca** [comment]
> In the end, I tried `ollama-cuda` and it worked using my GPU. So, something is not quite right with the official distribution (on Arch).

how to install `ollama-cuda` on the Ubuntu 22.04 with 4090

**Comment by TimSousa1** [comment]
@eruca it's a package for Arch linux, not Ubuntu..

**Comment by austinksmith** [comment]
How can we get ollama making use of the gpu on Ubuntu 22? I've also installed and am running llama3 and phi3 models, when I installed ollama it detected my GPU however it doesnt use my GPU? There are no errors or warning messages, the model runs fine.. it just uses the cpu and not the gpu.

**Comment by itinance** [comment]
I figured out, that for **LLama3**, the GPU will be used properly, while with **Mistral** and **StableLM2** the GPU is not being used at all: https://github.com/ollama/ollama/issues/4359

**Comment by CreeperMain** [comment]
hi i have tried both mistral:7b and llama3:8b and both didnt use my gpu, i dont know how to install ollama-cuda or if i need to flip a switch to get it to use my gpu
specs:
Version: ollama version is 0.1.37
GPU: GTX 1650
CPU: Ryzen 5 4600H
OS: Gentoo 2.15 x86_64

**Comment by xyproto** [comment]
For some (most?) distros, Ollama is distributed as a package that comes with an executable named `ollama` that supports CPU, AVX, CUDA, ROCm etc, and tries to auto-detect which one it should use.

For Arch Linux, the [`ollama`](https://archlinux.org/packages/extra/x86_64/ollama/) package just uses the CPU and uses less disk space (useful in combination with Docker and in the cloud), while [`ollama-cuda`](https://archlinux.org/packages/extra/x86_64/ollama-cuda/) comes with support for NVIDIA GPUs / CUDA and [`ollama-rocm`](https://archlinux.org/packages/extra/x86_64/ollama-rocm/) comes with support for AMD GPUs / ROCm. The `ollama-cuda` and `ollama-rocm` packages are much larger. than the `ollama` package. In addition to saving disk space, the idea is that installing a package named `-cuda` or `-rocm` is a strong hint and an aid for users in being sure that they installed the right package, and which capabilities they can then expect.

For Ubuntu, there appears to be [a snap package for Ollama](https://snapcraft.io/install/ollama/ubuntu), but [no regular official package](https://packages.ubuntu.com/search?keywords=ollama&searchon=names&suite=all&section=all).

**Comment by Syphdias** [comment]
@xyproto, what if you have an AMD GPU _and_ a NVIDIA GPU?
To be clear I, I don't. But out of curiosity. Would it make sense to have a `ollama-full` package (not sure if that meets the naming guidelines)?

**Comment by xyproto** [comment]
@Syphdias If someone has a very unusual setup, they can always install Ollama by tweaking and building the official package, install Ollama with a package from AUR, using snap/flatpak, download a release or build and install Ollama manually. Please let me know if AMD+NVIDIA GPU setups do become popular, though.

**Comment by frederickjjoubert** [comment]
Hi, I'm on PopOS 22.04, NVIDIA 2080 Ti. I am also noticing no GPU usage when I run `ollama` and my CPU spikes. How can I run `ollama` with my GPU?

**Comment by sammcj** [comment]
Hi all, give this fix a go: https://github.com/ollama/ollama/issues/4604#issuecomment-2130436000

**Comment by lakshaysethi** [comment]
Ollama, at least, needs to say in logs that i'm not going to use Gpu because your vram is less. Or give other reason as to why it chose to not use GPU.

For me, I am using an RTX3060 8GB and the issue really doesn't seem to be around which Linux distro, I get the same issue with ubuntu. It's a pain in the bum(ive spent the whole night trying), to get ollama to use the gpu instead of the cpu with the small models.


I'm going to install Arch linux and then try ollama-cuda.

 If I'm successful, I'll report back here.

**Comment by lakshaysethi** [comment]
Okay, found out what the issue was.

At least in my case.
We can look at the logs outputted by  ollama serve 

In there it said cpu doesn't support AVX

 

But my cpu  does actually support avx 


So the solution was to go into the bios settings, and then turn on the avx, to enabled, It was initially set to default auto, which I think means not enabled.


Now everything works as perfect the logs of ollama serve recognize my GPU and it is very fast when responding than GPU.

**Comment by luchfilip** [comment]
> Okay, found out what the issue was.
> 
> At least in my case. We can look at the logs outputted by ollama serve
> 
> In there it said cpu doesn't support AVX
> 
> But my cpu does actually support avx
> 
> So the solution was to go into the bios settings, and then turn on the avx, to enabled, It was initially set to default auto, which I think means not enabled.
> 
> Now everything works as perfect the logs of ollama serve recognize my GPU and it is very fast when responding than GPU.

it was already enabled, but still no GPU usage when running any ollama models. I see CPU spiking when interacting with ollama. 
RTX4070 TI
