### ISSUE TITLE
It takes forever to run ollama (llama2 or mistral) in wsl

### ISSUE THREAD

**Issue by allmin** [jmorganca/ollama#1654]
Hi I just installed ollama in wsl using curl. I tried **ollama run llama2** and **ollama run mistral**.
It doesn't enter into the prompt. A tiny rotating snake like objects appears in the terminal and it has been several hours like this. Nothing much happened. please help me fix it.

My system:
Intel i7
RTXA2000 Laptop GPU : 4GB vRAM (0 GB used)

**Comment by igorschlum** [comment]
Hi @allmin
I think that you don't have enough memory. 4GB is nice, but not for IA. Try phi model. It's only a 1.6GB Gigabit file size, but can take more in GPU.
ollama run phi

**Comment by allmin** [comment]
Thank you! phi works!, I was indeed looking for smaller models but the
model library page: library (ollama.ai) <https://ollama.ai/library> was
lacking the information on memory requirements.

**Comment by allmin** [comment]
BTW, It'd be helpful to also share here that I tried running llama2 through docker and it works perfectly on my 4GB GPU (Nvidia RTXA2000)!
