### ISSUE TITLE
Feature request: delete partially downloaded model

### ISSUE THREAD

**Issue by kokizzu** [jmorganca/ollama#1658]
So i was downloading some model, and apparently it took like 26GB of disk space XD
so i cancelled it midway
tried to `ollama rm dolphin-mixtral` but it shows `Error: model 'dolphin-mixtral' not found`
it would be nice if there's command to remove partially downloaded model.

**Comment by Stud1243** [comment]
https://colab.research.google.com/github/koboldai/KoboldAI-Client/blob/main/colab/GPU.ipynb#scrollTo=Lrm840I33hkC
