### ISSUE TITLE
unexpected EOF Mac OS

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [jmorganca/ollama#1668]
I got error
```
> ollama run dolphin-mixtral:latest
pulling manifest
pulling bdb11b0699e0...  60% ▕██████████████████             ▏  15 GB/ 26 GB  3.4 MB/s  52m23s
Error: max retries exceeded: unexpected EOF
```

Here is my `.ollama/logs/server.log`
[server.log](https://github.com/jmorganca/ollama/files/13748433/server.log)

**Comment by CupOfGeo** [comment]
Hi new here but looks like other are having this issue as well #1036 . Not entirely sure its an ollama issue or your internet connection. Looks like you might be able to retry the download.

**Comment by La-te** [comment]
Similar issue here. My connection is not reliable in this location and I have finally completed one model. However, it would be great if I could configure for much more retries instead of doing it manually.

**Comment by La-te** [comment]
Similar issue here. My connection is not reliable in this location and I have finally completed one model. However, it would be great if I could configure for much more retries instead of doing it manually.

**Comment by jmorganca** [comment]
Hi folks, I'm so sorry you hit this – it's being worked on! Merging in the meantime with https://github.com/jmorganca/ollama/issues/1158

**Comment by spikezz** [comment]
Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder zu löschen.Drücken Sie lange auf ein Element in der Zwischenablage, um es anzupinnen. Nicht angepinnte Elemente werden nach einer Stunde gelöscht.Drücken Sie lange auf ein Element in der Zwischenablage, um es anzupinnen. Nicht angepinnte Elemente werden nach einer Stunde gelöscht.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder zu löschen.Wä hlen Sie das Stiftsymbol aus, um       ~~  ~~ Elemente anzupinnen, hinzuzufügen oder zu löschen.Tippen Sie auf ein Element, um es in das Textfeld einzufügen.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder zu - [ ] löschen.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder zu löschen.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, hinzuzufügen oder h  zu löschen.Wählen Sie das Stiftsymbol aus, um Elemente anzupinnen, # hinzuzufügen oder zu löschen.....
