### ISSUE TITLE
"api/chat loads the model only when a request is received. Is it possible to add a flag to keep a specific model in memory permanently, to improve response time?"

### ISSUE THREAD

**Issue by highjim** [jmorganca/ollama#1672]
"api/chat loads the model only when a request is received. Is it possible to add a flag to keep a specific model in memory permanently, to improve response time?"

**Comment by justinh-rahb** [comment]
This is easily supported by llama.cpp by passing the mlock argument. Would make for slow switches if someone requests a different model I would think though, especially if you don't have a massive amount of RAM.

**Comment by rgaidot** [comment]
ah! I hadn't seen that they'd added "mlock" on ollama via "use_mlock" (default value is false). This information could answer several issues.

- https://github.com/jmorganca/ollama/blob/main/llm/ext_server.go#L157C34-L157C42
- https://github.com/jmorganca/ollama/blob/main/docs/api.md

**Comment by highjim** [comment]
@rgaidot  thxs

**Comment by anan-dad** [comment]
@highjim have you solved the problem, would you please give more detailed steps how you solve that
