### ISSUE TITLE
OLLAMA_ORIGINS=chrome-extension://etc does not work

### ISSUE THREAD

**Issue by sublimator** [jmorganca/ollama#1686]
```
(base) ➜  ~ OLLAMA_ORIGINS=chrome-extension://dofdpnoclkigpakdndmhigfojjecnfln ollama serve
2023/12/23 15:37:56 images.go:737: total blobs: 85
2023/12/23 15:37:56 images.go:744: total unused blobs removed: 0
panic: bad origin: origins must contain '*' or include http://,https://
```

**Comment by rgaidot** [comment]
why `chrome-extension://....` ? You can exposing ollama via `127.0.0.1:11434` or 0.0.0.0:11434 on your local network

**Comment by sublimator** [comment]
Yeah, but it restricts by origin, which last I checked (to be fair, years
ago) is set to chrome-extension:// in the header?

I have been using a proxy script, and only got around to trying the header
today. Seems need to use * or an http[s] url, with the former less than
ideal to direct users to set.

Am I missing/confusing something?

Thanks

**Comment by sublimator** [comment]
Fixed with: https://github.com/jmorganca/ollama/pull/1797/files
