### ISSUE TITLE
Old Models disappear  after Ollama Update (0.1.17)  

### ISSUE THREAD

**Issue by sthufnagl** [jmorganca/ollama#1687]
Hi,

**Environment:**
my environment ist WSL on Win11. 

**Update Command:**
curl https://ollama.ai/install.sh | sh

**Situation:**
After an Update to Ollama 0.1.17 all my old Models (202GB) are not visible anymore and when I try to start an old one the Model is downloaded once again. Physically the Model Files are available but not listed (ollama list) or used.
I want to avoid to download the old models once again.

**Reason for Update:**
I wanted to use PHI but after downloading I got some error messages ==> Update of ollama was necessary

**Question:**
* Can I restore my old Models?
* Is there an entry in a config file?

Thx in advance

**Comment by coffeecodechem** [comment]
Physically the model is in GGUF right? Maybe try this guide: https://github.com/jmorganca/ollama?tab=readme-ov-file#import-from-gguf

Then for each model you have, create a Modelfile https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md

You will find the recommended template for each model in https://ollama.ai/library. Look for the model, click Tags.

**Comment by BruceMacD** [comment]
There seems like there could be an on-going bug here, this sounds similar to #1493. In that case they were able to get Ollama to pick-up the models by running "list" a few times.

For troubleshooting reasons which directory are you seeing the model files in that Ollama is not picking up?

**Comment by sthufnagl** [comment]
Hi,
thanks for your helping hand.
:-)
Because my old PC had watercooling problems...I installed ollama on a different PC.
There I recognize that the **models are stored on a different location**.

**Ollama 0.1.16 use:** ~/.ollama/models
**Ollama 0.1.17 use:** /usr/share/ollama/.ollama/models

Maybe this is the reason? 

BTW, I made a backup on an USB Stick before I did an Ollama Upgrade. 
Can I simple copy the model files to /usr/share/ollama/.ollama/models ?

Thx

**Comment by sthufnagl** [comment]
Hi,
I'm now one step further...and find a workaround.

* It seems that Ollama 0.1.17 install a system service "ollama.service"
* This service expect the model files at /usr/share/ollama/.ollama/models
* When I stop the service with "systemctl stop ollama.service" and start Ollama with "ollama serve &" Ollama expect the Model Files at "~/.ollama/models"
* After restoring the Model Files from USB Stick to  "~/.ollama/models" everything works!!!
* So I will disable the Ollama system service

Thx

**Comment by sthufnagl** [comment]
Please see last comment...

**Comment by BruceMacD** [comment]
Thanks for following up 🙏

**Comment by davidbuzz** [comment]
I consider this a bug that 'ollama serve' and the ollama service look in different folder/s for their models. At the very least 'ollama serve' should be able to look at both folder/s.

**Comment by little-engineer-2025** [comment]
I faced similar situation; I started and downloaded a model by running `ollama serve` with my user, and thanks to this thread (thanks @sthufnagl ) I found where was downloaded the model; In my scenario I found that only moving the ~/.ollama/{blobs,manifests} to /usr/share/ollama/{blobs,manifests} respectively, and changing the owner to `ollama:ollama`, I could run as a systemd service and see the model was available by `ollama list` and use it by just `ollama run mymodel`. I was using Arch linux, maybe that made some path different; Sharing if it helps to other users.
