### ISSUE TITLE
How to enter multiline text

### ISSUE THREAD

**Issue by abulka** [jmorganca/ollama#169]
How to enter multiline text?
When I hit enter, the input prompt teminates. In ChatGPT I can hit SHIFT enter to begin a new line but not with ollama.
Even pasting multiline text works in  ChatGPT but not with ollama.

A workaround seems to be to pipe text files in - see #161 

Shouldn't there be a multiline mode or something? Like https://github.com/ggerganov/llama.cpp/issues/1382

**Comment by pdevine** [comment]
I'm definitely thinking about different ways to do this, but I'm still not 100% certain which way to go. Piping files does work for now. I'm not (yet) convinced about the llama.cpp approach though.

**Comment by abulka** [comment]
Seems you can use the API to enter multiline prompts e.g.

```json
{
    "model": "llama2",
    "prompt": "what does this code do\npublic class App \n{\n    public static void main( String[] args )\n    {\n        System.out.println( \"Hello World!\" );\n    }\n}"
}
```

If the API supported file upload that might be kind of cool too.

**Comment by mxyng** [comment]
This is possible as of v0.0.13 by starting the multiline string with `"""`. Once you are done with the multiline input, close it with another `"""`.

```
$ go run . run llama2
>>> """tell
... me
... a
... joke"""
Of course! Here is a neutral and respectful joke:

Why did the computer go to therapy?
It had a virus!

I hope you found that joke amusing. Is there anything else I can help you with?
```

**Comment by nonetrix** [comment]
Copying and pasting multiple lines doesn't seem to work still, how can I do that? Sorry for commenting on a old thread

**Comment by pdevine** [comment]
@nonetrix what platform/terminal are you using, and what version of Ollama are you using? We added "bracketed paste mode" a while ago, so it should be working as long as you have a decent terminal.

**Comment by nonetrix** [comment]
Hm I am using Wezterm so maybe it's a issue there?

**Comment by pdevine** [comment]
@nonetrix It looks like it supports [bracketed paste mode](https://wezfurlong.org/wezterm/cli/cli/send-text.html) is supported?

**Comment by nonetrix** [comment]
Strange, no idea then. I am running ollama 0.1.28, wezterm 20240203-110809-5046fc22. Knowing wezterm and it's currently abysmal Wayland support because of a Wayland backend rewrite that's still kinda buggy, I thought it could be Wayland maybe because it does clipboard stuff differently but same on XWayland

**Comment by pdevine** [comment]
Maybe a bug in wezterm then? I just tested this out w/ macOS and iTerm2 and it's definitely working correctly.

**Comment by nonetrix** [comment]
Seems fixed now suddenly

**Comment by ngocducdim** [comment]
Hi, is there anyway to enter new line in powershell when writing prompt? I try Ctrl + Enter & Shift + Enter both not working:

![Image](https://github.com/user-attachments/assets/402f8862-5d8a-4ffa-85b9-0610e118db84)

**Comment by colltoaction** [comment]
What if the documents have `"""` occurrences as well? A flag to pass multiple files as inputs would be great. The CLI would ingest all files as the prompt.

**Comment by pdevine** [comment]
if you're pasting I think the """'s will get skipped. For images, you should be able to copy multiple file names and it will pick them up automatically, but it'd be nice to do that for any file.

**Comment by webdevelopers-eu** [comment]
CTRL+J ?

**Comment by Jane-Doe-XD** [comment]
@webdevelopers-eu  Thank you o_0 <3
