### ISSUE TITLE
How to make the model stop generating response when using via API?

### ISSUE THREAD

**Issue by EliasPereirah** [jmorganca/ollama#1695]
When using Via Cli I can give Ctrl+C, but how to do it via API?
Can anyone help me with this?

**Comment by BruceMacD** [comment]
Hi @EliasPereirah when the connection is closed Ollama should stop generating. When you press ctrl+c in the CLI that is what is happening.

Here is a quick example in Python of closing a connection, which should stop Ollama from generating more on the back-end:
```Python
import requests
import json

url = 'http://localhost:11434/api/generate'

data = {
    'model': 'llama2',
    'prompt': 'Why is the sky blue?'
}

response = requests.post(url, json=data)

# Close the connection rather than reading through the streamed response, which stops Ollama from continuing to generate
response.close()
```

**Comment by EliasPereirah** [comment]
> Hi @EliasPereirah when the connection is closed Ollama should stop generating. When you press ctrl+c in the CLI that is what is happening.
> 
> Here is a quick example in Python of closing a connection, which should stop Ollama from generating more on the back-end:
> 
> ```python
> import requests
> import json
> 
> url = 'http://localhost:11434/api/generate'
> 
> data = {
>     'model': 'llama2',
>     'prompt': 'Why is the sky blue?'
> }
> 
> response = requests.post(url, json=data)
> 
> # Close the connection rather than reading through the streamed response, which stops Ollama from continuing to generate
> response.close()
> ```

Thank you very much, but I don't think that's exactly what I want.
I'll explain my use case, maybe it will be clearer.
  I'm creating my own interface to communicate with the ollama API and sometimes the model used starts to hallucinate, in this case I want to leave a button on the web interface that I can click and the answer stops being generated, so I can ask a new question /interaction because having two responses running at the same time would be too heavy for my machine

**Comment by rgaidot** [comment]
Have you set up `signal` on your `fetch` with `AbortController`?

**Comment by pdevine** [comment]
@EliasPereirah I think this should answer your question, so I'm going to go ahead and close. Feel free to reopen it if there's still an issue!
