### ISSUE TITLE
Any good examples of running flask with ollama(Mixtral)

### ISSUE THREAD

**Issue by andysingal** [jmorganca/ollama#1698]
Hi,
   I was trying to run my Mixtral model but was not sure how to verify:
```
python app.py
* Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000/
Press CTRL+C to quit
```
How to verify?
i saw some code online?

```
curl --location '<http://127.0.0.1:5000/process_form>' \\--form 'query="What does the author discuss about NFL"
```

**Comment by jeanjerome** [comment]
Hi,

Your curl request should be:
`curl --location 'http://127.0.0.1:5000/process_form' --form 'query="What does the author discuss about NFL"`

Have you tried these other implementations?: [https://github.com/jmorganca/ollama?tab=readme-ov-file#web--desktop](https://github.com/jmorganca/ollama?tab=readme-ov-file#web--desktop) ?

**Comment by rgaidot** [comment]
I don't understand, did you create a proxy for ollama with flask? Can you share your app.py?

If you want try directly via ollama:

```
curl http://127.0.0.1:11434/api/generate -d '{
  "model": "mistral",
  "prompt":"What does the author discuss about NFL"
}'
```

```
curl http://127.0.0.1:11434/api/chat -d '{
  "model": "mistral",
  "messages": [
    { "role": "user", "content": "What does the author discuss about NFL" }
  ]
}'
```

**Comment by technovangelist** [comment]
Hi @andysingal are you still having an issue or did the answers from @jeanjerome and @rgaidot solve it for you?

**Comment by andysingal** [comment]
Sorry for the late reply, the issue is resolved.

**Comment by technovangelist** [comment]
Great. Thanks so much for that info.
