### ISSUE TITLE
How do we output ollama response to file?

### ISSUE THREAD

**Issue by oliverbob** [jmorganca/ollama#1710]
If Ollama can read prompts from file, there has to be a way somehow to receive response to file and save it in the working directory.

How do I achieve this?

Scenario:

ollama run dolphin-phi
>>> '/home/ai/repo/llama2.c/run.c' rewrite this code with arguments for blah... :smile: 

Thanks.

**Comment by stmonty** [comment]
If you're on a Unix-like system (Linux, MacOS) you should be able to just do something like:
```
ollama run dolphin-phi "prompt" >> response.md
```
I have tried this using some other models and it worked.

**Comment by oliverbob** [comment]
Thanks

> If you're on a Unix-like system (Linux, MacOS) you should be able to just do something like:
> 
> ```
> ollama run dolphin-phi "prompt" >> response.md
> ```
> 
> I have tried this using some other models and it worked.

This is a big help.

**Comment by pongnguy** [comment]
I get a bunch of control characters.  How can I get a clean output?

**Comment by shakib04** [comment]
i developed  simple a bash script with the help of chatgpt to prompting.

`#!/bin/bash

# Define the output file
output_file="Response.md"

# # Ensure the output file is empty or create it if it doesn't exist
# > "$output_file"


# Loop until the user decides to exit
while true; do
    # Prompt the user for input
    read -p "Enter something (or type 'exit' to quit): " user_input

    # Check if the user wants to exit
    if [[ "$user_input" == "exit" ]]; then
        echo "Exiting..."
        break
    fi

    # Print the variable
    echo -e "<h2>======  Start of $user_input  ======</h2>" >> "Response.md"

    if [[ "$user_input" == *"-e"* ]]; then
      # Run the command and append the output directly to the file
      ollama run phi3:mini "explain/describe in easy way -$user_input" >> "$output_file"
    else
      # Run the command and append the output directly to the file
      ollama run phi3:mini "$user_input" >> "$output_file"
    fi

    echo -e "<h2>======  End of $user_input  ======</h2>" >> "Response.md"

    # Inform the user that the response has been saved
    echo "The response has been saved to $output_file"

done
`

**Comment by johntinker** [comment]
(I did an edit on the script above from shakib04:)

#!/bin/bash

# Define the output file
output_file="response.txt"

#Loop until the user decides to exit
while true; do
    # Prompt the user for input
    read -p "Enter something (or type 'exit' to quit): " user_input

    # Check if the user wants to exit
    if [[ "$user_input" == "exit" ]]; then
        echo "Exiting..."
        break
    fi

    # Print the variable
    echo -e "<h2>======  Start of $user_input  ======</h2>" >> ${output_file} 

    # Run the command and append the output directly to the file
    ollama run deepseek-r1:14b "$user_input" >> ${output_file} 
    
    echo -e "<h2>======  End of $user_input  ======</h2>" >> ${output_file} 

    # Inform the user that the response has been saved
    echo "The response has been saved to ${output_file}"
