### ISSUE TITLE
ollama pull shows a reversed question mark in the terminal

### ISSUE THREAD

**Issue by gerroon** [jmorganca/ollama#1725]
Hi

I know this is not an ollama caused issue, but I can't find a proper answer on the Internet, and `ollama pull` is the only command that is giving me this. Does anyone know why I am hitting this minor annoyance?

![image](https://github.com/jmorganca/ollama/assets/8519469/fc2080b0-7457-4091-afa1-ed11d50ab090)

**Comment by xprnio** [comment]
My guess is that you're missing nerd fonts, but I might be wrong

**Comment by technovangelist** [comment]
Thanks for submitting this issue, @gerroon . Did @xprnio comment solve your problem?
