### ISSUE TITLE
Streaming multiple json objects at the same time

### ISSUE THREAD

**Issue by pepperoni21** [jmorganca/ollama#1728]
It seems like sometimes Ollama streams multiple json objects one after the other in the same streamed response, which cannot be deserialized.

Here's an example of one single streamed json response using the /generate endpoint

```json
{"model":"dolphin-mixtral:latest","created_at":"2023-12-25T01:12:45.58944567Z","response":" you","done":false}\n
{"model":"dolphin-mixtral:latest","created_at":"2023-12-25T01:12:45.607384298Z","response":" today","done":false}\n
{"model":"dolphin-mixtral:latest","created_at":"2023-12-25T01:12:45.625372937Z","response":"?","done":false}\n
{"model":"dolphin-mixtral:latest","created_at":"2023-12-25T01:12:45.643531751Z","response":"","done":true,"context":[32001,6574,13,24205,574,8570,6817,28723,32000,13,32001,1838,13,21558,28801,13,32000,13,32001,489,11143,13,22557,28808,1602,541,315,6031,368,3154,28804],"total_duration":376468647,"load_duration":758387,"prompt_eval_count":23,"prompt_eval_duration":226302000,"eval_count":9,"eval_duration":147877000}
```

**Comment by xprnio** [comment]
Not sometimes, but always unless you specify `stream: false` in the request.
If `stream: true` (default), Ollama will stream a ND-JSON payload (Newline-Delimited JSON) which just means that each new line of the response is a separate JSON payload which you need to process. Depending on whether you want your application to support streaming the response or if you're okay with waiting for the whole response to come through before doing anything with it, you can change the `stream`  setting in the request.

https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion

**Comment by pepperoni21** [comment]
> Not sometimes, but always unless you specify `stream: false` in the request. If `stream: true` (default), Ollama will stream a ND-JSON payload (Newline-Delimited JSON) which just means that each new line of the response is a separate JSON payload which you need to process. Depending on whether you want your application to support streaming the response or if you're okay with waiting for the whole response to come through before doing anything with it, you can change the `stream` setting in the request.
> 
> https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion

Oh ok I didn't know this ND-JSON format, because most of the time I get 1 json object per payload. Thanks!

**Comment by marcospgp** [comment]
I ran into this same issue today and was unaware the format was expected. I guess two things come to mind:

1. If there are two chunks available, why not send them in a single object? If ollama sends chunks as soon as they are ready, one would expect there to only ever be one
2. The documentation should be clearer on this as I was not expecting it after reading it while setting up my code

**Comment by xprnio** [comment]
@marcusziade But the documentation does pretty clearly say that [the API returns a stream of JSON objects, as opposed to a single JSON object](https://github.com/ollama/ollama/blob/main/docs/api.md#response). I'm not sure if it's just me or what, but this seems like something that any moderately competent developer would be able to catch even without any documentation. But then again - we live in an age where more and more code is being written by AI, leading to the general reduction of actual programming knowledge among developers.

**Comment by pepperoni21** [comment]
> [@marcusziade](https://github.com/marcusziade) But the documentation does pretty clearly say that [the API returns a stream of JSON objects, as opposed to a single JSON object](https://github.com/ollama/ollama/blob/main/docs/api.md#response). I'm not sure if it's just me or what, but this seems like something that any moderately competent developer would be able to catch even without any documentation. But then again - we live in an age where more and more code is being written by AI, leading to the general reduction of actual programming knowledge among developers.

Then a simple link would've been enough, no one needed your opinion here

**Comment by marcusziade** [comment]
Why am I tagged here?

**Comment by xprnio** [comment]
> > [@marcusziade](https://github.com/marcusziade) But the documentation does pretty clearly say that [the API returns a stream of JSON objects, as opposed to a single JSON object](https://github.com/ollama/ollama/blob/main/docs/api.md#response). I'm not sure if it's just me or what, but this seems like something that any moderately competent developer would be able to catch even without any documentation. But then again - we live in an age where more and more code is being written by AI, leading to the general reduction of actual programming knowledge among developers.
> 
> Then a simple link would've been enough, no one needed your opinion here

Yet I felt it had to be mentioned. Was my opinion wrong in any way, or did you just feel hurt by the honesty within it? Trust me - if you want to have a discussion about this topic, then let's go. But being a delicate little snowflake and feeling hurt by my honest opinion (which, in my opinion, also carries valuable constructive criticism) isn't valuable to anybody either

**Comment by xprnio** [comment]
> Why am I tagged here?

Oh my god, I'm so sorry - I must've selected the wrong person from the dropdown. I'm sorry, I meant to tag @marcospgp

**Comment by marcusziade** [comment]
It's all good lol

**Comment by marcospgp** [comment]
@xprnio congrats on the hardcore non AI dev but docs say response is a stream of objects, doesn't mean more than one object will be sent per buffer flush

**Comment by xprnio** [comment]
@marcospgp Then please explain how you interpret what's said in the documentation, and how it could be improved. Maybe this is just the inverse of a skill issue, maybe it is just me understanding it because of prior experience, or maybe it's a language barrier. But in any case, I personally do think that the documentation is quite clear
