### ISSUE TITLE
Ollama - Llava Model Unable to detect image uploaded (WSL2 on Windows10)   

### ISSUE THREAD

**Issue by m4ttgit** [jmorganca/ollama#1734]
Trying to run Llava model using WSL2 on Windows10.  Ollama version is 0.1.16

Got this error message. 

![llava](https://github.com/jmorganca/ollama/assets/27547776/9ff50318-7c45-4ff8-9f2a-34184af29d56)

How do I fix this?  

Thanks

**Comment by technovangelist** [comment]
Hi @m4ttgit, thanks for submitting the issue. Let's see.. First I assume test.png is in that directory right now, correct? Also we are currently on version 0.1.17. There are sometimes little fixes along the way that may solve your issue. Can you first update to 0.1.17. 

I'll mark this as a bug for us to look into more, but let us know if the update to 0.1.17 solves it for you so we can then close the issue. Thanks so much.

**Comment by igorschlum** [comment]
@technovangelist the message is the same if the file doesn't exist or if the file exist, but is not a image.  It could be nice to have distinct messages.

**Comment by technovangelist** [comment]
Ahh, that’s a great thing to point out. We should change that.

**Comment by AndresAlgaba** [comment]
I am sorry to reopen this issue, but has any progress been made on this? 

On macOS (ollama version 0.1.32) with model llava:7b (https://ollama.com/library/llava:7b), I've also encountered the following issue: 
```shell
$ ollama run llava:7b
>>> What's in the image? /Desktop/joke_website.jpg
 I apologize, but I cannot see an image as you have provided a file path. Could you please provide me with the actual image or include it in your message so that I can assist you better?
 
$ ollama run llava:7b
>>> What's in this image? \Desktop\joke_website.jpg
 I'm sorry, but I cannot access or view external files. Can you please provide more context or details about the file?
 
$ ollama run llava:7b
>>> What's in this image? /Desktop/joke_website.jpg
 The image shows a joke website with the text "Why couldn't the bicycle stand up by itself?"
 
The answer to the riddle is "Because it was two-tired."
 
The website has a simple design, with a plain white background and black text. There is a logo in the top left corner, which appears to be of a bicycle. The overall style of the image suggests that it may
have been captured from a computer screen displaying the website.
```
