### ISSUE TITLE
Server doesn't listen on all available interfaces

### ISSUE THREAD

**Issue by zine999** [jmorganca/ollama#1735]
I think this might be a problem recently introduced in v0.1.17 but I'm not 100% sure.

`ollama serve` doesn't listen on `0.0.0.0` and therefore doesn't make itself available on all interfaces. This causes problems when trying to connect to it via an interface other than `localhost`.

A (hopefully temporary) workaround is using a utility like `socat`, e.g. to listen on all interfaces on port `8888` and relay traffic to port `11434`:

```
$ socat TCP-LISTEN:8888,reuseaddr,fork TCP:localhost:11434
```

**Comment by easp** [comment]
Listen address defaults to localhost. Are you setting it to 0.0.0.0?
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

**Comment by zine999** [comment]
I see, so it defaults to 127.0.0.1... but wouldn't it make more sense to have the default be 0.0.0.0 to avoid connection issues, and allow it to be overideable to something else like 127.0.0.1? I don't think there's a security issue as servers should have firewalls blocking traffic on ports anyway, and if it's run within a docker container the ports still need to be manually exposed.

**Comment by easp** [comment]
Ollama should use a secure configuration by default. The hosts firewall is another layer of defense and having multiple layers of security is consistent with the stance of defense in depth.

**Comment by zine999** [comment]
🤷‍♂️ OK, I'll close the issue, thanks for pointing me to the `OLLAMA_HOST` env var.
