### ISSUE TITLE
Low VRAM mode?

### ISSUE THREAD

**Issue by JumboTortoise** [jmorganca/ollama#1742]
I have a 12GB RTX 3060 that can easily run 7B models, but fails on the larger ones. Does ollama have a low-vram mode? Any way to move model layers from VRAM to system RAM? I would really like to try out larger LLM's without having to rent a cloud compute server or buy a new GPU, even if it is much slower due to inference optimizations.

I am not very knowledgeable on the subject, but maybe using DeepSpeed for boosting inference performance is a possibility?

**Comment by DrGood01** [comment]
#1727

**Comment by JumboTortoise** [comment]
Thanks, I saw this issue in the tracker but didn't understand it was what I was searching for.

**Comment by easp** [comment]
Ollama automatically spills models into system RAM, except when it doesn't work properly. I don't know why it sometimes doesn't work properly. I suspect it may be an issue with models that have larger context sizes, but I don't have a PC with NVIDIA, so I can't test it for myself.

**Comment by kilitary** [comment]
also if you have integrated video card, you have memory shared with cpu and belong to all system memory
