### ISSUE TITLE
[Feature] set Download directory for models while pulling/downloading from ollama

### ISSUE THREAD

**Issue by tikendraw** [jmorganca/ollama#1750]
Hey, 

In Ubuntu 23.10,
Previously, Ollama used to download the models into the root directory.
Now, it is downloading in the Home directory.  How do you control this?

I suggest a directory flag to let the user decide in which folder the model is supposed to go.

**Comment by BruceMacD** [comment]
Hi @tikendraw thanks for opening the issue, you should be able to set the directory that models are stored in using the `OLLAMA_MODELS` environment variable. There's a bit more detail on that here:
https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location

Let me know if you have any more follow up questions, I'm gonna resolve this one for now as it seems to be covered. n

**Comment by tikendraw** [comment]
> Setting the env variable, globally, permanently, and on the service itself, doesnt take effect, it keeps looking for space on /usr/share, is there something I could check?

Here is what i did that worked for me. Try this if you have not. 

in a `etc/systemd/system/ollama.service.d/environment.conf` file (if doesn't exist, then make one) and
write this or adjust accordingly

```
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_MODELS=/usr/share/ollama/.ollama/models"
```

restart maybe.

**Comment by marianoarga** [comment]
It works, thanks
