### ISSUE TITLE
How to add custom LLM models from Huggingface

### ISSUE THREAD

**Issue by yiouyou** [jmorganca/ollama#1754]
I have some fine-tuned models saved on Huggingface. How to add or convert any custome LLM to ollama fitted version?

**Comment by mongolu** [comment]
You need to convert it.
Assuming you have all the "requirements" installed and hf model on your local drive, you could inspire from this:
[converting hf to gguf](https://github.com/ggerganov/llama.cpp/blob/edd1ab7bc34c10a780ee7f9a4499f7689cdad36d/scripts/convert-gg.sh#L7)
[And after successfully converting to gguf, you need to import it in ollama from modelfile](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md)

I can confirm I've done it and it works.

**Comment by BruceMacD** [comment]
Thanks for opening the issue. Marking this as resolved for now as the question seems to have been answered (thanks to mongolu for that). Please feel free to ask any follow up questions though, I'll keep an eye out.

**Comment by easp** [comment]
@mongolu There is a better reference for importing models from HF into Ollama: https://github.com/jmorganca/ollama/blob/main/docs/import.md

This includes instructions on an ollama-provided docker image that makes converting and quantizing a single command.

**Comment by mongolu** [comment]
Didn't "find" it (named "import") into "./docs"... :(, so sorry.
Also it's a bit lengty, but detailed, i presume it's better.
I used a docker image where I had already (or installed) all the necessary deps for this.

**Comment by ozbillwang** [comment]
> You need to convert it. Assuming you have all the "requirements" installed and hf model on your local drive, you could inspire from this: [converting hf to gguf](https://github.com/ggerganov/llama.cpp/blob/edd1ab7bc34c10a780ee7f9a4499f7689cdad36d/scripts/convert-gg.sh#L7) [And after successfully converting to gguf, you need to import it in ollama from modelfile](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md)
> 
> I can confirm I've done it and it works.

this document is not for new model. with current design, we need adjust several files to adapt new model, I raised a new request in https://github.com/ggerganov/llama.cpp/issues/11460
