### ISSUE TITLE
[enhancement] use bert.cpp for /api/embeddings

### ISSUE THREAD

**Issue by fakezeta** [jmorganca/ollama#1755]
Llama2 and mistral base model are quite poor in embedding compared to sentence tranformer models like bert.

Why not integrate [bert.cpp](https://github.com/skeskinen/bert.cpp) or [sentence-transformers](https://sbert.net/) for `api/embeddings` endpoint so we can have the best of both architectures?

**Comment by easp** [comment]
Looks like there is slow movement on adding BERT support to llama.cpp
https://github.com/ggerganov/llama.cpp/issues/2872

**Comment by BruceMacD** [comment]
Hi @fakezeta thanks for opening the issue. This a commonly requested feature that we are definitely looking at.

Closing this issue for now to consolidate it with #327 just to keep this organized.
