### ISSUE TITLE
[WSL1] Ollama is outright ignoring keyboard input

### ISSUE THREAD

**Issue by TheSystemGuy1337** [jmorganca/ollama#1760]
It just had to happen. After running ollama, any attempt to type out a message fails, with the program acting like you have not pressed a single key on the keyboard. I am using a Unicomp New Model M, which is an industry-standard ANSI/ASCII QWERTY 108 key keyboard, and this "program" just doesn't want to touch it's output even with a 10-foot pole. I then tried a quick and dirty hack involving VcXsrv and XFCE4, and that still didn't fix the issue. I am about ready to just ditch WSL1 and use a VM like Virtualbox. I am using Ubuntu 22.04.3 LTS.

I did get these warnings, prob because Microsoft was too lazy to add proper PCI bus emulation:
```
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.
```

PS: I cannot use WSL2 as my system appears to have bizzare chipset and BIOS quirks that completely break WSL2 (ie WSL2 will complain that Virtualization and the Virtual Machine platform is not enabled, despite the fact they are)

**Comment by technovangelist** [comment]
Hi @TheSystemGuy1337 , so sorry you are having an issue. Can you tell me more about what is happening? You have run something like `ollama run llama2` and you can't type anything else in the terminal? thanks.

**Comment by TheSystemGuy1337** [comment]
That is exactly what's happening. I run `ollama run llama2-uncensored` and nothing happens at all. I get the `Send a message (/? for help)` but trying to type anything leads to nothing. I am using the bone stock Windows CMD (I don't like Windows Terminal)

I even tried using pwsh and of all things, a Tektronix 4010 emulator to try and fix it, to no avail. With the Tektronix emulator, it just displays nothing.

**Comment by pdevine** [comment]
Unfortunately Ollama doesn't work with WSL1 and you will need WSL2 at least until the native Windows version is ready.

**Comment by TheSystemGuy1337** [comment]
@pdevine , I looked it up and tons of people are having the same issue. **Micro$oft was too lazy to bugtest their code.**

Therefore, I recommend you remove all references to WSL2 and instead replace them with Oracle VM Virtualbox.

**Comment by Slapbox** [comment]
VMWare isn't very plausible for an application which needs direct GPU access and/or enormous amounts of memory.

WSL1 works - except that you can't type. I'm looking into [this project](https://github.com/ollama-webui/ollama-webui) as a GUI for WSL1.

Unfortunately we need nested virtualization in VMWare and the prerequisites for WSL2 break VMWare nested virtualization. Quite a pickle.

**Comment by TheSystemGuy1337** [comment]
@Slapbox , want to know the fix? It's so simple, you won't believe it.

**Just turn off the Virtual Machine Platform feature and you're back in business.**
Or, turn off Device/Credential Guard, then things should work again. You might have to use CPU only, but it's certainly better than having no I/O

**Comment by Slapbox** [comment]
@TheSystemGuy1337 The models (and partial downloads) are stored under their SHA256 hashes in `~/.ollama/models/blobs`.

The partial models are appended with `-partial`

Unfortunately I've already got those disabled and the issue is the same. I don't think GPU is an option anyway with WSL1 (though maybe nvidia-smi works with WSL1? It's only documented to work with WSL2 though)

**Comment by TheSystemGuy1337** [comment]
@Slapbox , I don't think WSL supports GPUs like AT ALL. It's prob like how VMware and Virtualbox handle GPUs, they treat them as discrete 3D accelerator cards rather than actual GPUs (example being the 3DFX Voodoo 2). The only way to pass a GPU to a VM is via KVM, and that requires a supported BIOS, motherboard and chipset to pull off. You can only get away with using the CPU on WSL. In most cases, CPUs would be acceptable with the main drawback being speed. There should be a warning saying "CAUTION: Running on CPU, because either current GPU is not supported or GPU could not be found. Responses will be slow."
