### ISSUE TITLE
Can't pull .ggml local model

### ISSUE THREAD

**Issue by reddiamond1234** [jmorganca/ollama#1765]
Hi, I created Modelfile: 
<code>FROM /models/phi-2.Q4_0.gguf
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
PARAMETER temperature 0
PARAMETER num_ctx 2048
PARAMETER num_thread 6
PARAMETER top_k 40
PARAMETER top_p 0.95
</code>
when i use command to create my custom model <code>ollama create phi2-SC -f ./models/modelfiles/Modelfile</code>, i get this error: Error: pull model manifest: Get "https://v2/models/phi-2.Q4_0.gguf/manifests/latest": dial tcp: lookup v2 on 172.20.80.1:53: server misbehaving

**Comment by BruceMacD** [comment]
Hi @reddiamond1234 there is a bug here that it shouldn't be trying to pull that URL, but it looks like the file path may not be specified correctly. `/models/phi-2.Q4_0.gguf` is looking in the root of your filesystem, when it doesn't find the file it tries to pull it from a URL. 

The path to the gguf file should be relative to the Modelfile location. Based on the path specified in your command try this:
```
FROM ../phi-2.Q4_0.gguf
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
PARAMETER temperature 0
PARAMETER num_ctx 2048
PARAMETER num_thread 6
PARAMETER top_k 40
PARAMETER top_p 0.95
```

Or if that doesn't work specify the absolute path.

Hope that helps.

**Comment by reddiamond1234** [comment]
> ollama create phi2-SC -f ./models/modelfiles/Modelfile

It works now, thanks.
