### ISSUE TITLE
Pulling manifest error

### ISSUE THREAD

**Issue by buczekkruczek** [jmorganca/ollama#1770]
Hello Everyone, 

I have problem with pulling manifest, while running "ollama run dolphin-mixtral:latest" for the first time I've got "Error: max retries exceeded: unexpected EOF" and now I am unable to restart download getting "Error: pull model manifest: file does not exist". 

I am grateful for all help or any kind of advice what to do next or how to deal with this

**Comment by igorschlum** [comment]
hi @buczekkruczek I just done it and it worked well. What is the amount of memory of your computer (CPU and GPU). I'm on a macstation with a large amount of memory. Dolphin-mixtral need at least 32GB on your computer if he is doing nothing. Be sur to have enough free space on your hardDrive.

dolphin-mixtral:latest  	cfada4ba31c7	26 GB 	4 minutes ago

**Comment by pdevine** [comment]
@buczekkruczek  The `Error: max retries exceeded: unexpected EOF` (which is admittedly not the greatest error message) typically happens because your network connection is dropping a lot of packets. Ollama tries to recover numerous times, but at some point it will give up. You can generally just try `ollama pull dolphin-mixtral` again and it should recover from where it left off.

The `Error: pull model manifest: file does not exist` error happens when you have a typo in the name of the model you're trying to pull or run.

**Comment by buczekkruczek** [comment]
I just reinstalled Ollama and it's working fine now

**Comment by JMAURICIORLIMA** [comment]
@pdevine Thank you for the contribution.

**Comment by yoandwo** [comment]
@pdevine thanks, i missed the typo ;)

**Comment by Alonge9500** [comment]
@pdevine  Thank you

**Comment by vedbhoskar** [comment]
(llms) PS C:\Users\vedbh\OneDrive\Desktop\LLM Projects\llm_engineering> ollama run llava-phi3
pulling manifest
pulling 377876be20ba...   0% ▕                                                                     ▏    0 B/2.3 GB
Error: max retries exceeded: Get "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/37/377876be20bac24488716c04824ab3a6978900679b40013b0d2585004555e658/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%2F20250101%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20250101T055200Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=68092487a4936639983f0a6d93a2a963b34f82628591f55d7dc28cef8d15dca6": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host 

i have a stable internet connection, tried multiple times and also reinstalled ollama but i still get this error for every model i try. pls hepl

**Comment by pdevine** [comment]
@vedbhoskar it looks like you're having a DNS issue. Try this:
```
% ping dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com
PING dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com (172.66.1.46): 56 data bytes
64 bytes from 172.66.1.46: icmp_seq=0 ttl=54 time=10.068 ms
64 bytes from 172.66.1.46: icmp_seq=1 ttl=54 time=12.356 ms
64 bytes from 172.66.1.46: icmp_seq=2 ttl=54 time=14.954 ms
```

**Comment by igorschlum** [comment]
@vedbhoskar it works for me. It could be a temporary problem of Cloudflare.

**Comment by MShahzadAbdulmajeed** [comment]
C:\Users\wel>ollama run deepseek-r1:14b
pulling manifest
Error: pull model manifest: 500: {"errors":[{"code":"INTERNAL_ERROR","message":"internal error"}]}

C:\Users\wel>ollama --version
ollama version is 0.5.7

please help me to solve this problem

**Comment by altunenes** [comment]
I got this error this morning. 
I rm the Ollama and installed it again.
it fixed. 
I don't know what caused it. 
MacOS

**Comment by zfy326543** [comment]
Get "https://registry.ollama.ai/v2/library/deepseek-r1/manifests/7b": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by HelloWorldLTY** [comment]
Another possible solution is stopping ollama serve, restart it, and then try to repull. That resolved my id_xxx non exist issue.

**Comment by tomachinz** [comment]
Yeah I found this to be a transient issue. Keep trying. Reboot. In my case, staying at ` ollama --help` I eventually did a `ollama pull qwen3:8b` which fixed it. My /home is very low on disk. Free that up some. `df -h`. Dunno if its related vyt to get it working on my 3D scene it helped to again mention Threejs and the output .html file I wanted it done in? More likely twas my pull command 🎸
