### ISSUE TITLE
Metadata field for multimodal models

### ISSUE THREAD

**Issue by shreyaskarnik** [jmorganca/ollama#1772]
Would it be possible to add some metadata to the model indicating that it is multimodal? This will help to select the right model in applications that are built on top of the API to support multimodal architecture. I believe this will also help to search through models at https://ollama.ai/library and filter based on multimodal support.

**Comment by pdevine** [comment]
This is possible already through the API by using the `/api/show` endpoint and looking through `.details.families`. An example with curl:

```
curl localhost:11434/api/show -X POST -d '{"name": "llava"}' | jq ".details.families"
```
It should output:
```
[
  "llama",
  "clip"
]
```

It shows the two families which the model uses (i.e. the "multimodal" part), namely the "llama" model family for that chat portion, and the "clip" family which is used for converting images into text descriptions.

Hopefully that helps! I'm going to close the issue, but feel free to keep commenting on it/re-open it.

**Comment by shreyaskarnik** [comment]
@pdevine thanks for the clarification I was using the clip selector to make the appropriate selection of model. Thanks for confirming that it is the way to go. In regards to the https://ollama.ai/library page will there be a option to select only multimodal models in the future?

**Comment by pdevine** [comment]
Sounds like a really good addition.
