### ISSUE TITLE
change in CMAKE flags in 0.1.18 causes illegal instruction on Intel mac

### ISSUE THREAD

**Issue by jhheider** [jmorganca/ollama#1777]
Reverting to the old flags as in [this](https://github.com/pkgxdev/pantry/pull/4710/files) seems to fix it for me (as far as our automated testing goes).

No fix: https://github.com/pkgxdev/pantry/actions/runs/7400916216/job/20135652033
Fix: https://github.com/pkgxdev/pantry/actions/runs/7402435273/job/20140385965

**Comment by jmorganca** [comment]
This should be fixed now @jhheider, please let me know if you're still seeing any issues. Thanks so much!

**Comment by jhheider** [comment]
Can confirm, 0.1.18 builds without alteration now:

https://github.com/pkgxdev/pantry/actions/runs/7414434019/job/20175499348
