### ISSUE TITLE
Langchain Ollama: OAuth2 authentication and URL parameters

### ISSUE THREAD

**Issue by skye0402** [jmorganca/ollama#1795]
**What this is  about:**
Add OAuth2 and basic authentication to the langchain Ollama libraries as well as flexible URLs and ports.

**Why:**
Not everyone runs Ollama on the local machine. As for me I run it on Kubernetes and use it always with its langchain library. For that proper authentication is required.

**How:**
I propose to keep Ollma "as-is" and let the wrapping platform define the authentication. That way, only the langchain components need enhancement to offer OAuth or basic authentication through parameters (".env"). 

**Status:**
I've already enhanced the Ollma libraries to use OAuth2 with Client Credentials. I'm happy to add Basic to it as well if there is interest to add the code to the main langchain libraries.
I'm talking about these classes:

- ChatOllama
- Ollama
- OllamaEmbeddings

Let me know if/ how I can contribute my code to it.

**Comment by mxyng** [comment]
This issue would be better served if it's created in the [langchain](https://github.com/langchain-ai/langchain) repo. The integration is maintained by LangChain, not Ollama.
