### ISSUE TITLE
Readme refers to 404 docker documentation

### ISSUE THREAD

**Issue by tommedema** [jmorganca/ollama#1796]
The main [readme](https://github.com/jmorganca/ollama/blob/main/docs/README.md) refers to https://github.com/jmorganca/ollama/blob/main/docs/docker.md which gives a 404. Is docker still supported?

**Comment by technovangelist** [comment]
Hi @tommedema So sorry you ran into that. We most certainly still support Docker. You can find out more about using it here on Docker Hub: https://hub.docker.com/r/ollama/ollama

**Comment by technovangelist** [comment]
I've updated the readme to point to docker hub. Thanks so much for pointing this out and for being a great part of this community.
