### ISSUE TITLE
Can we train custom models using pdfs?

### ISSUE THREAD

**Issue by akasranjan005** [jmorganca/ollama#181]
Instead of just the system prompts can we also pass custom knowledge base? mostly in pdf or any other format?

**Comment by jmorganca** [comment]
Hi @akasranjan005. Thanks for the issue! This is something we're looking into

**Comment by burryxie** [comment]
very looking forward to this feature

**Comment by breadchris** [comment]
It would be really sick if you could have a super easy training interface. I would use this shit out of this if you guys had that.

**Comment by alivardar** [comment]
My opinion is web interface part can be another project, exist version is versatile and very useful. PDF import can be easy with one folder integration.

**Comment by jmorganca** [comment]
Hi folks! Thanks for the issue – will merge this with #156
