### ISSUE TITLE
Add Phi2 support 

### ISSUE THREAD

**Issue by khalilxg** [jmorganca/ollama#1824]
Microsoft changed phiz license to become MIT. Plz Add the support for Phi2

**Comment by lainedfles** [comment]
This has been supported since the release of [v0.1.17](https://github.com/jmorganca/ollama/releases/tag/v0.1.17) 3 weeks ago. See also [https://ollama.ai/library/phi](https://ollama.ai/library/phi).

**Comment by jmorganca** [comment]
Indeed! It's available here: https://ollama.ai/library/phi
