### ISSUE TITLE
Massive slowdown on v 0.1.18 vs 0.1.17 with same model on Intel Mac

### ISSUE THREAD

**Issue by pjv** [jmorganca/ollama#1827]
<img width="255" alt="SCR-20240106-kfri" src="https://github.com/jmorganca/ollama/assets/327716/c1b5ce5b-acd5-4c81-a59a-6db39ff6a257">

I don’t have exact timings but the same model (in this case, `deepseek-coder:6.7b-instruct-q4_K_S`) generates tokens roughly 5 times faster on 0.1.17 than on 0.1.18 on my Intel Mac.

I upgraded to 0.1.18 and noticed the slowdown in token generation and then downgraded back to 0.1.17 and immediately saw the faster throughput I am accustomed to.

**Comment by jmorganca** [comment]
Sorry you hit this slowdown. Would it be possible to share the logs? They should be in `~/.ollama/logs/server.log` - thanks so much!

**Comment by jmorganca** [comment]
Also would it be possible to test `llama2` and see if you see the same slowdown with that model architecture? Thanks!

**Comment by jmorganca** [comment]
Ok! Update: I'm able to reproduce this for models with k-quants (e.g. `q4_K_S`, but not for regular quantization – e.g. `q4_0`). Will look into this!

**Comment by pjv** [comment]
wow, you’re a lot faster than me. I’m still generating logs for you. Do you still need them?

**Comment by pjv** [comment]
> Ok! Update: I'm able to reproduce this for models with k-quants (e.g. q4_K_S, but not for regular quantization – e.g. q4_0). Will look into this!

Yup, testing the `llama2` model, 0.1.18 seems a bit faster than 0.1.17. but the q4_K_S model is very slow.

**Comment by jmorganca** [comment]
No worries about the logs – I can reproduce on my side. Tracking this down

**Comment by coder543** [comment]
Semi-related, but isn't k-quant the newer/better quantization method? I have found it confusing that ollama defaults to the non-K quants, but maybe I'm confused about which method is better.
