### ISSUE TITLE
Ollama from remote

### ISSUE THREAD

**Issue by HAL9KKK** [jmorganca/ollama#1845]
Ollama is using always localhost.

I have 2 colab istances:
**Colab1 (server)**
```
# Set LD_LIBRARY_PATH so the system NVIDIA library 
import os
import asyncio
os.environ.update({'LD_LIBRARY_PATH': '/usr/lib64-nvidia'})

async def run_process(cmd):
  print('>>> starting', *cmd)
  p = await asyncio.subprocess.create_subprocess_exec(
      *cmd,
      stdout=asyncio.subprocess.PIPE,
      stderr=asyncio.subprocess.PIPE,
  )

  async def pipe(lines):
    async for line in lines:
      print(line.strip().decode('utf-8'))

  await asyncio.gather(
      pipe(p.stdout),
      pipe(p.stderr),
  )

await asyncio.gather(
    run_process(['ollama', 'serve']),
    run_process(['ngrok', 'http', '--log', 'stderr', '11434']),
)
```

```
>>> starting ollama serve
>>> starting ngrok http --log stderr 11434
2024/01/07 18:10:03 routes.go:929: Listening on 127.0.0.1:11434 (version 0.1.18)
t=2024-01-07T18:10:03+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://localhost:11434/ url=https://7b8c-34-83-27-150.ngrok-free.app/
```

**Colab2 (client)**

```
import os
os.environ["OLLAMA_HOST"]="https://7b8c-34-83-27-150.ngrok-free.app"

import subprocess
pr= subprocess.Popen(['ollama', 'run', 'openhermes'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
```

After running the subprocess "ollama run openhermes" the server start running the model, so the connection client server is working thanks to the OLLAMA_HOST variable

The problem is when I run ollama from langchain

```
from langchain.llms import Ollama
ollama_llm = Ollama(model="openhermes")
ollama_llm.generate(["hello"])
```

ConnectionError: HTTPConnectionPool(host='localhost', port=11434)

Why OLLAMA_HOST is not working with langchain?

**Comment by prusnak** [comment]
> Why OLLAMA_HOST is not working with langchain?

This is a bug in Langchain that it does not respect the `OLLAMA_HOST` variable. Please open an issue here: https://github.com/langchain-ai/langchain/issues

**Comment by wrapss** [comment]
> Ollama is using always localhost.
> 
> I have 2 colab istances: **Colab1 (server)**
> 
> ```
> # Set LD_LIBRARY_PATH so the system NVIDIA library 
> import os
> import asyncio
> os.environ.update({'LD_LIBRARY_PATH': '/usr/lib64-nvidia'})
> 
> async def run_process(cmd):
>   print('>>> starting', *cmd)
>   p = await asyncio.subprocess.create_subprocess_exec(
>       *cmd,
>       stdout=asyncio.subprocess.PIPE,
>       stderr=asyncio.subprocess.PIPE,
>   )
> 
>   async def pipe(lines):
>     async for line in lines:
>       print(line.strip().decode('utf-8'))
> 
>   await asyncio.gather(
>       pipe(p.stdout),
>       pipe(p.stderr),
>   )
> 
> await asyncio.gather(
>     run_process(['ollama', 'serve']),
>     run_process(['ngrok', 'http', '--log', 'stderr', '11434']),
> )
> ```
> 
> ```
> >>> starting ollama serve
> >>> starting ngrok http --log stderr 11434
> 2024/01/07 18:10:03 routes.go:929: Listening on 127.0.0.1:11434 (version 0.1.18)
> t=2024-01-07T18:10:03+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://localhost:11434/ url=https://7b8c-34-83-27-150.ngrok-free.app/
> ```
> 
> **Colab2 (client)**
> 
> ```
> import os
> os.environ["OLLAMA_HOST"]="https://7b8c-34-83-27-150.ngrok-free.app"
> 
> import subprocess
> pr= subprocess.Popen(['ollama', 'run', 'openhermes'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
> ```
> 
> After running the subprocess "ollama run openhermes" the server start running the model, so the connection client server is working thanks to the OLLAMA_HOST variable
> 
> The problem is when I run ollama from langchain
> 
> ```
> from langchain.llms import Ollama
> ollama_llm = Ollama(model="openhermes")
> ollama_llm.generate(["hello"])
> ```
> 
> ConnectionError: HTTPConnectionPool(host='localhost', port=11434)
> 
> Why OLLAMA_HOST is not working with langchain?

try with base_url as shown in this [tutorial ](https://github.com/jmorganca/ollama/blob/main/docs/tutorials/langchainpy.md)

**Comment by prusnak** [comment]
Yes, you should use the  following code as langchain does not use OLLAMA_HOST variables:

```
ollama_llm = OllamaEmbeddings(base_url="https://your_url:11434", model="llama2")
```

**Comment by HAL9KKK** [comment]
Thank you so much for your prompt reply @wrapss and @prusnak tomorrow I will try but I am quite sure you are right!!!

**Comment by mxyng** [comment]
As others have mentioned, ollama serves on localhost by default. If you want to change this, set `OLLAMA_HOST`. Please see the [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network) for details

**Comment by kzos** [comment]
@HAL9KKK By any chance , have you hosted this code somewhere or mind sharing it to me, I am trying to setup similar thing. if you could share the entire setup , I shall start working on actual study work.

Host/serve llama on server 
and access it in multiple clients.

thanks in advance.
