### ISSUE TITLE
Copying the response to the clipboard

### ISSUE THREAD

**Issue by goldytech** [jmorganca/ollama#1852]
Is there a way or feature available in the tool for the generated streamed response to be copied into the clipboard memory? Like how chatgpt UI gives the option to share it with the link.

**Comment by igorschlum** [comment]
Hi @goldytech 

Yes you can use Markdown. I asked "ollama run phi" how to do it.

>>> can you answer in a way that the answer can be copied, like using markdown?
 Sure, here's an example of how the same function could be written using 
markdown syntax:

```markdown
function addNumbers(num1, num2) {
  return num1 + num2;
}
```

You can copy and paste this code into your favorite text editor or 
integrated development environment (IDE) to use the function in your 
JavaScript program.

**Comment by goldytech** [comment]
Thanks for your support.
