### ISSUE TITLE
Error on large contexts & memory usage

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#186]
When having a "long" conversation and an increasing context window, `ollama run` will sometimes report an error:

```
"http://127.0.0.1:11434/api/generate": EOF" 
```

This also may occur if there is insufficient memory. Ollama should handle these cases gracefully.

**Comment by andrewblount** [comment]
Hello.  I get the error anytime I go over ~1200 tokens, regardless of the model.  num_ctx is set to 4096.  I'm on an M2 Mac with 96 GB memory and 64 GB free.  It occurs both via the command line and HTTP.  Thanks.  Otherwise, your product is wonderful.  Excellent work.

**Comment by mxyng** [comment]
There are a lot of stability improvements release in 0.0.13 which should address this and other `Post "http://127.0.0.1:11434/api/generate": EOF` issues

**Comment by jmorganca** [comment]
These errors should be gone (or at least far better) as of [0.13](https://ollama.ai/download) – will close this for now but do feel free to re-open if it happens again!
