### ISSUE TITLE
Where is the model file stored?

### ISSUE THREAD

**Issue by ParisNeo** [jmorganca/ollama#1866]
Hi there, I need to make a modification to the model file. Can you please tell me where do you store the model file?

Best regards

**Comment by ParisNeo** [comment]
Ok, I found how, but it would be cool if you expose a method to change the model template.

thanks

**Comment by mxyng** [comment]
Modelfiles themselves are not stored but there are multiple ways of changing a model template as well as other parameters.

Similar to Dockerfiles, you can inherit and override parts of a Modelfile. The [docs](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md) describe this in detail

You can also override the template in runtime with `template` in the [API](https://github.com/jmorganca/ollama/blob/main/docs/api.md) request or with `/set template` in the REPL

**Comment by ParisNeo** [comment]
Well i found exactly where they are, they are stored in blob as json file with a hash name so i did change it and it works. My front end already does the formatting that's why i just need bare text generation with no template.
If you add an endpoint to the api /set_template for example, that would be helpful because since the file name is a hash, it is extrememy difficult for me to automate the changing of the template from the front end.
Thanks for answering.
