### ISSUE TITLE
ollama in a docker - can't check healthiness - Support Ollama under Rosetta

### ISSUE THREAD

**Issue by FreakDev** [jmorganca/ollama#1868]
Hello !

i'm trying to setup ollama to run in a docker container, in order to have it run in runpod serverless function and to do so i'd like to pull a model file in my container image (embed the model file into the docker image)

basically i'd like to have a script like this that run during the build fo the image : 
```bash
#!/bin/bash

/bin/ollama serve &

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://0.0.0.0:11434)" != "200" ]]; do 
  echo "waiting for ollama"
  sleep 1
done

/bin/ollama pull mistral
```

but this doesn't work the curl never returns a http code 200...

any idea why ? and/or how could I achieve this (maybe there is another/easier way of doing this) ? 

thanks in advance !

**Comment by FreakDev** [comment]
nevermind, it works fine (when using the ollama docker image, I was trying to build my image by altering the Dockerfile found in this repository)

**Comment by FreakDev** [comment]
actually it works when I'm building the image without specifying a platform (I am on a mac) but if I try to build the image with `--platform linux/amd64` option it tells me 

```
> [11/13] RUN /bin/bash setup.sh tinyllama:
10.15 setup.sh: line 10:    18 Illegal instruction     ollama serve
```

any idea ?

**Comment by mxyng** [comment]
It looks like you're building and running this on macOS. With `--platform linux/amd64` it's possible it's using Rosetta. The Linux build currently enables AVX which isn't supported on Rosetta hence the illegal instruction.

**Comment by FreakDev** [comment]
I see... so, as far as I understand, I can't from my Apple Silicon mac, build image that uses Ollama and targets linux/amd64 platform ?

thank you for your feedback ! By any chance, do you know if there is another way to do what am I trying to do (embedding a model into a docker file) ?

**Comment by dhiltgen** [comment]
At present, that is correct.  Ollama won't run under Rosetta. 

I'm working on some updates that will enable Rosetta support as a fall back mode.
