### ISSUE TITLE
last update broke something on my late 2012 imac

### ISSUE THREAD

**Issue by umtksa** [jmorganca/ollama#1870]
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
Referenced from: /usr/local/bin/ollama (which was built for Mac OS X 11.3)
Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
in /usr/local/bin/ollama

I was using mistral and mixtral now I cannot even use tinyllama :/
any suggestion?

**Comment by igorschlum** [comment]
hi @umtksa try to restart the computer and if not working, try to remove and install again Ollama. Running on old iMac is a real challenge. You can also have bugs in MacOS.

**Comment by pdevine** [comment]
cc @dhiltgen

**Comment by jmorganca** [comment]
Hi @umtksa, this should be fixed as of https://github.com/jmorganca/ollama/releases/tag/v0.1.19 – please let me + @dhiltgen  know if you're still seeing the issue!

**Comment by umtksa** [comment]
> Hi @umtksa, this should be fixed as of https://github.com/jmorganca/ollama/releases/tag/v0.1.19 – please let me + @dhiltgen know if you're still seeing the issue!
@jmorganca @igorschlum  thank you so much for this fast response 
downloading manually from releases [v0.1.19](https://github.com/jmorganca/ollama/releases/tag/v0.1.19) 
(updating within app not worked) and restarting after install solved the problem for me
and I'm sending last entries from the log as [igorschlum](https://github.com/igorschlum) suggest

```
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /Applications/Ollama.app/Contents/Resources/ollama (which was built for Mac OS X 11.3)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Ollama.app/Contents/Resources/ollama
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /Applications/Ollama.app/Contents/Resources/ollama (which was built for Mac OS X 11.3)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Ollama.app/Contents/Resources/ollama
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /Applications/Ollama.app/Contents/Resources/ollama (which was built for Mac OS X 11.3)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Ollama.app/Contents/Resources/ollama
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /Applications/Ollama.app/Contents/Resources/ollama (which was built for Mac OS X 11.3)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Ollama.app/Contents/Resources/ollama
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /Applications/Ollama.app/Contents/Resources/ollama (which was built for Mac OS X 11.3)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/Ollama.app/Contents/Resources/ollama
2024/01/10 09:29:27 images.go:808: total blobs: 69
2024/01/10 09:29:27 images.go:815: total unused blobs removed: 4
2024/01/10 09:29:27 routes.go:930: Listening on 127.0.0.1:11434 (version 0.1.19)
[GIN] 2024/01/10 - 09:29:31 | 200 |     459.095µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/01/10 - 09:29:31 | 200 |   20.767866ms |       127.0.0.1 | GET      "/api/tags" 
```

**Comment by igorschlum** [comment]
@jmorganca are those
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
a normal behavior?
