### ISSUE TITLE
upgrade openchat

### ISSUE THREAD

**Issue by morandalex** [jmorganca/ollama#1892]
hello a new release of openchat was released : 
https://huggingface.co/openchat/openchat-3.5-0106#benchmarks

**Comment by jmorganca** [comment]
It's been updated 😊 https://ollama.ai/library/openchat

**Comment by morandalex** [comment]
perfect thank you. check also the description 
![image](https://github.com/jmorganca/ollama/assets/9484568/75211bf6-f487-4d30-8206-59030f211ef7)
