### ISSUE TITLE
response_json['eval_count'] doesn't exists - llms/ollama.py

### ISSUE THREAD

**Issue by mongolu** [jmorganca/ollama#1893]
after some time this error pops out.
i think it's related with same situation for `response_json['prompt_eval_count']`

Logs:
```
 'created_at': '2024-01-10T08:52:17.111694849Z',
 'done': True,
 'eval_duration': 516371613757000,
 'load_duration': 260310,
 'model': 'MixtralOrochi8x7B:latest',
 'response': '',
 'total_duration': 306412003}
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.11/site-packages/litellm/llms/ollama.py", line 325, in ollama_acompletion
    completion_tokens = response_json["eval_count"]
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'eval_count'
```

**Comment by mongolu** [comment]
sry, it's for litellm project.

**Comment by frgfm** [comment]
Mmmh I'm having the same problem after updating to ollama 0.1.20 :thinking: 

I first thought it was a mistake for one specific model, but running it against multiple ones, fetching the keys of the response gets me:
```
dict_keys(['model', 'created_at', 'response', 'done', 'context', 'total_duration', 'load_duration', 'prompt_eval_duration', 'eval_count', 'eval_duration'])
```

Checking versions, the API response in either generate or chat are missing some keys depending on the version:
- main/0.1.20: prompt_eval_count
- 0.1.19: load_duration (cf. #1524)


It looks like it's omitted when empty in the LLM response: https://github.com/jmorganca/ollama/blob/main/api/types.go#L78
And the problem doesn't look like it's from https://github.com/jmorganca/ollama/blob/main/server/routes.go

Trying to locate why the field could be empty for the eval_count and not duration :detective:

**Comment by gregnwosu** [comment]
i thought it was to do with prompt cache
