### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by ryanmerolle** [jmorganca/ollama#190]
A brew formula would be super helpful.  Thanks for all your work here!

**Comment by josh** [comment]
👍🏻 [Here's the formula I've been using](https://github.com/josh/homebrew-tap/blob/main/ollama.rb). The required `ollama serve` component works pretty great with homebrew services. Would be cool to see this upstreamed into [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core).

**Comment by josh** [comment]
https://github.com/Homebrew/homebrew-core/pull/138534

I think this issue can be marked as resolved.
