### ISSUE TITLE
zsh: illegal hardware instruction  ollama run mistral

### ISSUE THREAD

**Issue by MagzhanUnited** [jmorganca/ollama#1904]
I run mistral yesterday successfully on my Mac M1. But today I have the following error when I try to run mistral:
zsh: illegal hardware instruction  ollama run mistral

**Comment by MagzhanUnited** [comment]
If I just type ollama in terminal I have error:
zsh: illegal hardware instruction  ollama

**Comment by PeterHickman** [comment]
Installed 0.1.19 on my M1 Macmini and got `Invalid instruction: 4` or something. Re downloaded a couple of times to no avail. Reverted to 0.1.18. 0.1.19 works fine on my Intel MBP The can happen with just `ollama -v`

**Comment by MagzhanUnited** [comment]
> Installed 0.1.19 on my M1 Macmini and got `Invalid instruction: 4` or something. Re downloaded a couple of times to no avail. Reverted to 0.1.18. 0.1.19 works fine on my Intel MBP The can happen with just `ollama -v`
> 
> Not using zsh so that might not be relevant

I redownloaded but it didn't help

**Comment by jmorganca** [comment]
Hi all, I'm sorry you're getting this error. Would it be possible to run the following in your terminal?

```
sysctl -n sysctl.proc_translated
```

It seems like it's trying to run `ollama` as if it were an intel build, even on Apple Silicon. Ollama's build is universal though so it shoudl work on boht.

**Comment by MagzhanUnited** [comment]
> Hi all, I'm sorry you're getting this error. Would it be possible to run the following in your terminal?
> 
> ```
> sysctl -n sysctl.proc_translated
> ```
> 
> It seems like it's trying to run `ollama` as if it were an intel build, even on Apple Silicon. Ollama's build is universal though so it shoudl work on both.

It also didn't help. I'm still getting that error

**Comment by MagzhanUnited** [comment]
> Hi all, I'm sorry you're getting this error. Would it be possible to run the following in your terminal?
> 
> ```
> sysctl -n sysctl.proc_translated
> ```
> 
> It seems like it's trying to run `ollama` as if it were an intel build, even on Apple Silicon. Ollama's build is universal though so it shoudl work on both.

I'm facing with this error only in my terminal. When I run Ollama application I can make curl request to api

**Comment by PeterHickman** [comment]
On my M1 Macmini `sysctl -n sysctl.proc_translated` returns `1` and still reports `Illegal instruction: 4`

**Comment by PeterHickman** [comment]
This will get it to work `arch -arm64 ollama -v`

**Comment by MagzhanUnited** [comment]
> arch -arm64 ollama -v

wow thanks!

**Comment by MagzhanUnited** [comment]
arch -arm64 ollama [command] solve my problem

**Comment by PeterHickman** [comment]
To save typing set an alias in `.bashrc` such as

`alias ollama='arch -arm64 \ollama'`

**Comment by jmorganca** [comment]
Great! By the way, it seems you might be running `zsh` or `bash` using Rosetta. This might be due to installing amd64 `brew` or other tools that spawn your shell.

In any case, we'll be working on changes to support running `ollama` in Rosetta in an upcoming release. Stay tuned!
