### ISSUE TITLE
Wrong tag on dockerhub

### ISSUE THREAD

**Issue by otavio-silva** [jmorganca/ollama#1933]
# Description
It seems latest version was released under the 0.0.0 tag (see https://hub.docker.com/r/ollama/ollama/tags and https://hub.docker.com/layers/ollama/ollama/0.0.0/images/sha256-720e093927cfaed71c70dcc70bd32f9c39be3937243ebd6ddcdce5016d5deb2b?context=explore) instead of 0.1.20 that is the correct number.

**Comment by jmorganca** [comment]
Thanks for flagging! The version reported should now be `0.1.20` – apologies for the mixup.
