### ISSUE TITLE
Ollama GPU Process does not automatically terminate after inactivity

### ISSUE THREAD

**Issue by chereszabor** [jmorganca/ollama#1951]
Noticed with recent releases the ollama process does not get automatically terminated after a period of inactivity, idling the GPU process and keeping the last used model in VRAM. This also increases the time required to load a new model into VRAM and increases 'standby' power usage of the GPU.

I am deploying ollama via Docker and tested with the latest version v0.1.20.

**Comment by newjcj** [comment]
me to!!!

**Comment by cassidea** [comment]
Same here. Model gets unloaded after some time but still ~120MB on the GPU preventing to switch into lower power states.

**Comment by dhiltgen** [comment]
Closing as dup of #1848
