### ISSUE TITLE
Unable to push

### ISSUE THREAD

**Issue by julianallchin** [jmorganca/ollama#1969]
I followed all the steps in the documentation and Ollama is telling me 
```
unable to push <username>/example, make sure this namespace exists and you are authorized to push to it
```
I have created the model online and uploaded my public key, but it doesn't work.

**Comment by igorschlum** [comment]
Hi @julianallchin What model do you want to push? Actually and du to copyright issues, models must be accredited by Ollama team. It would be nice to have a public library where Ollama users could share their models and debate on them.

**Comment by easp** [comment]
> du to copyright issues, models must be accredited by Ollama team

Since when has Ollama required pre-screening before allowing model uploads to people's individual profiles on ollama.ai?

**Comment by igorschlum** [comment]
It's a logical deduction that I made. If true, it's from the begining.

**Comment by julianallchin** [comment]
> What model do you want to push?
A fine-tuned mistral instruct

**Comment by jmorganca** [comment]
Hi @julianallchin, sorry you hit this. What's the name of the model you're looking to push?

**Comment by julianallchin** [comment]
`julianallchin/sclip`

**Comment by pdevine** [comment]
There's no prescreening. You can upload anything you want (although please don't upload copyrighted stuff).

@julianallchin are you by any chance using linux? You need to upload the public key for the _server_ and not the _client_ right now, which the pub key by default is sitting in `/usr/share/ollama/.ollama/id_ed25519.pub'.

Sorry that this is so confusing right now.

**Comment by julianallchin** [comment]
I am indeeeed using Linux. I uploaded the key in the directory `~/.ollama/id_ed25519.pub` and not the one in `/usr/share`. Uploading the key from `/usr/share` **fixed it**. I don't know why there are two... maybe something to look at.

**Comment by pdevine** [comment]
The reason for two being created is that the server/client share the same binary, but in the case of Linux they're run in different locations/contexts. Ideally the server would just proxy the client key though, but we're a ways off from being able to do that.
