### ISSUE TITLE
Will ollama run dolphin-mixtral on my gtx 1080 Ti?

### ISSUE THREAD

**Issue by PixelovyLabyrintDev** [jmorganca/ollama#1975]
Im just asking since im about to buy one and im curious if it will see the gpu and use it to generate responses faster? Or does Ollama support all Nvidia gpus?

**Comment by easp** [comment]
dolphin-mixtral is a fairly large model. Less than 1/2 of the default q4_0 quantization will fit on the card and so text generation speeds are going to be much closer to CPU-only speeds than GPU speeds. I'd guess something less than 2x your CPU-only speeds. That's significant, but no where close to the GPU-only speeds.

**Comment by 300cpilot** [comment]
I have run Dolphin-Mixtral:v2.7 on 1 - 1080ti and 2 - T4's, it takes over 26 gigs of vram. It will not run on a single 1080ti
![2024-01-14_22-09-48](https://github.com/jmorganca/ollama/assets/9617359/a193b1fc-e9f6-46bf-b9be-753e43577a3b)

**Comment by jmorganca** [comment]
Hi @PixelovyLabyrintDev! Indeed, as mentioned, it will run, but not much of the model will be offloaded to run on the GPU given how much memory `dolphin-mixtral` requires (26GB+). Feel free to share any more questions!
