### ISSUE TITLE
nous-hermes and parameters

### ISSUE THREAD

**Issue by alivardar** [jmorganca/ollama#199]
Hello,
If I want to generate my model, this example with temperature and num_ctx paramters crashing "ollama" application.

FROM nous-hermes
# sets the temperature to 1 [higher is more creative, lower is more coherent]
# sets the context size to 4096
PARAMETER temperature 2
PARAMETER num_ctx 4096

Here is all result when app crashed.

alivardar@Alis-MacBook-Air ModelFiles % ollama serve  
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/jmorganca/ollama/server.Serve.func1 (3 handlers)
[GIN-debug] POST   /api/pull                 --> github.com/jmorganca/ollama/server.PullModelHandler (3 handlers)
[GIN-debug] POST   /api/generate             --> github.com/jmorganca/ollama/server.GenerateHandler (3 handlers)
[GIN-debug] POST   /api/create               --> github.com/jmorganca/ollama/server.CreateModelHandler (3 handlers)
[GIN-debug] POST   /api/push                 --> github.com/jmorganca/ollama/server.PushModelHandler (3 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/jmorganca/ollama/server.ListModelsHandler (3 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/jmorganca/ollama/server.DeleteModelHandler (3 handlers)
2023/07/24 22:54:48 routes.go:237: Listening on 127.0.0.1:11434
llama.cpp: loading model from /Users/alivardar/.ollama/models/blobs/sha256:d1735b93e1dc503f1045ccd6c8bd73277b18ba892befd1dc29e9b9a7822ed998
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9132.72 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  = 3200.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Applications/Ollama.app/Contents/Resources/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x152f0a280
ggml_metal_init: loaded kernel_mul                            0x152f0a880
ggml_metal_init: loaded kernel_mul_row                        0x152f0aeb0
ggml_metal_init: loaded kernel_scale                          0x152f0b3d0
ggml_metal_init: loaded kernel_silu                           0x152f0b8f0
ggml_metal_init: loaded kernel_relu                           0x152f0be10
ggml_metal_init: loaded kernel_gelu                           0x152f0c330
ggml_metal_init: loaded kernel_soft_max                       0x152f0c9e0
ggml_metal_init: loaded kernel_diag_mask_inf                  0x152f0d040
ggml_metal_init: loaded kernel_get_rows_f16                   0x152f0d6c0
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x152f0dd40
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x152f0e530
ggml_metal_init: loaded kernel_get_rows_q2_K                  0x152f0ebb0
ggml_metal_init: loaded kernel_get_rows_q3_K                  0x152f0f230
ggml_metal_init: loaded kernel_get_rows_q4_K                  0x152f0f8b0
ggml_metal_init: loaded kernel_get_rows_q5_K                  0x152f0ff30
ggml_metal_init: loaded kernel_get_rows_q6_K                  0x152f105b0
ggml_metal_init: loaded kernel_rms_norm                       0x152f10c70
ggml_metal_init: loaded kernel_norm                           0x152f11320
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x152f11cf0
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x152f123b0
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x152f12a70
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32               0x152f13150
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32               0x152f139d0
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32               0x152f14090
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32               0x152f14730
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32               0x152f14dd0
ggml_metal_init: loaded kernel_rope                           0x152f154f0
ggml_metal_init: loaded kernel_alibi_f32                      0x152f16010
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x152f168a0
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x152f17130
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x152f179c0
ggml_metal_init: recommendedMaxWorkingSetSize = 10922.67 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =    87.89 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  6984.06 MB, ( 6984.52 / 10922.67)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =  1040.00 MB, ( 8024.52 / 10922.67)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  3202.00 MB, (11226.52 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   597.00 MB, (11823.52 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB, (12335.52 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_graph_compute: command buffer 0 failed with status 5
GGML_ASSERT: ggml-metal.m:1023: false
SIGABRT: abort
PC=0x1a1500724 m=5 sigcode=0
signal arrived during cgo execution

goroutine 19 [syscall]:
runtime.cgocall(0x102d99e8c, 0x1400018d278)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/cgocall.go:157 +0x54 fp=0x1400018d240 sp=0x1400018d200 pc=0x102888c64
github.com/jmorganca/ollama/llama._Cfunc_llama_eval(0x153813c00, 0x14000471e28, 0x1, 0x0, 0x8)
	_cgo_gotypes.go:210 +0x38 fp=0x1400018d270 sp=0x1400018d240 pc=0x102d87448
github.com/jmorganca/ollama/llama.New.func4(0x102fc2de0?, {0x14000471e28, 0x1, 0x0?}, {0xffffffffffffffff, 0x0, 0x1000, 0x200, 0x1, 0x0, ...})
	/Users/jmorgan/workspace/ollama/llama/llama.go:141 +0x7c fp=0x1400018d2c0 sp=0x1400018d270 pc=0x102d8826c
github.com/jmorganca/ollama/llama.New({0x1400028ce00, 0x6d}, {0xffffffffffffffff, 0x0, 0x1000, 0x200, 0x1, 0x0, 0x0, 0x1, ...})
	/Users/jmorgan/workspace/ollama/llama/llama.go:141 +0x288 fp=0x1400018d480 sp=0x1400018d2c0 pc=0x102d88028
github.com/jmorganca/ollama/server.GenerateHandler(0x14000498300)
	/Users/jmorgan/workspace/ollama/server/routes.go:54 +0x5c0 fp=0x1400018d6e0 sp=0x1400018d480 pc=0x102d939f0
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0x14000498300)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x7c fp=0x1400018d730 sp=0x1400018d6e0 pc=0x102d7eb3c
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0x14000498300)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xac fp=0x1400018d8e0 sp=0x1400018d730 pc=0x102d7ddbc
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x1400047a820, 0x14000498300)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x54c fp=0x1400018da70 sp=0x1400018d8e0 pc=0x102d7cecc
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x1400047a820, {0x103014f10?, 0x14000443420}, 0x14000498200)
	/Users/jmorgan/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1d4 fp=0x1400018dab0 sp=0x1400018da70 pc=0x102d7c7d4
net/http.serverHandler.ServeHTTP({0x103012e70?}, {0x103014f10, 0x14000443420}, 0x14000498200)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:2936 +0x2d8 fp=0x1400018db60 sp=0x1400018dab0 pc=0x102b06408
net/http.(*conn).serve(0x140001a0900, {0x103015588, 0x1400049a060})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:1995 +0x560 fp=0x1400018dfa0 sp=0x1400018db60 pc=0x102b02100
net/http.(*Server).Serve.func3()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:3089 +0x30 fp=0x1400018dfd0 sp=0x1400018dfa0 pc=0x102b06c30
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400018dfd0 sp=0x1400018dfd0 pc=0x1028ec074
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:3089 +0x520

goroutine 1 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000337860 sp=0x14000337840 pc=0x1028bbee4
runtime.netpollblock(0x140003378f8?, 0x296fca4?, 0x1?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/netpoll.go:527 +0x158 fp=0x140003378a0 sp=0x14000337860 pc=0x1028b5408
internal/poll.runtime_pollWait(0x12aae7a18, 0x72)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/netpoll.go:306 +0xa0 fp=0x140003378d0 sp=0x140003378a0 pc=0x1028e5c40
internal/poll.(*pollDesc).wait(0x14000478600?, 0x0?, 0x0)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x14000337900 sp=0x140003378d0 pc=0x10296b2e8
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x14000478600)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_unix.go:614 +0x250 fp=0x140003379b0 sp=0x14000337900 pc=0x10296fd90
net.(*netFD).accept(0x14000478600)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/fd_unix.go:172 +0x28 fp=0x14000337a70 sp=0x140003379b0 pc=0x1029af2f8
net.(*TCPListener).accept(0x1400012ed68)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/tcpsock_posix.go:148 +0x28 fp=0x14000337aa0 sp=0x14000337a70 pc=0x1029c48f8
net.(*TCPListener).Accept(0x1400012ed68)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/tcpsock.go:297 +0x2c fp=0x14000337ae0 sp=0x14000337aa0 pc=0x1029c3a6c
net/http.(*onceCloseListener).Accept(0x140001a0900?)
	<autogenerated>:1 +0x30 fp=0x14000337b00 sp=0x14000337ae0 pc=0x102b2a3b0
net/http.(*Server).Serve(0x1400039cff0, {0x103014d00, 0x1400012ed68})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:3059 +0x304 fp=0x14000337c30 sp=0x14000337b00 pc=0x102b068d4
github.com/jmorganca/ollama/server.Serve({0x103014d00, 0x1400012ed68})
	/Users/jmorgan/workspace/ollama/server/routes.go:242 +0x294 fp=0x14000337ca0 sp=0x14000337c30 pc=0x102d95aa4
github.com/jmorganca/ollama/cmd.RunServer(0x14000449200?, {0x102deac46?, 0x0?, 0x0?})
	/Users/jmorgan/workspace/ollama/cmd/cmd.go:384 +0x114 fp=0x14000337d20 sp=0x14000337ca0 pc=0x102d98ea4
github.com/spf13/cobra.(*Command).execute(0x14000449200, {0x10348e290, 0x0, 0x0})
	/Users/jmorgan/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8 fp=0x14000337e60 sp=0x14000337d20 pc=0x102bacb18
github.com/spf13/cobra.(*Command).ExecuteC(0x14000448900)
	/Users/jmorgan/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c fp=0x14000337f20 sp=0x14000337e60 pc=0x102bad26c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jmorgan/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(0x14000054768?, {0x103015518?, 0x14000120010?})
	/Users/jmorgan/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x50 fp=0x14000337f40 sp=0x14000337f20 pc=0x102bace00
main.main()
	/Users/jmorgan/workspace/ollama/main.go:10 +0x34 fp=0x14000337f70 sp=0x14000337f40 pc=0x102d99c54
runtime.main()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:250 +0x248 fp=0x14000337fd0 sp=0x14000337f70 pc=0x1028bbab8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000337fd0 sp=0x14000337fd0 pc=0x1028ec074

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000054fa0 sp=0x14000054f80 pc=0x1028bbee4
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:305 +0xb8 fp=0x14000054fd0 sp=0x14000054fa0 pc=0x1028bbd28
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000054fd0 sp=0x14000054fd0 pc=0x1028ec074
created by runtime.init.6
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000055760 sp=0x14000055740 pc=0x1028bbee4
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgcsweep.go:278 +0xa4 fp=0x140000557b0 sp=0x14000055760 pc=0x1028a8bc4
runtime.gcenable.func1()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:178 +0x28 fp=0x140000557d0 sp=0x140000557b0 pc=0x10289d6d8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000557d0 sp=0x140000557d0 pc=0x1028ec074
created by runtime.gcenable
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1400007c000?, 0x102ee86e8?, 0x1?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000055f50 sp=0x14000055f30 pc=0x1028bbee4
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1033d2d60)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x14000055f80 sp=0x14000055f50 pc=0x1028a6a3c
runtime.bgscavenge(0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgcscavenge.go:628 +0x44 fp=0x14000055fb0 sp=0x14000055f80 pc=0x1028a6fb4
runtime.gcenable.func2()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:179 +0x28 fp=0x14000055fd0 sp=0x14000055fb0 pc=0x10289d678
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000055fd0 sp=0x14000055fd0 pc=0x1028ec074
created by runtime.gcenable
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:179 +0xb8

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x1033d37a0?, 0x40?, 0x23?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000054580 sp=0x14000054560 pc=0x1028bbee4
runtime.runfinq()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mfinal.go:193 +0x10c fp=0x140000547d0 sp=0x14000054580 pc=0x10289c76c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000547d0 sp=0x140000547d0 pc=0x1028ec074
created by runtime.createfing
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/mfinal.go:163 +0x84

goroutine 20 [IO wait]:
runtime.gopark(0xffffffffffffffff?, 0xffffffffffffffff?, 0x23?, 0x0?, 0x1028fe890?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000050540 sp=0x14000050520 pc=0x1028bbee4
runtime.netpollblock(0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/netpoll.go:527 +0x158 fp=0x14000050580 sp=0x14000050540 pc=0x1028b5408
internal/poll.runtime_pollWait(0x12aae7928, 0x72)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/netpoll.go:306 +0xa0 fp=0x140000505b0 sp=0x14000050580 pc=0x1028e5c40
internal/poll.(*pollDesc).wait(0x14000478680?, 0x1400049a161?, 0x0)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x140000505e0 sp=0x140000505b0 pc=0x10296b2e8
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000478680, {0x1400049a161, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/internal/poll/fd_unix.go:167 +0x200 fp=0x14000050680 sp=0x140000505e0 pc=0x10296c650
net.(*netFD).Read(0x14000478680, {0x1400049a161?, 0x0?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/fd_posix.go:55 +0x28 fp=0x140000506d0 sp=0x14000050680 pc=0x1029ad658
net.(*conn).Read(0x14000130d00, {0x1400049a161?, 0x0?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/net.go:183 +0x34 fp=0x14000050720 sp=0x140000506d0 pc=0x1029bbc64
net.(*TCPConn).Read(0x0?, {0x1400049a161?, 0x0?, 0x0?})
	<autogenerated>:1 +0x2c fp=0x14000050750 sp=0x14000050720 pc=0x1029ce1ac
net/http.(*connReader).backgroundRead(0x1400049a150)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:674 +0x44 fp=0x140000507b0 sp=0x14000050750 pc=0x102afc5b4
net/http.(*connReader).startBackgroundRead.func2()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:670 +0x28 fp=0x140000507d0 sp=0x140000507b0 pc=0x102afc4d8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000507d0 sp=0x140000507d0 pc=0x1028ec074
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/net/http/server.go:670 +0xcc

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x16f586c00
r6      0xa
r7      0x0
r8      0xe035c4e8feb62ded
r9      0xe035c4e991efdded
r10     0x2
r11     0xfffffffd
r12     0x10000000000
r13     0x0
r14     0x0
r15     0x0
r16     0x148
r17     0x201034f60
r18     0x0
r19     0x6
r20     0x16f59f000
r21     0x1603
r22     0x16f59f0e0
r23     0x8
r24     0x7
r25     0x8
r26     0x1fc513720
r27     0x102ddb9c0
r28     0x102f010f0
r29     0x16f586bb0
lr      0x1a1537c28
sp      0x16f586b90
pc      0x1a1500724
fault   0x1a1500724

**Comment by radiofreejohn** [comment]
Are you sure you're not running out of memory? The assertion failure there looks like a check for available memory. I was able to build and run a model with a temperature of 2 on a 64GB M1 Max.

**Comment by alivardar** [comment]
My macbook air has 16gb ram, probably you are right. But seems application has no control about memory size control.

**Comment by jmorganca** [comment]
Thanks for creating this issue!

**Comment by jmorganca** [comment]
This should be fixed as of the last few versions, but feel free to re-open!
