### ISSUE TITLE
Ollama requests hangs after about 20 requests and needs to be restarted

### ISSUE THREAD

**Issue by Shajan** [jmorganca/ollama#1994]
Request hangs after about 20 requests.
Ollama version : 0.1.20, Linux with T4 GPU as well as Mac M2.
All subsequent `api/generate` request hangs for all models. The only way to resume is to restart ollama `sudo systemctl restart ollama`.

Repro

```python
import requests

def query(session):
    url = "http://localhost:11434/api/generate"
    data = {
        "model": "llama2:7b",
        "prompt": "Why is the sky blue?",
        "stream": False,
    }

    with requests.post(url, json=data) as response: # Hangs about every 20 requests
        if response.ok:
            return response.text
        else:
            print(response)
            return None

def main():
    total = 0
    errors = 0

    with requests.Session() as session:
        for _ in range(100):
            total += 1
            r = query(session)
            if r is None:
                errors += 1
            success_rate = 100*((total - errors)/total)
            print(f"{total=} {errors=} {success_rate=:.2f}")

if __name__ == "__main__":
    main()

```

**Comment by Shajan** [comment]
Issue #1910 appears to be related. This issue appears to be different (unrelated to format='json').

**Comment by Shajan** [comment]
Same issue on version `0.1.19`

**Comment by johanngerberding** [comment]
Have the same issue with a gguf mistral model on a RTX6000 Quadro GPU on linux after 20-30 requests

**Comment by BruceMacD** [comment]
Thanks for the script in the report, I've reproduced this and found what is causing the issue. Working on getting to the root cause now.

**Comment by BruceMacD** [comment]
We have a mitigation in for the next release by disabling prompt-caching: #2018 

I'll follow up on why prompt-caching causes this in #2023

Thanks to everyone for the reports.
