### ISSUE TITLE
no healthy upstream

### ISSUE THREAD

**Issue by vesellov** [jmorganca/ollama#1995]
Hello Team.

Great tool you built. Thank you for that!

I am getting `no healthy upstream` when trying to open the ollama.ai web site... probably too many people loves Ollama today :heart:

**Comment by epicmario7133** [comment]
Same for ollama run llava:
pulling manifest
Error: pull model manifest: 503: no healthy upstream

**Comment by xavierallem** [comment]
Got the same issue. Is it with a new update?

**Comment by danyo1399** [comment]
Whats worse is ollama run doesnt even work. 
Ollama run <model> should be able to run offline when the model has already downloaded

**Comment by jmorganca** [comment]
Hi all this should be fixed now. Sorry you hit an error. @danyo1399 if you have a model already downloaded `ollama run` will not require a connection as it will run the model you have locally, but do let me know if you're seeing otherwise for any reason
