### ISSUE TITLE
how to enable amd gpu for ollama ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [jmorganca/ollama#2002]
how to enable amd gpu for ollama ?

**Comment by jmorganca** [comment]
Hi there, AMD and ROCm support aren't yet in the released version – I'll merge this with #738 so we can follow along there!

**Comment by hemangjoshi37a** [comment]
@jmorganca I hope AMD and ROCm get support ASAP because I know so many of my friends that have AMD GPU and wanting to run on their PCs. THanks
