### ISSUE TITLE
Project Sponsorship

### ISSUE THREAD

**Issue by peperunas** [jmorganca/ollama#2005]
First of all, I wanted to thank you for the amazing work and software!

For this reason, it would be great if there were ways to support the project - maybe through Github's Sponsor feature?

Thank you again!

**Comment by mchiang0610** [comment]
Hey @peperunas Thank you for the kind words and willingness to help!! 

The best way to help the project right now is to help share Ollama with others (including use cases / content), and any help in reporting bugs/feature requests. The project will have to work hard to earn its spot for users.
