### ISSUE TITLE
How to use Ollama in Google Colab?

### ISSUE THREAD

**Issue by MonikaVijayakumar25** [jmorganca/ollama#2010]
I have tried it via langchain but getting connection error.

ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd433ce48e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Is there any way to use Ollama in Colab?

**Comment by pdevine** [comment]
cc @mxyng

**Comment by mxyng** [comment]
There's insufficient details in your issue to understand where the problem is. I suggest starting with this example for running Ollama in Colab: https://github.com/jmorganca/ollama/tree/main/examples/jupyter-notebook

**Comment by pdevine** [comment]
Hey @MonikaVijayakumar25 please feel free to reopen the issue if you can't get it to work w/ the the tutorial that @mxyng mentioned.

**Comment by quartermaine** [comment]
@mxyng In the Colab [notebook](https://github.com/jmorganca/ollama/tree/main/examples/jupyter-notebook) how to set the ngrok AUTH_TOKEN.?
