### ISSUE TITLE
how to remove ollama from macos?

### ISSUE THREAD

**Issue by artnoimann** [jmorganca/ollama#2028]
When deleting an application from the list, the error "ollama is still running" is displayed
If you terminate processes from system monitoring, they start again immediately and the application itself cannot be deleted either.

**Comment by easp** [comment]
> When deleting an application from the list

What list?

Have you quit Ollama via the menu bar icon first?

**Comment by artnoimann** [comment]
> > When deleting an application from the list
> 
> What list?
> 
> Have you quit Ollama via the menu bar icon first?

Of course

**Comment by easp** [comment]
Some people think the app is just an installer and don't realize that it remains in the menu bar.

You still didn't say what list you are removing it from.

**Comment by artnoimann** [comment]
> Some people think the app is just an installer and don't realize that it remains in the menu bar.
> 
> You still didn't say what list you are removing it from.

finder - programs - move to trash
and
system monitoring - delete process

**Comment by dekstop** [comment]
To remove it completely, you also need to remove the symlink and app files:

    $ rm /usr/local/bin/ollama 
    $ rm -rf ~/Library/Application\ Support/Ollama

**Comment by TijuanaKez** [comment]
Most important of all you'll want to get rid of ~/.ollama as that's where all the huge model files are.

`rm -rf ~/.ollama`

**Comment by JINJIBOI** [comment]
> ```
> $ rm /usr/local/bin/ollama 
> $ rm -rf ~/Library/Application\ Support/Ollama
> ```
When I try to remove it it says "Command not found"

**Comment by didiBonocore** [comment]
I installed Ollama on an M2 Macbook. There were several files to remove, at least in my case. This is what I did:

`find / -name "*ollama*" 2>/dev/null` - this command will look for Ollama in your system. It might take a while to execute. Once you have the output skim through it and ensure you're not removing something you shouldn't. Then remove the files from the output using `rm -rf`. 

Alternatively, if you use something like Warp terminal you can just ask their AI assistant to do the work for you. I hope it helps.

**Comment by Nilpo** [comment]
> Have you quit Ollama via the menu bar icon first?

There isn't one on my machine.

**Comment by OpeyemiSanusi** [comment]
> rm -rf ~/.ollama

that's dangerous! especially with tons of AI related apps

**Comment by easp** [comment]
@OpeyemiSanusi Dangerous? How so? Other AI related apps shouldn't be saving anything in ~/.Ollama.

**Comment by OpeyemiSanusi** [comment]
> @OpeyemiSanusi Dangerous? How so? Other AI related apps shouldn't be saving anything in ~/.ollama.

my bad! i quoted the wrong reply. I want referring to the comment that suggested using `find / -name "*ollama*" 2>/dev/null` because that would all files with `"ollama" `

**Comment by bcp579** [comment]
Just simply go and click on apple icon on the top of the screen and go to force quit and delete it from there. You will able to delete it.

**Comment by flipbit03** [comment]
What an infuriating user experience. I cannot drag Ollama.app into the Trash because there are running processes. You kill the processes, they restart instantly

**Comment by j05hau** [comment]
Figured it out - the deleted .app **that was in the trash can** resurrected itself after every reboot of macOS. Empty it from the trash and it shouldn't come back.

```
source=app_darwin.go:215 msg="starting Ollama" app="/Users/username/.Trash/Ollama 6.14.32\u202fpm.app" version=0.9.6 OS=Darwin/24.5.0
```

This needs fixing, stat.

**Comment by antonreshetov** [comment]
is it such a joke that there is no simple button for deleting or does it not respect simple dragging to the trash?

**Comment by lopezm94** [comment]
This script this the trick for me on MacOS, it's AI generated, execute at your own risk, I was desperate to get it out of my pc. This stopped ollama from trying to install back the CLI at startup. These directories where selected by filtering from executing the command `find / -name "*ollama*" 2>/dev/null` suggested above.

```shell
#!/bin/bash

echo "==================================="
echo "Complete Ollama Removal Script"
echo "==================================="
echo ""

# Step 1: Kill all Ollama processes
echo "Step 1: Killing all Ollama processes..."
pkill -f ollama || true
killall Ollama 2>/dev/null || true
sleep 2

# Step 2: Remove Ollama from Applications and Trash
echo "Step 2: Removing Ollama application..."
rm -rf /Applications/Ollama.app 2>/dev/null || true
rm -rf ~/Applications/Ollama.app 2>/dev/null || true
rm -rf ~/.Trash/Ollama.app 2>/dev/null || true
rm -rf /Users/lopezm/.Trash/Ollama.app 2>/dev/null || true

# Step 3: Remove Ollama data and config directories
echo "Step 3: Removing Ollama data directories..."
rm -rf ~/.ollama 2>/dev/null || true
rm -rf ~/Library/Application\ Support/Ollama 2>/dev/null || true
rm -rf ~/Library/Caches/ollama 2>/dev/null || true
rm -rf ~/Library/Caches/com.electron.ollama 2>/dev/null || true
rm -rf ~/Library/Caches/com.electron.ollama.ShipIt 2>/dev/null || true
rm -rf ~/Library/HTTPStorages/com.electron.ollama 2>/dev/null || true
rm -rf ~/Library/HTTPStorages/com.electron.ollama.binarycookies 2>/dev/null || true

# Step 4: Remove Ollama preferences
echo "Step 4: Removing Ollama preferences..."
rm -f ~/Library/Preferences/com.electron.ollama.plist 2>/dev/null || true
rm -f ~/Library/Preferences/ByHost/com.electron.ollama.ShipIt.*.plist 2>/dev/null || true

# Step 5: Remove Electron cache directories
echo "Step 5: Removing Electron cache directories..."
rm -rf /private/var/folders/*/*/*/*/com.electron.ollama* 2>/dev/null || true
rm -rf /System/Volumes/Data/private/var/folders/*/*/*/*/com.electron.ollama* 2>/dev/null || true

# Step 6: Remove Ollama CLI if installed via homebrew
echo "Step 6: Checking for Homebrew installation..."
if command -v brew &> /dev/null; then
    brew uninstall ollama 2>/dev/null || true
    brew untap ollama/tap 2>/dev/null || true
fi

# Step 7: Remove Ollama binary from common locations
echo "Step 7: Removing Ollama binaries..."
sudo rm -f /usr/local/bin/ollama 2>/dev/null || true
sudo rm -f /opt/homebrew/bin/ollama 2>/dev/null || true
rm -f ~/bin/ollama 2>/dev/null || true

# Step 8: Clear Raycast cache
echo "Step 8: Clearing Raycast cache..."
rm -rf ~/Library/Caches/com.raycast.macos/urlcache/ollama 2>/dev/null || true

# Step 9: Remove any LaunchAgents
echo "Step 9: Removing LaunchAgents..."
rm -f ~/Library/LaunchAgents/com.ollama.* 2>/dev/null || true
rm -f ~/Library/LaunchAgents/com.electron.ollama.* 2>/dev/null || true

# Step 10: Final cleanup - empty trash
echo "Step 10: Final cleanup..."
osascript -e 'tell application "Finder" to empty trash' 2>/dev/null || true

echo ""
echo "==================================="
echo "Ollama removal complete!"
echo "==================================="
echo ""
echo "Note: Some files in npm/node modules and Python packages contain"
echo "Ollama references but are just integrations/libraries, not the"
echo "actual Ollama application. These are safe to keep unless you want"
echo "to remove those specific packages."
echo ""
echo "If you see any permission denied errors above, you may need to"
echo "manually check those locations with sudo access."
```

**Comment by lomeat** [comment]
> t's AI generated

it's a definitely good script otherwise

**Comment by shrestha-roshan** [comment]
https://docs.ollama.com/macos#uninstall

Here's the official way:
```
sudo rm -rf /Applications/Ollama.app
sudo rm /usr/local/bin/ollama
rm -rf "~/Library/Application Support/Ollama"
rm -rf "~/Library/Saved Application State/com.electron.ollama.savedState"
rm -rf ~/Library/Caches/com.electron.ollama/
rm -rf ~/Library/Caches/ollama
rm -rf ~/Library/WebKit/com.electron.ollama
rm -rf ~/.ollama
```

**Comment by forgit1925** [comment]
This script worked for me at once! No errors encountered 

echo "Stopping Ollama..."

# Kill running processes
pkill -9 ollama 2>/dev/null

# Detect current user
USER_HOME="$HOME"

echo "Removing binaries..."
sudo rm -f /usr/local/bin/ollama

echo "Removing app..."
sudo rm -rf /Applications/Ollama.app

echo "Removing user data..."
rm -rf "$USER_HOME/.ollama"
rm -rf "$USER_HOME/Library/Application Support/Ollama"
rm -rf "$USER_HOME/Library/Caches/ollama"

echo "Removing temp files..."
rm -rf /private/var/folders/*/*/*/C/com.electron.ollama 2>/dev/null

echo "Unloading launch agent..."
launchctl unload ~/Library/LaunchAgents/com.ollama.ollama.plist 2>/dev/null
rm -f ~/Library/LaunchAgents/com.ollama.ollama.plist

echo "Cleanup finished"

**Comment by WalterGropius** [comment]
guys!! if u installed ollama a long time ago with brew its prob the prob. run which ollama 😜
