### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by d1nuc0m** [jmorganca/ollama#2070]
System: ollama 0.1.20 on AlmaLinux 9.3, installed with `sudo su && curl https://ollama.ai/install.sh | sh`. SELinux does not influence the issue, enabled or not the problem is the same.

1. I'm using a wildcard certificate (*.example.com) to run ollama on a dedicated VM (ollama.example.com). 
2. Placed `cert.pem` and `key.pem` in `/usr/share/ollama/.ollama/ssl/` (also tried with `~/.ollama/ssl/`)
3. Certificate has been verified against the key ([link](https://www.ssl247.com/knowledge-base/detail/how-do-i-verify-that-a-private-key-matches-a-certificate-openssl-1527076112539/ka03l0000015hscaay/)), CA has been installed and the certificate has been  verified again ([link](https://jermsmit.com/install-a-ca-certificate-on-red-hat-enterprise-linux/))
4. Ollama has been bind to all interfaces, service has been reloaded as per [FAQ](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-server-environment-variables-on-linux)
5. http://ollama.example.com:11434 returns _Ollama is running_, while https://ollama.example.com:11434 returns error _SSL_ERROR_RX_RECORD_TOO_LONG_
6. I've tried both with certificate only and certificate with intermediates, same result. Note that the same certificate/key pair is in use on other *.example.com subdomains and it works

**Comment by mxyng** [comment]
There is currently no HTTPS support built into Ollama. If you want to use HTTPS, the suggestion is to put Ollama behind a reverse proxy like nginx

**Comment by d1nuc0m** [comment]
> There is currently no HTTPS support built into Ollama

Thank you, just seen #1310 , any plans on merging it?
