### ISSUE TITLE
Enable installation without root priviledge

### ISSUE THREAD

**Issue by chunhualiao** [jmorganca/ollama#2111]
It seems like ollama will run sudo during its installation on Linux.
 
Please support the installation and use of users without sudo priviledge.

thanks.

**Comment by jmorganca** [comment]
Hi @chunhualiao, thanks for the issue. The install script does this because it needs to check for devices, drivers and set up an `ollama` user. The [releases](https://github.com/jmorganca/ollama/releases) include pre-built binaries that will work without any sudo (e.g. just run `ollama serve`). Let me know if that helps!

**Comment by ReanFernandes** [comment]
> Hi @chunhualiao, thanks for the issue. The install script does this because it needs to check for devices, drivers and set up an `ollama` user. The [releases](https://github.com/jmorganca/ollama/releases) include pre-built binaries that will work without any sudo (e.g. just run `ollama serve`). Let me know if that helps!

Hello! 
Im trying to get ollama up and running on a cluster which i do not have sudo access to. Could you please elaborate how I could go about the installation? 
Note: I am a newbie to this, and the [install page](https://github.com/jmorganca/ollama/blob/main/docs/linux.md) does not have any info on how to go about this. I would gladly appreciate any help you could provide! :) 
Thank you!

**Comment by Anirudh257** [comment]
> @ReanFernandes The download page has a list of assets, one of them is binary for Linux named ollama-linux-amd64.
> 
> Just download it to your Linux cluster, then run the following:
> 
> # start the server in background
> ./ollama-linux-amd64 serve&
> 
> # run a local model afterwards
> ./ollama-linux-amd64 run llama2
> 
> I wish someone can add this into their official instructions.

Hi @chunhualiao even bash access is prohibited on cluster.

**Comment by Anirudh257** [comment]
Hi @chunhualiao and @ReanFernandes, if you still need help. I figured out a temporary solution. Download the binary from https://github.com/ollama/ollama/blob/main/docs/linux.md and run it normally without sudo access.

**Comment by zrgtzjwh** [comment]
> @ReanFernandes The download page has a list of assets, one of them is binary for Linux named ollama-linux-amd64.
> 
> Just download it to your Linux cluster, then run the following:
> 
> # start the server in background
> ./ollama-linux-amd64 serve&
> 
> # run a local model afterwards
> ./ollama-linux-amd64 run llama2
> 
> I wish someone can add this into their official instructions.

It works for me.

**Comment by clmerlos** [comment]
> The download page has a list of assets, one of them is binary for Linux named ollama-linux-amd64.
> 
> Just download it to your Linux cluster, then run the following:
> 
> # start the server in background
> ./ollama-linux-amd64 serve&
> 
> # run a local model afterwards
> ./ollama-linux-amd64 run llama2
> 
> I wish someone can add this into their official instructions.

Build from scratch instructions?

**Comment by bozo32** [comment]
had to 
chmod +x ollama-* 
to get it to work

**Comment by krz** [comment]
I'm in a similar situation, trying to run ollama without sudo access. Downloading ollama and starting the server with `./ollama-linux-amd64 serve&` worked fine, but when I try to run a model, I get this error:

> time=2024-04-26T15:13:33.513+02:00 level=INFO source=gpu.go:126 msg="Nvidia GPU detected via cudart"
time=2024-04-26T15:13:33.513+02:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
⠙ time=2024-04-26T15:13:33.588+02:00 level=INFO source=gpu.go:202 msg="[cudart] CUDART CUDA Compute Capability detected: 6.0"
time=2024-04-26T15:13:33.618+02:00 level=INFO source=server.go:127 msg="offload to gpu" reallayers=33 layers=33 required="5222.5 MiB" used="5222.5 MiB" available="16020.1 MiB" kv="1024.0 MiB" fulloffload="164.0 MiB" partialoffload="193.0 MiB"
time=2024-04-26T15:13:33.618+02:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-26T15:13:33.622+02:00 level=INFO source=server.go:264 msg="starting llama server" cmd="/tmp/ollama2278607108/runners/cuda_v11/ollama_llama_server --model /home/oll/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --port 45845"
time=2024-04-26T15:13:33.623+02:00 level=INFO source=server.go:264 msg="starting llama server" cmd="/tmp/ollama2278607108/runners/cpu_avx2/ollama_llama_server --model /home/oll/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 33 --port 40273"
time=2024-04-26T15:13:33.624+02:00 level=ERROR source=server.go:285 msg="unable to load any llama server" error="error starting the external llama server: fork/exec /tmp/ollama2278607108/runners/cpu_avx2/ollama_llama_server: permission denied "
[GIN] 2024/04/26 - 15:13:33 | 500 |  1.176409787s |       127.0.0.1 | POST     "/api/chat"
Error: error starting the external llama server: fork/exec /tmp/ollama2278607108/runners/cpu_avx2/ollama_llama_server: permission denied

**Comment by haozhuang0000** [comment]
I got this error by following above comments, anyone know how?

Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/8b": read tcp xxxxxx: read: connection reset by peer

**Comment by GonyRosenman** [comment]
i used chatgpt to modify the install script (can anyone verify this solution???) - 
#!/bin/sh
set -eu

status() { echo ">>> $*" >&2; }
error() { echo "ERROR $*"; exit 1; }
warning() { echo "WARNING: $*"; }

TEMP_DIR=$(mktemp -d)
cleanup() { rm -rf $TEMP_DIR; }
trap cleanup EXIT

ARCH=$(uname -m)
case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) error "Unsupported architecture: $ARCH" ;;
esac

VER_PARAM="${OLLAMA_VERSION:+?version=$OLLAMA_VERSION}"

status "Downloading ollama..."
curl --fail --show-error --location --progress-bar -o $TEMP_DIR/ollama "https://ollama.com/download/ollama-linux-${ARCH}${VER_PARAM}"

# Ensure bin directory exists
mkdir -p ~/bin
status "Installing ollama to ~/bin..."
install -m755 $TEMP_DIR/ollama ~/bin/ollama

status 'Install complete. Run "~/bin/ollama" from the command line.'

**Comment by Haruki-Kny** [comment]
@justin4ai 
Hi, I also had the same problem.
I think you should execute `./bin/ollama serve&`. It's because the name of the extracting directory might have changed from `ollama-linux-amd64`  to `bin`.
If it doesn't work, you should check the content of the bin.

**Comment by famura** [comment]
> Hi [@chunhualiao](https://github.com/chunhualiao), thanks for the issue. The install script does this because it needs to check for devices, drivers and set up an `ollama` user. The [releases](https://github.com/jmorganca/ollama/releases) include pre-built binaries that will work without any sudo (e.g. just run `ollama serve`). Let me know if that helps!

Can you please say more about this? On [this doc page](https://github.com/ollama/ollama/blob/main/docs/linux.md) I still read `sudo` before tar.

Let's assume I am under Linux, have no sudo permissions, and I just downloaded v0.5.10.tar.gz. How do I get to run ollama such that I can use it in a different process, e.g. from a python script via the ollama python package?

**Comment by wangjiawen2013** [comment]
> Hi [@chunhualiao](https://github.com/chunhualiao), thanks for the issue. The install script does this because it needs to check for devices, drivers and set up an `ollama` user. The [releases](https://github.com/jmorganca/ollama/releases) include pre-built binaries that will work without any sudo (e.g. just run `ollama serve`). Let me know if that helps!

Is there a binary for Centos linux server ? I only find binary for macos.

**Comment by mobraine** [comment]
> > Hi [@chunhualiao](https://github.com/chunhualiao), thanks for the issue. The install script does this because it needs to check for devices, drivers and set up an `ollama` user. The [releases](https://github.com/jmorganca/ollama/releases) include pre-built binaries that will work without any sudo (e.g. just run `ollama serve`). Let me know if that helps!
> 
> Can you please say more about this? On [this doc page](https://github.com/ollama/ollama/blob/main/docs/linux.md) I still read `sudo` before tar.
> 
> Let's assume I am under Linux, have no sudo permissions, and I just downloaded v0.5.10.tar.gz. How do I get to run ollama such that I can use it in a different process, e.g. from a python script via the ollama python package?

If you have downloaded the tgz file, simply `tar -xzvf v0.5.10.tar.gz` this should extract and show you where the files are extracted. Like @justin4ai said, ollama is now living in the bin directory.

> [@justin4ai](https://github.com/justin4ai) Hi, I also had the same problem. I think you should execute `./bin/ollama serve&`. It's because the name of the extracting directory might have changed from `ollama-linux-amd64` to `bin`. If it doesn't work, you should check the content of the bin.
