### ISSUE TITLE
Full model names

### ISSUE THREAD

**Issue by freQuensy23-coder** [jmorganca/ollama#2141]
Your code can serve mistral's models, but which one exactly??? Is it:
- mistralai/mistral-7b-instruct-v0.1
- mistralai/mistral-7b-v0.1
- mistralai/mistral-7b-instruct-v0.2

Thanks for anwer

**Comment by pdevine** [comment]
You can find each of the tags for Mistral here: https://ollama.ai/library/mistral/tags

* For `mistralai/mistral-7b-instruct-v0.1`, you can use `ollama run mistral:v0.1`
* For `mistralai/mistral-7b-v0.1`, you can use `ollama run mistral:7b-text-q4_0` (I think this is there text modal, and not instruct?)
* For `mistralai/mistral-7b-instruct-v0.2`, you can use `ollama run mistral`

Going to go ahead and close this, but hopefully it answers your question. There are more details in the overview on that page.

**Comment by freQuensy23-coder** [comment]
And what about llama2 - it is llama2-chat or llama2 base
