### ISSUE TITLE
True SVG of Ollama logo?

### ISSUE THREAD

**Issue by sqs** [jmorganca/ollama#2152]
I see https://github.com/jmorganca/ollama/blob/a0a829bf7a29b532f4bebe00e7cb1304ff9f0190/app/src/ollama.svg, but it's an SVG that embeds PNG data. Is there a true SVG of the Ollama logo? I would like to use it in the model selection dropdown in Cody:

![image](https://github.com/jmorganca/ollama/assets/1976/8d2a173a-8e54-4cb8-9e30-bc26186a2a11)

(Not urgent!)

**Comment by mchiang0610** [comment]
[logo.svg.zip](https://github.com/jmorganca/ollama/files/14018428/logo.svg.zip)

**Comment by mchiang0610** [comment]
Thanks @sqs. Attaching the SVG here.

**Comment by timheuer** [comment]
@jmorganca is it acceptable to use the SVG/PNG with attribution to Ollama org?

**Comment by Sekky61** [comment]
In case you need a square, just edit the svg tag: `width="854" height="854" viewBox="-104 0 854 854"`.
