### ISSUE TITLE
Stop generation on specific keyword(s)

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#217]
Certain models don't automatically stop generation when it's the "user" or "human"'s turn to input data, causing the prompt to be output.

**Comment by neopunisher** [comment]
Is that whats happening here? https://gist.github.com/neopunisher/0647fbbec9faf9b2c651fdd7748a660a

**Comment by jmorganca** [comment]
@neopunisher yes, that's it! Great find.
