### ISSUE TITLE
Sending input with a + crashes

### ISSUE THREAD

**Issue by benr75** [jmorganca/ollama#220]
Maybe an url escaping issue? I didn't dig much deeper but wanted to report. 

```
$ ollama run llama2:13b
>>> I cannot send input with a + in it
Error: Post "http://127.0.0.1:11434/api/generate": EOF
```

**Comment by mchiang0610** [comment]
Hey @benr75, may I ask how much memory you have on your mac? One of the most common reasons for this error is due to out-of-memory. 

I just tried using `+` works

**Comment by benr75** [comment]
64GB, all other queries worked. Let me know if there are some logs to look at or more info I can provide. 

<img width="214" alt="image" src="https://github.com/jmorganca/ollama/assets/661/4e23523b-9086-430e-ade0-62854763439a">

**Comment by mxyng** [comment]
This is less likely an issue with `+` and more likely stability related. There are a lot of stability improvements release in 0.0.13 which should address this and other `Post "http://127.0.0.1:11434/api/generate": EOF` issues

**Comment by benr75** [comment]
@mxyng thx for looking into this. Testing on the new version is working with the provided prompt. Closing.
