### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by alivardar** [jmorganca/ollama#229]
ollama.ai discord invitation link seems broken,
i want to help to project, how can we discuss?

**Comment by BruceMacD** [comment]
https://discord.gg/MrfB5FbNWN

Do you see any error? This link seems to work for me

**Comment by alivardar** [comment]
![image](https://github.com/jmorganca/ollama/assets/10295369/3863a872-88c1-412d-9f5a-1c6e939c1466)

**Comment by alivardar** [comment]
maybe you can test  on a browser private tab

**Comment by BruceMacD** [comment]
Thanks, we will get his fixed, in the meantime:
https://discord.gg/acgsEcDF

**Comment by mchiang0610** [comment]
@alivardar does this one work for you? https://discord.com/invite/ollama 

I just checked the other link, and it's working: 

<img width="1267" alt="Image 2023-07-27 at 3 38 55 PM" src="https://github.com/jmorganca/ollama/assets/3325447/5d869338-fd4b-44b1-8415-4e4b6df42f2c">

**Comment by mchiang0610** [comment]
updated the website link now: https://discord.com/invite/ollama 

PR: https://github.com/jmorganca/ollama/pull/231 

Closing this issue for now. @alivardar, please let me know if you are running into issues joining. 

Thanks!

**Comment by alivardar** [comment]
Thanks, It is ok .
