### ISSUE TITLE
Descriptions for 3rd Party Imports

### ISSUE THREAD

**Issue by eagleEggs** [jmorganca/ollama#233]
Just wanted to share that it would be nice to have in the docs a list of the imported 3rd party libraries for transparency - Really just for the smaller obscure ones. One of them threw me down a rabbit hole looking over their code as it was a small repo with not much activity. Just a suggestion.

**Comment by mchiang0610** [comment]
Hey @eagleEggs sorry for the delay. Wanted to see if you meant for us to document every single 3rd party dependency? 

Otherwise, it is listed here: 
https://github.com/jmorganca/ollama/blob/main/go.mod 

Hope this helps! Thank you so much.
