### ISSUE TITLE
ctrl c answering time crashing server

### ISSUE THREAD

**Issue by alivardar** [jmorganca/ollama#242]
Hi my model based on llama2:13b
I am opening two terminal on macos air, when start to work answering ollama, If i click on keyboard ctrl-c on ollama run window for exit, server crushing.

<img width="1093" alt="image" src="https://github.com/jmorganca/ollama/assets/10295369/5417397e-08be-47aa-85a4-87b24b20cf20">

**Comment by BruceMacD** [comment]
Thanks for the report, this should be fixed in the next upcoming release soon.

**Comment by alivardar** [comment]
I tested on new release, it is fixed.
