### ISSUE TITLE
Falcon models

### ISSUE THREAD

**Issue by jkleckner** [jmorganca/ollama#243]
I'm hearing lots of great things about the Falcon models.  They are Apache 2 licensed [1] so should be amenable to publishing in your repo.  The 40b model would probably not fit into 64GB of memory but some people are beginning to get larger memory Macs.
And it is a unified memory model.

[1] https://huggingface.co/tiiuae/falcon-40b#why-use-falcon-40b

**Comment by mchiang0610** [comment]
Sorry for not getting back to this sooner, but we do have Falcon support: 

https://ollama.ai/library/falcon
