### ISSUE TITLE
api: make host configurable

### ISSUE THREAD

**Issue by bmizerany** [jmorganca/ollama#261]
I'd like to run `ollama serve` somewhere other than where I am running my client. I'd like to propose a `OLLAMA_HOST` environment variable which is picked up by `api.NewClient` if no other hosts are specified in the `hosts` param.

I have a patch locally I'm happy to convert to a PR if anyone thinks this has legs the team is open to it.

**Comment by mxyng** [comment]
This is already possible through `OLLAMA_HOST` and `OLLAMA_PORT` when starting the server. The server can be access with any HTTP client on this separate host/port but the client only uses `127.0.0.1:11434` (for now)

**Comment by bmizerany** [comment]
>  but the client only uses 127.0.0.1:11434

I'm proposing changing it so that clients (including the CLI) can access an Ollama server running on a remote server, and by way of setting `OLLAMA_HOST=https://example.com`

**Comment by bmizerany** [comment]
Maybe keeping `OLLAMA_HOST/POST` for `ollama serve` and clients can honor a `OLLAMA_BASE_URL=https://example.com`?

**Comment by pdevine** [comment]
maybe `OLLAMA_CLIENT_HOST` just to be explicit? I like the change though.

**Comment by bmizerany** [comment]
@pdevine SGTM. I'll send a PR.

**Comment by bmizerany** [comment]
PR up https://github.com/jmorganca/ollama/pull/262

**Comment by jmorganca** [comment]
Closed by #262
