### ISSUE TITLE
Pressing enter during `ollama pull` causes newlines to be printed repeatedly

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#269]
<img width="1531" alt="Screenshot 2023-08-03 at 11 59 21 AM" src="https://github.com/jmorganca/ollama/assets/251292/1e782cfa-75f2-4bc3-84da-567c685ef36c">

**Comment by technovangelist** [comment]
I think this is resolved as you originally described with Mikes new progress bar. Though pressing enter a bunch of extra times adds the manifest line. Can we close?
![CleanShot 2023-12-04 at 11 04 56](https://github.com/jmorganca/ollama/assets/633681/37ec43fd-2ff3-4544-ad57-d579e5efbc55)
