### ISSUE TITLE
Ability to download Vicuna v1.5 Models

### ISSUE THREAD

**Issue by jlarmstrongiv** [jmorganca/ollama#274]
- https://twitter.com/lmsysorg/status/1686794639469371393
- https://github.com/lm-sys/FastChat/tree/main#model-weights

**Comment by mxyng** [comment]
@jlarmstrongiv these are available for download under `vicuna:7b-v1.5-q4_0`, `vicuna:7b-v1.5-16K-q4_0`, `vicuna:13b-v1.5-q4_0`, and `13b-v1.5-16k-q4_0`. K quants are also available, e.g. for `vicuna:7b`:

```
vicuna:7b-v1.5-q2_K
vicuna:7b-v1.5-q3_K_L
vicuna:7b-v1.5-q3_K_M
vicuna:7b-v1.5-q3_K_S
vicuna:7b-v1.5-q4_0
vicuna:7b-v1.5-q4_1
vicuna:7b-v1.5-q4_K_M
vicuna:7b-v1.5-q4_K_S
vicuna:7b-v1.5-q5_K_M
vicuna:7b-v1.5-q5_K_S
vicuna:7b-v1.5-q6_K
```

Alias tags will be available in the future, such as `vicuna:7b` and `vicuna:13b` but for the time being, you can access the models with these tags.
