### ISSUE TITLE
error on macos

### ISSUE THREAD

**Issue by Fungungun** [jmorganca/ollama#277]
~  ollama run llama2                                   ABRT х  base Py  13:56:30
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /usr/local/bin/ollama
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal

[1]    8409 abort      ollama run llama2

**Comment by mxyng** [comment]
Can you provide your system information? i.e. what version of MacOS, the type of chip (Intel or Apple Silicon), and how much memory. This information can all be found in the `About This Mac` windows on the top left of your UI.

**Comment by Fungungun** [comment]
![image](https://github.com/jmorganca/ollama/assets/24078180/7449e394-8b1f-4ea8-8a40-c4300c98dd3c)

**Comment by helxsz** [comment]
my os version is 11.7.8 and I encountered a similar issue.

dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /usr/local/bin/ollama
  Expected in: /usr/lib/libc++.1.dylib

is it because of the OS incompatibility, any ideas how to get around in the current version?

**Comment by beckettgithub** [comment]
I had the same issue on 10.15.7.  Any fixes yet?
<img width="586" alt="Screen Shot 2023-08-10 at 12 04 25 PM" src="https://github.com/jmorganca/ollama/assets/97408285/57913c13-e8f2-4074-95ae-aebfbc9b9f8a">

**Comment by djamshed** [comment]
same issue on Mac v11.4

<img width="571" alt="Screen Shot 2023-08-11 at 2 20 05 PM" src="https://github.com/jmorganca/ollama/assets/223121/cc2bd782-fbe1-413e-9190-45a508db29ed">

**Comment by larsr** [comment]
me too, at macOS Big Sur, 11.7.6

**Comment by felideon** [comment]
Was experiencing the [same](https://github.com/jmorganca/ollama/issues/277#issuecomment-1671053173) on macOS Big Sur (11.7.8) and upgrading to Ventura (13.5.1) fixed the issue for me. Currently seeing this instead of the error:

```
pulling manifest
pulling 8daa9615cce3...  55% |██████████████████████████                      | (2.1/3.8 GB, 14 MB/s) [2m32s:1m59s]
```

**Comment by lshgdut** [comment]
> 

I have the same issue

**Comment by lshgdut** [comment]
same issue on Mac 10.15.7
<img width="587" alt="image" src="https://github.com/jmorganca/ollama/assets/1192527/4f48f65c-1500-46e6-af3d-3468a6e372d0">

**Comment by lshgdut** [comment]
same issue on Mac 10.15.7
<img width="587" alt="image" src="https://github.com/jmorganca/ollama/assets/1192527/22939a1a-2143-43a8-8dca-85fe318340b9">

**Comment by dauith** [comment]
Same situation as the original poster; the only information I can add that might be useful is that this is still happening with Ollama 0.0.16

(By "same situation", I mean really the same :) -- MacOS 10.15.7, MacBook Pro 16-inch 2019, Intel, 32 GB RAM, same Symbol not found: 

$ ollama -v
dyld: Symbol not found: _OBJC_CLASS_$_MTLComputePassDescriptor
  Referenced from: /usr/local/bin/ollama
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal

Abort trap: 6

**Comment by dauith** [comment]
Just validating: it now executes in my environment (Catalina):

$ ollama --version
ollama version 0.0.18

Now to try actually running some models ;)
