### ISSUE TITLE
ollama + LlamaIndex

### ISSUE THREAD

**Issue by jowamedia** [jmorganca/ollama#278]
Verry nice and easy to use Ollama.

Is it planned to use it with LlamaIndex ?
It would be verry nice to index our local documents (and others) ;-)

**Comment by sqpollen** [comment]
Would be great to see this - or info on how to get Llamindex working with the Ollama models.

**Comment by Satyam7166-tech** [comment]
@sqpollen , pls update if you find a way to indiuce streaming.

**Comment by mchiang0610** [comment]
The python parts are officially out!! https://gpt-index.readthedocs.io/en/latest/examples/llm/ollama.html 

Closing this issue. Please feel free to join our discord to discuss more or if you run into more issues!

**Comment by jamesbraza** [comment]
```python
from langchain.embeddings import OllamaEmbeddings
from llama_index import ServiceContext
from llama_index.llms.ollama import Ollama

service_context = ServiceContext.from_defaults(
    llm=Ollama(model="llama2:13b"),
    embed_model=OllamaEmbeddings(model="llama2:13b"),
)
```

Nice work!  A full Ollama stack 🦙
