### ISSUE TITLE
Consider a non streaming api for `/api/generate`

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#281]
If `Content-Type: application/json` is set, we should consider returning a single large json object vs an event stream. This would be an elegant design as there are no new flags

**Comment by priamai** [comment]
Please please please! Also I would like to see at least temperature and max tokens available in the API request and as settings in the model.

![image](https://github.com/jmorganca/ollama/assets/57333254/da558a11-cd48-4c66-b6f9-14db08436459)

**Comment by BruceMacD** [comment]
Hi @priamai, you can actually set temperature through an API option right now, I'll have to make a separate issue for max tokens, I dont think we take that.

Here's an example of setting temperature in the API:
```
curl -X POST -H "Content-Type: application/json" -d '{
    "model": "llama2",
    "prompt": "why is the sky blue",
    "options": {
      "temperature": 1
    }
}' 'localhost:11434/api/embeddings'
```

Here is an example of setting temperature in a Modelfile:
```
FROM llama2
PARAMETER temperature 1
```
```

**Comment by samilao101** [comment]
So is the API able to handle non-stream requests right now?

**Comment by SabareeshGC** [comment]
@samilao101  here is an example 
```

curl --location 'http://localhost:11434/api/generate' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
  "model": "mistral",
  "prompt": "Why is the sky blue?"
}'
```
