### ISSUE TITLE
CORS requests don't work when origin is `0.0.0.0`

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#282]
When connecting to `localhost:11434` from a host served on `0.0.0.0`, requests are blocked due to CORS checks – which are important to have, but we should consider opening them up to `0.0.0.0` as well

**Comment by Kylejustknows** [comment]
OMG, running Ollama is so easy, but connect to it is so hard and require super deep advanced network/server/html knowledge.

There are tons of posts all asking the same thing.

I consider myself a pretty good old-school server manager. I spent like 2 hours tuning the env OLLAMA_ORIGINS and the caddy + HTML on a windows server, still getting the CORS. Now trying to setup a local proxy to forward the stupid thing.

If running a non-standard service (simple handmade etc.) trying to connect to Ollama, it is a nightmare!

Could Ollama just remove all the CORS restrict things, just run as a plaint service, let users handle their network port security etc please?
