### ISSUE TITLE
Add downloaded models to local list

### ISSUE THREAD

**Issue by jkleckner** [jmorganca/ollama#287]
Either implement or document how to add a downloaded model to be available locally.

**Comment by technovangelist** [comment]
hi @jkleckner can you clarify this? You can list all the pulled models using the `list` command. so `ollama list`, or in the repl, use the `/list` slash command.

**Comment by jkleckner** [comment]
My apologies for being to cryptic.  I think I found out how, since the Modelfile can reference a local file downloaded from a model card and will add it to the list of available models with `create`.

**Comment by AdityaSher** [comment]
hey can you share more info on this @jkleckner ?

**Comment by AdityaSher** [comment]
> hi @jkleckner can you clarify this? You can list all the pulled models using the `list` command. so `ollama list`, or in the repl, use the `/list` slash command.

hey I already have ggml_q4_0s downloaded can I add them directly? or ollama runs on f16 directly?

**Comment by jkleckner** [comment]
> 



> hey can you share more info on this @jkleckner ?

Download a compatible model then copy an existing examplel
Create the Modelfile with a the parameter:   MODEL  dirname/modelname.ggml.bin
Then ./allama create Modelfile
