### ISSUE TITLE
create a model with body content

### ISSUE THREAD

**Issue by priamai** [jmorganca/ollama#315]
Hi there,
when we create a model via the API POST we should be able to include the string file inside the body request.
Otherwise is cumbersome to provide the file separately.

**Comment by BruceMacD** [comment]
Just for clarification, you're looking for HTTP file upload?

**Comment by priamai** [comment]
Hi, I would prefer a POST method with body text/plain type. It will be easier to call via Rest API clients.Ph.D. Paolo Di ProdiCo-Founder and CEOPriam Cyber AI ltd ---- On Thu, 10 Aug 2023 20:12:26 +0100  ***@***.***  wrote ----
Just for clarification, you're looking for HTTP file upload?

**Comment by technovangelist** [comment]
We are looking into this. We will let you know when we have a solution.
