### ISSUE TITLE
Re-use already loaded model if only the prompt changes

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#337]
If only the prompt (or other model-independent data) changes, then the model should stay loaded vs being reloaded

**Comment by technovangelist** [comment]
Use cases include:
Modelfile development: As I am figuring out the right prompt, i am creating and running the same thing over and over with just a new prompt
Asking a question to different models: I might have a collection of models that are based on the same base model but with different prompts and parameters.
