### ISSUE TITLE
Cleaning the context

### ISSUE THREAD

**Issue by toto83fr** [jmorganca/ollama#342]
Hi,

AFAIK it is impossible to clean the context when a model is running. Is there plans to implement this function?

**Comment by mchiang0610** [comment]
@toto83fr Thanks for submitting this. Do you mind elaborating a little bit more on what you are looking to do? Looking at the comment, I assume you're doing this on the CLI instead of using the Ollama API?

**Comment by toto83fr** [comment]
Yes, to start a new conversation without closing the terminal and re-running the model.

**Comment by technovangelist** [comment]
Thanks for submitting. We will keep looking into this to see if we can achieve what you are looking for.

**Comment by mchiang0610** [comment]
@toto83fr 

Sorry for the delay in getting back to you. You shouldn't need to close the terminal, but if you do want a new session on the CLI, you do need to do ollama run again. 

If you use the API, you will be able to just 'clean' the context. 

Please let me know if this helps. Closing this for now.
