### ISSUE TITLE
crash on allocated size greater than the recommended max working set size

### ISSUE THREAD

**Issue by BruceMacD** [jmorganca/ollama#352]
When trying to load a large context window ollama crashed due to llama.cpp throwing an exception:
```
size =   160.00 MB, (12018.69 / 10922.67), warning: current allocated size is greater than the recommended max working set size
ggml_metal_graph_compute: command buffer 0 failed with status 5
GGML_ASSERT: ggml-metal.m:1177: false
SIGABRT: abort
PC=0x1a0f58724 m=10 sigcode=0
signal arrived during cgo execution
```

To reproduce:
- download a 16K model
```
FROM llongma-2-7b.ggmlv3.q4_0.bin
PARAMETER num_ctx 16000
TEMPLATE """
{{ .Prompt }}
"""
```

Specs:
<img width="277" alt="image" src="https://github.com/jmorganca/ollama/assets/5853428/f547523e-af64-46c6-9af0-82e81041d328">

**Comment by jmorganca** [comment]
This should be fixed in https://github.com/jmorganca/ollama/releases/tag/v0.0.18 but feel free to re-open otherwise!
