### ISSUE TITLE
`ollama pull` doesn't start mac app if it's not running

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#361]
Calling `ollama run` will start the Mac app if it's not running and if the `ollama` is contained in `Ollama.app`, but `ollama pull` doesn't seem to do this

**Comment by t3r-cni** [comment]
Is this issue fixed or is there only a problem on M1/M2 macs? It works on my intel mac machine.

**Comment by jmorganca** [comment]
It does! Marking this as fixed 😊
