### ISSUE TITLE
nous-hermes wrong model name?

### ISSUE THREAD

**Issue by carbocation** [jmorganca/ollama#365]
The README currently says:

https://github.com/jmorganca/ollama/blob/5ee611642049e9e4b8facb865325b33cb7343f06/README.md?plain=1#L42

But that pulls a 3GB model. Shouldn't this instead be suffixed with `:13b` like so?

| Model                    | Parameters | Size  | Download                        |
| ------------------------ | ---------- | ----- | ------------------------------- |
 | Nous-Hermes              | 13B        | 7.3GB | `ollama pull nous-hermes:13b`       |

**Comment by mchiang0610** [comment]
Hey @carbocation, sorry about the confusion. You are totally correct. The default will pull the 7b model which is 3.8GB 

more nous-hermes models here: 
https://ollama.ai/library/nous-hermes/tags

just fixed this in the readme as well: 
https://github.com/jmorganca/ollama/pull/367
