### ISSUE TITLE
Can we optimize performance with the Apple M1 Max's 32-core GPU and Neural Engine?

### ISSUE THREAD

**Issue by pascalandy** [jmorganca/ollama#373]
Hello everyone,

I'm keen to explore ways to maximize the efficiency of my robust machines. It appears that Ollama currently utilizes only the CPU for processing.

I'm wondering if there's an option to configure it to leverage our GPU. Specifically, I'm interested in harnessing the power of the **32-core GPU** and the **16-core Neural Engine** in my setup.

Considering the **specifications** of the Apple M1 Max chip:

- 10-core CPU with 8 performance cores and 2 efficiency cores
- 32-core GPU
- 16-core Neural Engine
- 400GB/s memory bandwidth

Media engine
- Hardware-accelerated H.264, HEVC, ProRes, and ProRes RAW
- Video decode engine
- Two video encode engines
- Two ProRes encode and decode engines

Cheers!

**Comment by technovangelist** [comment]
Are you downloading the program from the download button on ollama.ai? It should automatically use the GPU. When you right click on the app in /Applications, what version does it say it is?

**Comment by pascalandy** [comment]
yes
> Are you downloading the program from the download button on ollama.ai?

v 0.0.14

**Comment by jkleckner** [comment]
Take a look at the brilliant "Apple Silicon top" implementation [1].
To get the metrics, you will have to trust it with `sudo asitop` so it is  up to you to take that risk.
To install is as simple as `pip install asitop`.

[1] https://github.com/tlkh/asitop

**Comment by jkleckner** [comment]
And, by the way, you can see the max use of GPU and as a bonus see the peak power usage.
With llama2:70b, I see about 31W max power for cpu/gpu/ane (ane never seems used by anything I do).
The 70b model uses around 32GB of memory
Compare this with an nVidia card in a machine with TDP of around 400W.
The Apple silicon is about 1/8 the perf at 1/15 the power, very much ballpark.

**Comment by pascalandy** [comment]
I didn't tried the 70b models as I was sure they would choke the system. Now I'm curious!

**Comment by Nipol** [comment]
When using the 70b model, I observed that the CPU was utilized when sending my messages and waiting for a response, while the GPU was activated during the answer generation process. However, I'm uncertain whether this setup is functioning correctly.

**Comment by technovangelist** [comment]
Hi @pascalandy is your question answered? If so, can you go ahead and close? If not answered, how can we help further?

**Comment by jkleckner** [comment]
Yes, GPU is used for inference.   You can increase the default session duration from 5 to 60 minutes [1] to ensure that you will reuse the session and buffers while you are testing.  If you do that, you should find that it can be GPU bound rather than CPU, which is used for setup.  Of course, only if you want to have such a long default session!

[1] https://github.com/jmorganca/ollama/blob/e3054fc74e2101de8416976c2dd63e2796081061/api/types.go#L330nn

**Comment by jmorganca** [comment]
Thanks for creating an issue! Going to close this for the time being, however do know that I am keeping an eye on all the improvements CoreML (which will run models on CPU+GPU+Neural Engine) as a candidate way to run models faster

**Comment by RooSoft** [comment]
Hello, I'm Marc, 5 months in the future...

I'd like to know the status of CoreML and Neural Engine development. Considering buying a powerful Mac Mini or Mac Studio to run models as a headless server.

**Comment by Mecil9** [comment]
I have the same question. When I run ollama on apple M1 Max. My activity monitor shows 100% CPU usage and 0% GPU usage, and after running for a while ollama becomes unresponsive. Don't know what caused it.

**Comment by shiva404** [comment]
@Mecil9 if you have installed with brew, it might be using older version of ollama. Try downloading from [Download](https://ollama.com/download/Ollama-darwin.zip) that should resolve it, at least it solved for me.

**Comment by qdrddr** [comment]
Idea/Feature request to add CoreML so Apple Neural Engine can be utilized alongside GPU.
https://github.com/ollama/ollama/issues/3898
