### ISSUE TITLE
Whether the integration of llama2-chinese is supported

### ISSUE THREAD

**Issue by cypggs** [jmorganca/ollama#386]
https://chinese.llama.family/
https://github.com/FlagAlpha/Llama2-Chinese

**Comment by mchiang0610** [comment]
Hey thank you for bringing this up. Will try to quantize these and upload it. The source is on: 

https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat
https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat-LoRA
https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat
https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat-LoRA

**Comment by jmorganca** [comment]
Seems like we're missing the 7B models from the [library](https://ollama.ai/library/llama2-chinese)

**Comment by mchiang0610** [comment]
@cypggs Llama 2 chinese is available: 

https://ollama.ai/library/llama2-chinese 

Try the 7B model: 
`ollama run llama2-chinese:7b-chat-q4_0` 

13B model: 
`ollama run llama2-chinese:13b-chat-q4_0`

**Comment by mchiang0610** [comment]
I'll close this for now. If you run into any issues or have feedback, please feel free to reopen, contact us, or just reach out! 

Thank you
