### ISSUE TITLE
Chat with documents

### ISSUE THREAD

**Issue by mohdyasa** [jmorganca/ollama#388]
Is it possible to chat with documents (pdf, doc, etc.) using this solution?

**Comment by gusanmaz** [comment]
You could use LangChain with Ollama for this purpose. There is a tutorial (https://github.com/jmorganca/ollama/blob/main/docs/tutorials/langchainpy.md) that could be helpful in the repo.

You could also check out LangChain's Ollama class documentation (https://python.langchain.com/docs/integrations/llms/ollama).

**Comment by mchiang0610** [comment]
Yes, there is also an example using a modified version of privateGPT to use Ollama. Code example here: 

https://github.com/jmorganca/ollama/tree/main/examples/privategpt

**Comment by mchiang0610** [comment]
I will close this issue for now. If you need any help or run into anything, feel free to re-open or create another issue. Thx!
