### ISSUE TITLE
How to know which model(s) to use?

### ISSUE THREAD

**Issue by burggraf** [jmorganca/ollama#404]
How can I learn about what each main model does, and when it's appropriate to use each one?  Also, there are many versions of each model, and how do I figure out which one to download and use?

I've looked at a lot of these models on the HuggingFace site, but there's often little or no signification background information that tells me anything useful about the model.   I'm pretty lost here.

**Comment by mchiang0610** [comment]
Hi @burggraf we're starting to add overview to the models. It depends on your specific use case, but for most general tasks, I'd recommend Meta's Llama 2 models. 

https://ollama.ai/library/llama2

**Comment by burggraf** [comment]
Understood -- but it's certainly confusing to have so many choices when there's no way to distinguish how to choose intelligently.  Plus there's even a lot of confusion over **which** Llama 2 model to use and for what purpose(s).  I also understand this is more of a HuggingFace problem.

**Comment by burggraf** [comment]
That'll be awesome once there's anything written in the overviews :)  Looking forward to that.

**Comment by burggraf** [comment]
I guess the only one so far that really answers the question "Why should I use THIS model?" is in the overview for MedLlama2.  I'd like to see more helpful info like this:

MedLlama2 by llSourcell (Siraj Raval) is a Llama 2-based model trained with [medalpaca/medical_meadow_medqa](https://huggingface.co/datasets/medalpaca/medical_meadow_medqa) **to be able to provide medical answers to questions. It is not intended to replace a medical professional, but to provide a starting point for further research.**

**Comment by technovangelist** [comment]
Many of them are general use. Medllama and WizardMath are the only ones that are tuned for a specific use. You really just have to try them to see what works in your use case.

**Comment by jkleckner** [comment]
In the case of codellama, TheBloke has annotated size/quality tradeoffs for the quantizations here.
Note the GGUF appears to be completely deprecating GGML in llama.cpp as of August 21?

nhttps://huggingface.co/TheBloke/CodeLlama-34B-GGUF

**Comment by mchiang0610** [comment]
@burggraf @PaulWoitaschek @jkleckner 

Overviews are available now in the model library: 
example for llama 2 https://ollama.ai/library/llama2 

code llama https://ollama.ai/library/codellama 
medllama https://ollama.ai/library/medllama2 

and more here: https://ollama.ai/library 

There are still lots of tasks to do for organizing these. Please feel free to to create new issues regarding the specifics! Thank you. 


@PaulWoitaschek Yeah, the -text models are 'completion' models, where it'll build stories, etc to 'continue' your prompt. I definitely agree we should document this better. 

Chat models on the other hand will have a dialog with you. 

--- 

Closing this issue, but please feel free to create new ones for specific concerns, bugs, feedback etc. 

Our discord is also available here: https://discord.com/invite/ollama
