### ISSUE TITLE
Model request: brand new “Code Llama” released by Facebook

### ISSUE THREAD

**Issue by strangelearning** [jmorganca/ollama#406]
https://ai.meta.com/blog/code-llama-large-language-model-coding/

**Comment by BruceMacD** [comment]
The model is available now:
`ollama run codellama`

https://ollama.ai/library/codellama/tags

**Comment by technoplato** [comment]
They ... just .. announced it you guys are the best!!!

Side quest: what does the process for adding a new mode look like? I know we can create model files but that is for a slightly different use case, right?

**Comment by BruceMacD** [comment]
Right now we are hand-curating the models, but soon you'll be able to push whatever base model you want.

Process looks something like this:
1. Download/create/train a model.
2. Quantize the model into a format ollama can run (gguf or ggml) right now.
3. Create a model file using the model binary.
4. Push to ollama's registry.

**Comment by technoplato** [comment]
Thanks for detailing out @BruceMacD and for everyone's hard work who's a part of this project.
