### ISSUE TITLE
Custom model based on codellama just outputs blank lines

### ISSUE THREAD

**Issue by tomduncalf** [jmorganca/ollama#409]
Hi, super cool project, impressed how easy it was to get started!

I created a custom model based on codellama with a system message explaining its task, but when I run it with my input, the model just infinitely outputs blank lines. 

I saw on a [comment on Hacker News](https://news.ycombinator.com/item?id=37252690) that this was a more general problem with codellama until you fixed it, so I wondered if you had any specific thoughts or advice on what might be causing this?

Thanks!

**Comment by BruceMacD** [comment]
Hey @tomduncalf, we tried a few things. The model seems to be pretty sensitive to configuration.

What seemed to help the most with stability was setting the rope frequency base. Here is what that looks like in a Modelfile:
```
PARAMETER rope_frequency_base 1000000
```

It also seemed pretty sensitive to white-space at the end of the prompt. Here's an example Modelfile you can try working from that will get our configuration by default:
```
FROM codellama
TEMPLATE """
[INST] {{ if and .First .System }}<<SYS>>{{ .System }}<</SYS>>

{{ end }}{{ .Prompt }} [/INST]
"""
SYSTEM """
Provide answers in JavaScript
"""
```

**Comment by tomduncalf** [comment]
Hey @BruceMacD, that seems to have helped! Thanks very much :)

Out of interest, where can I find the templates you use internally?

Thanks,
Tom

**Comment by BruceMacD** [comment]
@tomduncalf 

It will be in each library's description soon at https://ollama.ai/library

The other option (which works right now) is to download the model, and output the model info during an interactive session.
```
$ ollama run codellama
>>> /help
commands:
  /help
  /list
  /set
  ├── history
  ├── nohistory
  ├── verbose
  ├── quiet
  ├── mode
  ├────── vim
  ├────── emacs
  ├────── default
  /show
  ├── license
  ├── system
  ├── template
  /exit
  /bye

>>> /show template
[INST] {{ if and .First .System }}<<SYS>>{{ .System }}<</SYS>>
```

Hope that helps.

**Comment by tomduncalf** [comment]
Ooh, nice. It does help! Thanks :)
