### ISSUE TITLE
Discard misinformation in model

### ISSUE THREAD

**Issue by Muhammad-1990** [jmorganca/ollama#414]
How do I get a model to dispose information I deem to be incorrect.

Some date about my religion is incorrect in my opinion. For my personal use I would like the model to correspond with my opinion and not the data it has.

Do I correct it in a prompt?
Do I correct it by providing an embedding?
Should I use a doc that contains my opinions? 
Do I retrain/fine tune the model?
Do I use a censored model that excludes religious datasets?

Are there any base models that do not have religious data?

do I build my own model?

thanks,

**Comment by mchiang0610** [comment]
Hey @Muhammad-1990 thank you for sending this in. 
- You can use prompts to try to guide it 

The best will be for you to build your own model, of course, coming up with the data, and the compute resources will be hard. 

Thanks!
