### ISSUE TITLE
?allow for model files to be located in a different location than ~/.ollama?

### ISSUE THREAD

**Issue by vegabook** [jmorganca/ollama#419]
On my M2 mac, Ollama stores pulled models in `~/.ollama/models` and its security keys in `~/.ollama`. Is it possible to specify an alternative directory? My interest is in compartmentalizing ollama as much as possible into a single directory (happen to be using nix where [ollama is available in the unstable channel](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=ollama), but that's an aside).

**Comment by BruceMacD** [comment]
Thanks for your feedback, this is on our radar. Consolidating this issue into #153 to keep things organized.
