### ISSUE TITLE
`Error: Post "http://localhost:11434/api/generate": EOF` with long propmts with phind-codellama

### ISSUE THREAD

**Issue by tomduncalf** [jmorganca/ollama#422]
It seems like if you provide a long prompt (I was using one of 1,000ish tokens according to OpenAI tokenizer) with this model, you get an error `Error: Post "http://localhost:11434/api/generate": EOF`. It may or may not relate to the contents of the prompt as well as the length

**Comment by hmottestad** [comment]
Here is an example:

```
ollama run phind-codellama " Finished the method marked as TODO in the following Java code:\n\n\npackage org.eclipse.rdf4j.sail.shacl.ast.constraintcomponents;\n\nimport java.util.Collections;\nimport java.util.HashSet;\nimport java.util.List;\nimport java.util.Set;\n\nimport org.eclipse.rdf4j.model.IRI;\nimport org.eclipse.rdf4j.model.Literal;\nimport org.eclipse.rdf4j.model.Model;\nimport org.eclipse.rdf4j.model.Resource;\nimport org.eclipse.rdf4j.model.Value;\nimport org.eclipse.rdf4j.model.vocabulary.SHACL;\nimport org.eclipse.rdf4j.sail.shacl.SourceConstraintComponent;\nimport org.eclipse.rdf4j.sail.shacl.ValidationSettings;\nimport org.eclipse.rdf4j.sail.shacl.ast.SparqlFragment;\nimport org.eclipse.rdf4j.sail.shacl.ast.StatementMatcher;\nimport org.eclipse.rdf4j.sail.shacl.ast.StatementMatcher.Variable;\nimport org.eclipse.rdf4j.sail.shacl.ast.ValidationApproach;\nimport org.eclipse.rdf4j.sail.shacl.ast.ValidationQuery;\nimport org.eclipse.rdf4j.sail.shacl.ast.paths.Path;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.BulkedExternalLeftOuterJoin;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.EmptyNode;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.GroupByFilter;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.PlanNode;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.PlanNodeProvider;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.ShiftToPropertyShape;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.TrimToTarget;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.UnBufferedPlanNode;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.UnionNode;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.Unique;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.ValidationTuple;\nimport org.eclipse.rdf4j.sail.shacl.ast.planNodes.ValueInFilter;\nimport org.eclipse.rdf4j.sail.shacl.ast.targets.EffectiveTarget;\nimport org.eclipse.rdf4j.sail.shacl.wrapper.data.ConnectionsGroup;\nimport org.eclipse.rdf4j.sail.shacl.wrapper.data.RdfsSubClassOfReasoner;\n\npublic class HasValueConstraintComponent extends AbstractConstraintComponent {\n\n	private final Value hasValue;\n\n	public HasValueConstraintComponent(Value hasValue) {\n		this.hasValue = hasValue;\n	}\n\n	@Override\n	public void toModel(Resource subject, IRI predicate, Model model, Set<Resource> cycleDetection) {\n		model.add(subject, SHACL.HAS_VALUE, hasValue);\n	}\n\n	@Override\n	public SourceConstraintComponent getConstraintComponent() {\n		return SourceConstraintComponent.HasValueConstraintComponent;\n	}\n\n	@Override\n	public ConstraintComponent deepClone() {\n		return new HasValueConstraintComponent(hasValue);\n	}\n\n	@Override\n	public PlanNode generateTransactionalValidationPlan(ConnectionsGroup connectionsGroup,\n			ValidationSettings validationSettings, PlanNodeProvider overrideTargetNode, Scope scope) {\n\n		StatementMatcher.StableRandomVariableProvider stableRandomVariableProvider = "
```

**Comment by matiasdominguez** [comment]
I'm getting the same error without a long prompt, even a short `hey` will trigger the same `Error: Post "http://localhost:11434/api/generate": EOF` for me. Specs: 2021 M1 Pro / 32 GB RAM.

**Comment by hmottestad** [comment]
> I'm getting the same error without a long prompt, even a short `hey` will trigger the same `Error: Post "http://localhost:11434/api/generate": EOF` for me. Specs: 2021 M1 Pro / 32 GB RAM.

If you installed Ollama through homebrew then you might have an old version. Have you tried with downloading the newest version directly from https://ollama.ai ?

**Comment by matiasdominguez** [comment]
Thanks @hmottestad. That actually fixed it, I thought the homebrew version was the latest one.

**Comment by hmottestad** [comment]
This seems to be fixed in the latests v0.0.18 :)

**Comment by jmorganca** [comment]
Fantastic. Closing this for now, but feel free to re-open if we see it again.

**Comment by Alpha-404** [comment]
![image](https://github.com/jmorganca/ollama/assets/63340001/f372eced-ac56-436b-adf6-048f45723fb2)
installer seems to give the same error

**Comment by gokulkumar3198** [comment]
I am also facing the same EOF error, could not figure out the problem. I have tried with the latest docker image as of today and v0.1.18 also.
**Error: Post "http://0.0.0.0:11434/api/generate": EOF**

**Comment by nps798** [comment]
same here

**Comment by blackandcold** [comment]
Observed with 
dolphin-mixtral:latest 
and 
llama2-uncensored:70b

installing fresh did not change anything. 
I am trying to run some on ROCm, but did not add any parameters yet.

EndeavourOS but not the repository version, the latest from the installer.

`
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 routes.go:930: Listening on 127.0.0.1:11434 (version 0.1.20)
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 shim_ext_server.go:142: Dynamic LLM variants [cuda rocm]
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:88: Detecting GPU type
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:203: Searching for GPU management library libnvidia-m>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:248: Discovered GPU libraries: [/usr/lib/libnvidia-ml>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:259: Unable to load CUDA management library /usr/lib/>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:259: Unable to load CUDA management library /usr/lib6>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:203: Searching for GPU management library librocm_smi>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:248: Discovered GPU libraries: [/opt/rocm/lib/librocm>
Jän 20 19:31:28 XX-eOS ollama[26605]: 2024/01/20 19:31:28 gpu.go:104: Radeon GPU detected

`

**Comment by fabianslife** [comment]
Same problem here, giving it a prompt longer than two words immediately results in: Error: Post "http://127.0.0.1:11434/api/generate": EOF

**Comment by alexhegit** [comment]
I go a problem like this one with log : 

Error: Post "http://localhost:11434/api/chat": EOF

**Comment by mehdiataei** [comment]
Still happening

**Comment by AntDX316** [comment]
I have the issue on gemma:7b but mistral one works?

**Comment by jafarzzz** [comment]
Facing the same issue with gemma:7b. Other models are working fine. I updated the ollama. Still the problem persists.

**Comment by serhanylmz** [comment]
have the same issue with gemma:7b, can confirm

**Comment by jafarzzz** [comment]
I fixed it by upgrading the ollama to 0.1.26. You wont be able to do it from the application. Uninstall the ollama and download the latest one from: https://ollama.com/

**Comment by fithisux** [comment]
In Windows 10PRO after calling

```
resp = gemma_2b.complete("Who is Paul Graham?")
print(resp)
```

I have the same error. In logs

```
[GIN] 2024/02/28 - 13:21:17 | 404 |         709µs |       127.0.0.1 | POST     "/api/generate"
```


System:

Edition	Windows 10 Pro
Version	22H2
Installed on	‎19/‎1/‎2024
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by BestMat** [comment]
Same here, any solution for this problem?
