### ISSUE TITLE
llamma.cpp breaking change deprecating GGML in favor of GGUF

### ISSUE THREAD

**Issue by jkleckner** [jmorganca/ollama#423]
Note that the upstream llama.cpp project has now completely deprecated GGML in favor of GGUF [1].

How should the repository and user models adapt to this?

[1] https://github.com/ggerganov/llama.cpp/pull/2398

**Comment by BruceMacD** [comment]
We're going to be adding the gguf runner very soon. We're going to make the transition such that Ollama can still run both gguf and older ggml formats, this means the transition will not require any action on the user's part.

**Comment by jkleckner** [comment]
Cool, thanks!
