### ISSUE TITLE
Error: Head "http://localhost:11434/": dial tcp: lookup localhost: no such host

### ISSUE THREAD

**Issue by DreamDevourer** [jmorganca/ollama#424]
This is very odd, but after updating to the latest v0.0.16, this error started showing when I use ollama. For example,if I try to run a simple "ollama list" this shows up:

Error: Head "http://localhost:11434/": dial tcp: lookup localhost: no such host

I've cleaned any DNS traces, hosts file is untouched and there are no firewall conflicts.

What could be causing this issue? Is it only happening on my end?

**Comment by jmorganca** [comment]
Hi @DreamDevourer sorry you hit this error, and thanks for creating an issue. We'll work on fixing this in the next update. In the meantime if possible make sure your `/etc/hosts` file has an entry like:

```
127.0.0.1       localhost
```
