### ISSUE TITLE
UTF-8 characters 

### ISSUE THREAD

**Issue by arpecop** [jmorganca/ollama#431]
How to render properly such characters , is this per-model issue ... or font related ?
![Screenshot 2023-08-27 at 15 54 34](https://github.com/jmorganca/ollama/assets/168974/6cc84d4a-f438-467f-bf7c-207ec45ee6fe)

**Comment by jmorganca** [comment]
Thanks for creating an issue. I've seen this too – may I ask which model this is?

**Comment by arpecop** [comment]
Thanks for creating such sophisticated software  @jmorganca 
`llama2` was tested here , I got those running on my old home server ,  the process is few extra steps than for those using Mac , why you are hesitant to claim Ollama is multi-platform

**Comment by jmorganca** [comment]
@arpecop great question. Want to make sure Ollama has fast, easy GPU support on Linux and Windows 😊 . Glad to hear you got it working

**Comment by mchiang0610** [comment]
@arpecop Sorry about the issue! We do currently support UTF-8; I'm not sure what the specific character type is, or if it's just the model outputting wrong data, or if it's a font that's not available in the terminal. 

We will keep this in mind as we test future releases. If you don't mind, I'll close this for now. 

If you have more information, please feel free to reopen! Thank you so much!
