### ISSUE TITLE
Incorrect size displayed for codellama:34b-code-q4_0 on ollama.ai

### ISSUE THREAD

**Issue by spqw** [jmorganca/ollama#435]
It seems like there is a typo on the following url https://ollama.ai/library/codellama/tags, where the displayed model size for `34b-code-q4_0` is 6.7 GB. When downloading it, it appears to be 19 GB instead. 
<img width="996" alt="image" src="https://github.com/jmorganca/ollama/assets/101190846/0d32d491-6498-4b1f-9a65-06bf7a8458e4">

**Comment by mxyng** [comment]
This has been fixed
