### ISSUE TITLE
Ollama embeddings LangChain integration

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#436]
It would be great combo to be able to use Ollama as both a model and embeddings back end (i.e. `langchain.embeddings.OllamaEmbeddings`) together.

**Comment by herrjemand** [comment]
@jmorganca I done it: https://github.com/langchain-ai/langchain/pull/10124 *)

**Comment by herrjemand** [comment]
Ref: #472

**Comment by jmorganca** [comment]
This is [completed](https://python.langchain.com/docs/integrations/llms/ollama) 🎉

**Comment by Sravani-ytp** [comment]
loader = TextLoader("a.txt")
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500, chunk_overlap=10)
# docs = text_splitter.split_documents(documents)
web_docs, meta = [], []
splits1 = text_splitter.split_text(str(documents))
web_docs.extend(splits1)
embeddings = OllamaEmbeddings()
query_result =embeddings.embed_query(splits1)
print(query_result[:5])

Here,nothing is printing
