### ISSUE TITLE
Document Wolfi package?

### ISSUE THREAD

**Issue by dlorenc** [jmorganca/ollama#438]
Hey!

I noticed it says there are no official downloads for Linux yet - would you be open to documenting the official Wolfi Linux package? You can see how it's packaged here: https://github.com/wolfi-dev/os/blob/main/ollama.yaml

You can install it with:

```
docker run -it cgr.dev/chainguard/wolfi-base sh
apk add ollama
```

We'll probably ship an image based on this as well, and add CUDA drivers soon.

**Comment by mchiang0610** [comment]
Thank you @dlorenc!! Would be happy to add this once we get the CUDA drivers working properly! This is the main reason preventing us to release an official version of Ollama for Linux.
