### ISSUE TITLE
commit 8bbff2df986629e5481547e913ab4de0245afb37 stops "ollama ls" from working here

### ISSUE THREAD

**Issue by xyproto** [jmorganca/ollama#447]
`go generate ./... && go build . && ./ollama ls` worked fine for previous versions, but does not work for the latest commit.

Using `git bisect`, the commit that creates this problem seems to be 8bbff2df986629e5481547e913ab4de0245afb37 (from the 28th of Aug).

Here is the error message for when it is not working:

```
panic: runtime error: slice bounds out of range [:12] with length 0

goroutine 1 [running]:
github.com/jmorganca/ollama/cmd.ListHandler(0x140004a8200?, {0x1052159e0, 0x0, 0x104a71539?})
	/Users/username/clones/ollama/cmd/cmd.go:199 +0x4e8
github.com/spf13/cobra.(*Command).execute(0x1400045bb00, {0x1052159e0, 0x0, 0x0})
	/Users/username/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x1400045a900)
	/Users/username/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/username/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/username/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
	/Users/username/clones/ollama/main.go:11 +0x54
```

**Comment by mxyng** [comment]
@xyproto did you restart the server after building from source? `ollama list` on `main` looks for a field that was added in the commit you linked so if the server hasn't been updated, it will error.

**Comment by xyproto** [comment]
@mxyng Thanks for the reply. After restarting the server, the issue disappeared. :+1:
