### ISSUE TITLE
Way to download modelfile for model, but not weights?

### ISSUE THREAD

**Issue by spott** [jmorganca/ollama#452]
I'm interested in getting the modelfile for a model as I have ggml quantized weights already and don't want to redownload (and re-store) weights, but I don't know what the system prompts are.

Where can I browse the metadata for different models without downloading them in their entirety?

**Comment by technovangelist** [comment]
We will be adding a way to see the modelfile from the website for all our models very soon.

**Comment by mxyng** [comment]
The content of Modelfiles are available on the [website](https://ollama.ai), e.g. for [falcon:7b](https://ollama.ai/library/falcon:7b), as well through the ollama cli:

```
$ ollama show --modelfile falcon:7b
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM falcon:7b

FROM /Users/michaelyang/.ollama/models/blobs/sha256:3230a638a2da7f51833ddf0f5567b9eae61a983d5e176ecc9ba451c7a4498ece
TEMPLATE """{{- if and .First .System }}
{{ .System }}
{{- end }}
User: {{ .Prompt }}
Assistant:"""
SYSTEM """"""
```
