### ISSUE TITLE
Dedicated hardware for 16b/70b models

### ISSUE THREAD

**Issue by zdeneksvarc** [jmorganca/ollama#499]
Hey guys, let's say I want to get a dedicated home server that would run `ollama serve` 13b/70b in Docker. Is there any chance to get such hardware (CPU) to achieve speed comparable to ChatGPT4? Since Ollama doesn't use GPU acceleration.

**Comment by mxyng** [comment]
We're actively working on GPU acceleration on Linux and Windows. You can follow the progress in #454 which includes GPU accelerated Docker images

**Comment by zdeneksvarc** [comment]
What a great news. This Ollama thing is awesome. Thank you.

**Comment by zdeneksvarc** [comment]
Although the answer to the OP was encouraging, I was still looking for hard data to tell me what hardware is needed to get at least 5 tok/s. For completeness here is a partial answer from the link below:

>The M1/M2 Pro supports up to 200 GB/s unified memory bandwidth, while the M1/M2 Max supports up to 400 GB/s. For example MacBook M2 Max using Llama.cpp can run 7B model with 38 t/s, 13B model with 22  t/s, and [65B model with 5 t/s](https://twitter.com/natfriedman/status/1665408927431884800).However in terms of inference speed dual setup of RTX 3090/4090 GPUs is faster compared to the Mac M2 Pro/Max/Ultra. Two RTX 4090s [can run 65b models at a speed of 20 tokens per second](https://github.com/turboderp/exllama#dual-gpu-results), while two affordable secondhand RTX 3090s achieve 15 tokens per second with Exllama. Additionally, the Mac evaluates prompts slower, making the dual GPU setup more appealing.

And here is awesome comprehensive answer: https://www.hardware-corner.net/guides/computer-to-run-llama-ai-model/
