### ISSUE TITLE
large embedded file fails on model create

### ISSUE THREAD

**Issue by BruceMacD** [jmorganca/ollama#501]
Adding a large file to an embedding may cause an unexpected error.

```
ollama crate exampleModel -f Modelfile
...
Error: unexpected end to create model
```

```
FROM codellama

SYSTEM """
You are a DND game master that reviews dice rolls and responds with JSON  in the following format: "{\"action\":\"do stuff\"}"
"""

EMBED embeds/*.txt
```

```
 2% || (4367/151236, 31 it/s) [4m59s:1h19m37s]creating model system layer
```

There shouldn’t be a limit. The buffer size may be reaching its capacity.

**Comment by fmackenzie** [comment]
I'm also experiencing this.  I've tried a number of things, including breaking down the text files into smaller chunks with overlapping chunks, updating the num_ctx value (to 4096, 8192, and 16384).  I've tried this on a VM with 32GB of RAM, and bare metal with 64GB of RAM, both on Ubuntu linux.  All have the same outcome, so I am wondering if it is tied to the total amount of content, not the size of a specific file.  The experience is consistent when specifying each file individually instead of specifying the entire folder.

**Comment by chronicblondiee** [comment]
I am also running into the same issue I have even tried spiting the large file into various different smaller files still seems to fail at some point?

I am also looking to make something DnD related and tried to import the rules as a txt file dataset but haven't been able to make it work..

below two different runs with two versions of the DnD rule set one with new lines the other with all new lines stripped I thought it would help didn't seem to make a difference 
`
ollama create dnd-gen -f ./Modelfile
parsing modelfile    
looking for model    
creating model template layer    
creating model system layer    
creating parameter layer    
creating embeddings for file /tmp/llm-model-stuff/mistral/data/DnD_Basic_rules.txt   2% |███                                                                                                                                                                                            | (892/36409, 3 it/s) [5m0s:3h46m51s]creating parameter layer

ollama create dnd-gen -f ./Modelfile
parsing modelfile    
looking for model    
creating model template layer    
creating model system layer    
creating parameter layer    
creating embeddings for file /tmp/llm-model-stuff/mistral/DnD_BasicRules_2018.txt   3% |█████                                                                                                                                                                                           | (591/18119, 2 it/s) [5m0s:2h53m35s]creating parameter layer
Error: unexpected end to create model
`

**Comment by chronicblondiee** [comment]
@vividfog I am trying your method with my data I used split -l 600 mydata.txt to split by line and just going to try run through each of the EMBED Layers.

I will note that the max number of lines I could input per EMBED txt varied in my testing anything above 800 seemed to be unstable at least on my system. Open SUSE Tumbleweed 12core Ryzen 9 5900x 64GB RAM

**Comment by BruceMacD** [comment]
Closing this for now as we removed this feature for the time being.
