### ISSUE TITLE
ollama pull llama2 error

### ISSUE THREAD

**Issue by EasonZhaoZ** [jmorganca/ollama#503]
404 Client Error: Not Found for url: https://ollama.ai/api/models

**Comment by jmorganca** [comment]
Hi @EasonZhaoZ sorry you hit this issue. It looks like you may have a very old prototype of `ollama`. Would it be possible to uninstall and it and download the current version?

```
pip uninstall ollama
```

Then the easiest way to download Ollama is to install it from here [here](https://ollama.ai/download). I've created https://github.com/jmorganca/ollama/issues/504 in case you're looking to use Ollama more tightly with Python

**Comment by EasonZhaoZ** [comment]
thanks, it works !
