### ISSUE TITLE
Loading a model from a file for embeddings not found

### ISSUE THREAD

**Issue by BruceMacD** [jmorganca/ollama#506]
Add an embeded text file to a modelfile with a model from a file may error:
```
creating parameter layer  Error: unexpected error opening model to generate embeddings: stat /Users/username/.ollama/models/manifests/registry.ollama.ai/library/latest: no such file or directory
```

**Comment by antonio-castellon** [comment]
I have the same problem running the ollama serve, and by default is not open to 0.0.0.0, apparently only to localhost is accessible.

**Comment by suoko** [comment]
> Add an embeded text file to a modelfile with a model from a file may error:
> 
> ```
> creating parameter layer  Error: unexpected error opening model to generate embeddings: stat /Users/username/.ollama/models/manifests/registry.ollama.ai/library/latest: no such file or directory
> ```

Can I ask you what you're trying to do ? You want to pass a text file to the model so that you can ask questions about that text file ?
If yes, can I ask you how you're doing it ?

**Comment by antonio-castellon** [comment]
I just relaunched the server and I'm able to send all request without issue at all
