### ISSUE TITLE
Make models directory customizable

### ISSUE THREAD

**Issue by tastycode** [jmorganca/ollama#513]
https://github.com/jmorganca/ollama/blob/45ac07cd025f9d1e84917db3f00e0f3e5651aede/server/modelpath.go#L135C7-L136C31

If you are often working with different AI packages, you know that the models add up quickly. I keep my models on an external drive. The user to at least customize this behavior with an environment variable. I am not up-to-speed on go tooling, otherwise I'd be happy to open a PR.

**Comment by justinmayer** [comment]
Dupe of #153. This should be closed to prevent issue clutter.

**Comment by mchiang0610** [comment]
Closing this for the duplicate issue #153 

Thanks @justinmayer and @tastycode
