### ISSUE TITLE
LLM falcon:text infinity loop

### ISSUE THREAD

**Issue by dcasota** [jmorganca/ollama#523]
Hi,

I was trying to run falcon, but it responds ... weired.

Setup recipe.
```
git clone https://github.com/jmorganca/ollama
cd .\ollama
mkdir ..\.ollama
go generate .\...
go build .
```

Then, start the server component of ollama.
`start "Ollama server component" ollama.exe serve`

Download the selected model.
`ollama.exe pull falcon:text`

Run the model.
`ollama.exe run falcon:text`

I've started a conversation with a simple "Hi".
The output started with listing `date.getDay();` but it didn't stop, not at 7, not at 31, and not at 365...seems an infinity loop.

<img src="https://github.com/jmorganca/ollama/assets/14890243/59f54411-f58d-4f9e-97ef-bce53cb6fedc" alt="image" width="200">

After ctrl-c, and restarting the 2nd and 3rd time a simple Hi, it doesn't list anymore getDay, but responds with extract from letters someone wrote.

What is the purpose of falcon:text?

**Comment by BruceMacD** [comment]
Hi @dcasota, the falcon:text model is a raw model that is meant for fine tuning. Quoting from the original authors:
> This is a raw, pretrained model, which should be further finetuned for most usecases. If you are looking for a version better suited to taking generic instructions in a chat format, we recommend taking a look at Falcon-7B-Instruct.

Try this instead, to run the instruct/chat Falcon model: `ollama run falcon`

**Comment by dcasota** [comment]
@BruceMacD I switched to llama2:70b for langchain-document purposes. The response quality in English is very good.

Because of the wording "text" I though that the falcon LLM is more predestinated for answer/questions constellations than other LLMs. Imho it is not.

Thank you for the quick reply and clarification. As a beginner, it is difficult to distinct between "good" and "not good" LLMs for a specific purpose. You're right. It is necessary to read the LLM thesis and answers to choose wisely.

**Comment by BruceMacD** [comment]
No worries, it is really confusing. Thanks for opening the issue!
