### ISSUE TITLE
Docs request: connecting to front end

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#538]
Hello ollama, excited to start using this!

I have a docs request:
- How to connect a front end to ollama
- Link example or suggested front ends

Thank you in advance!

**Comment by TahaScripts** [comment]
Could you elaborate on the issue? Are you describing a use-case like a chat-bot?

This project will probably help you a lot: https://github.com/ollama-ui/ollama-ui

**Comment by jamesbraza** [comment]
Yes thank you @TahaScripts, that partly answers my question.  Appreciated, and just opened a PR to link that in the `README`.

So for example, check this: https://github.com/abetlen/llama-cpp-python#web-server

> web server which aims to act as a drop-in replacement for the OpenAI API

It would be useful to document if the Ollama server already complies with any standard API formats.

It looks like there's requests (https://github.com/jmorganca/ollama/issues/278, https://github.com/jmorganca/ollama/issues/305) to add LlamaIndex and OpenAI API compatibility, so it may be that the Ollama server isn't currently compatible with any other API formats.
