### ISSUE TITLE
Request: Linux (with GPU) support

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#545]
I found Ollama to be really user friendly, and quite enjoy using it on my Mac.

I would like to use Ollama to serve our dev models, which run on AWS EC2 right now (Ubuntu 22.04 with 1+ GPUs).

The [README currently says](https://github.com/jmorganca/ollama/tree/c345053a8bf47d5ef8f1fe15d385108059209fba#download):
> Download for Windows and Linux (coming soon)

I see https://github.com/jmorganca/ollama/issues/403 is tracking Windows support. I think this can be a sister ticket to track Linux support.  Thank you in advance!

**Comment by BruceMacD** [comment]
Hi @jamesbraza thanks for opening this issue. GPU support on Linux will be in the upcoming release, I've just merged #259 as of last week into our main branch.

**Comment by jamesbraza** [comment]
Okay thanks @BruceMacD, I see https://github.com/jmorganca/ollama/pull/454 add a `Dockerfile.cuda`.  It would be good to update the `README` to mention Linux is supported.

Check https://github.com/jmorganca/ollama/issues/551 if you're interested in my beta test haha 😄
