### ISSUE TITLE
ollama is version 0.0.0

### ISSUE THREAD

**Issue by Dialga** [jmorganca/ollama#547]
I've installed version 0.0.19 but the output of `-v` is 0.0.0.
```
$ ollama -v
ollama version 0.0.0
```

**Comment by mxyng** [comment]
Where did you install ollama from?

**Comment by Dialga** [comment]
On Linux, Arch.

**Comment by mxyng** [comment]
The Arch package is community maintained. I believe it's building from source instead of downloading the prebuilt binaries from the GitHub release. It's likely the flags to set version isn't being passed

**Comment by satvikpendem** [comment]
I have the same issue, on macOS, installed via homebrew.

**Comment by technovangelist** [comment]
Homebrew is also a community maintained package. For best results, install ollama using the package at https://Ollama.ai

**Comment by Dialga** [comment]
I no longer have this problem on Arch Linux.

**Comment by shriramters** [comment]
I'm on fedora 42, using the community maintained dnf package from https://docs.fedoraproject.org/en-US/quick-docs/ollama/

```
shriram@dora:~$ ollama -v
ollama version is 0.0.0
```
