### ISSUE TITLE
Is IPv6 supported?

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#560]
With the Ollama server running:

```bash
> curl -X POST --header 'Content-Type: application/json' "http://[::1]:11434/api/generate" -d '{
  "model": "llama2:13b",
  "prompt": "Your first prompt goes here"
}'
curl: (7) Failed to connect to ::1 port 11434 after 5 ms: Couldn't connect to server
```

I am wondering, is IPv6 supported with Ollama server?

**Comment by mxyng** [comment]
Ollama listens on 127.0.0.1 by default so IPv6 requires setting OLLAMA_HOST to either any address e.g. `:11434` or explicitly IPv6 e.g. `[::1]:11434`. There's a bug with the latter which is fixed in the linked PR

**Comment by jamesbraza** [comment]
Thank you @mxyng !  Appreciated.

```bash
> export OLLAMA_HOST=":11434"
> ./ollama serve
...
2023/09/20 23:07:11 routes.go:536: Listening on 127.0.0.1:11434
```

What did you mean by:

> any address e.g. `:11434`

It seems to be using `127.0.0.1` when I set `OLLAMA_HOST=":11434"`

**Comment by mxyng** [comment]
Yes, you'll need to pull main and rebuild right now but it'll be part of the next release
