### ISSUE TITLE
Will ollama support Deci/DeciLM-6b-instruct series models in the future?

### ISSUE THREAD

**Issue by ParseDark** [jmorganca/ollama#564]
## my purpose is?

To get more faster response and reduce the cost of GPU.

Model detail: https://deci.ai/blog/decilm-15-times-faster-than-llama2-nas-generated-llm-with-variable-gqa/

live demo: https://huggingface.co/spaces/Deci/DeciLM-6b-instruct

The Deci model builds on the llama. So I think maybe we can support it. For getting better experience.

**Comment by maxkrieger** [comment]
This was never added, right? Any plans to?
