### ISSUE TITLE
Enter multiline text via stdin in non-interactive mode

### ISSUE THREAD

**Issue by tiborvass** [jmorganca/ollama#568]
https://github.com/jmorganca/ollama/issues/169 only addressed interactive mode, but not stdin via non-interactive mode

```
cat multiline_file | ollama run llama2
```

**Comment by mxyng** [comment]
Can you elaborate? Non-interactive multiline text was already possible since the shell handles the quotes

```
$ ollama run llama2 'this
quote> is
quote> a
quote> multiline
quote> prompt'
 Great, I'm ready to help! Please provide the text you would like me to read, and I will be happy to assist you.

```

**Comment by tiborvass** [comment]
@mxyng ah i see, I updated the issue to explain a little better hopefully!

**Comment by mxyng** [comment]
Ah I see. This is by design. Each line of stdin is seen as a separate prompt. See #416 for more information.

If you're trying to ingest the entire file as a single prompt, an option could be as command line arguments:

```
$ ollama run llama2 "$(cat multiline_file)"
```

**Comment by technovangelist** [comment]
Looks like this issue was addressed by Mike's comment. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
