### ISSUE TITLE
"Invalid file magic" with falcon models

### ISSUE THREAD

**Issue by vadim0x60** [jmorganca/ollama#573]
This happens every time I try to interact with a falcon model:

```
❯ ollama run falcon:40b
>>> hi
Error: invalid file magic
```

Hardware is Apple silicon with 96GB of RAM

**Comment by mxyng** [comment]
What version of ollama are you using? Falcon support was added in 0.0.19. You can check with `ollama --version`. Make sure the server has also been restarted since the upgrade

**Comment by vadim0x60** [comment]
I just ran `ollama --version` and it is 0.0.21. But then I ran `ollama run falcon:40b` and couldn't reproduce the bug. Probably the error was related to an earlier version of ollama that got updated.

**Comment by BruceMacD** [comment]
That sounds right, this error message wasn't very good but it usually shows up when trying to run Falcon on an earlier Ollama version that does not support it. Marking this as resolved for now. Let us know if the issue comes back.
