### ISSUE TITLE
How to use `num_predict`?

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#581]
From https://github.com/jmorganca/ollama/issues/318#issuecomment-1710181439, I see `num_predict` exists, and am trying to figure out how to use it.

Where are the docs on parameters like this?

More specifically, I am trying to figure out how to specify `num_predict` (and similar parameters) to the Ollama server process and/or `/generate` API calls.

**Comment by willowell** [comment]
Hello @jamesbraza!

Had a look around - looks like the docs for these parameters are in llama.cpp. For instance, here's the doc for `n_predict`: https://github.com/ggerganov/llama.cpp/tree/master/examples/main#number-of-tokens-to-predict.

I found these types for the parameters https://github.com/jmorganca/ollama/blob/main/llm/llama.go#L378 - it looks like these are out-of-sync with the ones in https://github.com/jmorganca/ollama/blob/main/api/types.go#L161?

I don't see `num_predict` used outside `types.go`.

Does this help?

**Comment by BruceMacD** [comment]
This parameter tells the LLM the maximum number of tokens it is allowed to generate. 

It's not exposed in the CLI at the moment, but you can define it directly in the body of requests make to the API at the `/generate` endpoint. Here is an example of that, setting the `num_predict` to 1.

## Request
```
curl --request POST \
     --url http://localhost:11434/api/generate \
     --header "Content-Type: application/json" \
     --data '{
         "prompt": "hi",
         "model": "llama2",
         "options": {
             "num_predict": 1
         }
     }'
```

## Response Stream
```
{
    "model": "llama2",
    "created_at": "2023-09-25T14:32:13.093801Z",
    "response": " Hello",
    "done": false
}
{
    "model": "llama2",
    "created_at": "2023-09-25T14:32:13.095352Z",
    "done": true,
    "context": [29961,25580,29962,7251,518,29914,25580,29962,29871,15043],
    "total_duration": 383724416,
    "load_duration": 1833458,
    "prompt_eval_count": 5,
    "prompt_eval_duration": 373471000,
    "eval_count": 1
}
```

**Comment by jamesbraza** [comment]
Thank you both @willowell and @BruceMacD!  Is there a relevant portion of the Ollama docs for this somewhere?  Otherwise I would gladly add this somewhere, if you could point me to the right place

**Comment by BruceMacD** [comment]
The closest documentation would be this table of parameter options in the modelfile docs. It looks like it is missing a few options now though, num_predict isn't there:
https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values

**Comment by jamesbraza** [comment]
As long as a search for `num_predict` has some matches in `docs/`, I will call it a win.

Looks like that table comes from [`Options`](https://github.com/jmorganca/ollama/blob/v0.0.21/api/types.go#L161), I will add a few entries to it shortly

**Comment by vusiernestmthuk** [comment]
Ind lunchtime and teatime for today

**Comment by vusiernestmthuk** [comment]
Lunchtime and teatime
