### ISSUE TITLE
Support speechless-llama2-hermes-orca-platypus-wizardlm-13b or Qwen-14b models

### ISSUE THREAD

**Issue by cheuk-cheng** [jmorganca/ollama#600]
Is there any plan to support recent models like speechless-llama2-hermes-orca-platypus-wizardlm-13b or Qwen-14b?  User reviews seem to indicate that they are powerful and fast even when compared with other llama2 models that have larger sizes.  Thanks.

**Comment by FairyTail2000** [comment]
Speechless works flawlessly for me. I downloaded speechless-llama2-hermes-orca-platypus-wizardlm-13b.Q4_K_M.gguf from huggingfaces and used the following modelfile:
```
FROM ./speechless-llama2-hermes-orca-platypus-wizardlm-13b.Q4_K_M.gguf
```
And then `ollama create speechless:13b-q4 -f Modelfile`. You can replace speechless:13b-q4 with whatever name you like or go with mine. You can then use it like any other model

**Comment by cheuk-cheng** [comment]
Thanks @FairyTail2000.

**Comment by pdevine** [comment]
@FairyTail2000 do you want to push it to ollama.ai? You can DM me on Discord and I can give you the details.

**Comment by FairyTail2000** [comment]
Pushed to rasun/speechless-llama2-hermes-orca-platypus-wizardlm:13b-q4

**Comment by jmorganca** [comment]
@FairyTail2000 awesome - will close this for now!
