### ISSUE TITLE
Getting permission denied when attempting to create a model 

### ISSUE THREAD

**Issue by DeanKamali** [jmorganca/ollama#613]
ollama version: v0.1.0

**Steps to Reproduce:**

- Ran` curl https://ollama.ai/install.sh | sh` to install ollama.
- Navigated to ollama/examples/devops-engineer/.
- Executed `ollama create devops-engineer -f ./Modelfile`.

Error Encountered:
`couldn't open modelfile '/root/ollama/examples/devops-engineer/Modelfile'. Error: failed to open file: open /root/ollama/examples/devops-engineer/Modelfile: permission denied.`

![image](https://github.com/jmorganca/ollama/assets/1252959/4da3d481-87f3-4472-aba8-97ceb71df8f0)
After trying to set the Model file with 755 in my WSL environment, I still couldn't get it to work. I'm wondering if there is a bug with the recent Linux release.

**Comment by syhw** [comment]
You need to be in a folder accessible/browsable by the `ollama` user. A solution is to make your home traversable (`a+x`).

**Comment by AlexandrePoisson** [comment]
I am also using WSL2, ubuntu, and I get the same message, even afer chmod a+x /home/, chmod a+x /home/modelfiles and chmod 777 the modelfile, 

`couldn't open modelfile '/home/alexandre/modelfiles/Modelfile'  Error: failed to open file: open /home/alexandre/modelfiles/Modelfile: permission denied`

Not sure the version I am using, maybe a ollama version command would be usefull. I've installed it the 01 oct. 2023 using 
`curl https://ollama.ai/install.sh | sh`

**Comment by nalyk** [comment]
A solution is to make your home traversable (a+x).


> You need to be in a folder accessible/browsable by the `ollama` user. A solution is to make your home traversable (`a+x`).

No working

NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy

**Comment by shayakogan** [comment]
still no solution?

**Comment by jmorganca** [comment]
Hey all, sorry you're hitting this issue. Ollama on linux uses a user `ollama` to run in the background, but unfortunately this user doesn't have access to all files (including `Modelfile`s in your user directory).

Working on a fix but in the meantime you can give access to all users to your Modelfile so it can pick it up

```
chmod a+r ./Modelfile
```

**Comment by samskarion** [comment]
> Hey all, sorry you're hitting this issue. Ollama on linux uses a user `ollama` to run in the background, but unfortunately this user doesn't have access to all files (including `Modelfile`s in your user directory).
> 
> Working on a fix, and in the meantime you can add your current user to the `ollama` group:
> 
> ```
> usermod -aG ollama $USER
> ```
> 
> If you're `root`, the easiest way for the time being is to allow other users to access a specific directory that contains the `Modelfile`
> 
> ```
> chmod -R o+rx <dir containing Modelfile>
> ```

This didnt work for me still somehow BUT I ended up just copying the whole folder to /tmp and building from there. Worked like a charm

**Comment by usUpal** [comment]
> > Hey all, sorry you're hitting this issue. Ollama on linux uses a user `ollama` to run in the background, but unfortunately this user doesn't have access to all files (including `Modelfile`s in your user directory).
> > Working on a fix, and in the meantime you can add your current user to the `ollama` group:
> > ```
> > usermod -aG ollama $USER
> > ```
> > 
> > 
> > If you're `root`, the easiest way for the time being is to allow other users to access a specific directory that contains the `Modelfile`
> > ```
> > chmod -R o+rx <dir containing Modelfile>
> > ```
> 
> This didnt work for me still somehow BUT I ended up just copying the whole folder to /tmp and building from there. Worked like a charm

/tmp dir worked for me as well

**Comment by espadrine** [comment]
Is this issue truly fixed? I can see that my user is indeed added to the ollama group with `grep '^ollama:' /etc/group`, but the binary is still run as the ollama user, and thus cannot access files in the home directory, right? I tried running `ollama create openchat -f ./openchat/Modelfile`, with a freshly compiled binary put on /usr/local/bin and with `sudo systemctl restart ollama`, but the error remains.

**Comment by eramax** [comment]
I have the same issue

**Comment by romanoff** [comment]
Same for me

**Comment by jidun67** [comment]
I just thought it was me but, now I see it's not. I am not gonna try the temp dir fix I tried the others and had no luck :( I will keep an eye out for the fix I doubt I'd be much help in that area.

**Comment by marianoarga** [comment]
> > Hey all, sorry you're hitting this issue. Ollama on linux uses a user `ollama` to run in the background, but unfortunately this user doesn't have access to all files (including `Modelfile`s in your user directory).
> > Working on a fix, and in the meantime you can add your current user to the `ollama` group:
> > ```
> > usermod -aG ollama $USER
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you're `root`, the easiest way for the time being is to allow other users to access a specific directory that contains the `Modelfile`
> > ```
> > chmod -R o+rx <dir containing Modelfile>
> > ```
> 
> This didnt work for me still somehow BUT I ended up just copying the whole folder to /tmp and building from there. Worked like a charm

@samskarion wich folder you move and where to?, thanks

**Comment by arsenij-ust** [comment]
Hey all, for me worked to change the group ownership of the directory containing the models to ollama with `sudo chown -R $USER:ollama <ollama models dir>`. This solved the issue. Hope it helps.

**Comment by guoshuqi1212** [comment]
That is due to not sudo user. Use a Different Temporary Directory is fine.
mkdir -p ~/ollama_tmp
export OLLAMA_TMPDIR=~/ollama_tmp
ollama serve
just try

**Comment by highfillgoods** [comment]
I didn't need to use temp directory. Just make sure ollama service is completely stopped. and change permissions add user to ollama group whatever you need.

`sudo systemctl stop ollama.service && systemctl status ollama
`
here is what my user permissions look like for models.
```
/usr/share/ollama/.ollama$ ls -l
-rw------- 1 ollama ollama  387 Feb  7 17:56 id_ed25519
-rw-r--r-- 1 ollama ollama   81 Feb  7 17:56 id_ed25519.pub
drwxr-xr-x 4 user   ollama 4096 Feb  7 17:58 models
```
