### ISSUE TITLE
Request: exposing `Options` in `ollama serve`

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#617]
Coming from https://github.com/jmorganca/ollama/issues/581#issuecomment-1733841969, it would be useful to expose `Options` parameters like `num_predict` in the CLI (`ollama serve`).

Thanks in advance, and also feel free to close this as only supporting `options` in POST

**Comment by mchiang0610** [comment]
if we do it for `ollama serve` in the CLI, we'd be doing it across all requests. 

We give you the flexibility to set this in the API, so you can change it based on the request. 

Thank you for bringing this up though! Helps me learn where Ollama is a little weird to use.
