### ISSUE TITLE
How to add a new model with a .pth file ?

### ISSUE THREAD

**Issue by GautierT** [jmorganca/ollama#622]
Hi.

I would like to use ollama with https://huggingface.co/manu/mistral-7B-v0.1.

The files available are : 
```
tokenizer.model
consolidated.00.pth
params.json
RELEASE
```

Thanks.

**Comment by mxyng** [comment]
mistral 7b is available in the [library](https://ollama.ai/library/mistral). However if you want to add it from original weights, you'll need to convert it to gguf and optionally quantize. more information can be found in [llama.cpp](https://github.com/ggerganov/llama.cpp#prepare-data--run)
