### ISSUE TITLE
Mistral model can't be pulled

### ISSUE THREAD

**Issue by instanceofme** [jmorganca/ollama#623]
Hi,

I saw the [page about mistral](https://ollama.ai/library/mistral) but trying to pull it does not work, is it too soon / some files need to propagate through a CDN?

```
ollama pull mistral
pulling manifest
Error: pull model manifest: model not found
```

**Comment by jtoy** [comment]
it can be pulled for me, but I get "Error: invalid file magic" when I run a prompt on it

**Comment by BruceMacD** [comment]
@jtoy It is in the newer model format so make sure you're on the most recent version of Ollama. That is an error commonly seen on older versions.

**Comment by jtoy** [comment]
thanks. the auto updated didnt work. i had to come here and download the latest version even though the app kept telling me it downloaded a new version and I need to restart.

**Comment by mxyng** [comment]
The initial version didn't have a `latest` tag which is what's used when no tag is specified, e.g. `ollama pull mistral`. This has been fixed
