### ISSUE TITLE
Rectify the docs about ```ollama run```

### ISSUE THREAD

**Issue by thebigbone** [jmorganca/ollama#646]
I noticed that after running ```ollama run```, it also starts the API server because when I tried to exit the chat and run ```ollama serve```, it gave me an error saying ```port already in use``` and upon checking I realized that the API is already running.

Would it make sense if the README would specify this or is there no need for that? I can open up a PR for it if that's alright.

And thank you for working on this amazing project! It's awesome.

**Comment by mchiang0610** [comment]
Hey @thebigbone thank you for taking the time to create the issue. I really appreciate it. 

The reason for this is you don't need to run `ollama serve` on the mac if you have the desktop app. By having the desktop app running, it means that we will run ollama in the background. 

Hope this helps! The `ollama serve` command is great if you want to use it without the app
