### ISSUE TITLE
Read-only filesystem support

### ISSUE THREAD

**Issue by swthorn** [jmorganca/ollama#647]
Hi,

I ran the installation command described in the README:
`curl https://ollama.ai/install.sh | sh`
on NixOS.

However, the binaries and systemd service are not installed correctly. Is it possible to install this on a read-only file system? Or, can we install this in a local directory rather than /usr/bin?

This is the entire output:
```❯ curl https://ollama.ai/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7391    0  7391    0     0  28304      0 --:--:-- --:--:-- --:--:-- 28209
>>> Downloading ollama...
######################################################################## 100.0%##O=#  #                                                                      
>>> Installing ollama to /usr/bin...
[sudo] password for swthorn: 
>>> Creating ollama user...
useradd: Warning: missing or non-executable shell '/bin/false'
>>> Creating ollama systemd service...
tee: /etc/systemd/system/ollama.service: Read-only file system
>>> Install complete. Run "ollama" from the command line.
❯ ollama
ollama: command not found
❯ zsh
❯ ollama
ollama: command not found

**Comment by Dinour** [comment]
Hey @swthorn 

did u find a solution for this ? i'm in the same situation with the same problem ?

**Comment by BruceMacD** [comment]
Hey y'all, installing Ollama on a read-only file-system will only work but only as a client.

When running `ollama serve` Ollama will create logs, ssh keys (for pushing models to ollama.ai) and download modelfiles to the filesystem.

Running other commands from the CLI should be ok in a read-only file system as far as I'm aware, you could connect to an external server like this: `OLLAMA_HOST=123.456.789 ollama run mistral`

**Comment by mxyng** [comment]
Closing this since Ollama requires some form of write in order to download and run models
