### ISSUE TITLE
Request: ensemble Llamas 🦙 (`llama2:13b-ensemble`)

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#649]
From Hugging Face's Open LLM leaderboard: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

A 13b model ranked somewhat highly is [`yeontaek/llama-2-13B-ensemble-v5`](https://huggingface.co/datasets/open-llm-leaderboard/details_yeontaek__llama-2-13B-ensemble-v5).

![image](https://github.com/jmorganca/ollama/assets/8990777/a602fffb-0148-4202-9608-c186a9037d4a)

I believe TheBloke exposes it here via GGUF: https://huggingface.co/TheBloke/Llama-2-13B-Ensemble-v5-GGUF

It would be cool to add it to the [llama2](https://ollama.ai/library/llama2) offerings as `13b-ensemble`, `13b-ensemble-q4_0`.

**Comment by mchiang0610** [comment]
hey! Would you like to try to import it, and perhaps even upload it into Ollama library (if you want). We support importing both GGML and GGUF files. [Would seriously love input to make this experience better] 


1. Create a file named Modelfile, and add a FROM instruction with the local file path to the model you want to import.

```
FROM ./llama-2-13b-ensemble-v5.Q4_0.gguf
``` 

2. Create the model in Ollama

```
ollama create name -f path_to_modelfile
``` 

3. Run the model

```
ollama run name
```

Now you'll be able to try changing the prompt template in the modelfile. For example:

```
FROM ./llama-2-13b-ensemble-v5.Q4_0.gguf 

TEMPLATE """ 

### Instruction:
{{.Prompt}}

### Response:

"""

```

Now for uploading the model: 
Sign up: https://ollama.ai/signup 
(Bear with me on this, we're working hard to improve this experience before more broadly sharing it) 

and once you upload your public keys, you'll be able to push the model to your own namespace 

ie.) 
`ollama create jamesbraza/llama2-ensemble`

and then `ollama push jamesbraza/llama2-ensemble`

**Comment by mchiang0610** [comment]
@jamesbraza hope all is well! Just wanted to check if you were running into any trouble with this

**Comment by jamesbraza** [comment]
Yeah I appreciate the follow up and also the excellent instructions!

I haven't gotten around to this yet but it's one of the first things I will do Monday.  I was going to upstream any notable learnings from the process to https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md in a PR that closes this issue

**Comment by jamesbraza** [comment]
Okay I did hit a hiccup.  I previously downloaded [llama-2-13b-ensemble-v5.Q4_K_M.gguf](https://huggingface.co/TheBloke/Llama-2-13B-Ensemble-v5-GGUF/blob/main/llama-2-13b-ensemble-v5.Q4_K_M.gguf) using [huggingface_hub.hf_hub_download](https://huggingface.co/docs/huggingface_hub/guides/download).

When I use `FROM llama2` and then `ollama/ollama create llama-ensemble -f Modelfile`, Ollama starts downloading `llama2`.  How can I get it not to download `llama2`? I want to use my GGUF

**Comment by jamesbraza** [comment]
Alright, to answer my question, you have to use local `FROM`: https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#build-from-a-bin-file

I will pick this back up next week.  If `.gguf` works, we should update that docs title to be `#build-from-a-local-file` (not specific to `.bin`)

**Comment by technovangelist** [comment]
I think it looks like this issue has been resolved with Michaels help. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
