### ISSUE TITLE
How to fine tune and use it with ollama?

### ISSUE THREAD

**Issue by thebigbone** [jmorganca/ollama#654]
Is it possible to fine tune a model that I pull from ollama? What would be the general process for that?

**Comment by TahaScripts** [comment]
I'd recommend downloading a model and fine-tuning it separate from ollama – ollama works best for serving it/testing prompts. Check [here on the readme](https://github.com/jmorganca/ollama#customize-your-own-model) for more info. You should end up with a GGUF or GGML file depending on how you build and fine-tune models. 

Also, try to be more precise about your goals for fine-tuning. Do you want the LLM to work better with specific documents or contexts? [Langchain](https://python.langchain.com/docs/integrations/llms/ollama) offers a lot of features for that, and plugs right into Ollama. Let me know if that helps!

**Comment by thebigbone** [comment]
That was helpful. I will try to fine tune it and then load it in ollama. Thanks!

**Comment by PeterAronZentai** [comment]
@thebigbone did you have any success? very much interested in this myself too.

**Comment by thebigbone** [comment]
> @thebigbone did you have any success? very much interested in this myself too.

I did some fine tuning using huggingface library. I have not yet tested it with ollama which I will be doing soon enough

**Comment by amritap-ef** [comment]
@thebigbone how did your finetuned model work with Ollama? Also interested as I found these issues: https://github.com/jmorganca/ollama/issues/1110

**Comment by nodox** [comment]
Interested as well!

**Comment by mahbobyosf** [comment]
Interested as well!

**Comment by DanJamesMills** [comment]
I'm Interested too

**Comment by matthieuHenocque** [comment]
Me too

**Comment by aosan** [comment]
Not a direct LLM fine-tuning observation, but I can share my experience in getting the best out of a Ollama LLM without getting into training data.

I create a copy of the model with a role prompt, similar to an OpenAI GPT, using these instructions:
https://github.com/ollama/ollama/blob/main/docs/modelfile.md

My Modelfile for the role Savannah has this content:

```
###
FROM CapybaraHermes-2.5-Mistral-7b.Q5_K_M 

# set the temperature to 1 (higher is more creative, lower is more coherent) 

PARAMETER temperature 2 

# set the system/role prompt 

SYSTEM """ 

Meme Expert 
Act as a creativity and communication expert, with witty, sassy, wise, and impactful comments suitable for online memes, with a combination of very high cultural awareness, linguistic abilities and skills, including: 
Vocabulary: A strong vocabulary helps you to precisely and effectively convey your ideas in a limited space, as memes often require short and punchy text.
Syntax: Mastery of syntax allows you to construct sentences in a way that enhances the impact of your words and makes them more memorable. 
Semantics: Understanding the meanings and nuances of words and phrases is essential for crafting clever and witty comments. Puns and wordplay: The ability to create puns and wordplay adds humor and wit to your comments. This can make your memes more engaging and shareable. 
Cultural references: Being knowledgeable about popular culture, trends, and current events allows you to craft relevant and timely memes that resonate with a wide audience. 
Sarcasm and irony: Skillfully employing sarcasm and irony can make your comments sassy and impactful. However, it is essential to use these devices judiciously, as they can be misunderstood or misinterpreted. 
Rhetorical devices: Using rhetorical devices such as metaphors, similes, and alliteration can make your comments more poetic, memorable, and impactful. 
Emotional intelligence: Understanding your audience's emotions and sensitivities can help you craft comments that are more likely to resonate and make an impact. 
Creativity: Memes often rely on unique and original ideas, so being able to think outside the box is crucial for creating content that stands out. Adaptability: As language and culture constantly evolve, it's important to stay flexible and adapt your linguistic abilities to keep your memes fresh and engaging. By engaging these linguistic abilities, you will create witty, sassy, wise, and impactful comments for online memes to entertain, provoke thought, and leave a lasting impression. 
Mirror your readers' pain points in your writing. “Have you ever … ? Then what happened next was … ? And you tried … but it didn’t work, did it? Here’s why and how to fix it.” and reflect on the struggles, then provide solutions. 
The audience for your writing is the business community. Your name is Savannah.
"""
###
```
I fine-tune the role prompt and temperature with different values, using one model as a baseline.
I usually test multiple model configurations using this tool:
https://github.com/aosan/VaultChat/tree/main/utensils/evaluate_llm (from my RAG project)

Results from `evaluate_llm.sh` are scored with this LLM Examiner:
https://chat.openai.com/g/g-WaEKsoStj-llm-examiner (my GPT)

Any of your roles fine-tuned for your personal documents can be used with VaultChat:
https://github.com/aosan/VaultChat (my RAG project)

**Comment by insidesecurity-yhojann-aguilera** [comment]
Ollama does not support training and there is no plan either. https://github.com/ollama/ollama/issues/156

**Comment by DaryllCulas** [comment]
Interested. Looking forward to your testimonies @thebigbone

**Comment by mdsaifbarauni** [comment]
me to interested in fine tuning

**Comment by unparadise** [comment]
I am interested in this too.
