### ISSUE TITLE
Question: where is ollama.ai website source?

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#655]
I was going to try to make some docs PRs into [ollama.ai](https://ollama.ai/). Where is the source code for the website?

**Comment by mchiang0610** [comment]
Hey @jamesbraza we’ve tried to keep Ollama docs inside our GitHub for now. It’s still very barren. Would love your help! 

Anything in particular you’re looking to contribute to?

**Comment by jamesbraza** [comment]
Yeah thanks!  I was gonna try to combine the aliases and model sources tables here into one, and add a column for quantization: https://ollama.ai/library/llama2

Just try to make it more centralized/clear to eliminate future questions like https://github.com/jmorganca/ollama/issues/643

That being said, I don't see [llama2](https://ollama.ai/library/llama2)'s source file in `docs/`, so I was wondering where that page's source files are.

**Comment by technovangelist** [comment]
Each of the model overviews is edited directly. If you have any edits you would suggest you can let us know with an issue here. But I think I can close this issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
