### ISSUE TITLE
Chat completion endpoint

### ISSUE THREAD

**Issue by zifeo** [jmorganca/ollama#657]
Most of the UI are compatible with OpenAI endpoint definitions. Would it be possible to support the same format on ollama so frontend could be easily plugged into? See https://docs.typingmind.com/other-resources/how-tos/use-custom-models-or-local-models-in-typing-mind-(vicuna-alpaca-llama-gpt4all-dolly-etc.).

**Comment by jamesbraza** [comment]
I think OpenAI compatibility is being discussed here: https://github.com/jmorganca/ollama/issues/305

Not a contributor, just sharing so you can see

**Comment by technovangelist** [comment]
Ollama has a much simpler approach to using the API and changing it may be possible, but would require some work to get it right. As @jamesbraza mentioned, its being tracked on #305, so I will close this
