### ISSUE TITLE
Request: Docker image build having name/tag

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#660]
Having just built the Docker image successfully 🥳 :

```bash
> sudo docker image ls
REPOSITORY                        TAG       IMAGE ID       CREATED              SIZE
<none>                            <none>    acfffae34e3a   About a minute ago   824MB
```

Running `docker image ls`, there is no info about the Ollama image.  Any chance we can configure the `Dockerfile` such that `REPOSITORY` and `TAG` is not `<none>`?

**Comment by mchiang0610** [comment]
@jamesbraza Thanks! you'll have to use the `-t` tag with docker to give it a tag. 

We have an image available for Docker that you can use, and it's tagged: 

https://hub.docker.com/r/ollama/ollama
