### ISSUE TITLE
Linux Installation `curl` command fails

### ISSUE THREAD

**Issue by Shihab-Shahriar** [jmorganca/ollama#666]
`curl https://ollama.ai/install.sh | sh`

This leads to:

```
>>> Downloading ollama...
Warning: Failed to open the file /tmp/tmp.hE5cI4TvS7/ollama: No such file or 0%##O#-#
Warning: directory
curl: (23) Failure writing output to destination
```

Ubuntu 22.04.3 LTS

**Comment by mxyng** [comment]
Hi @Shihab-Shahriar, can you describe briefly how this server was installed? Is it using a base image from a cloud provider (AWS, GCP, etc.), installed using Ubuntu's ISO, or a container?

**Comment by Shihab-Shahriar** [comment]
I didn't really install anything. I thought all I had to do was run that command:
``
curl https://ollama.ai/install.sh | sh
```

**Comment by mxyng** [comment]
You shouldn't need to install anything in order to run the install script however I need to better understand how the system is setup to reproduce this issue. For example, my test using GCP's Ubuntu 22.04 LTS image succeeds without errors.

**Comment by Shihab-Shahriar** [comment]
I'm sorry I missed part of your question last time. I tried that command on the terminal of my local desktop.

**Comment by dominicdev** [comment]
getting this 2 ubunto 22

**Comment by datafields** [comment]
It has to do with Curl, I had the same issue. Please try the following and it fixed the problem.
$ sudo snap remove curl
$ sudo apt install curl

**Comment by CorpHackRyan** [comment]
^ I had the same issue, and the above  worked.

**Comment by Eous638** [comment]
Same issue, datafields solution of reinstalling curl fixed it

**Comment by RogerGMarch** [comment]
I had the same issue, datafields solution of reinstalling curl fixed it, Thanks!

**Comment by mxyng** [comment]
This seems to be an issue with the installed curl, not the install script.

**Comment by kajackdfw** [comment]
I am having the same issue

**Comment by parthdey** [comment]
The solution given above really worked for me guys

**Comment by thiagoaag** [comment]
> It has to do with Curl, I had the same issue. Please try the following and it fixed the problem. $ sudo snap remove curl $ sudo apt install curl

I had the same problem, and this worked for me. Thanks @datafields

**Comment by Murilho** [comment]
Obrigado...
o meu deu certo tambem depois que eu vi o comentario do [datafields]

**Comment by MominIqbal-1234** [comment]
sudo apt-get update
sudo apt-get install curl

its work
