### ISSUE TITLE
Allow customizing allowed headers in CORS settings

### ISSUE THREAD

**Issue by spaceemotion** [jmorganca/ollama#669]
Based on some additional research on an issue I have (https://github.com/jmorganca/ollama/issues/300#issuecomment-1742099347), I am getting the following error in chrome/firefox:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:11434/api/tags. (Reason: header ‘baggage’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

(see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight for details)

It would be helpful to allow all headers (if possible?) as I am able to call the API via tools like curl, postman, etc., but not using `fetch()` from a webpage. This does not need to be the default, an env variable like `OLLAMA_HOST` and such works for me.

**Comment by spaceemotion** [comment]
Quick update: I found a middleware that intercepted the fetch calls to add custom headers. Blocking the middleware for requests to Ollama did the trick. However, it would still be nice to be able to control this natively.

**Comment by jmorganca** [comment]
Hi @spaceemotion, `OLLAMA_ORIGINS` is available as an environment variable you can set: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama

Hope this helps! Sorry for taking awhile to respond.

**Comment by do-me** [comment]
Did anyone find a solution to make this work on Firefox as well? I'm not sure whether it's missing user agent headers or whether it's http to https connection problem. 

I currently run:   
- on Windows Powershell:`$env:OLLAMA_ORIGINS="https://do-me.github.io"; ollama serve`
- on Ubuntu: `OLLAMA_ORIGINS="https://do-me.github.io" ollama serve`

This works on Chromium (like Chrome and Edge) but not FF. FF gives me a link to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default) and the logs show a 204 error. 

`[GIN] 2024/03/06 - 13:16:24 | 204 |            0s |       127.0.0.1 | OPTIONS  "/api/chat"`

Background: I want to make the [Ollama SemanticFinder integration work in FF too](https://www.reddit.com/r/ollama/comments/1b79c23/inbrowser_rag_feeding_ollama/).

**Comment by osfa** [comment]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:11434/api/chat. (Reason: header ‘user-agent’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).` same issue. missing user agent headers i the issue I think? I have the same issue in safari, but works in chrome.

**Comment by do-me** [comment]
The issue is precisely this, right. I suppose one could just route everything over a proxy like https://corsproxy.io/ but I'd prefer a clean solution not relying on third-party service.

**Comment by Anivie** [comment]
I am get the same error even I am run with chrome, is there any way to solve this error with `Access-Control-Allow-Headers`?

**Comment by Kmfernan5** [comment]
same here

**Comment by Yash-1511** [comment]
same issue! please resolve this issue

**Comment by ewantindale** [comment]
> Hi @spaceemotion, `OLLAMA_ORIGINS` is available as an environment variable you can set: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama
> 
> Hope this helps! Sorry for taking awhile to respond.

I followed the steps here for Linux but I am still getting this error in Chrome:

`Access to fetch at 'http://localhost:11434/v1/chat/completions' from origin 'http://localhost:5173' has been blocked by CORS policy: Request header field x-stainless-os is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by spaceemotion** [comment]
@ewantindale the `x-stainless` headers are from the OpenAI SDK, you have to replace how it handles headers internally as a workaround:

```ts

class NoStainlessOpenAI extends OpenAI {
  defaultHeaders(opts: FinalRequestOptions) {
    return {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      ...this.authHeaders(opts),
    };
  }
}
```

**Comment by ewantindale** [comment]
> @ewantindale the `x-stainless` headers are from the OpenAI SDK, you have to replace how it handles headers internally as a workaround:
> 
> ```ts
> class NoStainlessOpenAI extends OpenAI {
>   defaultHeaders(opts: FinalRequestOptions) {
>     return {
>       Accept: 'application/json',
>       'Content-Type': 'application/json',
>       ...this.authHeaders(opts),
>     };
>   }
> }
> ```

Thanks, fixed that issue but now I get 

`Access to fetch at 'http://localhost:11434/v1/chat/completions' from origin 'http://localhost:5173' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

I am following the instructions here: https://github.com/ollama/ollama/blob/main/docs/openai.md

**Comment by spaceemotion** [comment]
@ewantindale you can just remove this line from the extended class:
```ts
      ...this.authHeaders(opts),
```

**Comment by j2l** [comment]
Same issue on FF on ubuntu, but working with Chromium.
I'd love to use this on FF.

**Comment by LoopControl** [comment]
Same issue here. User agent header should be allowed in CORS for Ollama.

Without it, it makes the CORS support basically useless in Ollama since almost every client sends a user-agent header.

**Comment by whinc** [comment]
alternative solution: start a nginx server as a proxy to ollama server, then you can configure cors in nginx leaving ollama server untouched.

request chain: browser -> nginx proxy -> ollama server

nginx conf

```
server {
    listen 8080;
    server_name <your_domain>;

    location /api {
        # keep host same as ollama server to avoid cors
        proxy_set_header Host '127.0.0.1';
        # hide origin to avoid ollama server response 403
        proxy_set_header Origin '';

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' "$cors_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, x-requested-with';
           # uncomment if you request include credentials
            #add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        if ($cors_origin) {
            add_header 'Access-Control-Allow-Origin' "$cors_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, x-requested-with';
            #add_header 'Access-Control-Allow-Credentials' 'true';
        }
        proxy_pass http://localhost:11434;
    }
}

```

**Comment by mmar58** [comment]
Hi, I found a solution. We can use a node js middle man. Who will receive prompt through the api and send ollama stream response.
I created a node project https://github.com/mmar58/Ollama-Global-API for this reason. You guys can also try it. It allows you to access ollama through any network on any device thought the api.

**Comment by whinc** [comment]
> alternative solution: start a nginx server as a proxy to ollama server, then you can configure cors in nginx leaving ollama server untouched.
> 
> request chain: browser -> nginx proxy -> ollama server
> 
> nginx conf
> 
> ```
> server {
>     listen 8080;
>     server_name <your_domain>;
> 
>     location /api {
>         # keep host same as ollama server to avoid cors
>         proxy_set_header Host '127.0.0.1';
>         # hide origin to avoid ollama server response 403
>         proxy_set_header Origin '';
> 
>         if ($request_method = 'OPTIONS') {
>             add_header 'Access-Control-Allow-Origin' "$cors_origin";
>             add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
>             add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, x-requested-with';
>            # uncomment if you request include credentials
>             #add_header 'Access-Control-Allow-Credentials' 'true';
>             add_header 'Access-Control-Max-Age' 1728000;
>             add_header 'Content-Type' 'text/plain charset=UTF-8';
>             add_header 'Content-Length' 0;
>             return 204;
>         }
> 
>         if ($cors_origin) {
>             add_header 'Access-Control-Allow-Origin' "$cors_origin";
>             add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
>             add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, x-requested-with';
>             #add_header 'Access-Control-Allow-Credentials' 'true';
>         }
>         proxy_pass http://localhost:11434;
>     }
> }
> ```
Oh my! It turns out that `ollama serve` natively supports setting cross-origin configuration, you just need to set an environment variable.

```bash
$ollama serve --help
......
Environment Variables:                                                         [0/1195]
      OLLAMA_DEBUG               Show additional debug information (e.g. OLLAMA_DEBUG=1)     
      OLLAMA_HOST                IP Address for the ollama server (default 127.0.0.1:11434)
      OLLAMA_KEEP_ALIVE          The duration that models stay loaded in memory (default "5m")       
      OLLAMA_MAX_LOADED_MODELS   Maximum number of loaded models per GPU              
      OLLAMA_MAX_QUEUE           Maximum number of queued requests                    
      OLLAMA_MODELS              The path to the models directory                     
      OLLAMA_NUM_PARALLEL        Maximum number of parallel requests                  
      OLLAMA_NOPRUNE             Do not prune model blobs on startup                  
      OLLAMA_ORIGINS             A comma separated list of allowed origins             
      OLLAMA_SCHED_SPREAD        Always schedule model across all GPUs                
                                                                                       
      OLLAMA_FLASH_ATTENTION     Enabled flash attention                              
      OLLAMA_KV_CACHE_TYPE       Quantization type for the K/V cache (default: f16)    
      OLLAMA_LLM_LIBRARY         Set LLM library to bypass autodetection              
      OLLAMA_GPU_OVERHEAD        Reserve a portion of VRAM per GPU (bytes)            
      OLLAMA_LOAD_TIMEOUT        How long to allow model loads to stall before giving up (default "5m")                        
```

**Comment by LoopControl** [comment]
> Oh my! It turns out that `ollama serve` natively supports setting cross-origin configuration, you just need to set an environment variable.

If you read the above replies, you can see that was already mentioned but even with that environment variable enabled, ollama still denies some headers which is the issue.

**Comment by whinc** [comment]
> 
> > Oh my! It turns out that `ollama serve` natively supports setting cross-origin configuration, you just need to set an environment variable.
> 
> If you read the above replies, you can see that was already mentioned but even with that environment variable enabled, ollama still denies some headers which is the issue. 

Oh, yes. Ollama can only set the "origin", and currently does not support setting other "access-control-*" headers. It still needs to rely on Nginx or other proxy services to achieve this.

**Comment by z4none** [comment]
first set OLLAMA_ORIGINS environment variable when starting the ollama process，
for example:
```
OLLAMA_ORIGINS=http://*
```

then in js: 
```
const client = new OpenAI({
  apiKey: 'ollama',
  baseURL: 'http://localhost:11434/v1',
  dangerouslyAllowBrowser: true,
  defaultHeaders: {
    'x-stainless-retry-count': null,
    'x-stainless-timeout': null,
  },
});
```
