### ISSUE TITLE
Context at each token, to allow interrupting a response?

### ISSUE THREAD

**Issue by tonyg** [jmorganca/ollama#670]
Forgive me if I misunderstand, but would it be possible to get context at every streamed JSON partial-response, instead of just at the end, to allow the user to interrupt a response without the conversation losing a memory of how far it had gotten before being interrupted?

**Comment by jmorganca** [comment]
Hi there, we've designed the new [Chat completion](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion) endpoint for this use case. With chat completions, no more worrying about passing in `context`. Instead, you can accumulate the response-so-far and send that in next.

I'll mark this issue as closed, that said let me know if it doesn't solve your use case and I'll make sure to re-open it :)
