### ISSUE TITLE
api improvements

### ISSUE THREAD

**Issue by jtoy** [jmorganca/ollama#675]
its a stream of objects that are separated with a newline. often times new lines are returned in the response, so that breaks just splitting on new lines. 
I think the split should be on something else.
Also it seems like there should be an api endpoint that just returns the whole response in a string. 

thoughts?

**Comment by technovangelist** [comment]
If using JS, sometimes fetch will grab multiple json objects at once if there are more than one available. Your code should split the string received by '\n' to ensure its dealing with a single response to parse. This is common in other streaming apis as well.

**Comment by jtoy** [comment]
the problem is newlines in the responses

**Comment by technovangelist** [comment]
perhaps you can give an example of what you are referring to.

**Comment by technovangelist** [comment]
Do you have an example of the problem you are seeing and what you think it should be?

**Comment by reustle** [comment]
> Also it seems like there should be an api endpoint that just returns the whole response in a string.

For this, fortunately there is a recent PR for this that seems like it will be merged soon https://github.com/jmorganca/ollama/pull/639

**Comment by technovangelist** [comment]
Haven't heard back from you. If you have an example, please reopen but for now I'll close this.

**Comment by mccainz** [comment]
> > Also it seems like there should be an api endpoint that just returns the whole response in a string.
> 
> For this, fortunately there is a recent PR for this that seems like it will be merged soon #639

`"stream" : false` works perfectly in this regard.
