### ISSUE TITLE
Is there a way to change the download/run directory? 

### ISSUE THREAD

**Issue by improvethings** [jmorganca/ollama#680]
On Linux, I want to download/run it from a directory with more space than /usr/share/

**Comment by heyheyhello** [comment]
It's just using `$HOME` as seen here:

https://github.com/search?q=repo%3Ajmorganca%2Follama+.ollama&type=code

The `/usr/share` is coming from `Environment="HOME=/usr/share/ollama"`

https://github.com/search?q=repo%3Ajmorganca%2Follama%20usr%2Fshare&type=code

**Comment by BruceMacD** [comment]
@improvethings I think #897, which will be in the next release may resolve your issue. It allows setting the directory where the model files are stored.

**Comment by adbrei** [comment]
Do you know approximately when the next release will be deployed?

**Comment by technovangelist** [comment]
This is solved by using the OLLAMA_MODELS environment variable. Once you set that for the account that runs ollama, then models will go wherever you want. I will go ahead and close this issue now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by BananaAcid** [comment]
> This is solved by using the OLLAMA_MODELS environment variable.

@technovangelist Great addition - works well with WSL using another drive (otherwise defaults to C:) Should probably be added to the README.md

**Comment by mrektor** [comment]
Could it be possible to set this download path from the ollama command line? Like `ollama set-model-path /my/path` or something like this...

**Comment by kac487** [comment]
I second this, I'm unable to get the OLLAMA_MODELS to make any difference to where models are stored. Having the ability to directly set the model path would be great.

**Comment by amorphius** [comment]
same issue. OLLAMA_MODELS variable does not work for me

**Comment by BananaAcid** [comment]
It works for me, in the service by adding `Environment="OLLAMA_MODELS=/srv/models"` as well as (in one line):  `OLLAMA_MODELS=/srv/models ollama run mixtral`

**Comment by amorphius** [comment]
Sorry for confusion, it works now. In my case I had to start first `ollama serve` and only then `ollama run ...`. So inititally I've passed `OLLAMA_MODELS` to `ollama run` command but it turned out that I need to pass it to `ollama serve`.
Now everything works fine for me.

**Comment by RiverHousePresents** [comment]
For users of the newly released Windows version of Ollama, you need to add your new directory to both the "System variables" in the "Environment Variables" and in the "Path" under the "User variables for ***"

**Comment by macmus82** [comment]
> For users of the newly released Windows version of Ollama, you need to add your new directory to both the "System variables" in the "Environment Variables" and in the "Path" under the "User variables for ***"

How did u install model in other directory then c? I don't have enough storage in windows on drive c and I'm not able to download it to other directory

**Comment by ArbyC** [comment]
Similar concern on how do I install or download models to a different directory then C which seems to be the default for both installing ollama and run model.

**Comment by bryanhughes** [comment]
This does not work for me. I second the feature of a command line to formally set the path. I am on a linux instance and the installer creates `/usr/share/ollama` as the home directory without a shell which contains `.bashrc` and `.profile`. I tried adding the `OLLAMA_MODELS=...` and nothing is written to the new location. :(

**Comment by AnandBhandari1** [comment]
On windows, it worked perfectly. setx OLLAMA_MODELS "D:\ollama_model"

**Comment by jay-singhvi** [comment]
Can we have a way to store the model at custom paths for each model, like specifying the path when its being downloaded for first time.
If the model is not there already then download and run, else directly run.
In this way we can even maintain different versions of same model in different directories.
I am really hoping this would work for windows too :)

**Comment by ElderMedic** [comment]
It’s so counter-intuitive that ollama pull cannot set the location of the downloaded model through an optional parameters, actually all ollama commands basically have no flag. 
I believe most linux user does not use /usr/share to store data as large as LLM. 
Please consider something like adding a --out for pull and --in for run, it would be perfect.

**Comment by satangel2222** [comment]
How To Change Ollama Model Default Directory
https://www.youtube.com/watch?v=uj1VnDPR9xo

**Comment by vector4wang** [comment]
> On windows, it worked perfectly. setx OLLAMA_MODELS "D:\ollama_model"

it worked for me on windows

**Comment by igadmg** [comment]
For everyone who say it does not work OLLAMA_MODELS - kill ollama instances first, then run it again

**Comment by yoyojacky** [comment]
Just a new idea,  i have attached a m.2 PCIe NVME SSD to my Raspberry Pi 5 and it run Raspberry Pi OS 64bit (bookworm), 
I found that ollama user's home directory is `/usr/share/ollama` ,  so I've tried this :
* 1. stop ollama service 
```bash 
sudo systemctl stop ollama.service
```
* 2. patitioning my SSD and format it, mount it direct to `/usr/share/ollama` folder .
```bash
sudo fdisk /dev/nvme0n1 
> d
> p
> n 
> p
> 1 
> enter -->enter 
> w 

sudo mkfs.ext4  /dev/nvme0n1p1 
sudo mount -t ext4 /dev/nvme0n1p1  /usr/share/ollama -v 
sudo chown -R ollama:ollama /usr/share/ollama 
sudo systemctl daemon-reload
sudo systemctl restart ollama.service
```
* 3. Pull models 
```bash
for  model in llama3 llama2  mistral phi3  qwen:4b  qwen:7b  codegema
do 
     ollama pull $model 
done 
```
and it works perfect. hope it can help you out.

**Comment by yordis** [comment]
If you are using the MacOS app, make sure to restart the app to pick up the new secret value

**Comment by chriskosinski** [comment]
To run as a service in other directory:

1. sudo vi /etc/systemd/system/ollama.service
2. Change 
Environment="PATH=/home/user/anaconda3/condabin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin"
to 
Environment="PATH=/home/user/anaconda3/condabin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin" "OLLAMA_MODELS=/mnt/mydrive/ollama/models"
3. save, sudo systemctl daemon-reload 
4. sudo systemctl force-reload ollama.service
5. sudo systemctl start ollama.service  

Now you have ollama running as a service in a chosen directory.

**Comment by denohk** [comment]
Win10:
Press Windows key on your keyboard search: Edit the system environment > Environment Variables >New
Variable Name: OLLAMA_MODELS
Variable value: put/paste the folder you like to here, logout the windows 10 and then start the OLLAMA servers again you are now can save your models into the folder you have just set up. done.

![Image](https://github.com/user-attachments/assets/06bcdd4c-2ed6-4a1d-868c-0986756b70c5)

**Comment by Ramadanko** [comment]
> OLLAMA_MODELS

after setting the env variable, quit the ollama app and wait for about 30 seconds

**Comment by ikskoder** [comment]
Changing /etc/systemd/system/ollama.service on Ubuntu didn't work for me, but declaring env variable just before running ollama does the trick:
```
export OLLAMA_MODELS=/path/you/want/
ollama serve
```

**Comment by bkrajendra** [comment]
Following worked for me on macOS: https://github.com/ollama/ollama/blob/main/docs%2Ffaq.md#setting-environment-variables-on-mac
### Fore setting host
`launchctl setenv OLLAMA_HOST "0.0.0.0"`

### For changing model directory
`launchctl setenv OLLAMA_MODELS "/Users/<user>/Documents/llm_models"`

Restart the ollama app.

**Comment by giantamoeba** [comment]
The following worked on linux for me:

`sudo systemctl edit ollama.service`
And then in the specified location write:
`[Service]
Environment="OLLAMA_MODELS=/mnt/mymodels_dir"`
Save and then restart the service
`sudo systemctl stop ollama.service`
`sudo systemctl start ollama.service`

**Comment by bkrajendra** [comment]
> As of March 11 2025, adding ```export OLLAMA_MODELS="custom/path/to/ollama-models"``` to .bashrc or .zshrc does not work. Setting ownership to ollama:ollama to the folder ollama-models doesn't work. Setting Environment="OLLAMA_MODELS=custom/path/to/ollama-models" in ollama.service file doesn't work.
> 
> Downloading an LLM to another folder is a basic requirement. Considering ollama is so extensively used and maintained, this should have easily worked.
> 

Can you make sure you restarted the ollama service.
Also check if these environment variables are set and accessible.

I am using the latest version, for me it works on windows, mac and Linux without any issue.

**Comment by kabyanil** [comment]
> > As of March 11 2025, adding `export OLLAMA_MODELS="custom/path/to/ollama-models"` to .bashrc or .zshrc does not work. Setting ownership to ollama:ollama to the folder ollama-models doesn't work. Setting Environment="OLLAMA_MODELS=custom/path/to/ollama-models" in ollama.service file doesn't work.
> > Downloading an LLM to another folder is a basic requirement. Considering ollama is so extensively used and maintained, this should have easily worked.
> 
> Can you make sure you restarted the ollama service. Also check if these environment variables are set and accessible.
> 
> I am using the latest version, for me it works on windows, mac and Linux without any issue.

Yes, I restarted the ollama service. I also checked if the env variables were accessible by printing them on the terminal.

Can you share your configuration steps?

**Comment by erickmiller** [comment]
I'm on linux.  I just ran this to install the latest version:

`curl -fsSL https://ollama.com/install.sh | sh`

And then threw this in my `.bashrc` to keep it simple for testing:

```
export OLLAMA_MODELS=/path/to/my/ollama/models
nohup ollama serve > /dev/null 2>&1 &
```

And everything works fine, models are downloading to the custom directory and ollama silently starts up whenever I launch a shell.

**Comment by anuprulez** [comment]
For me also setting OLLAMA_MODELS path did not work. I went for the manual installation guide (https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install) and then set the path `/usr` mentioned in the command to my custom path while extracting the package. Then, `ollama pull llama2` pulled the the Llama2 to the path I provided. Hope it helps

**Comment by Binjian** [comment]
I move the models folder to the desired partition and add a softlink in the original place pointing to the new folder. It seems to work. Would this be a problem in the future?

**Comment by StewartSethA** [comment]
`ln -s /your/model/path ~/.ollama/`

**Comment by jonas-eschle** [comment]
@Binjian you can follow the instructions here to set the environment variables: https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by Gene1125** [comment]
I try to set the environment variables by editing /etc/systemd/system/ollama.service and it failed at `systemctl status ollama`.
Then I directly add export OLLAMA_MODELS="custom/path/to/ollama-models" , it still doesn't work.
Finally I use soft link   `ln -s /mnt/ollama/models /usr/share/ollama/.ollama/models` and it works fine. 
Hope that helps :D

**Comment by jclsn** [comment]
@bryanughes You are probably running ollama via systemd, so try doing a

```bash
sudo systemctl edit ollama.service
```

and then paste this inside

```systemd
[Service]
Environment="OLLAMA_MODELS=/home/user/.ollama/models"
```

This will overwrite the unit that automatically starts ollama.

**Comment by ahashem** [comment]
> Following worked for me on macOS: https://github.com/ollama/ollama/blob/main/docs%2Ffaq.md#setting-environment-variables-on-mac
> 
> ### Fore setting host
> 
> `launchctl setenv OLLAMA_HOST "0.0.0.0"`
> 
> ### For changing model directory
> 
> `launchctl setenv OLLAMA_MODELS "/Users/<user>/Documents/llm_models"`
> 
> Restart the ollama app.

I can confirm this works on macOS. Additionally if Ollama were installed using homebrew:

`launchctl setenv OLLAMA_MODELS "/path/to/external/volume/llm_models"`

then: `brew services restart ollama` to restart the ollama app.

**Comment by timebinding-sinus** [comment]
// Ollama 'config' catalog in "~/.ollama"
//
//

// Go to Home catalog
cd ~

// sure make catalogs
// where you planning save new models

// i use mounted 500GB harddisk and safe big models 
mkdir ~/Hard_500G
mount /dev/sda1 ~/Hard_500G

// create catalogs (you can change it)
mkdir ~/Hard_500G/AI/
mkdir ~/Hard_500G/AI/Ollama/
mkdir ~/Hard_500G/AI/Ollama/models

// move saved models in new place (not delete)
mv .ollama/models ~/Hard/AI/Ollama/models


// create symbolic link to new place
ln -s /home/USERNAME/Hard_500G/AI/Ollama/models ~/.ollama/models


// Install (run, pull) new model
ollama serve

// (open new terminal)

ollama run gemma3

**Comment by Kraven1109** [comment]
@echo off
:: Set the custom path for your models (for those who using windows like me, models will be stored in e:\llm\blobs)
set OLLAMA_MODELS=e:\llm\

:: Navigate to the directory where ollama is installed (optional but recommended, if you don't have ollama in PATH)
cd /d "d:\Apps\ollama\"

:: Start the Ollama server
echo Starting Ollama with models at E:\llm...
ollama serve
pause
