### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by fakerybakery** [jmorganca/ollama#683]
How can I uninstall this program?

**Comment by jmorganca** [comment]
@fakerybakery on macOS, removing Ollama.app` and then if you want to remove the model data it's stored under `~/.ollama`

Sorry to see you go, curious if there's a reason we can improve that caused you to consider uninstalling 😊 ?

**Comment by fakerybakery** [comment]
Hi, thank you for your fast response!
I removed `Ollama.app`, `/usr/local/bin/ollama`, and `~/.ollama`.
For why I uninstalled this app: there's nothing wrong with it, it looks like a great project, but `llama.cpp` (which this project is built in) is enough for me. But thanks for making this project!
