### ISSUE TITLE
Question: where are all the `Modelfile`s?

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#685]
https://ollama.ai/library has a lot of models.  I would like to add a new model, and want to make sure it uses the GPU.  So I am looking to refer to `Modelfile`s for models featured on https://ollama.ai/library.

Where is the source `Modelfile`s for the current "built in" models?

**Comment by technovangelist** [comment]
There is nothing to add to ensure it uses the gpu.

**Comment by technovangelist** [comment]
All the settings in the modelfile are shown for each tag in each model.

**Comment by jamesbraza** [comment]
Oh that's pretty convenient, I didn't realize that about Tags, thank you!  Though I don't think it's the full `Modelfile`, for example with https://ollama.ai/library/llama2:13b

![screenshot of `llama2:13b` Tags](https://github.com/jmorganca/ollama/assets/8990777/b1b825cd-cfca-4ce8-8f84-af52370226db)

I don't see a `FROM` field, though [the docs](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#from-required) state it's required.  In the `llama2:13b`'s `Modelfile`, does it have a `FROM` field?

**Comment by technovangelist** [comment]
It's from a model weights file on the system that built the model

**Comment by jamesbraza** [comment]
When you say model weights file on the system, you mean something like a local `.bin` or `.gguf`?  So something like `FROM ./downloaded-model.bin`.

And if yes, feel free to close this out 👍

**Comment by technovangelist** [comment]
Exactly right

**Comment by pdevine** [comment]
@jamesbraza You can also use the `show` command to print out the Modelfile:

```
% ollama show llama2:13b
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM llama2:13b

FROM /Users/pdevine/.ollama/models/blobs/sha256:f79142715bc9539a2edbb4b253548db8b34fac22736593eeaa28555874476e30
TEMPLATE """[INST] {{ if and .First .System }}<<SYS>>{{ .System }}<</SYS>>

{{ end }}{{ .Prompt }} [/INST] """
SYSTEM """"""
PARAMETER stop [INST]
PARAMETER stop [/INST]
PARAMETER stop <<SYS>>
PARAMETER stop <</SYS>>
```
