### ISSUE TITLE
Unable to create account with a secure password

### ISSUE THREAD

**Issue by FairyTail2000** [jmorganca/ollama#688]
I was just about to create an account with the following passwords:

»,àî´æ=`"((Ý#±«"ü×%'yWðÍ&îPqØTX;¯þ;¿×æXËµ¾ÖÛDþí,Á_+*Ä¬Ê<µ¾¡f'»êÎÖp¢e_P°óZk@XñÊ7ÒÊÖ©mðÂÝs5jÛCCýZ-C¹ÎÖúÃ'ô½¡7§îW(ÂcT_*Jo©h9>9Ãèh[Í

pw_E}]kz#uEnn`Lr@[FF{jfS+~M*rd/52iWxja%jobADqcWX\oaZ[;=bPM].5Kc(gJH-_+okZbeQ'wQ_nVVQV-C{r3/7}+%#:{,->y.K,'A-M/fR9gw%*H}!H3=LY!{u

Shortening the password to 50 chars works. However I would still like to use the max number of chars available in my password manager

**Comment by iamexe** [comment]
Wrong repo?

Gruss

**Comment by FairyTail2000** [comment]
Is there a repo for the ollama.ai website? If so I will move my issue of course

**Comment by technovangelist** [comment]
This is the right place

**Comment by technovangelist** [comment]
We appreciate anyone who is as concerned with security as we are which is why we have a very secure maximum of 50 characters. A password with 18 characters will take 500 million years to crack. By the time quantum computers become a threat we will have changed the scheme we use entirely.

**Comment by jmorganca** [comment]
@FairyTail2000 we'll get this fixed – stay tuned 😊

**Comment by FairyTail2000** [comment]
Thank you

**Comment by jmorganca** [comment]
This should be fixed now @FairyTail2000. Feel free to re-open or create another issue if the problem persists!
