### ISSUE TITLE
no space left on device Error

### ISSUE THREAD

**Issue by daaniyaan** [jmorganca/ollama#689]
I'm getting " no space left on device " error while i have enough space on my MacBook.
![CleanShot 2023-10-03 at 14 27 13](https://github.com/jmorganca/ollama/assets/31348710/e361dd12-db9b-4f38-ae02-32b98e2190fb)
![CleanShot 2023-10-03 at 14 27 54](https://github.com/jmorganca/ollama/assets/31348710/4f5638cb-e101-4162-a3ba-e446f841144b)
![CleanShot 2023-10-03 at 14 44 46@2x](https://github.com/jmorganca/ollama/assets/31348710/21d3432a-de08-4f18-b7e0-92900d3f25d5)

**Comment by daaniyaan** [comment]
shouldn't it download the models in the ~./ollama ?
why in the first screenshot it's mentioning "/usr/share/ollama/.ollama/models/blobs"

![CleanShot 2023-10-03 at 15 28 06@2x](https://github.com/jmorganca/ollama/assets/31348710/c40cebce-dafa-49af-b2bc-d382dd5c3259)

**Comment by technovangelist** [comment]
That's an error from your Mac. These models can be big. I often have to delete models I don't want to make room for more and I have 4 TB.

**Comment by daaniyaan** [comment]
> That's an error from your Mac. These models can be big. I often have to delete models I don't want to make room for more and I have 4 TB.

weird that there is nothing to delete and when i try to pull the data it resume and says not enough space.

![CleanShot 2023-10-03 at 17 26 15](https://github.com/jmorganca/ollama/assets/31348710/4fa320ad-eccb-4981-8eae-a2af9e9cc2b8)

**Comment by mxyng** [comment]
Are you running ollama in a container? The model path `/usr/share/ollama` is a giveaway because it's used exclusively for Linux installs. If that's the case, Docker Desktop allocate a subset of total system disk space for the Linux VM hosting the container runner. You could increase this in Docker Desktop settings. 

If this isn't the case, please describe your installation environment and process.

**Comment by daaniyaan** [comment]
maybe the problem is related to curl that even tho you're tying to pull the model from macos while you use curl it try to download it in /usr/share ?

**Comment by nimkar** [comment]
Can you check what is listening to your port 11434 ? 

`lsof -i:11434`

**Comment by daaniyaan** [comment]
> Can you check what is listening to your port 11434 ?
> 
> `lsof -i:11434`

![CleanShot 2023-10-04 at 00 19 23](https://github.com/jmorganca/ollama/assets/31348710/d7da1bff-2f52-4799-a79f-0d36d33df839)

**Comment by mxyng** [comment]
Is it possible your Ollama is configured to use another instance? Can you run `OLLAMA_HOST` and paste the outputs?

**Comment by daaniyaan** [comment]
I managed to fix this by cloning the source code and then building from the source.
and then using the proxy to download the model via "ollama pull mistral" instead of using curl.
so the problem could have been either
- ollama command wasn't respecting my proxy
- there was a problem with downloading via curl

**Comment by mxyng** [comment]
It was the first one, not using configured proxies, which is fixed in #743

**Comment by daaniyaan** [comment]
> It was the first one, not using configured proxies, which is fixed in #743

looks like it's still there.
![image](https://github.com/jmorganca/ollama/assets/31348710/6e4998e8-b8d3-48d7-bf72-b71ab37024c0)

**Comment by r0mer0** [comment]
I managed this issue editing the `/etc/systemd/system/ollama.service` file adding the line:

`Environment="OLLAMA_MODELS=/any-path-with-space/"`

Then restart the service:
```
sudo systemctl daemon-reload
sudo systemctl restart ollama.service
```

**Comment by potCookie** [comment]
> > 我已经通过编辑`/etc/systemd/system/ollama.service`文件添加了以下行来解决这个问题：
> > `Environment="OLLAMA_MODELS=/any-path-with-space/"`
> > 然后重新启动服务：
> > ```
> > sudo systemctl daemon-reload
> > sudo systemctl restart ollama.service
> > ```
> 
> hi，请问下这样新的模型存储地址放到那里了

我这样配置了，启动时还是不行，依然报同样的错误，同样的no space路径，请问是否还有哪些额外配置？

**Comment by potCookie** [comment]
> > > 我已经通过编辑`/etc/systemd/system/ollama.service`文件添加了以下行来解决这个问题：
> > > `Environment="OLLAMA_MODELS=/any-path-with-space/"`
> > > 然后重新启动服务：
> > > ```
> > > sudo systemctl daemon-reload
> > > sudo systemctl restart ollama.service
> > > ```
> > 
> > 
> > hi，请问下这样新的模型存储地址放到那里了
> 
> 我这样配置了，启动时还是不行，依然报同样的错误，同样的no space路径，请问是否还有哪些额外配置？

最后通过扩展/tmp空间解决……
