### ISSUE TITLE
Stop Ollama

### ISSUE THREAD

**Issue by pmorange** [jmorganca/ollama#690]
Hi,
How can I stop Ollama ? 
If I run with "ollama run llama2" for instance and then quit with "Ctrl-C", then go to http://127.0.0.1:11434/ in a browser, it shows "Ollama is running"
When I kill the running process with a kill -9, a new process is instantly spawned.
Therefore I don't know how to totally stop Ollama... 
(I'm on macos)

**Comment by BruceMacD** [comment]
Are you using the Ollama Mac app? If so just exiting the toolbar app will stop the server. The Mac app will restart the server also, if left open.

Here:
![image](https://github.com/jmorganca/ollama/assets/5853428/8eaaffa4-114c-4bea-98a6-05e72367c13d)

Otherwise, in a terminal:
```
$ pgrep ollama
74877
$ kill 74877
```

or to stop the Mac App:
```
osascript -e 'tell app "Ollama" to quit'
```

**Comment by pmorange** [comment]
Thanks a lot, I didn't check in the upper toolbar, my bad. 
Indeed, closing properly from there stopped spawning new processes.
Thanks again :-)

**Comment by dongyuwei** [comment]
The bug not fixed, can't kill it on Mac.
ollama version 0.1.1

**Comment by BruceMacD** [comment]
@dongyuwei have you exited the mac app from the toolbar?

**Comment by dongyuwei** [comment]
Yes. @BruceMacD 
I logout my system then re-login, no more ollma.

**Comment by jwandekoken** [comment]
This is happening on Linux too. After I issue the command `ollama run model`, and after I close the terminal with `ctrl + D`, the ollama instance keeps running. If I kill it, it just respawn.

**Comment by devhims** [comment]
> Are you using the Ollama Mac app? If so just exiting the toolbar app will stop the server. The Mac app will restart the server also, if left open.
> 
> Here: ![image](https://user-images.githubusercontent.com/5853428/272356926-8eaaffa4-114c-4bea-98a6-05e72367c13d.png)
> 
> Otherwise, in a terminal:
> 
> ```
> $ pgrep ollama
> 74877
> $ kill 74877
> ```

Thanks! This worked on MacOS.

**Comment by JermellB** [comment]
sudo service ollama stop worked for me on ubuntu

**Comment by devwaseem** [comment]
For Mac: 
```pkill ollama```  works

**Comment by airtonix** [comment]
> systemctl stop ollama.service

Should this not be made obvious by an abstraction? 

```
ollama server start --system

# prompts for sudo to create system.d unit if it doesn't exist and start it

ollama server stop --system

# again, sudo required.

ollama server start

# no sudo required

# user presses: ctrl + d

# server stops.
```

**Comment by shayneoneill** [comment]
This really is not a great behavior. Thanks to that notch, the llama icon gets obscured so its not obvious at all its running nor how to access that toolbar item. Is there some sort of config option to just forbid the system from putting things there and using command line start/stop instead? Can I just remove the service entirely? 

pkill ollama does NOT solve the problem btw as it somewhat disobediently just restarts it.

**Comment by tmceld** [comment]
also having this problem on mac - its def. running, but i don't have anything in the taskbar and pgrep/kill just causes a restart

**Comment by marhar** [comment]
I've been having similar problems on my mac... server is running, I don't see anything on my taskbar to stop it, and I can't install the new ollama since the process is running.  pkill/pgrep etc as per other users, killing the process just restarts it.

I worked around by `rm -rf /Applications/Ollama; pkill ollama` which caused an error.  Following that, ollama process was not running, and I could install the new Ollama.app into /Applications.

**Comment by MehrCurry** [comment]
> rm -rf /Applications/Ollama; pkill ollama

It has to be `rm -rf /Applications/Ollama; pkill ollama`

**Comment by AnirudhaGohokar** [comment]
How do i stop on windows

**Comment by keebOo** [comment]
In the Mac terminal, I am attempting to check if there is an active service using the command:

`lsof -i :11434`

This is to verify if anything is running on the ollama standard port.

Following suggestions from other users, I then execute also:

`pgrep ollama`

After this, if the `lsof` command shows any process, I use the `kill` command followed by the PID to terminate the service (pgrep show eventually all the ollama process)

**Comment by HazemElAgaty** [comment]
I was only able to kill the process using the activity monitor.

**Comment by skytodmoon** [comment]
I use 'systemctl stop ollama.service' to stop the ollama
But when I use 'systemctl start ollama.service', the default port is bind again.
How to stop the service really?

**Comment by techkanna** [comment]
How do i stop on windows??

**Comment by sohaibsoussi** [comment]
> How do i stop on windows??

Use this commande in your powershell : ` Get-Process | Where-Object {$_.ProcessName -like '*ollama*'} | Stop-Process`

**Comment by hpsaturn** [comment]
In my Debian I can reproduce it. Nothing works: `kill`, `service stop` or `systemctl` fails trying to stop the service, and also produce conflicts with my `amdgpu` driver: #3527

**Comment by trustedtomato** [comment]
Not a good practice, but `pkill -9 ollama` works for now on Arch Linux (probably other distros as well). Haven't experienced any file corruption so far, but be careful with it.

**Comment by hpsaturn** [comment]
re-open the issue? maybe yes..

**Comment by gros-chat** [comment]
> > rm -rf /Applications/Ollama; pkill ollama
> 
> It has to be `rm -rf /Applications/Ollama.app; pkill ollama`

it worked for me (Mac)

**Comment by lselector** [comment]
This works on Mac:  sudo pkill -9 ollama Ollama

**Comment by lzhhh93** [comment]
@

> > How do i stop on windows??
> 
> Use this commande in your powershell : ` Get-Process | Where-Object {$_.ProcessName -like '*ollama*'} | Stop-Process`

On my side, this command seems to only kill the ollama server but does not release RAM. RAM needs to be released manually in task manager.

**Comment by alby13** [comment]
> @jwandekoken On Linux Ollama is running on as a systemd service. You can stop it using `systemctl`.
> 
> ```
> $ systemctl stop ollama.service
> ```

We used systemctl and we noticed that ollama was running in the background.
We ran this command to disable the auto-starting of the ollama server, and we can start it manually.
To start it manually, we use this command: sudo systemctl start ollama.service

Thank you for the information.

**Comment by p1r473** [comment]
Add an execstop for your systemd file
```
[Service]
ExecStop=/bin/kill -TERM $MAINPID
```

**Comment by joliss** [comment]
On Mac, this problem seems to be fixed as of a few releases ago (currently on 0.1.38). 👍 Quitting the Ollama app in the menu bar, or alternatively running `killall Ollama ollama`, reliably kills the Ollama process now, and it doesn't respawn.

**Comment by Eliyahou** [comment]
in Windows the command is 
Get-Process | Where-Object {$_.ProcessName -like '*ollama*'} | kill

**Comment by metamec** [comment]
> in Windows the command is Get-Process | Where-Object {$_.ProcessName -like '_ollama_'} | kill

That causes it to restart here.  This works better: 

`Stop-process -name "ollama", "ollama app"`

It's a horrible way to exit the program though.

Clicking 'quit ollama' from the systray app will close it down gracefully (ie. all ollama processes are quit too).  The systray app does not handle the WM_CLOSE message though so we can't use $process.CloseMainWindow() from Powershell to do the same.   It's gotta be nuked. 

I'm tempted to write a Powershell wrapper to get around all my problems with the systray app.  The other night it even notified me of an update while I was watching a film.  🤨

**Comment by godefroi** [comment]
> RAM needs to be released manually in task manager.

@lzhhh93 what does this even mean? A process, when stopped, does not consume any memory, and "task manager" does not have any functionality for "manually" "releasing" memory.

**Comment by pawliczka** [comment]
> > RAM needs to be released manually in task manager.
> 
> @lzhhh93 what does this even mean? A process, when stopped, does not consume any memory, and "task manager" does not have any functionality for "manually" "releasing" memory.

I have the same problem. When you TerminateProcess ollama.exe on Windows ollama_llama_server.exe is not terminated.

**Comment by Skarian** [comment]
> > > RAM needs to be released manually in task manager.
> > 
> > 
> > @lzhhh93 what does this even mean? A process, when stopped, does not consume any memory, and "task manager" does not have any functionality for "manually" "releasing" memory.
> 
> I have the same problem. When you TerminateProcess ollama.exe on Windows ollama_llama_server.exe is not terminated.

I am having this exact same issue. Am able to end ollama.exe but the runners stay running and using RAM seemingly perpetually.

**Comment by kleer001** [comment]
I too would appreciate the syntatic sugar of an 'ollama server_stop' command.

**Comment by Vimiso** [comment]
I found on mac `pkill ollama` doesn't work because the main process actually starts with a capital.

`pkill Ollama` should do it.

**Comment by cedricferry** [comment]
if you use Hombrew:
```
$ brew services stop ollama
```

**Comment by AledHe** [comment]
> > @jwandekoken On Linux Ollama is running on as a systemd service. You can stop it using `systemctl`.
> > ```
> > $ systemctl stop ollama.service
> > ```
> 
> We used systemctl and we noticed that ollama was running in the background.
> 
> We ran this command to stop the process and disable the auto-starting of the ollama server, and we can restart it manually at anytime. To start it manually, we use this command: sudo systemctl start ollama.service
> 
> However, we noticed that once we restarted the ollama.service and then reboot the machine, the process gets added to the auto-start again.
> 
> So what we did was we stop the process, and then disable it every time. This prevents it from automatically starting when Linux is started. The commands are:
> 
> sudo systemctl stop ollama.service sudo systemctl disable ollama.service
> 
> Thank you for the original information in your post.

Very useful method, for an auto script:
`
#!/bin/bash

check_ollama() {
    pgrep ollama > /dev/null
}

check_autostart() {
    systemctl is-enabled --quiet ollama.service
}

check_service_active() {
    if systemctl is-active --quiet ollama.service; then
        echo "Ollama service is active."
    else
        echo "Ollama service is inactive."
    fi
}

start_service() {
    if check_ollama; then
        echo "Ollama is already running."
    else
        echo "Starting Ollama service..."
        sudo systemctl start ollama.service
        echo "Ollama service started."
    fi
}

disable_service() {
    if check_ollama; then
        echo "Disabling and stopping Ollama service..."
        sudo systemctl stop ollama.service
        sudo systemctl disable ollama.service
        echo "Ollama service stopped and disabled."
    else
        echo "Ollama is not running. No need to disable."
    fi
}

disable_autostart() {
    if check_autostart; then
        echo "Disabling Ollama service auto-start..."
        sudo systemctl disable ollama.service
        echo "Ollama service auto-start disabled."
    else
        echo "Ollama service auto-start is already disabled."
    fi
}

echo "Checking Ollama service status..."
check_service_active
echo

PS3="Select an option: "
options=("Start Ollama service" "Disable Ollama service" "Disable Ollama auto-start" "Exit")
select opt in "${options[@]}"
do
    case $REPLY in
        1) start_service; break ;;
        2) disable_service; break ;;
        3) disable_autostart; break ;;
        4) echo "Exiting."; exit ;;
        *) echo "Invalid option. Please select 1-4." ;;
    esac
done
`
Please sudo first to run the bash : ))

**Comment by flashlan** [comment]
What works for me is:
```bash
killall pt_main_thread
```

**Comment by MrBns** [comment]
why so many drama to stop Ollama. why not just ollama stop model/name. and stopped that.

**Comment by Mustafanaji0413** [comment]
> This works on Mac: `sudo pkill -9 ollama Ollama`
> 
> Then double-click on Ollama in Applications to start it

Thus works for mac! THANKS!!

**Comment by gvirus21** [comment]
Facing this problem for 30 minutes, Solved it by just force-killing Ollam from Mac's activity monitor.

**Comment by Ranjithdss15** [comment]
For Mac:

Close the ollama process from the Activity Monitor and avoid confirming it again with ollama ps from your terminal, as this will restart the process.

**Comment by kiran-bsv** [comment]
If ollama is managed by systemd, you can stop and disable it with these commands:

```
sudo systemctl stop ollama
sudo systemctl disable ollama
```

This worked for me

**Comment by alaeddingurel** [comment]
> If ollama is managed by systemd, you can stop and disable it with these commands:
> 
> ```
> sudo systemctl stop ollama
> sudo systemctl disable ollama
> ```
> 
> This worked for me

Thank you! This worked for me too!

**Comment by tranvanthai** [comment]
It worked with me
`sudo pkill -9 ollama Ollama`

**Comment by webdev23** [comment]
Without all the mess, simply closing the HTTP connection client-side is what you are looking for.

**Comment by shayneoneill** [comment]
Has there been any movement on this bug? Its been months now, and my current solution of uninstalling it or rebooting the computer is incredibly onerous. 

Does *anyone* know how to stop it on a mac without rebooting?

**Comment by chenshaoju** [comment]
Why can't we elegantly stop ollama? For example: `ollama.exe stopserve`

**Comment by tobsecret** [comment]
@shayneoneill you can go to the activity manager, sort by name and select and close all processes with ollama in the name.
There is an ollama helper process which I would guess is what restarts the main ollama process in case it crashes but it seems it might also restart it if you deliberately kill the ollama process.

**Comment by webdev23** [comment]
In Linux, without sudo, eiher wait 5 minutes to free up the VRAM, or:

`curl -s http://localhost:11434/api/generate -d '{"model": "'$(ollama ps | tail -n1 | cut -d ' ' -f1 )'", "keep_alive": 0}'`

You should get:
`.... "done_reason":"unload"`

**Comment by lamberta** [comment]
> Does _anyone_ know how to stop it on a mac without it restarting?

I just hit this using when running the ollama-darwin binary (with no menu icon) ...
The following worked for me on macos (from comment above): `sudo pkill -9 ollama Ollama`

**Comment by abdrhxyii** [comment]
I used windows, I manage to fix it by manually opening the task manager with ctr + shift + esc command, then i found out already there is an alama running, right clicked it and end the task, then in the powershell. I restarted the olama. and now it works

**Comment by tyagi-py** [comment]
Spent few minutes struggling, I figured out if you installed it through homebrew you need to run `brew services stop ollama` to stop it, else it'll respawn itself for no reason.

**Comment by ramonjd** [comment]
>  I figured out if you installed it through homebrew you need to run brew services stop ollama to stop it, else it'll respawn itself for no reason.

Thank you! This was driving me crazy.

**Comment by ultimatedirty** [comment]
In my case I wanted to increase the context length through an environment variable, so i did this

> pkill ollama; OLLAMA_CONTEXT_LENGTH=32768 ollama serve

**Comment by austindd** [comment]
Weirdly, running `pkill ollama` on MacOS did kill the process, but it just automatically restarts in a new process. Clicking the toolbar icon and quitting from the dropdown menu worked as expected.

I think I understand the reasoning behind this behavior... It's convenient for other programs to not worry about how to restart Ollama when it fails for whatever reason, so auto-restart makes sense for that use case. But it's a very unintuitive behavior. Most professional programmers would just assume `pkill ollama` or `kill -9 <pid>` would just work.

I would suggest adding a command to the Ollama CLI tool to force it to tear itself down without restarting. Maybe `ollama destroy` or something like that?

**Comment by SinghAayushi** [comment]
Using below approach worked for me: openclaw gateway stop

I did following thing to debug: 

lsof -i:18789   - To find the process id 
ps -j -p 1718 - With the process id, I got process id of parent
ps -p 1  - Then when I checked parent process id, I saw that it's running from /sbin/launchd
From /sbin/launchd it's automatically picked and started

**Comment by rbeazleyspot** [comment]
i found the process was managed by `brew services` and running `brew services stop ollama` was the way forward

just like this user said: https://github.com/ollama/ollama/issues/690#issuecomment-2257191133
