### ISSUE TITLE
Can't resume download (pull) on restart server 

### ISSUE THREAD

**Issue by KcZLog** [jmorganca/ollama#695]
Auto pruning on server start was added in #491
But this cause losing unfinished/failed download progress if restarting server

Please change this to allow continuing downloads. 

Suggestions: 
1. Don't auto prune, pruning on delete is probably enough? 
2. If want auto prune, use seperate directory for unfinished download, or use name prefix (may orphan unfinished file if new version)
3. Use a file to list every downloads, and don't prune those files. If new version, update the list, previous unlisted files automatically get pruned. 
4. Immediately create the manifest before download, to prevent pruning those files, and add + check property for incomplete download.

**Comment by BruceMacD** [comment]
Hi @KcZLog as a workaround you can set the `OLLAMA_NOPRUNE` environment variable.

For example:
```
OLLAMA_NOPRUNE=true ollama serve
```

Or adding it to your $PATH.

**Comment by KcZLog** [comment]
Hi thank you, I'm aware and have set the `OLLAMA_NOPRUNE` env since finding #491, and it does prevent pruning on start/serve.

But others who have download issues, may be frustrated to lose their download progress when restarting server, especially #330 hints to restart the server. Hopefully this gets fixed soon.

**Comment by technovangelist** [comment]
It looks like Bruce's comment solved your issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by technovangelist** [comment]
actually, it looks like the only mention of that environment variable is in a buried issue and PR. I am updating the docs to mention this.

**Comment by technovangelist** [comment]
And I am going to re open this, because NOPRUNE is definitely a workaround and not the actual solution.

**Comment by mxyng** [comment]
Pruning by default is the desired behaviour. The issue seems to be restarting the server after a failed download which should _not_ be the go to solution. Instead, repulling will resume where the previous download left off. 

Restarting the server should be the last resort.

**Comment by cyangalaxy** [comment]
Ollama's pull feature, for me, has been completely unreliable. 90% of the time the download stops.

Because of this, I instead download the models from HuggingFace and import them. This way I have the model as a file and don't need to redownload the models in case I move computers or reinstall my OS.

**Comment by siakc** [comment]
Recently I tried to pull llama3.3 which is about 40 GBs. It stuck at 50%. I canceled and repeated the pull. It stuck again. Had to restart the system. This time it started from start while NOPRUNE was set.

**Comment by exalented** [comment]
Extremely annoying. Just make the `OLLAMA_NOPRUNE=true` the default and then let ppl prune on their own as losing a download sucks on slow connections.
