### ISSUE TITLE
Offline Installation and Model Download

### ISSUE THREAD

**Issue by OguzcanOzdemir** [jmorganca/ollama#696]
Hello,

I'm trying to install ollama on an offline Ubuntu computer, Due to the lack of an internet connection, I need guidance on how to perform this installation offline. Additionally, I would like to understand how to download and utilize models on this offline Ubuntu machine.

Here are the specific questions and challenges I'm facing:

Offline Installation:

Is it possible to download all the necessary installation files and dependencies on an online machine and then transfer them to the offline Ubuntu computer?
Can you provide step-by-step instructions for manually installing the software offline?
Are there any specific dependencies or libraries that I need to be aware of for the installation?

Offline Model Usage:
How can I download pre-trained models or data sets for the software offline?
Once the models are downloaded, how can I integrate them with the software and use them?

I would greatly appreciate any guidance or assistance you can provide to help me with this offline installation and model usage. 
Thank you in advance for your help!

**Comment by BruceMacD** [comment]
Hi @OguzcanOzdemir, Ollama will work offline. Here are some install steps.

**Offline installation:**
This will be possible by downloading the `ollama-linux-ARCH` binary then moving it onto your offline machine.
You can find the binary in the release assets here:
https://github.com/jmorganca/ollama/releases

If you want to use you GPU you will also need to install the relevant CUDA driver:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local

**Offline model usage:**
The easiest way to do this would be to download the Ollama models on a machine which is connected to the internet, then moving the `~/.ollama` directory to the offline machine.

**Comment by Mouradif** [comment]
What if I already downloaded the model from Facebook, where should I put it for ollama to be able to use it?

**Comment by HEI201** [comment]
hi, i want to download models from ollama and move to a offline computer to use it in ollama, is there any guide or instructions to flow?

**Comment by zioalex** [comment]
Why has this been closed? I do not see any real answer here.
Has anybody an update on how to do it?

**Comment by nbfhscl** [comment]
need an answer

**Comment by Pyenb** [comment]
For anyone interested on where to put the model after downloading: https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by Pyenb** [comment]
Hey there, small update for anyone interested. Since this was still bothering me, I took matters into my own hands and created an [Ollama model repository](https://github.com/Pyenb/Ollama-models), where you can download the zipped official Ollama models and import them to your offline machine or wherever.

Any feedback is appreciated 👍 More models will be coming soon.

**Comment by MikeB2019x** [comment]
> Hey there, small update for anyone interested. Since this was still bothering me, I took matters into my own hands and created an [Ollama model repository](https://github.com/Pyenb/Ollama-models), where you can download the zipped official Ollama models and import them to your offline machine or wherever.
> 
> Any feedback is appreciated 👍 More models will be coming soon.

Literally _just_ had this need come up an hour ago.  Well done!

**Comment by amirrezaDev1378** [comment]
If anyone did not find a solution for their problem, I've created this simple app that will give you links to download and model in any size you want from the Ollama registry:

https://github.com/amirrezaDev1378/ollama-model-direct-download

**Comment by yelog** [comment]
> hi, i want to download models from ollama and move to a offline computer to use it in ollama, is there any guide or instructions to flow?

@HEI201 I successfully installed an offline model downloaded from Hugging Face, you can check it out. [Installing Ollama offline and loading offline models](https://yelog.org/2024/10/10/install-ollama-offline-english/)

**Comment by cgjosephlee** [comment]
Since ollama has a similar CLI interface to docker, I implement `save` and `load` functions to ollama just like docker, for transferring models to remote server without access to internet. 
https://github.com/cgjosephlee/ollama-save-load
```sh
ollama pull gemma2:2b-instruct-q4_K_M
ollama list

export OLLAMA_MODELS="/path/to/ollama/models"  # change this if you have alternative path
./ollama-save.py gemma2:2b-instruct-q4_K_M | gzip > gemma2.tar.gz
./ollama-load.py gemma2.tar.gz
```

**Comment by kaoutaar** [comment]
@yelog hey! i am trying to follow the steps in you blog, but i can't find the install.sh file you're talking about in the extracted directory 

> Extract the installation package ollama linux amd64.tgz, navigate to the extracted directory, and run the install.sh script to complete the installation.

here is what i get when i extract the files:
`!tar -zxvf /kaggle/working/ollama-linux-amd64.tgz`

`./
./lib/
./lib/ollama/
./lib/ollama/libcublas.so
./lib/ollama/libcudart.so.12
./lib/ollama/libcublasLt.so.12.4.5.8
./lib/ollama/libcudart.so
./lib/ollama/libcudart.so.11.0
./lib/ollama/libcublas.so.11
./lib/ollama/libggml_cuda_v11.so
./lib/ollama/libcublas.so.12
./lib/ollama/libcudart.so.11.3.109
./lib/ollama/libcublas.so.12.4.5.8
./lib/ollama/libhipblas.so.2
./lib/ollama/libcudart.so.12.4.127
./lib/ollama/librocblas.so.4
./lib/ollama/libcublasLt.so.11.5.1.109
./lib/ollama/librocblas.so.4.1.60102
./lib/ollama/libcublasLt.so.11
./lib/ollama/libcublas.so.11.5.1.109
./lib/ollama/libggml_rocm.so
./lib/ollama/libcublasLt.so.12
./lib/ollama/libcublasLt.so
./lib/ollama/libggml_cuda_v12.so
./lib/ollama/libhipblas.so.2.1.60102
./bin/
./bin/ollama`
