### ISSUE TITLE
Can not download the model of codellama:13b

### ISSUE THREAD

**Issue by danny-su** [jmorganca/ollama#697]
<img width="1004" alt="image" src="https://github.com/jmorganca/ollama/assets/12178855/0de2b8b6-6b26-4f67-b70e-b73de8020852">

**Comment by jmorganca** [comment]
@danny-su thanks for the issue. Are you running behind an https proxy by chance?

**Comment by igorschlum** [comment]
It works for me with version 0.1.0 on MacOS

**Comment by danny-su** [comment]
> @danny-su thanks for the issue. Are you running behind an https proxy by chance?

Yes, I used http proxy, but even if using a VPN, I still got the same error.

**Comment by danny-su** [comment]
@jmorganca When visiting https://registry.ollama.ai/v2/library/codellama/manifests/13b-instruct in browser, I got the following error:
<img width="1035" alt="image" src="https://github.com/jmorganca/ollama/assets/12178855/1987daef-1aab-42f6-b965-9f1b6f021410">

**Comment by igorschlum** [comment]
I have the same

**Comment by BruceMacD** [comment]
A workaround for the proxy issue was suggested here:
https://github.com/jmorganca/ollama/issues/676#issuecomment-1744722380

Worth a try.

**Comment by danny-su** [comment]
> A workaround for the proxy issue was suggested here: [#676 (comment)](https://github.com/jmorganca/ollama/issues/676#issuecomment-1744722380)
> 
> Worth a try.

It doesn't work for me.

**Comment by danny-su** [comment]
Great, ollama is pulling the model, it looks like the issue was fixed.
<img width="1001" alt="image" src="https://github.com/jmorganca/ollama/assets/12178855/d9be57f8-1996-403c-b012-2249c915b317">
