### ISSUE TITLE
How to uninstall ollama ai on Linux

### ISSUE THREAD

**Issue by scalstairo** [jmorganca/ollama#698]
How can ollama be uninstalled on linux? Do not see an obvious entry the package listings

**Comment by BruceMacD** [comment]
If you have any feedback to how we could improve Ollama, please let me know. Would love to hear your opinion.

Here is how you can uninstall:
1. stop the ollama service: 
```
$ systemctl stop ollama
```
2. remove the ollama service from start-up: 
```
$ systemctl disable ollama
```
3. remove the ollama binary from your bin directory (either `/usr/local/bin`, `/usr/bin`, or `/bin`): 
```
rm /usr/local/bin/ollama
```
4. remove the downloaded models and configuration: 
```
$ rm -r ~/.ollama
```

**Comment by jameswilky** [comment]
For me, the `.ollama` folder was in ~`/usr/share,` not `~/`.

It would be neat to have an `ollama update` or `ollama uninstall` to basically do the above, so that we can upgrade llama as needed to keep up to date with new versions

**Comment by pabloasanchez** [comment]
The script also adds an `ollama` user, so additionally need to do
`$ userdel ollama`
