### ISSUE TITLE
Allow for directed dir installation

### ISSUE THREAD

**Issue by vRobM** [jmorganca/ollama#704]
Ask where the users wants it installed, with some defaults if you want to be nice.

Forcing install in /usr/local/bin is unusable in containers and other file system mapped configurations

**Comment by jmorganca** [comment]
Hi @vRobM! Thanks for creating an issue. For a customized install see the [Linux](https://github.com/jmorganca/ollama/blob/main/docs/linux.md) guide which contains the full install steps
