### ISSUE TITLE
127.0.0.1:11434: bind: address already in use

### ISSUE THREAD

**Issue by Nivek92** [jmorganca/ollama#707]
When I run `ollama serve` I get

`Error: listen tcp 127.0.0.1:11434: bind: address already in use`

After checking what's running on the port with `sudo lsof -i :11434`

I see that ollama is already running

`ollama  2233 ollama    3u  IPv4  37563      0t0  TCP localhost:11434 (LISTEN)`

I killed the process and ran the serve command again and got the same error. So it seems that it tries to start the server twice.

**Comment by BruceMacD** [comment]
Is this on Mac or Linux?

On Mac the app (running in the toolbar) will automatically restart the server when it stops. Exit the toolbar app to stop the server.

On Linux the Ollama server is added as a system service. To stop it you can run `$ systemctl stop ollama`.

**Comment by xyproto** [comment]
`brew services restart ollama` might also be helpful, if on macOS.

**Comment by orpic** [comment]
same happened with me but only after the initial install.
Running from next time after `systemctl stop ollama` , it worked fine.

**Comment by Nivek92** [comment]
yeah it's on Linux, Ubuntu specifically. It's not really a problem as the service is working but very confusing as it happens on the initial install, when you don't assume the service is already running, making you believe another service is blocking the port.

**Comment by Yadheedhya06** [comment]
https://github.com/jmorganca/ollama/pull/872

**Comment by technovangelist** [comment]
It looks like this issue was solved already as per the linked issue as well as Bruce's comment. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by ibehnam** [comment]
I'm on macOS and still have the issue even after doing `brew services restart ollama`. I used to see ollama's icon in menu bar but not anymore.

**Comment by DoLife** [comment]
I`m having the same isssue but Im on windows using the docker

**Comment by buts101** [comment]
disable firewalld or any other ip filtering

**Comment by ClaudeRobbinCR** [comment]
@technovangelist Actually, I was just running it on WSL2 ubuntu 22.04, and it showed the same error.

**Comment by shivrajjadhav733** [comment]
OS - Apple M1 Pro chip

I tried to install ollama on machine. Installation was successful. I can see Ollama icon in menu bar at the top.

when I try to run model using command -

ollama run laama2 
Or
ollama run mistral 

I get attached error of operation timed out.

![BC48A4D0-AA86-41AA-B611-961467611449](https://github.com/jmorganca/ollama/assets/35407279/6532b007-2626-4f4a-87fc-499aa96e9d2f)


I tried to run - brew services restart ollama and I got error saying “ Error: Formula ‘ollama’ is not installed.


How do I fix the errors and run models using ollama?

**Comment by inteligenciamilgrau** [comment]
For me it's is happening because ollama was already running

try:

`systemctl status ollama`

And you will get something like:

` ollama.service - Ollama Service
     Loaded: loaded (/etc/systemd/system/ollama.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-02-05 08:33:09 -03; 25min ago
   Main PID: 3525 (ollama)
      Tasks: 51 (limit: 9459)
     Memory: 4.6G
     CGroup: /system.slice/ollama.service
             └─3525 /usr/local/bin/ollama serve`

To start/stop this service use:

`systemctl stop ollama
systemctl start ollama`

**Comment by lovincyrus** [comment]
If you're still encountering this on mac,

```
lsof -i :11434
kill <PID>
```

**Comment by HPUhushicheng** [comment]
ubuntu/debian
`sudo apt update`
`sudo apt install lsof`
`lsof -i :11434`
`kill <PID>`
`ollama serve`

centos
`sudo yum update`
`sudo yum install lsof`
`lsof -i :11434`
`kill <PID>`
`ollama serve`

**Comment by abdurahmanadilovic** [comment]
when I run `lsof -i :11434` I get no results, but if I do `ollama serve` I still get the address already in use error

**Comment by DeepNeurons** [comment]
i encountered the same issue on Ubuntu 20.04.5 LTS 
solution : export OLLAMA_HOST=localhost:8888
source : [here](https://pypi.org/project/ollamac/)

**Comment by Tchez** [comment]
> When I run `ollama serve` I get
> 
> `Error: listen tcp 127.0.0.1:11434: bind: address already in use`
> 
> After checking what's running on the port with `sudo lsof -i :11434`
> 
> I see that ollama is already running
> 
> `ollama 2233 ollama 3u IPv4 37563 0t0 TCP localhost:11434 (LISTEN)`
> 
> I killed the process and ran the serve command again and got the same error. So it seems that it tries to start the server twice.

Try this:

```bash
 sudo systemctl stop ollama
```

> I wasn't able to do it without 'sudo'

**Comment by svr123456789** [comment]
Look like need to add 
`Environment="OLLAMA_HOST=0.0.0.0:11434"` 
into /etc/systemd/system/ollama.service

**Comment by AmmariAbdelmounaim** [comment]
Ran into a bit of a snag with WSL where I was still getting errors even after stopping ollama using `systemctl stop ollama`. Turns out the listener port was still active. Here's a quick fix I found that worked for me on Windows:

Fire up your Command Prompt as admin and run the following to grab the PID of the problematic port:`netstat -aon | findstr :11434`
With the PID in hand, kill the process: `taskkill /F /PID <PID>`
Make sure to replace <PID> with your actual process ID.
After that's done, just restart ollama: `ollama serve`

**Comment by Pathsis** [comment]
> Ran into a bit of a snag with WSL where I was still getting errors even after stopping ollama using `systemctl stop ollama`. Turns out the listener port was still active. Here's a quick fix I found that worked for me on Windows:
> 
> Fire up your Command Prompt as admin and run the following to grab the PID of the problematic port:`netstat -aon | findstr :11434` With the PID in hand, kill the process: `taskkill /F /PID <PID>` Make sure to replace with your actual process ID. After that's done, just restart ollama: `ollama serve`

我杀死了所有 pid，以至于运行`lsof -i :11434 `没有任何输出，但是运行`ollama serve`仍然得到这个错误。

**Comment by BruceMacD** [comment]
Hey all, not seeing ollama in the output of `lsof` could be a permissions issue. When you install ollama on linux via the install script it creates a service user for the background process. You may need to stop the process via systemctl in that case.

Here is some troubleshooting steps that will hopefully help:
- Stop the background service: `sudo systemctl stop ollama`
- Run `lsof` as sudo to rule out permissions issues: `sudo lsof -i :11434`

**Comment by RichardScottOZ** [comment]
that has seemed to work thanks Bruce

**Comment by justingolden21** [comment]
Same problem here (win10)

![image](https://github.com/ollama/ollama/assets/30274440/5b673cac-aec8-44aa-bc51-5326cb06d394)

I only run ollama through command prompt and it doesn't let me kill the process

![image](https://github.com/ollama/ollama/assets/30274440/2b166fb3-3ee0-4c03-96b9-94c9e53d8a8f)

**Comment by fcalabrow** [comment]
On Windows, make sure that Llama app is not already running. Hit the right click and then quit Llama, then run it from the terminal
<img width="176" alt="image" src="https://github.com/ollama/ollama/assets/87214888/4b18497a-45a8-4edc-bade-84f51b393a86">

**Comment by paralyser** [comment]
Fresh install.
System synology .
Installed with both docker and portainer.
Wiped/restarted/updated/reinstalled several times. Tried around 10 (8888,8778,11434,11535,11636,11433 etc.. )different ports, but every port gives the same error( with different ports).
Error: listen tcp 0.0.0.0:11434: bind: address already in use. 
Have no idea how to fix it.

**Comment by SebastianoF** [comment]
On Mac first install was naughty for me.

Even with the app quitted (from the top bar), the port was in use and being re-created immediately after killing it with `kill <PID>`.

So:
- I started again the ollama app again, double clicking on the applications list.
- I quitted it again via the right click icon, and the problem solved itself (I also disabled the app running at startup from the system settings, for the next time).

Now the ollama CLI from terminal works as expected, with the app still quitted.

**Comment by loveplay1983** [comment]
1. On Ubuntu, Ollama is typically installed as a `systemd service` that starts automatically at system startup. This means the Ollama API server is already running in the background, so you generally don't need to run `ollama serve` manually. If you do, the system complains with "127.0.0.1:11434: bind: address already in use."
 
2. To solve the issue, we can define a custom port in the service file as we do above. However, commands like `ollama list` will complain after we set up a custom port since they are bound to the default 11434. We can explicitly export the environment variable `OLLAMA_HOST` and use the same port defined in the service file. For example, `export OLLAMA_HOST=0.0.0.0:11450 # 11450 is the custom port defined in the service file.` Then, the command `ollama list` will work again.

**Comment by loveplay1983** [comment]
> When I run `ollama serve` I get
> 
> `Error: listen tcp 127.0.0.1:11434: bind: address already in use`
> 
> After checking what's running on the port with `sudo lsof -i :11434`
> 
> I see that ollama is already running
> 
> `ollama 2233 ollama 3u IPv4 37563 0t0 TCP localhost:11434 (LISTEN)`
> 
> I killed the process and ran the serve command again and got the same error. So it seems that it tries to start the server twice.

On Ubuntu, Ollama is typically installed as a systemd service that starts automatically at system startup. This means the Ollama API server is already running in the background, so you generally don't need to run ollama serve manually. If you do, the system complains with "127.0.0.1:11434: bind: address already in use."

To solve the issue, we can define a custom port in the service file as we do above. However, commands like ollama list will complain after we set up a custom port since they are bound to the default 11434. We can explicitly export the environment variable OLLAMA_HOST and use the same port defined in the service file. For example, export OLLAMA_HOST=0.0.0.0:11450 # 11450 is the custom port defined in the service file. Then, the command ollama list will work again.

**Comment by Haseeeb21** [comment]
@Jaykumaran 

> For **Ubuntu**
> 
> Step 1. `sudo nano /etc/systemd/system/ollama.service`
> 
> Add `Environment="OLLAMA_HOST=0.0.0.0:11434"`
> 
> Step 2: `source ~/.bashrc`
> 
> Step 3: `systemctl stop ollama`
> 
> If an warning pops up like: `Warning: The unit file, source configuration file or drop-ins of ollama.service changed on disk. Run 'systemctl daemon-reload' to reload units.`
> 
> Finally,
> 
> Step 4: `systemctl daemon-reload`
> 
> It should work now,
> 
> `ollama serve`

Worked Thanks!

**Comment by eniodev** [comment]
this worked for me https://github.com/ollama/ollama/issues/2194

**Comment by ghost** [comment]
This model is the best to work for Bittensor.com
