### ISSUE TITLE
Where is the model file path on MacOS

### ISSUE THREAD

**Issue by RoversX** [jmorganca/ollama#712]
Hello, I would like to know where is the model path on Mac OS and how can I fully uninstall Ollama because I installed it in the wrong place. 

Thanks

**Comment by RoversX** [comment]
Oh it's here

~/.ollama/models

**Comment by xyproto** [comment]
Ideally, Ollama should store the cache in `~/Library/Caches/ollama` on macOS, instead of in `~/.ollama`.

**Comment by Clivern** [comment]
Anyway to copy and release these models somehow for a multi node setup. I can't fine them locally. 

Under `~/.ollama/models` i see `blobs` and `manifests`

**Comment by RoversX** [comment]
> Anyway to copy and release these models somehow for a multi node setup. I can't find them locally!
> 
> Under `~/.ollama/models` i see `blobs` and `manifests`

If you check the folder size, it's under blobs

**Comment by justinmayer** [comment]
Knowing where models are stored, as well as what other things will happen on first launch, would be **_so_** much easier to discover and understand if someone would merge the [pull request I submitted back in August](https://github.com/jmorganca/ollama/pull/395) (#395).

It seems cruel to subject so many first-time users to this kind of confusion when the problem could be so easily solved by mashing the _Merge_ button 😞

**Comment by xyproto** [comment]
Also, when using ollama within a GitHub action, it would helpful to be able to cache models and only pull models if they are not already pulled. Having a file with the same name as the model (perhaps with ":" replaced with "_") would be nice.

**Comment by technovangelist** [comment]
You can put models anywhere you like when you use the OLLAMA_MODELS environment variable which I think addresses the issue. I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.

**Comment by brandoncarl** [comment]
Thanks for the repository.

I am running v0.1.13 on macOS Sonoma. The OLLAMA_MODELS environment variable is having no impact.

```
$ echo $OLLAMA_MODELS
(prints appropriate directory)

$ ollama run <model>
(downloads to ~/.ollama/..)

$ OLLAMA_MODELS=<directory> run <model>
(downloads to ~/.ollama/...)
```

**Comment by xyproto** [comment]
Looking at the code, `OLLAMA_MODELS` is only being respected when starting the Ollama server, and not when `ollama run` or `ollama pull` is being used (and `~` is not expanded, since `os.LookupEnv` is used).

Being able to run something like:

```sh
OLLAMA_MODELS=~/models ollama run mistral
```

would be nice.

Here's one way of expanding `~`, using my `env` package:

```go
package main

import "github.com/xyproto/env/v2"

func main() {
        // Will output a full path if OLLAMA_MODELS is set to ie. ~/models
	println(env.Dir("OLLAMA_MODELS"))
}
```

**Comment by mtrin** [comment]
same here -  OLLAMA_MODELS has no effect on the folder for the Mac app @technovangelist

**Comment by xyproto** [comment]
@brandoncarl @mtrin Is `OLLAMA_MODELS` set when executing `ollama serve`, or just when executing `ollama run`?

**Comment by mtrin** [comment]
seems like you have to quit the Mac app then run ollama serve with OLLAMA_MODELS set which is like the linux setup not a mac setup. from the documentation it didn't seem like ollama serve was a necessary step for mac.
once I did it, it worked

**Comment by brandoncarl** [comment]
The best workaround for this is to remove the environment variable and to instead create a symlink.

`ln -s <target_path> ~/.ollama/models`

**Comment by unikitty37** [comment]
There seems to be a setting for this in `Settings…` now — but the README still says to use the environment variable.

@technovangelist Is the environment variable still the best way to do this, or does the README need updating to reflect the UI change? (It's still worth keeping information on `launchctl setenv` around, of course, since there isn't UI for other variables…)
