### ISSUE TITLE
Using ollama with llm-ls

### ISSUE THREAD

**Issue by noahbald** [jmorganca/ollama#713]
I've been trying to setup ollama to use codellama with FIM in my editor with nvim.llm and llm-ls.
As suggested in the ollama docs, this is what the locally running API may expect as a FIM request.
```sh
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "codellama:7b-code",
  "prompt": "<PRE> def compute_gcd(x, y): <SUF>return result <MID>"
}'
```

However, when using llm-ls we can't (afaik) tell it how to structure the data it sends. It ends up sending a request that looks more like this
```sh
curl -X POST http://localhost:11434/api/generate -d '{
  "inputs": "<PRE> def compute_gcd(x, y): <SUF>return result <MID>",
  "parameters": { ... },
}'
```

Has anyone found a better way to set this up? Is there an alternative api endpoint we can use? Something like `/api/generate/codellama:7b-code?src=llm-ls`?

**Comment by noahbald** [comment]
https://github.com/gsuuon/llm.nvim#adding-your-own
I've found this part of the documentation on adding your own providers, I'll work on making a working example for others' reference

**Comment by noahbald** [comment]
Alternatively, llm-ls could support various backends?
https://github.com/huggingface/llm-ls/issues/17

**Comment by mxyng** [comment]
Thanks for creating this. I wasn't aware of llm-ls. I personally use copilot and created a proxy for intercepting and rerouting copilot requests to ollama requests. You can find it [here](https://github.com/mxyng/proxypilot). 

As for implementing this in ollama, we don't normally integrate with external projects and instead rely on the integration to implement compatibility. There are so many integrations so this approach will be unsustainable.
