### ISSUE TITLE
install script works but first prompt throws error

### ISSUE THREAD

**Issue by jonnytest1** [jmorganca/ollama#715]
![image](https://github.com/jmorganca/ollama/assets/13507796/70cd4325-f54e-4bdd-9171-fef2a775bf9a)

after testing around i noticed the file should be a json of some sort but i got no clue on the further details

**Comment by jonnytest1** [comment]
ok my bad - i think i had to run ollama run llama2 afterwards (maybe we can make it more obvious that that isnt part of the installation)

**Comment by BruceMacD** [comment]
Thanks for opening the issue.

You were using the API directly here, correct? I've seen this error a couple times now. The problem is that the model had to be pulled before it could be run (which the CLI does automatically). I'm going to improve the error message here.

**Comment by jonnytest1** [comment]
yes i just ran it in accordance to the installation instruction in the readme md
