### ISSUE TITLE
Change system model when running as a service

### ISSUE THREAD

**Issue by wifiuk** [jmorganca/ollama#717]
If I originally was messing around with Llama 7b and got it running as a background service, how do I change the model that it uses?

**Comment by BruceMacD** [comment]
Ollama orchestrates which model is loaded based on the model requested in your prompt. 

In other words, all you have to do is send a new request to Ollama, and if the requested model is changed the currently model is un-loaded and the new one is loaded in.

Ex:
```
$ ollama run llama2 hello
# llama2 is loaded and used to generate a response

$ ollama run mistral hello
# llama2 is un-loaded, mistral is loaded, and used to generate a response
```

**Comment by wifiuk** [comment]
i mean as the system service, not just in the terminal

**Comment by BruceMacD** [comment]
No problem, the system service is what actually manages the running model rather than the CLI tool. The CLI tool is just an interface for the system service.

**Comment by wifiuk** [comment]
i dont see where to mention the model in the ollama.service file:

  GNU nano 7.2                                                                                     /etc/systemd/system/ollama.service                                                                                              
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="HOME=/usr/share/ollama"
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
Environment="OLLAMA_HOST=0.0.0.0:11435"
Environment="OLLAMA_ORIGINS=http://x.x.x.x:*"
[Install]
WantedBy=default.target
