### ISSUE TITLE
On Windows, support configurable paths for storage

### ISSUE THREAD

**Issue by clebio** [jmorganca/ollama#730]
As a user of ollama on Windows, I would like to be able to store models and other large files on a secondary drive of my choosing.

I built from source and ran the server, then tried pulling models and realized I would run out of disk space. On my gaming rig, my C drive (where `$HOME` is) is fairly constrained and I store most things on a larger D.

I was able to work around this limitation with the following diff, but ideally this would be a command-line opt. I defer to y'all maintainers as to how you'd refactor this. Thanks for the awesome work!

```diff 
diff --git a/server/modelpath.go b/server/modelpath.go
index c6798a0..df48afc 100644
--- a/server/modelpath.go
+++ b/server/modelpath.go
@@ -123,10 +123,7 @@ func GetManifestPath() (string, error) {
 }

 func GetBlobsPath(digest string) (string, error) {
-       home, err := os.UserHomeDir()
-       if err != nil {
-               return "", err
-       }
+       home := "/d/ollama-data"

        if runtime.GOOS == "windows" {
                digest = strings.ReplaceAll(digest, ":", "-")
```

**Comment by mjtechguy** [comment]
+1

**Comment by BruceMacD** [comment]
Great feedback, this scenario was one of my targets for #897, it is now possible in the most recent release.
