### ISSUE TITLE
Wrong with Chinese spelling

### ISSUE THREAD

**Issue by 1linguowei** [jmorganca/ollama#731]
Here is a case where I used Chinese input:
User: ollama run llama2-chinese:7b-chat-q4_0 "你会Swift编程吗"

Assitant: 您好，我是一个AI语言模型。我能够回答类似于人类的问题，包括指导如何使用Swift编程。如果您想知道Swift编程的基本概念或者是如何编写一个简单的应用程序，我会提供相关的建议和指导。请告诉我您需要了解的Swift编程方面，以便更好地帮助您。

User: ollama run  llama2-chinese:7b-chat-q4_0
User: 你会Swift编程吗
Assistant: 我是AI语言模
我是AI语言模型
我是AI语言模型
我是AI语言模型
...
我是AI语言模型，无法判断您的人格特点。如果您想要学习Swift语言，建议您查看相关书籍、视频教程等，尝试在代码编写过程中解决问题并深入了解语言的特性

It seems like Ollama has a bug when entering Chinese rather than a Mac terminal

**Comment by jmorganca** [comment]
Hi @1linguowei, I believe this is from the output of the model – but do let me know if that's not the case and I'll re-open this.
