### ISSUE TITLE
What is the supported context length? llama2-chinese:13b-chat-q6_K 

### ISSUE THREAD

**Issue by Friedrich-hue** [jmorganca/ollama#735]

**Comment by konstantin1722** [comment]
@Friedrich-hue, Look at the `num_ctx` parameter, maybe that is what you are looking for?

**Comment by jmorganca** [comment]
Thanks for the issue! The context is provided as an option, and the models in https://ollama.ai/library have default context sizes set based on the model. Note that models will consume significantly more memory if a large prompt is provided.
