### ISSUE TITLE
How to tune params like temperature, max tokens etc.?

### ISSUE THREAD

**Issue by andr0s** [jmorganca/ollama#736]
I don't see anything like that in the `usage` section of the `ollama` command output.
P. S. I'm using the mac binary

**Comment by konstantin1722** [comment]
@andr0s, Did you read `ollama/docs/modelfile.md`? This might be what you're looking for.

**Comment by mchiang0610** [comment]
@andr0s You can do it via the modelfile or via API. 

https://github.com/jmorganca/ollama/blob/main/docs/api.md

https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md

Let me know if this helps! Closing this for now. Thank you

**Comment by andr0s** [comment]
Oh ok got it, thanks. It's a bit confusing since some other AI tools allow specifying it via the command line. Maybe it could be a feature you guys can consider. Just a suggestion :) Besides that, I absolutely love how Ollama is user friendly and optimized. Good job!

**Comment by andr0s** [comment]
Oh ok got it, thanks. It's a bit confusing since some other AI tools allow specifying it via the command line. Maybe it could be a feature you guys can consider. Just a suggestion :) Besides that, I absolutely love how Ollama is user friendly and optimized. Good job!
