### ISSUE TITLE
"Delete word" buggy in TUI

### ISSUE THREAD

**Issue by mjvmroz** [jmorganca/ollama#744]
Using a delete word hotkey (e.g. ctrl-w) when the cursor is within the first word of a prompt causes the entire prompt to be deleted.

Steps to reproduce:
1. Type several words at an ollama LLM prompt
2. Move the cursor to the first word (immediately following ">>>")
3. Use a "delete word" hotkey (e.g. ctrl-w)
4. The entire prompt is deleted

Expected behavior: Only the first word of the prompt is deleted

**Comment by pdevine** [comment]
This is fixed with #847
