### ISSUE TITLE
unable to terminate session in TUI

### ISSUE THREAD

**Issue by praveenc** [jmorganca/ollama#749]
Hi, I pasted text to the prompt that contained many new line characters. Seems like the session is considering each line as an input prompt and it  goes on to generate responses. I'v tried to `Ctrl-c`, `Ctrl-z`, `Ctrl-d` but the prompt wouldn't terminate, essentially locking up the terminal session

```shell
ollama run mistral
>>> Summarize this doc for me """Use Docker containers to build models 

Makes extensive use of Docker containers for build and runtime tasks. Provides pre-built Docker images for its built-in algorithms and the supported deep learning frameworks used for training and inference. Using containers, you can train machine learning algorithms and deploy models quickly and reliably at any scale. 

The topics in this section show how to deploy these containers for your own use cases. .

For information about how to bring your own containers for use , see Bring your own Docker image
```

couldn't close the starting quotes i.e. `"""` as the model  started generating text already ...

Would be nice to capture this.

_p.s.: Seems the  `Ctrl-C`,  `Ctrl-D` signal was queued at the end..._

```shell
...
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^C
Use Ctrl-D or /bye to exit.
>>> ^D
```

**Comment by pdevine** [comment]
I'm looking at revamping this right now w/ replacing the `readline` library with something that also includes a way to do bracketed paste mode.

**Comment by pdevine** [comment]
This is fixed w/ #922.

**Comment by pdevine** [comment]
@praveenc you shouldn't need to add """ now when you paste, although it still should work.

**Comment by praveenc** [comment]
Thanks @pdevine ! Just tested this, TUI is now able to capture `Ctrl-C` signal. 

However, when new line separated text is pasted to the TUI, it still considers each line as a separate input. 

Tested this on  ```text iTerm2 (Build: 3.4.21) on Macos Sonoma 14.1. ```


![multiline-tui-30Oct2023](https://github.com/jmorganca/ollama/assets/1090396/02c2b3e1-8921-4366-ae5a-848dd76001f5)

**Comment by praveenc** [comment]
@pdevine Sure. Here it is. `ollama version 0.1.5`
and yes, my iTerm setting has `Terminal may enable paste bracketing` enabled already.
