### ISSUE TITLE
Processing inference in parallel 

### ISSUE THREAD

**Issue by SabareeshGC** [jmorganca/ollama#761]
I was using http endpoint but it appears it is limited to 1 request for processing , is it possible to process multiple inference request at the same time. 
ref https://github.com/ggerganov/llama.cpp/pull/3228

**Comment by morandalex** [comment]
good point! how to process multiple request in parallel ?

**Comment by UmutAlihan** [comment]
I am also looking forward for this feature. It would be perfect if "ollama server" could deploy the model to let multiple users infere in parallel.

As of now at each request from different clients, ollama loads the model again even though it is the same model name.

**Comment by morandalex** [comment]
news on that?

**Comment by UmutAlihan** [comment]
It is solved in new ollama versions. Currently our Ollams deployment gracefully balances the inference load as requests from different sources. You can check the discourse for up to date news.

**Comment by UmutAlihan** [comment]
> It is solved in new ollama versions. Currently our Ollams deployment gracefully balances the inference load as requests from different sources. You can check the discourse for up to date news.
> 

Even though it is not parallel, there is a kind of queue mechanism and it saves the day :)

**Comment by gningue** [comment]
Hi
Any news ?

**Comment by jmorganca** [comment]
Hi all! Thanks for the issues and comments. Going to merge this with https://github.com/jmorganca/ollama/issues/358

**Comment by ITHealer** [comment]
How to set env to run parallel in linux?
I had set up env by:

# sudo nano ~/.bashrc
# export [VARIABLE_NAME]=[variable_value].
# source ~/.bashrc

But it doesn't work
Please help me!!!

**Comment by swlee9087** [comment]
> How to set env to run parallel in linux? I had set up env by:
> 
> sudo nano ~/.bashrc export OLLAMA_NUM_PARALLEL=4 source ~/.bashrc
> 
> But it doesn't work Please help me!!!

I had the exact same problem. I solved it this way, hope it helps: 

# Open service file
sudo nano /etc/systemd/system/ollama.service

# Paste service content and save the file
> # DO NOT JUST ADD THE REVISED CONTENT TO OG FILE
> [Unit]
> Description=Ollama Service
> After=network-online.target
> 
> [Service]
> ExecStart=/usr/local/bin/ollama serve (or wherever your linux ollama is installed )
> User=ollama
> Group=ollama
> Restart=always (i find that this restart option doesn't always work)
> RestartSec=3
> Environment= (check your paths in linux)
> Environment="OLLAMA_HOST=0.0.0.0:11434"
> Environment="OLLAMA_NUM_PARALLEL=2"
> Environment="OLLAMA_MAX_LOADED_MODELS=2" (i think this is optional, but i'm always juggling 2 models at the same time so it works for me)
> 
> 
> [Install]
> WantedBy=default.target


# Reload systemd configuration
sudo systemctl daemon-reload

# Enable the Ollama service
sudo systemctl enable ollama (again, i'm unsure about "enable" but it's definitely not "start"/"restart" if you want to monitor ollama directly)
