### ISSUE TITLE
Support for HuggingFaceH4/zephyr-7b-alpha

### ISSUE THREAD

**Issue by shauryr** [jmorganca/ollama#762]
https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha : zephyr-7b-alpha model outperforms ChatLlama 70B

It would be great to have this run inside Ollama!

**Comment by jmorganca** [comment]
Check out https://ollama.ai/library/zephyr or run it with:

```
ollama run zephyr
```

**Comment by jmorganca** [comment]
Will close this for now, but feel free to re-open if something doesn't seem quite right!

**Comment by shauryr** [comment]
thank you for this!
