### ISSUE TITLE
update local ollama install

### ISSUE THREAD

**Issue by morandalex** [jmorganca/ollama#763]
How to update ollama cli locally with latest features?

**Comment by BruceMacD** [comment]
Thanks for opening this issue, it hasn't been documented yet. When a new version is released (at this exact moment the new github release is still pre-release):

**Mac:**
- The Mac app will automatically download the update and prompt to install the new version.

**Linux:**
- Re-running the install script will download the new version and move it to the right place, it won't re-install any of the other external libraries (like the GPU libraries).
```
curl https://ollama.ai/install.sh | sh
```

**Comment by milen-prg** [comment]
@BruceMacD this script on Ubuntu Linux (wsl2) does not updates v0.1.16 to v0.1.17.

**Comment by BruceMacD** [comment]
@milen-prg try again now, 0.1.17 was pre-release last night

**Comment by milen-prg** [comment]
Oh, yes, now it succeed! I saw the message for the new version yesterday and instantly start to try to update. Thank, you!

**Comment by wgong** [comment]
@BruceMacD 
ollama service is running, 
`service ollama status`
do you recommend one stops the service before upgrading to a new release ?

**Comment by BruceMacD** [comment]
@wgong no need to stop the service, it should be restarted automatically if you are upgrading via the `curl -fsSL https://ollama.com/install.sh | sh` script.

**Comment by Shivamkushwaha9** [comment]
> @wgong no need to stop the service, it should be restarted automatically if you are upgrading via the `curl -fsSL https://ollama.com/install.sh | sh` script.

How to update in windows?

**Comment by BruceMacD** [comment]
@Shivamkushwaha9 on Windows the toolbar icon will have an option to update when a new version is available. It will also install the new version next time Ollama restarts.
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama

**Comment by bighaidao** [comment]
There is a bug in ollama upgrade, which will overwrite the original configuration file. This is a bit annoying

**Comment by melMass** [comment]
Can we safely use that script on macOS too? The doc seems to mention a GUI but I'm using only the CLI (I didn't even know ollama had one)

**Comment by plekeas** [comment]
A `curl https://ollama.ai/install.sh | sh` worked updating ollama to version `0.3.13`. After the Linux amd64 bundle downloaded, ollama user was added again to video group, current user was added to ollama group, and ollama systemd service was (re)created enabled and started.

**Comment by Septemberlemon** [comment]
> @Shivamkushwaha9 on Windows the toolbar icon will have an option to update when a new version is available. It will also install the new version next time Ollama restarts. https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-upgrade-ollama

I didn't see any option to update and my version is 0.3.13,how should I update ollama?
![image](https://github.com/user-attachments/assets/a41f68dc-006f-40cf-9da3-b12a880540c4)
please help me!

**Comment by jhetuts** [comment]
Can we do it programmatically on windows?

**Comment by TimMensch** [comment]
I'm seeing the "Restart to update" option, but when I select it, nothing happens. 🫤

**Comment by BruceMacD** [comment]
@TimMensch what OS are you seeing this issue on? Might work to just quit the Ollama application and start it again.

**Comment by TimMensch** [comment]
Windows 11.

I haven't been able to figure out how to restart the app without binding it to a console. If there's an option to run it detached, I haven't found it.

**Comment by omarnahdi** [comment]
> I'm seeing the "Restart to update" option, but when I select it, nothing happens. 🫤

I did that too and ollama did get updated to the latest version. try `ollama --version` and check the version.

**Comment by raffaem** [comment]
> I'm seeing the "Restart to update" option, but when I select it, nothing happens. 🫤

Same thing here.

Restarting ollama does not update it.

**Comment by dionmaicon** [comment]
> Thanks for opening this issue, it hasn't been documented yet. When a new version is released (at this exact moment the new github release is still pre-release):
> 
> **Mac:**
> 
> * The Mac app will automatically download the update and prompt to install the new version.
> 
> **Linux:**
> 
> * Re-running the install script will download the new version and move it to the right place, it won't re-install any of the other external libraries (like the GPU libraries).
> 
> ```
> curl https://ollama.ai/install.sh | sh
> ```

**Linux** 
If you have any custom configuration in `etc/systemd/system/ollama.service`, save it, otherwise it will be overwritten.

**Comment by Anaphylaxis** [comment]
> **Linux** If you have any custom configuration in `etc/systemd/system/ollama.service`, save it, otherwise it will be overwritten.

Custom configuration should be done in the override file (`systemctl edit ollama`) and this was not overwritten by the script for me

**Comment by gabriel-r** [comment]
_UPDATE: The ollama service was launched and still used by Raycast. I found it in Application Monitor, quit it manually, and everything fell back into place afterwards._ 

----

I just updated the macOS client via the DMG download. 
In Terminal, I get this when running `ollama --version`
> ollama version is 0.9.0
> Warning: client version is 0.9.6

Running `which ollama` returns `/usr/local/bin/ollama`

The UI client is of course in /Applications

Still getting the dredged error _"The model you are attempting to pull requires a newer version of Ollama"_

Can I update the CLI version separately from the Mac App? Should I?

**Comment by wmichelin** [comment]
@gabriel-r wow, you just saved me. Also had Raycast installed and quitting it fixed my exact issue.

**Comment by seohyunjun** [comment]
```
ollama update
```
please add options update cli command

**Comment by resting** [comment]
> _UPDATE: The ollama service was launched and still used by Raycast. I found it in Application Monitor, quit it manually, and everything fell back into place afterwards._
> 
> I just updated the macOS client via the DMG download. In Terminal, I get this when running `ollama --version`
> 
> > ollama version is 0.9.0
> > Warning: client version is 0.9.6
> 
> Running `which ollama` returns `/usr/local/bin/ollama`
> 
> The UI client is of course in /Applications
> 
> Still getting the dredged error _"The model you are attempting to pull requires a newer version of Ollama"_
> 
> Can I update the CLI version separately from the Mac App? Should I?

Never knew it was using it. Good share.

**Comment by calebl** [comment]
For me, it was a process called `ollama-darwin` that I had stop and then restart my terminal

**Comment by razametal** [comment]
> > **Linux** If you have any custom configuration in `etc/systemd/system/ollama.service`, save it, otherwise it will be overwritten.
> 
> Custom configuration should be done in the override file (`systemctl edit ollama`) and this was not overwritten by the script for me

I did it and it is working:

~~~
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_CONTEXT_LENGTH=8192"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KV_CACHE_TYPE=q8_0"
Environment="OLLAMA_KEEP_ALIVE=true"
~~~
~~~
systemctl restart ollama.service
~~~

**Comment by CZR770** [comment]
I'm using a Mac and I'm trying to update it from the little oval menu thing on the top bar. It says "Update". I click "Update", I put my password in, it maybe loads for a second, and then nothing happens. For some reason, I can't use ollama in cline because ollama isn't updated.

**Comment by sarthakpati** [comment]
> Can we do it programmatically on windows?

Try: `irm https://github.com/ollama/ollama/releases/download/v0.21.0/install.ps1 | iex`

Adjust the powershell instance permissions for the type of installation you want.
