### ISSUE TITLE
Release mac and linux binaries alongside the desktop packages

### ISSUE THREAD

**Issue by Clivern** [jmorganca/ollama#766]
Maybe ollama is intended to be a desktop app but I believe a lot are using it as an API service. 

Honestly i couldn't get it to work as desktop app on Intel Mac but works as API service. Assuming the 500% spike in cpu usage is expected with each prompt and model pulling on a decent mac. I guess i need to give it a try on better machine.

Anyways I gave it a try with goreleaser on a fork https://github.com/Clivern/ollama/commit/ef2d0da969343ba1d5fef0b8777f5cca056c1be1. 
It failed to publish to github but maybe because it is a fork! I need to debug but are you interested in such a thing? 

Also goreleaser doesn't append to the release, it publish the changelog, binaries ... etc but then desktop packages can be added. it sound they are done manually.

**Comment by Clivern** [comment]
> Hi @Clivern thanks for putting together that goreleaser configuration. We definitely want people to be able to use Ollama as an API, a lot of the maintainers have built tools on top of the Ollama API also.
> 
> We actually do publish the binaries in our Github releases: https://github.com/jmorganca/ollama/releases
> 
> To get the Mac binary download `ollama-darwin` and make it executable `chmod +x ollama-darwin`. Then you can run the binary without the app.
> 
> The build process for Ollama is a bit more complicated than I have been able to achieve with goreleaser, specifically the Linux release. The Linux build needs to be done on a machine with CUDA libraries available, and on an old `libc` version for maximum compatibility.

Thanks @BruceMacD! I can confirm that `ollama-darwin` works. 

That solves my issue!

**Comment by arran4** [comment]
@Clivern You need to add: 

```
permissions:
   content: write
```

to the workflow yaml

Details:
* https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
* https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents

**Comment by Clivern** [comment]
> @Clivern You need to add:
> 
> ```
> permissions:
>    contents: write
> ```
> 
> to the workflow yaml
> 
> Details:
> 
> * https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> * https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents

Yeah it works with that permission 👍

**Comment by arran4** [comment]
Hopefully we see packages soon. Refuse to install via shell scripts, reminds me of corporate unix from the 00s.
