### ISSUE TITLE
I ask Ollama how to prompt thru my Safari or Chrome and it doesn't work

### ISSUE THREAD

**Issue by igorschlum** [jmorganca/ollama#777]
is this working for you? We tried on different computers.

`http://127.0.0.1:11434?prompt=How+can+I+ask+you+a+question+from+another+computer+on+my+local+network%3F`

I only get a webpage saying: Ollama is running what ever the prompt is.

I'm using Ollama 0.1.1 on MacOS.

It would be very nice to have this working.

Here is my discussion with Ollama:

>>> I would like to ask you a question from another computer on my local network. How to do that?
Ah, I see! *smile* You can ask me questions from another computer on your local network by using the IP address of this chat interface as 
a gateway. Here's how:

1. Open a new tab in your browser and navigate to `http://127.0.0.1:11434`.
2. Once the chat interface loads, you can type your question in the chat window and press Enter just like you would on this computer.
3. The response will be displayed in the chat window of the other computer, allowing you to ask me questions remotely.

Note that since I'm an AI and not a physical entity, I don't have a fixed IP address, so you may need to use the IP address of this chat 
interface (127.0.0.1:11434) as a gateway to reach me from other computers on your local network.

I hope that helps! Let me know if you have any other questions. *smile*

>>> I don't see the chat window when I type : http://127.0.0.1:11434
Ah, I see! *smile* It looks like you're accessing the chat interface directly without going through a web page. In that case, you can 
still ask me questions by typing them in the command line of your terminal or command prompt. Here's how:

1. Open a new tab in your terminal or command prompt and type `http://127.0.0.1:11434`.
2. Once the chat interface loads, you can type your question in the chat window and press Enter just like you would on this computer.

Note that since I'm an AI and not a physical entity, I don't have a fixed IP address, so you may need to use the IP address of this chat 
interface (127.0.0.1:11434) as a gateway to reach me from other computers on your local network.

I hope that helps! Let me know if you have any other questions. *smile*

>>> I go thru a web poage at the address : http://127.0.0.1:11434 and the webpage displays "Ollama is running" but I'm stuck at this point. How to transmit the prompt I want you to answer?
Ah, I see! *smile* When you access `http://127.0.0.1:11434` directly in your web browser, you can't type a prompt directly into the chat 
window like you would on this computer. Instead, you can use the following technique to transmit the prompt to me:

1. Open a new tab in your web browser and navigate to `http://127.0.0.1:11434`.
2. Once the chat interface loads, you'll see a small box at the bottom of the page where you can enter a message.
3. Type your prompt in this message box, making sure it's on one line and doesn't exceed 80 characters (including spaces).
4. Click the "Send" button or press Enter to transmit the prompt to me.

I'll do my best to provide a helpful response! *smile* Let me know if you have any other questions.

>>> I don't see the small box on the page. Is it possible for me to type the prompt directly in the URL?
Of course! *smile* Yes, you can type your prompt directly in the URL by using the following syntax:

`http://127.0.0.1:11434?prompt=<your_message>`

Replace `<your_message>` with the prompt you want to send to me. Here's an example:

`http://127.0.0.1:11434?prompt=How+can+I+ask+you+a+question+from+another+computer+on+my+local+network%3F`

By using the `?prompt=` syntax in the URL, you can send me your prompt directly without having to use the chat window. I'll do my best to 
provide a helpful response! *smile* Let me know if you have any other questions.

**Comment by BruceMacD** [comment]
Hi @igorschlum, there is no UI for the base version of Ollama. You can only interact with it through the CLI and the API. However, there are many UI projects, they are just a separate download:
https://github.com/jmorganca/ollama#community-integrations
