### ISSUE TITLE
i got this issue from orca-mini 7b

### ISSUE THREAD

**Issue by Boluex** [jmorganca/ollama#788]
i am using an 8gb of RAM cpu system.....No vram...Downloaded the orca-mini 7b model on ollama.....but got this error....... Error: llama runner process has terminated.....How can i fix this?...please guys

**Comment by jmorganca** [comment]
Hi @Boluex sorry you hit an error. Would it be possible to check the logs to help us find the error?
* On Linux: `journalctl -u ollama`
* On macOS: `cat ~/.ollama/logs/server.log`

Also, make sure to try with the latest version 0.1.3 as we've added some improvements with memory detection & allocation

**Comment by Boluex** [comment]
ollama run orca-mini
⠸   Error: llama runner process has terminated


this is what i am getting

**Comment by zhoug0x** [comment]
hello! old Thinkpad/Ubuntu guy here again, getting this same error so might as well throw my logs in the ring too, hopefully helps:

getting `Error: llama runner process has terminated` like _immediately_ after running `ollama run open-orca`

the logs say `llama runner stopped with error: signal: illegal instruction (core dumped)`

- running ollama 0.1.3
- same error when trying `ollama run open-orca:3b`

### ollama log:
```
Oct 15 13:23:34 mferbox ollama[1380]: [GIN] 2023/10/15 - 13:23:34 | 200 |      34.367µs |       127.0.0.1 | HEAD     "/"
Oct 15 13:23:34 mferbox ollama[1380]: [GIN] 2023/10/15 - 13:23:34 | 200 |     344.681µs |       127.0.0.1 | GET      "/api/tags"
Oct 15 13:23:34 mferbox ollama[1380]: 2023/10/15 13:23:34 llama.go:333: skipping accelerated runner because num_gpu=0
Oct 15 13:23:34 mferbox ollama[1380]: 2023/10/15 13:23:34 llama.go:356: starting llama runner
Oct 15 13:23:34 mferbox ollama[1380]: 2023/10/15 13:23:34 llama.go:408: waiting for llama runner to start responding
Oct 15 13:23:34 mferbox ollama[1380]: 2023/10/15 13:23:34 llama.go:373: error starting llama runner: llama runner process has terminated
Oct 15 13:23:34 mferbox ollama[1380]: 2023/10/15 13:23:34 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)
Oct 15 13:23:34 mferbox ollama[1380]: [GIN] 2023/10/15 - 13:23:34 | 500 |  128.925806ms |       127.0.0.1 | POST     "/api/generate"
```

### system info:
![image](https://github.com/jmorganca/ollama/assets/90252209/287f2740-d603-4188-a07a-124967403696)

**Comment by alix2013** [comment]
Hi, I got the same error on Ubuntu 22.04, x86 CPU host
 llama.go:373: error starting llama runner: llama runner process has terminated
 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)

ollama run mistral
Error: llama runner process has terminated

pull the latest code to the ubuntu x86, build on the host, and got the same errors.
I tried installing ollama on google colab with T4 GPU runtime, seems colab cuda version is lower than
required, what is the required cuda driver version? 
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0

**Comment by dominiksr** [comment]
I have a similar problem:
Error: llama runner process has terminated

$ journalctl -u ollama
(...)
ollama[5093]: 2023/10/21 11:23:49 llama.go:333: skipping accelerated runner because num_gpu=0
ollama[5093]: 2023/10/21 11:23:49 llama.go:356: starting llama runner
ollama[5093]: 2023/10/21 11:23:49 llama.go:408: waiting for llama runner to start responding
ollama[5093]: 2023/10/21 11:23:49 llama.go:373: error starting llama runner: llama runner process has terminated
ollama[5093]: 2023/10/21 11:23:49 llama.go:438: llama runner stopped with error: signal: illegal instruction
ollama[5093]: [GIN] 2023/10/21 - 11:23:49 | 500 |  545.543144ms |       127.0.0.1 | POST     "/api/generate"
ollama[5093]: [GIN] 2023/10/21 - 11:24:41 | 200 |      36.703µs |       127.0.0.1 | HEAD     "/"
ollama[5093]: [GIN] 2023/10/21 - 11:24:41 | 200 |     431.918µs |       127.0.0.1 | GET      "/api/tags"

Debian 12(I try fedora 38 and same problem)/VM on proxmox.
On a laptop with nvidia 4060 everything works great.

**Comment by push-panjali23** [comment]
Same error any luck ??..



pulling manifest
pulling e84705205f71... 100% |█████████████| (1.9/1.9 GB, 3.1 MB/s)            
pulling e7214e2f1a0f... 100% |██████████████████████| (66/66 B, 16 B/s)        
pulling 93ca9b3d83dc... 100% |██████████████████████| (89/89 B, 30 B/s)        
pulling 65009e4e7fee... 100% |████████████████████| (359/359 B, 92 B/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
⠧   Error: llama runner process has terminated
(bot-py3.10) blacks@blacks-Inspiron-3647:~/Desktop/Ollama$ ollama run orca-mini
⠋   Error: llama runner process has terminated

**Comment by SonicWarrior1** [comment]
I have a similar problem:
Command: ollama run mistral
Error: llama runner process has terminated

$ journalctl -u ollama
Oct 22 18:10:25 UBUNTU ollama(816): 2023/10/22 18:10:25 llama.go:333: skipping accelerated runner because num_gpu=0
Oct 22 18:10:25 UBUNTU ollama[816]: 2023/10/22 18:10:25 llama.go:356: starting llama runner 
Oct 22 18:10:25 UBUNTU ollama[816]: 2023/10/22 18:10:25 llama.go:408: waiting for llama runner to start responding
Oct 22 18:10:25 UBUNTU ollama[816]: 2023/10/22 18:10:25 llama.go:373: error starting llama runner: llama runner process has terminated 
Oct 22 18:10:25 UBUNTU ollama[816]: 2023/10/22 18:10:25 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped) 
Oct 22 18:10:25 UBUNTU ollama[816]: [GIN] 2023/10/22 18:10:25 | 500 | 353.853052ms | 127.0.0.1 POST "/api/generate" 
Oct 22 18:11:48 UBUNTU ollama[816]: [GIN] 2023/10/22-18:11:48 | 200| 22.020267ms  | 127.0.0.1 | HEAD
Oct 22 18:11:48 UBUNTU ollama[816]: [GIN] 2023/10/22-18:11:48 | 200| 224.278ps | 127.0.0.1 GET "/api/tags"

System Info:
![image](https://github.com/jmorganca/ollama/assets/73881129/8a3c0cc8-23d1-42bf-935c-46bbc2f5a3e4)

**Comment by nnmykn** [comment]
@jmorganca 
I'm experiencing the same error in this environment, but there are no errors in `journalctl`. Is there anything I can verify?

![CleanShot 2023-10-23 at 18 24 35@2x](https://github.com/jmorganca/ollama/assets/79746996/301a9a60-993d-4303-ab4c-42764a04adcd)

![CleanShot 2023-10-23 at 18 24 46@2x](https://github.com/jmorganca/ollama/assets/79746996/66738eff-8608-4500-9dbb-78240702c685)

![CleanShot 2023-10-23 at 18 24 54@2x](https://github.com/jmorganca/ollama/assets/79746996/8db10e3d-fbb2-4b9f-9311-06eba6b9b2e4)

**Comment by dominiksr** [comment]
Works again on v0.1.5 for me. Nice

**Comment by Boluex** [comment]
Still got the same error

**Comment by mxyng** [comment]
This looks related #644

**Comment by dominiksr** [comment]
> Still got the same error

Did you remove the model and ollama before and install everything from scratch?

**Comment by MadathilSA** [comment]
> Works again on v0.1.5 for me. Nice

Hi dominiksr, 

I have simillar setup: proxmox and ubuntu 22.04.
Did you reinstall ollama to v0.1.5? how?

**Comment by dominiksr** [comment]
> > Works again on v0.1.5 for me. Nice
> 
> Hi dominiksr,
> 
> I have simillar setup: proxmox and ubuntu 22.04. Did you reinstall ollama to v0.1.5? how?

I remove files in:
/usr/bin/ollama
and install one more time.

Manual installation:
https://github.com/jmorganca/ollama/blob/main/docs/linux.md

**Comment by Boluex** [comment]
![Screenshot from 2023-10-27 00-13-10](https://github.com/jmorganca/ollama/assets/90112749/3539ed73-262d-4c38-9c8b-35133f128eba)
this is my system specs but ollama is not working.....I think i will uninstall and install it again

**Comment by jmorganca** [comment]
Please feel free to re-open if this is still an issue

**Comment by ttio2tech** [comment]
Trying to run it in an old CPU (without AVX). Built from source (0.1.7) but got the same issue. Is it possible to disable the AVX ?

**Comment by ttio2tech** [comment]
> Hi folks, as of `0.1.6`+ this should be fixed. Note: you'll need a CPU with [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions), but as of 0.1.6 CPU instruction set requirements have been relaxed significantly!

is it possible to add support for CPU without AVX? maybe detect if cpu has AVX, if not add "-DLLAMA_F16C=OFF -DLLAMA_FMA=OFF"(saw it in one llama.cpp discussion) to CMAKE?

**Comment by defconhaya** [comment]
> > Works again on v0.1.5 for me. Nice
> 
> Hi dominiksr,
> 
> I have simillar setup: proxmox and ubuntu 22.04. Did you reinstall ollama to v0.1.5? how?

Make sure your VM CPU supports AVX. You can set the CPU type to host
![image](https://github.com/jmorganca/ollama/assets/186805/b5f4b36c-295b-4a52-8690-f9cf4d618e5b)

**Comment by dominiksr** [comment]
> > > Works again on v0.1.5 for me. Nice
> > 
> > 
> > Hi dominiksr,
> > I have simillar setup: proxmox and ubuntu 22.04. Did you reinstall ollama to v0.1.5? how?
> 
> Make sure your VM CPU supports AVX. You can set the CPU type to host ![image](https://user-images.githubusercontent.com/186805/280305475-b5f4b36c-295b-4a52-8690-f9cf4d618e5b.png)

In my case it just works. I think it's a good idea. Using proxmox I had a lot of problems if the hardware was a little unique.

**Comment by TunaFFish** [comment]
I have the same problem.

MacBook Air (13-inch, 2017)
macOS Big Sur version 11.7.6 (20G1231)
Processor: 1,8 GHz Dual-Core Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB

Running the command `sysctl -a | grep machdep.cpu.features`in the Terminal shows me that I have `AVX1.0`

Bugger, I thought at least I could play around with orca-mini:3b

% ollama run orca-mini:3b
pulling manifest
pulling 66002b78c70a... 100% |██████████████████████████████████████████| (2.0/2.0 GB, 5.0 TB/s)        
pulling dd90d0f2b7ee... 100% |█████████████████████████████████████████████| (95/95 B, 1.4 MB/s)        
pulling 93ca9b3d83dc... 100% |█████████████████████████████████████████████| (89/89 B, 1.4 MB/s)        
pulling 33eb43a1488d... 100% |█████████████████████████████████████████████| (52/52 B, 468 kB/s)        
pulling fd52b10ee3ee... 100% |███████████████████████████████████████████| (455/455 B, 2.3 MB/s)        
verifying sha256 digest
writing manifest
removing any unused layers
success
⠇   Error: llama runner process has terminated

**Comment by tjlcast** [comment]
I have same problem.

I reinstall ollama(from 0.1.3 to 0.1.8 ). But when I run `ollama run llama2`, it shows: `Error: llama runner process has terminated`

Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB

And `./.ollama/logs/server.log` like below:
```
[GIN] 2023/11/08 - 18:37:15 | 200 |      27.403µs |       127.0.0.1 | HEAD     "/"
[GIN] 2023/11/08 - 18:37:15 | 200 |    3.545476ms |       127.0.0.1 | POST     "/api/show"
2023/11/08 18:37:15 llama.go:384: starting llama runner
2023/11/08 18:37:15 llama.go:386: error starting the external llama runner: fork/exec /var/folders/1w/bfjzbwc53hbgzsk1spq8f_5w0000gn/T/ollama1055606081/llama.cpp/ggml/build/metal/bin/ollama-runner: bad CPU type in executable
2023/11/08 18:37:15 llama.go:384: starting llama runner
2023/11/08 18:37:15 llama.go:442: waiting for llama runner to start responding
{"timestamp":1699439835,"level":"WARNING","function":"server_params_parse","line":847,"message":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":0}
{"timestamp":1699439835,"level":"INFO","function":"main","line":1191,"message":"build info","build":1009,"commit":"9e232f0"}
{"timestamp":1699439835,"level":"INFO","function":"main","line":1196,"message":"system info","n_threads":2,"total_threads":4,"system_info":"AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | "}
llama.cpp: loading model from /Users/jialtang/.ollama/models/blobs/sha256:8daa9615cce30c259a9555b1cc250d461d1bc69980a274b44d7eda0be78076d8
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 3615.73 MB (+ 1024.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
llama_new_context_with_model: compute buffer total size =  153.35 MB
2023/11/08 18:37:15 llama.go:399: signal: segmentation fault
2023/11/08 18:37:15 llama.go:407: error starting llama runner: llama runner process has terminated
2023/11/08 18:37:15 llama.go:473: llama runner stopped successfully
```

Before reinstalling I can do `ollama run llama2` in ollama(0.1.3)

So how can I fix it?

**Comment by defconhaya** [comment]
`bad CPU type in executable
2023/11/08 18:37:15 llama.go:384: starting llama runner`
do a lscpu and make sure the CPU is AVX capable

**Comment by tjlcast** [comment]
Running the command 'sysctl -a | grep machdep.cpu.featuresin ' like below:
```
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
```
There is AVX1.0

**Comment by TunaFFish** [comment]
The `lscpu`command mentioned by @defconhaya on macOS would be `sysctl` with `sysctl -a` to dump them all.
Here a list of props with AVX in the name,
for example `sysctl -n hw.optional.avx1_0` I get: 1

```
hw.optional.avx1_0: 1
hw.optional.avx2_0: 1
hw.optional.avx512bw: 0
hw.optional.avx512cd: 0
hw.optional.avx512dq: 0
hw.optional.avx512f: 0
hw.optional.avx512ifma: 0
hw.optional.avx512vbmi: 0
hw.optional.avx512vl: 0
```

**Comment by tjlcast** [comment]
I check it just now, it as same as you :
```
% sysctl -n hw.optional.avx1_0
1
```

```
% sysctl -a | grep avx
hw.optional.avx1_0: 1
hw.optional.avx2_0: 1
hw.optional.avx512f: 0
hw.optional.avx512cd: 0
hw.optional.avx512dq: 0
hw.optional.avx512bw: 0
hw.optional.avx512vl: 0
hw.optional.avx512ifma: 0
hw.optional.avx512vbmi: 0
```

**Comment by TunaFFish** [comment]
Strange thing is that if I run `cat ~/.ollama/logs/server.log` and search for AVX

```
2023/11/08 14:09:29 llama.go:384: starting llama runner
2023/11/08 14:09:29 llama.go:386: error starting the external llama runner: fork/exec /var/folders/xn/63p1jx4130l1rb_01t_ynd3r0000gn/T/ollama339294303/llama.cpp/gguf/build/metal/bin/ollama-runner: bad CPU type in executable
2023/11/08 14:09:29 llama.go:384: starting llama runner
2023/11/08 14:09:29 llama.go:442: waiting for llama runner to start responding
{"timestamp":1699448970,"level":"WARNING","function":"server_params_parse","line":873,"message":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":-1}
{"timestamp":1699448970,"level":"INFO","function":"main","line":1324,"message":"build info","build":219,"commit":"9e70cc0"}
{"timestamp":1699448970,"level":"INFO","function":"main","line":1330,"message":"system info","n_threads":2,"n_threads_batch":-1,"total_threads":4,"system_info":"**AVX = 0** | **AVX2 = 0** | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}
...
2023/11/08 14:09:37 llama.go:399: signal: segmentation fault
2023/11/08 14:09:37 llama.go:407: error starting llama runner: llama runner process has terminated
2023/11/08 14:09:37 llama.go:473: llama runner stopped successfully
[GIN] 2023/11/08 - 14:09:37 | 500 |   7.66148366s |       127.0.0.1 | POST     "/api/generate"
```

**Comment by jpmcarvalho** [comment]
> Strange thing is that if I run `cat ~/.ollama/logs/server.log` and search for AVX: `AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0`
> 
> ```
> 2023/11/08 14:09:29 llama.go:384: starting llama runner
> 2023/11/08 14:09:29 llama.go:386: error starting the external llama runner: fork/exec /var/folders/xn/63p1jx4130l1rb_01t_ynd3r0000gn/T/ollama339294303/llama.cpp/gguf/build/metal/bin/ollama-runner: bad CPU type in executable
> 2023/11/08 14:09:29 llama.go:384: starting llama runner
> 2023/11/08 14:09:29 llama.go:442: waiting for llama runner to start responding
> {"timestamp":1699448970,"level":"WARNING","function":"server_params_parse","line":873,"message":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":-1}
> {"timestamp":1699448970,"level":"INFO","function":"main","line":1324,"message":"build info","build":219,"commit":"9e70cc0"}
> {"timestamp":1699448970,"level":"INFO","function":"main","line":1330,"message":"system info","n_threads":2,"n_threads_batch":-1,"total_threads":4,"system_info":"AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | "}
> ...
> 2023/11/08 14:09:37 llama.go:399: signal: segmentation fault
> 2023/11/08 14:09:37 llama.go:407: error starting llama runner: llama runner process has terminated
> 2023/11/08 14:09:37 llama.go:473: llama runner stopped successfully
> [GIN] 2023/11/08 - 14:09:37 | 500 |   7.66148366s |       127.0.0.1 | POST     "/api/generate"
> ```

Did you solve the problem? I have the same issue in my macOS

**Comment by antreev-brar** [comment]
same issue
`llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.08 MB
llm_load_tensors: mem required  = 1887.57 MB
.......................
.......................................
.........................
.......
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  650.00 MB
llama_new_context_with_model: compute buffer total size = 156.88 MB
2023/11/09 14:17:19 llama.go:399: signal: segmentation fault
2023/11/09 14:17:19 llama.go:407: error starting llama runner: llama runner process has terminated
2023/11/09 14:17:19 llama.go:473: llama runner stopped successfully
[GIN] 2023/11/09 - 14:17:19 | 500 |  862.879775ms |       127.0.0.1 | POST     "/api/generate"`

**Comment by antreev-brar** [comment]
> 0.1.

Did you find the solution to this? I am getting the exact same logs

**Comment by jackiezhangcn** [comment]
when I run codellama, have the same issue

**Comment by erickhavel** [comment]
MacOS here.

```
$ ollama run llama2-uncensored
>>> hi
Error: llama runner process has terminated
```

`server.log`:
```
[GIN] 2023/11/24 - 03:24:55 | 200 |     106.959µs |       127.0.0.1 | HEAD     "/"
2023/11/24 03:24:58 llama.go:420: starting llama runner
2023/11/24 03:24:58 llama.go:478: waiting for llama runner to start responding
2023/11/24 03:24:58 llama.go:435: signal: segmentation fault
2023/11/24 03:24:58 llama.go:443: error starting llama runner: llama runner process has terminated
2023/11/24 03:24:58 llama.go:509: llama runner stopped successfully
[GIN] 2023/11/24 - 03:24:58 | 500 |    120.5145ms |       127.0.0.1 | POST     "/api/generate"
```

It was working fine a couple of weeks ago. I also ran `ollama pull llama2-uncensored`, no change.

**Comment by erickhavel** [comment]
MacOS here.

```
$ ollama run llama2-uncensored
>>> hi
Error: llama runner process has terminated
```

`server.log`:
```
[GIN] 2023/11/2X XX03:24:55 | 200 |     106.959µs |       127.0.0.1 | HEAD     "/"
2023/11/2X XX:24:58 llama.go:420: starting llama runner
2023/11/2X XX:24:58 llama.go:478: waiting for llama runner to start responding
2023/11/2X XX:24:58 llama.go:435: signal: segmentation fault
2023/11/2X XX:24:58 llama.go:443: error starting llama runner: llama runner process has terminated
2023/11/2X XX:24:58 llama.go:509: llama runner stopped successfully
[GIN] 2023/11/2X XX03:24:58 | 500 |    120.5145ms |       127.0.0.1 | POST     "/api/generate"
```

It was working fine a couple of weeks ago. I also ran `ollama pull llama2-uncensored`, no change.

**Comment by Brockmerkwan** [comment]
i am just getting the llama runner process has terminated error as well i dont have logs i am on a mac mini the 8 gig version but i have had sucsess on running it before was trying to run mistral 
![Screenshot 2023-12-12 at 2 56 58 PM](https://github.com/jmorganca/ollama/assets/24733579/4a9001b9-d380-4ccc-aa71-88ab3749a888)
!

**Comment by EdByrnee** [comment]
> i am just getting the llama runner process has terminated error as well i dont have logs i am on a mac mini the 8 gig version but i have had sucsess on running it before was trying to run mistral ![Screenshot 2023-12-12 at 2 56 58 PM](https://private-user-images.githubusercontent.com/24733579/290001657-4a9001b9-d380-4ccc-aa71-88ab3749a888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTk2NjUsIm5iZiI6MTcwMjk5OTM2NSwicGF0aCI6Ii8yNDczMzU3OS8yOTAwMDE2NTctNGE5MDAxYjktZDM4MC00Y2NjLWFhNzEtODhhYjM3NDlhODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NTMzYTJkM2QyNWJkY2FmMjIyMzRhNTFjNDg4Yjk4YzhkMGU5NmY2ZTJjNzlkZmFlZTAyMWJmZTM1OTQ3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d1RRSmYEqvzhTFtERlEvQDbQJrbRN5yQ9Y6b0-eaahY) !

Is this because we need more RAM?

**Comment by wyy511511** [comment]
> Is this because we need more RAM?

I think so.
<img width="401" alt="image" src="https://github.com/ollama/ollama/assets/45887805/a2821c55-1b54-47bd-bac9-57294e7702ed">

when it reached the max(24G), it immediately be killed and gave me the error info (Error: llama runner process has terminated: signal: killed ).

**Comment by marvinHC54654g** [comment]
error: llama runner process has terminated: signal: killed是什么意思哦
