### ISSUE TITLE
How to disable streaming output in Rest API 

### ISSUE THREAD

**Issue by ajasingh** [jmorganca/ollama#789]
I am trying to get structured information like json back from model , so i am not looking at streamed output . I have tried setting content-type:application/json as mentioned in one of the issues but is still get back streamed output . Can somebody help me how to disable streamed output

**Comment by wzulfikar** [comment]
I tried and it works for me. I assume you're referring to https://github.com/jmorganca/ollama/pull/639 (where it adds the optional `"stream": false` param). Note that I didn't use `content-type: application/json`, just using `curl`.

```sh
curl -XPOST localhost:11434/api/generate -d '{"model": "zephyr", "prompt": "Why is the sky blue?", "stream": false }'
```

https://github.com/jmorganca/ollama/assets/7823011/914a4445-e051-4936-9ddb-a12c4221718d

**Comment by mxyng** [comment]
This is done in #639 and part of the release starting 0.1.2
