### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by technovangelist** [jmorganca/ollama#8]
When I ask a few questions in a conversation, there is no context between questions. So I have to include all the details in every prompt manually. I asked a question about Bainbridge Island, but after the response, it forgot and couldn't refer to it later in the conversation:

![CleanShot 2023-06-27 at 15 51 03](https://github.com/jmorganca/ollama/assets/633681/0c81fe58-71f8-4983-864f-2a0c86303a70)

**Comment by jmorganca** [comment]
#77 is an initial stab at this
