### ISSUE TITLE
Feature request: pull multiple models with ollama pull

### ISSUE THREAD

**Issue by rickknowles-cognitant** [jmorganca/ollama#803]
Would it be possible to request a feature allowing you to do the following on the command line:

```ollama pull mistral falcon orca-mini```

instead of having to do:

```
ollama pull mistral
ollama pull falcon
ollama pull orca-mini
```

Not a huge deal but it feels fairly natural to do this sort of approach for anyone using dev-ops or scripting heavy deployments. Thanks

(EDIT: at the moment it simply ignores the falcon and orca-mini in the first example and reports success, which is arguably a small bug)

**Comment by mxyng** [comment]
Ignoring the rest of the parameters is a bug and has been fixed in #841.

As for pulling multiple models, there's currently no plans but there are ways to achieve the same using bash:

```bash
echo mistral falcon orca-mini | xargs -n1 ollama pull
```

```bash
for model in mistral falcon orca-mini; do ollama pull $model; done
```

**Comment by purificant** [comment]
To update all downloaded models:

```bash
ollama list | tail -n +2 | cut -f1 | xargs -n1 ollama pull
```

**Comment by suizideFloat** [comment]
> To update all downloaded models:
> 
> ```shell
> ollama list | tail -n +2 | cut -f1 | xargs -n1 ollama pull
> ```

Is this downlaoding a models again or just the ones that actually got updated?

**Comment by fallenreaper** [comment]
@suizideFloat When I attempted to run it, it seemed like it pulled pulled updates.  It didnt seem to redownload.
That said, I prefer something like this:
```shell
for item in $(ollama list | cut -d" " -f1); do ollama pull $item; done;
```
which will loop through all the items and attempt to repull them as needed.

**Comment by iamthekwan** [comment]
Use && instead. Just copypaste into cmd:

`ollama pull mistral && ollama pull falcon && ollama pull orca-mini`
