### ISSUE TITLE
Is there a maximum in Modelfile??

### ISSUE THREAD

**Issue by LiuYang328** [jmorganca/ollama#804]
how many prompt I can provide in Modelfile

**Comment by simonSlamka** [comment]
> how many prompt I can provide in Modelfile

You should only define a system prompt in `Modelfile`. There's only one system prompt at a time.

**Comment by mxyng** [comment]
Modelfile docs are available here: https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md

If by prompt, you mean the system prompt, @simonSlamka is correct; you can only define one. However its contents can be long, e.g. thousands of bytes. 

If by prompt, you mean the general prompt template, you can modify that to whatever you want. The size limit is the same as the system prompt.

e.g. here's an example of a sentiment analysis using llama2 by seeding it with a preceding conversation

```
FROM llama2

TEMPLATE """[INST] <<SYS>>{{ .System }}<</SYS>>

Tweet: 'I hate it when my phone battery dies.' [/INST] Sentiment: Negative </s><s>[INST] Tweet: 'My day has been 👍' [/INST] Sentiment: Positive </s><s> [INST] Tweet: 'This is the link to the article' [/INST] Sentiment: Neutral </s><s> [INST] Tweet: '{{ .Prompt }}' [/INST] Sentiment: """
```

Keep in mind the LLM's context size becomes an issue at some point with large inputs.
