### ISSUE TITLE
Where are the role names specified?

### ISSUE THREAD

**Issue by louisabraham** [jmorganca/ollama#805]
Different models have different names for the roles (eg USER, ASSISTANT, AI).

This is how llama.cpp handles them:
- https://github.com/ggerganov/llama.cpp/blob/11bff290458f12f020b588792707f76ec658a27a/examples/chat-vicuna.sh
- https://github.com/ggerganov/llama.cpp/blob/11bff290458f12f020b588792707f76ec658a27a/examples/chat-13B.sh

I didn't find any specification of reverse-prompt anywhere. Do you know if it is used?

I found templates, like 

```
USER: {{ .Prompt }}
ASSISTANT: 
```

for Vicuna and 

```
[INST] {{ .Prompt }} [/INST]
```

for Mistral.

**Comment by mxyng** [comment]
Roles are defined in the Modelfile. You can see the Modelfile of a particular model with `ollama show --modelfile <model>`.

**Comment by louisabraham** [comment]
My question is actually: do you use reverse prompts? Can Vicuna have "USER:" in its output?
