### ISSUE TITLE
Add System prompt in WizardLM template

### ISSUE THREAD

**Issue by louisabraham** [jmorganca/ollama#806]
I think the following works quite well

```
{{ .System }}
USER: {{ .Prompt }}
ASSISTANT: 
```

**Comment by technovangelist** [comment]
It looks like this has been addressed. You can see the current template at https://ollama.ai/library/wizardlm:7b-q4_0. So I will go ahead and close it now. If you think there is anything we left out, reopen and we can address. Thanks for being part of this great community.
