### ISSUE TITLE
Unable to provide site access to the model running on Ubuntu Virtual Machine

### ISSUE THREAD

**Issue by NishaDeepak** [jmorganca/ollama#816]
I installed Ollama desktop in my ubuntu VM and ran the following commands:
$ OLLAMA_ORIGINS=https://webml-demo.vercel.app OLLAMA_HOST=127.0.0.1:11435 ollama serve

Then, in another window:
$ OLLAMA_HOST=127.0.0.1:11435 ollama pull mistral

But am unable to access the webpage.

**Comment by BruceMacD** [comment]
Do you see the ollama server in `netstat -tuln | grep 11435`?

**Comment by NishaDeepak** [comment]
Yes I can see it. Attached is the screenshot of the same.
<img width="484" alt="ollama_server" src="https://github.com/jmorganca/ollama/assets/68985503/d8de8a79-e5a4-4f93-bf76-c6fc1806ece3">

**Comment by mxyng** [comment]
What webpage are you referring to? What exactly is the error?

**Comment by NishaDeepak** [comment]
Could you please help me understand what the following command is doing:
OLLAMA_ORIGINS=https://webml-demo.vercel.app/ OLLAMA_HOST=127.0.0.1:11435 ollama serve

**Comment by mxyng** [comment]
It starts the ollama server and configures it bind to localhost port 11435 and allows webml-demo.vercel.app, a third-party web app, to communicate with the server.

**Comment by NishaDeepak** [comment]
Once I execute the command, how do I test this connection from the URL?
