### ISSUE TITLE
 failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sureshpatel66** [jmorganca/ollama#823]
~$ docker exec -it ollama ollama run llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": tls: failed to verify certificate: x509: certificate signed by unknown authority
please guide to solve this issue

**Comment by jmorganca** [comment]
Hi @sureshpatel66, which Docker image are you using? The official Ollama [image](https://hub.docker.com/r/ollama/ollama)  has the `ca-certificates` package as part of it which should avoid these errors

Thanks for creating an issue!

**Comment by sureshpatel66** [comment]
Thank you for prompt response.  I am using latest docker image. below is complete info.
~$ docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
Unable to find image 'ollama/ollama:latest' locally
latest: Pulling from ollama/ollama
ae---493d397: Pull complete
4---ad9be--: Pull complete
4a502874d---: Pull complete
Digest: sha256:7c2e4fefff8a7ec0a------6bc8d09aa88799a96d815e4d145---------
Status: Downloaded newer image for ollama/ollama:latest
40c------------------------------------------------------7
:~$ docker exec -it ollama ollama run llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by TimCoates** [comment]
Also hitting this on corporate device, despite trying different networks. Is it possible to add a flag to ignore unknown certs?

**Comment by mbbyn** [comment]
Facing the same issue here. I already set the corporate certificates as trusted using `ca-certificates` package, and using `curl` works without the `-k, --insecure` flag. According to Go, the language picks up the system certificates, but not sure why it's not in this case.

**Comment by marcellodesales** [comment]
I'm getting the same error while running it in a Kubernetes cluster without mounting any volume... Is there anything to set the trust of the certificate? or the error is in something else... Is there a way to set the container logger to DEBUG/TRACE?

**Comment by marcellodesales** [comment]
So, some clues on this:

* According to https://github.com/kubernetes/kubernetes/issues/43924#issuecomment-290905127, this error occurs when a docker client tries to pull docker images from an insecure Docker Registry... 
* Considering Ollama uses a docker registry to implement the model repository, I would say it's possible ollama's backend is actually a Docker Registry whose TLS certs were self-signed... Meanwhile, ollama's CLI client runs a client that connects to the docker daemon to pull the Models... 
* I don't get the same error running from my local machine, but I get it when running in a Kubernetes cluster... 
  * My local machine has all the bypass and lower security configuration while the Kubernetes cluster doesn't

**Comment by marcellodesales** [comment]
@sureshpatel66 Could you please reopen this ticket...? 

The error is on the ollama CLI client while pulling images from the docker registry... I would implement a param to trust any Ollama server (for the future)... And ollama's endpoint should use a CA to solve the OSS use...

**Comment by TimCoates** [comment]
Is it possible to provide alternative ways to download models, one or more of those might be able to circumvent the CA problem?

**Comment by zioalex** [comment]
Hi there, any update here. I am hitting the same problem

**Comment by andrealesani** [comment]
It seems that [ollama.ai](ollama.ai) now redirects to [ollama.com](ollama.com), and even opening the first one from the browser I get certificate errors... Is it possible that simply changing the URL from "[https://registry.ollama.ai/v2/library/llama2/manifests/latest](https://registry.ollama.ai/v2/library/llama2/manifests/latest)" to "[https://registry.ollama.com/v2/library/llama2/manifests/latest](https://registry.ollama.com/v2/library/llama2/manifests/latest)" solves the problem?

**Comment by maximeperrindev** [comment]
@andrealesani yeah, that probably should do the trick

**Comment by andrealesani** [comment]
> @andrealesani yeah, that probably should do the trick

Good to know! By chance, do you also know if there is a way to specify the URL from command line? Unfortunately, I am on Windows and I would like to avoid recompiling the whole thing (otherwise I might also try with WSL, but specifying URL manually would seem the easiest option)

**Comment by maximeperrindev** [comment]
@andrealesani i'm afraid we can't. If you don't want to recompile the whole app. You can also, as a workaround, create a `Modelfile` and use a downloaded .gguf.

I know it's not the best, but it's the easiest if you don't want to wait

**Comment by andrealesani** [comment]
FYI, they are talking about this in issue #3336. Easiest solution seems to change system time to 2 hours ago because the certificate expired an hour ago hahaha

**Comment by maximeperrindev** [comment]
@andrealesani no way ahha ! thanks

**Comment by Vasil-Dimitrov** [comment]
@andrealesani Worked for me like a charm after I moved my local time a few hours back lol

Simple yet genius solution

**Comment by bigghe** [comment]
For anyone still facing this issue, in my case from my office network I don't have any proxy but the SSL inspection enabled connecting to public resources.

I solved following the steps here https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy-in-docker which basically means building a custom container starting from _ollama/ollama_ and then add the firewall CA in _/usr/local/share/ca-certificates_ (without _-e HTTPS_PROXY=https://my.proxy.example.com_ in the docker run command).

**Comment by zongweix** [comment]
Hi there, any update here. I am hitting the same problem

**Comment by chengs** [comment]
this happens in large companies, in which SSL certs are modified to track users behaviors.

need ollama to have an option to bypass cert check.

such as -k --insure in `curl`

**Comment by pivu-sbab** [comment]
https://docs.ollama.com/faq#how-do-i-use-ollama-behind-a-proxy
