### ISSUE TITLE
Context modification

### ISSUE THREAD

**Issue by VladimirKras** [jmorganca/ollama#831]
Sometimes I would like to steer a dialogue in a certain direction by adding a fake message on behalf of the LLM. How to achieve that with Ollama seems quite opaque:
1. The context that is sent is just an array of token ids, which is hard to manipulate.  
2. The tokenizer and de-tokenizer aren't exposed.

**Comment by mxyng** [comment]
The context is intended to be opaque to the user. In that sense, you're expected to pass into the context what was returned by the previous response. 

If your use case requires changing history, it'll probably be better to not use the context at all but track the conversation yourself.

**Comment by MelihOzb** [comment]
The context shouldn't be opaque to the user, assume I want to load a past conversation with AI (just like you can do with ChatGPT and other LLMs). If we can insert context (i.e. access to tokenizer) then we can read the whole conversation from a database,  tokenize them and insert them into context and continue where we left. But now, I have to choose another method to be able to continue past conversation.

**Comment by mxyng** [comment]
@MelihOzb the current implementation supports that without needing to tokenize a previous conversation. You can see an example of exactly what you've described in https://github.com/mxyng/discollama. It [saves](https://github.com/mxyng/discollama/blob/main/discollama.py#L61) the context in redis which can be [loaded](https://github.com/mxyng/discollama/blob/main/discollama.py#L69) at a later point to continue the conversation.

**Comment by emsi** [comment]
OK, so regardless the context modification, how I can fake previous LLM response with ollama? This technique is used to better guide models without system prompt and acts as an example. Is it possible at all with ollama?

**Comment by emsi** [comment]
It's possible that chat api #1392 addresses that but I didn't test it yet.

**Comment by mxyng** [comment]
While it might not the intent of the issue creator, you can create and modify chat history as well as use multi-shot inputs using the chat API.
