### ISSUE TITLE
Support setting parameters without a modelfile

### ISSUE THREAD

**Issue by chigkim** [jmorganca/ollama#836]
I know you can set temperature using modelfile or api, but it would be much more convenient to be able to do it in cli.

For example:
`ollama run llama-2 -temperture 0.1` when loading
and/or
`/set temperature 0.1` in runtime
Thanks for your consideration!

**Comment by technovangelist** [comment]
Hi @chigkim, back when you submitted this, you suggested doing this on the CLI **OR** in the REPL. I'm not sure when it was rolled out, but you can now do this in the REPL. So if you run `ollama run llama2`, then you can type: `/set parameter temperature 0.1`. I think that addresses your issue. Would you say that is what you were hoping for? Should we close the issue?

**Comment by chigkim** [comment]
Thanks for letting me know!
That's seems possible now, and that was exactly what I was looking for.
Thanks!

**Comment by sammcj** [comment]
Is this actually fixed? I still can't find a way to set parameters without first loading a model (e.g. `ollama set parameter flash_attn true` etc...)
