### ISSUE TITLE
macOS Intel support

### ISSUE THREAD

**Issue by michaelthomasclark** [jmorganca/ollama#84]
Upon unzipping the Ollama download, I'm unable to launch the app. I get the following error: "You can’t open the application “Ollama” because this application is not supported on this Mac."

Mac is a MacBook Pro 15" from summer 2020 (w/ 64GB RAM on board - 32 of which is available)

**Comment by jmorganca** [comment]
@michaelthomasclark thanks for creating an issue!

Currently Ollama runs on Apple Silicon devices. We're working building a universal version that runs on both Intel and Apple Silicon. Stay tuned!

**Comment by jmorganca** [comment]
Merging this with #123 . Stay tuned for a universal version soon!
