### ISSUE TITLE
Ollama Docker: Error LLama runner process has terminated

### ISSUE THREAD

**Issue by randywreed** [jmorganca/ollama#845]
I'm running the latest docker version of ollama (as of 10/19/2023). When I do docker exec -it ollama ollama run mistral
I get the error Error Llama runner process has terminated.
The docker does not have .ollama/logs directory and journalctl is not installed.
Inside the docker it seems to have plenty of space, and free -m reports it has 127gb of ram available

Any help would be appreciated.

**Comment by mxyng** [comment]
Logs for Docker Ollama can be retrieved with `docker logs ollama`. Please attach it for troubleshooting. It's possible it's related to unsupported CPU instructions similar to https://github.com/jmorganca/ollama/pull/778 but it's impossible to know without logs.

What platform is this using?

**Comment by randywreed** [comment]
Thanks here it is. This is running on a linux machine, running centos. 
```
2023/10/19 18:59:13 download.go:126: downloading 8daa9615cce3 in 64 59 MB part(s)
2023/10/19 18:59:48 download.go:126: downloading 8c17c2ebb0ea in 1 7 KB part(s)
2023/10/19 18:59:51 download.go:126: downloading 7c23fb36d801 in 1 4 KB part(s)
2023/10/19 18:59:54 download.go:126: downloading bec56154823a in 1 59 B part(s)
2023/10/19 18:59:57 download.go:126: downloading e35ab70a78c7 in 1 90 B part(s)
2023/10/19 18:59:59 download.go:126: downloading 09fe89200c09 in 1 529 B part(s)
[GIN] 2023/10/19 - 19:00:22 | 200 |         1m11s |       127.0.0.1 | POST     "/api/pull"
2023/10/19 19:00:23 llama.go:333: skipping accelerated runner because num_gpu=0
2023/10/19 19:00:23 llama.go:356: starting llama runner
2023/10/19 19:00:23 llama.go:408: waiting for llama runner to start responding
2023/10/19 19:00:23 llama.go:373: error starting llama runner: llama runner process has terminated
[GIN] 2023/10/19 - 19:00:23 | 500 |  506.899039ms |       127.0.0.1 | POST     "/api/generate"
2023/10/19 19:00:23 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)
```

**Comment by mxyng** [comment]
those are the same symptoms as #778 which we're actively investigating

**Comment by randywreed** [comment]
Just for fun, I tried to rebuild the docker from the dockerfile i the repo, since grabs the latest update which would include the #778 pr. There error persisted
```
[GIN] 2023/10/20 - 19:45:33 | 200 |          1m7s |       127.0.0.1 | POST     "/api/pull"
2023/10/20 19:45:36 llama.go:340: skipping accelerated runner because num_gpu=0
2023/10/20 19:45:36 llama.go:363: starting llama runner
2023/10/20 19:45:36 llama.go:421: waiting for llama runner to start responding
2023/10/20 19:45:36 llama.go:378: signal: illegal instruction (core dumped)
2023/10/20 19:45:36 llama.go:386: error starting llama runner: llama runner process has terminated
2023/10/20 19:45:36 llama.go:452: llama runner stopped successfully
[GIN] 2023/10/20 - 19:45:36 | 500 |  2.570280569s |       127.0.0.1 | POST     "/api/generate"
```

**Comment by sunzh231** [comment]
same error in Dell R720.
CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Physical Host Operating System: vmware ESXI 6.7.0
Virtual host operating system: Ubuntu 22.04

**Comment by fabceolin** [comment]
same here:
2023/10/22 18:48:11 llama.go:356: starting llama runner
2023/10/22 18:48:11 llama.go:408: waiting for llama runner to start responding
2023/10/22 18:48:11 llama.go:373: error starting llama runner: llama runner process has terminated
2023/10/22 18:48:11 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)
2023/10/22 18:48:11 llama.go:356: starting llama runner
2023/10/22 18:48:11 llama.go:408: waiting for llama runner to start responding
2023/10/22 18:48:11 llama.go:373: error starting llama runner: llama runner process has terminated
[GIN] 2023/10/22 - 18:48:11 | 500 |  4.608264866s |       127.0.0.1 | POST     "/api/generate"
2023/10/22 18:48:11 llama.go:438: llama runner stopped with error: signal: illegal instruction (core dumped)
root@rig:/home/ubuntu#

**Comment by randywreed** [comment]
I was able to get this to work.
In my docker, I cloned the repo using gh cli  
then I installed pr #871 
and recompiled and it worked.  Here's my Dockerfile:
```
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ARG TARGETARCH="amd64"
ARG GOFLAGS="'-ldflags=-w -s'"

WORKDIR /go/src/github.com/jmorganca/ollama

# Update package list and install necessary tools
RUN apt-get update && apt-get install -y git build-essential cmake

# Download and install necessary tools
RUN apt-get update && apt-get install -y curl

# Download the GitHub CLI repository GPG key
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /usr/share/keyrings/githubcli-archive-keyring.gpg

# Update permissions on the GPG key
RUN chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg

# Add the GitHub CLI repository to the APT sources list
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

# Update the APT package index and install the GitHub CLI
RUN apt-get update && apt-get install -y gh
# Authenticate with GitHub (assuming a personal access token is used)
# Replace 'your_token_here' with your actual GitHub personal access token, make sure it has repo.read permissions
RUN echo 'ghp_github_token' | gh auth login --with-token

# Clone the repository (including submodules) and checkout the specified pull request
RUN gh repo clone jmorganca/ollama /go/src/github.com/jmorganca/ollama -- --recurse-submodules && \
    cd /go/src/github.com/jmorganca/ollama && \
    gh pr checkout 871

# Download and setup Go
ADD https://dl.google.com/go/go1.21.3.linux-$TARGETARCH.tar.gz /tmp/go1.21.3.tar.gz
RUN mkdir -p /usr/local && tar xz -C /usr/local </tmp/go1.21.3.tar.gz

# Build the application
ENV GOARCH=$TARGETARCH
ENV GOFLAGS=$GOFLAGS
RUN /usr/local/go/bin/go generate ./... \
    && /usr/local/go/bin/go build .

# Create a new stage for the final image
FROM ubuntu:22.04 

RUN apt-get update && apt-get install -y ca-certificates
COPY --from=0 /go/src/github.com/jmorganca/ollama/ollama /bin/ollama
EXPOSE 11434
ENV OLLAMA_HOST 0.0.0.0
ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]
```

**Comment by mxyng** [comment]
This is likely related to #644

**Comment by jmorganca** [comment]
Hi all! Ollama will now run on a larger range of CPUs as of version `0.1.6` and later. Note: AVX is still required – this should work for all CPUs released after 2011. If this doesn't fix the issue please feel free to re-open

**Comment by eviathan** [comment]
I am still getting this issue I guess the computer I am trying to run it on is too old.

**Comment by Zetto12** [comment]
I got the same issue. Pretty old hardware too.

Running a Ubuntu Server VM in Proxmox on an HP Z800 with DDR3 and X5690 CPU.

**Comment by Professor-Codephreak** [comment]
Same error. Using Mint 9.1 

verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
Error: llama runner process has terminated

**Comment by trifoil** [comment]
Error: llama runner process has terminated 

Running in a debian VM on TrueNAS
 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz 
DELL Poweredge R720

**Comment by chrisdromey** [comment]
Same issue.

Running in Ubuntu 22 VM on proxmox
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

**Comment by dosuken123** [comment]
Same issue.

MBA M2
OS: 14.0 (23A344)

```
Shinyas-Air:~ shinya$ ollama run llama2
pulling manifest 
pulling 22f7f8ef5f4c... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 3.8 GB                         
pulling 8c17c2ebb0ea... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 7.0 KB                         
pulling 7c23fb36d801... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 4.8 KB                         
pulling 2e0493f67d0c... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   59 B                         
pulling 2759286baa87... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  105 B                         
pulling 5407e3188df9... 100% ▕████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  529 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
Error: llama runner process has terminated
```

**Comment by dosuken123** [comment]
Ah, it turned out it's lacking memory https://github.com/jmorganca/ollama/issues/1508

**Comment by thommue** [comment]
Same issue here:

Error: llama runner process has terminated

VM on Proxmox, with 25 cores and 64GB of Ram
The CPU is an AMD 5950X.

**Comment by Bottlecap202** [comment]
Same issue here as well.
Error: llama runner process has terminated
Lenovo thinkstation c20
I was attempting to run with cuda but this was the most relevant

**Comment by timozn** [comment]
Same error running in Docker on a QNAP TS-855eU with a Intel Atom C5125, 64GB RAM and a nVidia Quadro P1000:

```
docker exec -it ollama-ollama-1 ollama run llama2
Error: llama runner process has terminated
```

```
docker logs ollama-ollama-1                      
2023/12/28 22:36:46 images.go:737: total blobs: 6
2023/12/28 22:36:46 images.go:744: total unused blobs removed: 0
2023/12/28 22:36:46 routes.go:895: Listening on [::]:11434 (version 0.1.17)
[GIN] 2023/12/28 - 22:36:53 | 200 |      45.607µs |       127.0.0.1 | HEAD     "/"
[GIN] 2023/12/28 - 22:36:53 | 200 |    3.464403ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2023/12/28 - 22:36:53 | 200 |    1.963032ms |       127.0.0.1 | POST     "/api/show"
{{false 2048 512 0 -1 0 false true false false true false true 0 0 0} 0 -1 -1 40 0.9 1 1 64 0.8 1.1 0 0 0 5 0.1 true [[INST] [/INST] <<SYS>> <</SYS>>]} 0 0
[--model /root/.ollama/models/blobs/sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --n-gpu-layers 26 --embedding]
2023/12/28 22:36:56 llama.go:300: 4037 MB VRAM available, loading up to 26 GPU layers
2023/12/28 22:36:56 llama.go:440: starting llama runner
2023/12/28 22:36:56 llama.go:498: waiting for llama runner to start responding
2023/12/28 22:36:56 llama.go:455: signal: illegal instruction
2023/12/28 22:36:56 llama.go:463: error starting llama runner: llama runner process has terminated
2023/12/28 22:36:56 llama.go:529: llama runner stopped successfully
2023/12/28 22:36:56 llama.go:440: starting llama runner
2023/12/28 22:36:56 llama.go:498: waiting for llama runner to start responding
2023/12/28 22:36:56 llama.go:455: signal: illegal instruction
2023/12/28 22:36:56 llama.go:463: error starting llama runner: llama runner process has terminated
2023/12/28 22:36:56 llama.go:529: llama runner stopped successfully
[GIN] 2023/12/28 - 22:36:56 | 500 |  2.808293837s |       127.0.0.1 | POST     "/api/generate"
```
When running without GPU attached to the container, the logs look like this:

```
docker logs ollama-ollama-1                      
2023/12/28 22:44:32 images.go:737: total blobs: 6
2023/12/28 22:44:32 images.go:744: total unused blobs removed: 0
2023/12/28 22:44:32 routes.go:895: Listening on [::]:11434 (version 0.1.17)
2023/12/28 22:44:32 routes.go:915: warning: gpu support may not be enabled, check that you have installed GPU drivers: nvidia-smi command failed
[GIN] 2023/12/28 - 22:45:15 | 200 |      76.164µs |       127.0.0.1 | HEAD     "/"
[GIN] 2023/12/28 - 22:45:15 | 200 |     729.665µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2023/12/28 - 22:45:15 | 200 |     547.037µs |       127.0.0.1 | POST     "/api/show"
{{false 2048 512 0 -1 0 false true false false true false true 0 0 0} 0 -1 -1 40 0.9 1 1 64 0.8 1.1 0 0 0 5 0.1 true [[INST] [/INST] <<SYS>> <</SYS>>]} 0 0
[--model /root/.ollama/models/blobs/sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --n-gpu-layers 0 --embedding]
2023/12/28 22:45:16 llama.go:407: skipping accelerated runner because num_gpu=0
2023/12/28 22:45:16 llama.go:440: starting llama runner
2023/12/28 22:45:16 llama.go:498: waiting for llama runner to start responding
2023/12/28 22:45:16 llama.go:455: signal: illegal instruction
2023/12/28 22:45:16 llama.go:463: error starting llama runner: llama runner process has terminated
2023/12/28 22:45:16 llama.go:529: llama runner stopped successfully
[GIN] 2023/12/28 - 22:45:16 | 500 |  1.074327638s |       127.0.0.1 | POST     "/api/generate"
```

**Comment by mr-biz** [comment]
> Same issue here:
> 
> Error: llama runner process has terminated
> 
> VM on Proxmox, with 25 cores and 64GB of Ram The CPU is an AMD 5950X.

I encountered the same error on Proxmox.  I resolved it by changing the VM CPU type from KVM64 (default) to host.
<img width="589" alt="image" src="https://github.com/jmorganca/ollama/assets/44796116/fbd25c96-e98e-454d-a723-addc7dc1dbf0">

**Comment by thommue** [comment]
> > Same issue here:
> > Error: llama runner process has terminated
> > VM on Proxmox, with 25 cores and 64GB of Ram The CPU is an AMD 5950X.
> 
> I encountered the same error on Proxmox. I resolved it by changing the VM CPU type from KVM64 (default) to host. <img alt="image" width="589" src="https://private-user-images.githubusercontent.com/44796116/293463494-fbd25c96-e98e-454d-a723-addc7dc1dbf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NjMyMzEsIm5iZiI6MTcwMzk2MjkzMSwicGF0aCI6Ii80NDc5NjExNi8yOTM0NjM0OTQtZmJkMjVjOTYtZTk4ZS00NTRkLWE3MjMtYWRkYzdkYzFkYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE5MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZWJhZDZmZGMxZjU4MGFjZDljNThjODUwOTE5Yjg1ZDUyMzI0ODJkNmU0ZDU3MjI0MTE5NGE2YjM3ODQxZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zyOvysIfZ3FUwZYoibKMwi_S3J0bTRhx2b5nXEjUnQs">

Yes it works!
Thanks for the help!

**Comment by kyuumeitai** [comment]
> > Same issue here:
> > Error: llama runner process has terminated
> > VM on Proxmox, with 25 cores and 64GB of Ram The CPU is an AMD 5950X.
> 
> I encountered the same error on Proxmox. I resolved it by changing the VM CPU type from KVM64 (default) to host. <img alt="image" width="589" src="https://private-user-images.githubusercontent.com/44796116/293463494-fbd25c96-e98e-454d-a723-addc7dc1dbf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjU4MDQsIm5iZiI6MTcwNDE2NTUwNCwicGF0aCI6Ii80NDc5NjExNi8yOTM0NjM0OTQtZmJkMjVjOTYtZTk4ZS00NTRkLWE3MjMtYWRkYzdkYzFkYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAzMTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZTM2NjdhMjI5ZWIzM2Y0YjFhNDYyNjY2NjIzZGFiNTAyZDgzMGU1Yjg0Y2MyZjQwNzJhMTJkZDFhMWVkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XT7L5D6mAWmZ5-_buAk7_i10_eT6vCkFgDZfymqndPI">

thank you so much. For me in proxmox changing the vm CPU to host solved it.

**Comment by idem2lyon** [comment]
Hi all, is it possible to get the same option in esxi ?

**Comment by xdfnet** [comment]
Same issue here:
`ollama create eduaigc -f modelfile
transferring model data
using existing layer sha256:265610b1c6f4ad9d6d1d6377b3ebe39d348a3db5bc5d37185de7d554e31e6f75
creating new layer sha256:1507233b03785311a99a1beaf27f72d5a1c15abb3d2deba635defb2c68059262
creating new layer sha256:1da117d6723df114af0d948b614cae0aa684875e2775ca9607d23e2e0769651d
creating new layer sha256:fa304d6750612c207b8705aca35391761f29492534e90b30575e4980d6ca82f6
creating new layer sha256:74454e71de083d29904e44fd8f5a7a0e5c1c020cd2553a0860a72bc4d5a9c6ef
writing manifest
success`
` ollama run eduaigc
Error: llama runner process has terminated: exit status 0xc0000409`

**Comment by vishalharkal15** [comment]
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Follama%2Follama%2Fissues%2F845
![Uploading Screenshot 2024-06-27 190147.png…]()

**Comment by vishalharkal15** [comment]
![Screenshot 2024-06-27 185319](https://github.com/ollama/ollama/assets/168349626/e7b4e0d9-d032-4e7b-b26e-f71b4969f6a4)
![Screenshot 2024-06-27 184756](https://github.com/ollama/ollama/assets/168349626/9d271da4-647d-49b6-bfd3-92c78bbd2e75)

**Comment by 121212wwd** [comment]
i just have an issue when downloading the codegemma 7b, i am going to try install the lesser version, but i have 4gb or ram and some really 4SS CPU, i'm thinking maybe its not enough but seeing that there was a guy that had some good specs including a GPU, maybe the computers just aren't enough to handle these ai apis. my sinopsis or conclusion is that maybe the type of hardware is needed to handle the AI's we just dont have, maybe one person had an AMD GPU but it says  it looks for a NVIDIA gpu, if anyone has something like an NVIDIA gpu, or some specs that can handle this sort of thing post down, i'm very curious about this.

oh and i think i read half of this thread XD

**Comment by vishalharkal15** [comment]
I've encountered an issue while downloading the CodeGemma 7B model. Before trying to install a lesser version, I wanted to share some details about my hardware. I have 4GB of RAM and a 4SS CPU. I'm starting to think that my setup might not be sufficient to handle these AI APIs.

I noticed a post from someone with good specs, including a GPU, who was also facing issues. This makes me wonder if our computers might just not be powerful enough to handle these AI models.

Additionally, it seems that CodeGemma is looking for an NVIDIA GPU, but one person mentioned having an AMD GPU. If anyone has an NVIDIA GPU or hardware that can handle these kinds of models, could you please share your specs? I'm very curious to see what kind of hardware is needed to run this smoothly.

**Comment by 121212wwd** [comment]
dude, did you just steal my comment  and post it as your own? actually post something of your own

**Comment by Bhavya031** [comment]
> dude, did you just steal my comment and post it as your own? actually post something of your own

Yeah, I think he is trying to comment to get a contribution highlight on his GitHub page. He also posted a screenshot of installing Ollama on Windows, which is irrelevant to this topic. Above that, there is some other screenshot link. I think he doesn't understand that you have to make a commit to get that dot.

**Comment by ISMAEL45966** [comment]
![IMG_20240728_090438818_1.jpg](https://github.com/user-attachments/assets/6f578d1b-9944-456b-bdcf-c52b6132a0b7)

One question: how can I solve this problem? Thank you very much for your response.

**Comment by 121212wwd** [comment]
Add your specs in a new comment, maybe it's because you haven't got the power to run it or maybe try and find an answer in the thread, it's closed so someone has already found the problem and fixed it. 

Good Luck

DOODES MALOODES OUT >>

**Comment by 121212wwd** [comment]
ITS A MEMORY PROBLEM, IF NOT THEN GOD KNOWS WHAT IT IS

**Comment by ISMAEL45966** [comment]
![IMG_20240802_164219670_1.jpg](https://github.com/user-attachments/assets/ed73c250-68d7-47b4-b705-ebb233e45813)
Does anyone know why I get that?

**Comment by ISMAEL45966** [comment]
![IMG_20240802_164219670_1.jpg](https://github.com/user-attachments/assets/ed73c250-68d7-47b4-b705-ebb233e45813)
Does anyone know why I get that?

**Comment by 121212wwd** [comment]
@ISMAEL45966 PLEASE READ THE ABOVE COMMENT, Your lack of observation is concerning. If you are running an AI it is very power and resource dependent. SO if you have a laptop it's not the vast idea to run Deepseek code VERSION 2 ON A LAPTOP. Please read this and stop commenting, i have an answer for you, READ IT

**Comment by RobRoyce** [comment]
I am getting the same error while trying to run `llama3.1:8b` (~4GB) on a 64GB M2 Mac. The same model ran two days ago just fine. This is _not_ a memory problem.

**Comment by RobRoyce** [comment]
> @RobRoyce Hey I have the same exact problem. It was working yesterday but now my ollama returns 500 Internal Server Error

I was previously running in Docker. After installing Ollama locally, it magically started working. My Docker resources were set to provide 24GB of RAM, so I still don't see why it failed.

**Comment by khuezy** [comment]
@RobRoyce I believe 0.3.8 (3 days ago) broke ollama in docker. 
Try `curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.3.6 | sh`
It's always a good idea to lock down the specific version instead of running latest.

**Comment by RobRoyce** [comment]
Thank you, I'll give this a shot!

**Comment by 121212wwd** [comment]
Hey, i think this is a memory problem for people that have laptops and try to run something where you NEED that memory, but you've found the solution. so have fun.
maybe it's docker, maybe it's RAM, but my comment was just an assumption and warns people that use laptops with specs that can't handle ollama, to not use ollama, instead use chatgpt.
I hope you got your issue resolved but i only made an assumption while also being very positive and strong that that was the issue. 
My bad.
I, in total, have 4gbs of memory and i'm running in linux. Bit of a different situation for me, if you have a solution plz comment, i'd really like to try on my pc instead.
got to try it first though.

**Comment by ShivamSrng** [comment]
> I am getting the same error while trying to run `llama3.1:8b` (~4GB) on a 64GB M2 Mac. The same model ran two days ago just fine. This is _not_ a memory problem.

Were you able to solve it ? I am facing the same issue as yours. Here's how it looks in case:
CUDA error: an illegal instruction was encountered
  current device: 0, in function ggml_backend_cuda_synchronize at C:\a\ollama\ollama\llm\llama.cpp\ggml\src\ggml-cuda.cu:2473
  cudaStreamSynchronize(cuda_ctx->stream())
C:\a\ollama\ollama\llm\llama.cpp\ggml\src\ggml-cuda.cu:106: CUDA error

OS: Windows
GPU: Nvidia
CPU: Intel
Ollama version: 0.3.14
Driver Version: 552.44
CUDA Version: 12.4

**Comment by 121212wwd** [comment]
That means an illegal thing was done, don't override it or belreak it. Try to reinstall. I also think with bigger models you might need a beefier pc, don't use a laptop it will melt

**Comment by smdhussain06** [comment]
Same error using in android
