### ISSUE TITLE
Can't access model information in fresh (botched?) Linux (Ubuntu 22.04 LTS) install

### ISSUE THREAD

**Issue by TM-hub** [jmorganca/ollama#846]
Step1, run linux install script in terminal window
    $curl https://ollama.ai/install.sh | sh

Step 2, install ollama model ***in the same terminal window***
    $ollama run mistral

Model is installed to /usr/share/ollama/.ollama owned by ollama:ollama.
    >>>/show template
Fails with message ~"can't access /home/<user>/.ollama"

Step 3, try adding my user to group ollama to get access to model info
    $sudo usermod -a -G ollama <user>
Open new terminal window and still can't access /usr/share/ollama as I can't be added to the group without access to ollama's home directory (/usr/share/ollama).

WORKAROUND
Step 4, Edited /etc/passwd to change ollama's home directory to /home/<user>
Models are still installed to /usr/share/ollama/.ollama but I can now access, e.g. --template

QUESTIONS
Is the ollama home directory supposed to be in /home/<user>?
How do I change it from /usr/share/ollama? 

Linux install.sh should warn the user to close terminal before running ollama for the first time.

**Comment by mxyng** [comment]
This is a bug with `/show` where it uses server functions directly instead of making a call to the API. It's fixed in https://github.com/jmorganca/ollama/pull/778 and should be in the next release

**Comment by TM-hub** [comment]
Thank you for the reply mxyng.

Is /usr/share/ollama the intended location for OLLAMAHOME?
If so, the ownership ollama:ollama and permissions (drwxr-x---) are problematic.
I had to use lsof -u ollama to find the hidden, unreadable directory where the models are stored.
Why have hidden directories in /usr/share?
