### ISSUE TITLE
How to secure the API with api key

### ISSUE THREAD

**Issue by ajasingh** [jmorganca/ollama#849]
We have deployed OLLAMA container with zephyr model inside kubernetes , so as a best practice we want to secure the endpoints via api key similar way to OpenAI , so is there any way to do this ?

**Comment by BruceMacD** [comment]
The solution to this for the time being would be to add an authenticating proxy in front of Ollama (ex: nginx with basic auth)

**Comment by coolaj86** [comment]
Here's how you add HTTP Basic Auth with `caddy`, which also handles HTTPS automatically:

0. Install caddy
   ```sh
   # Mac, Linux
   curl https://webi.sh/caddy | sh

   # Windows
   curl.exe https://webi.ms/caddy | powershell
   ```
1. Put your password in a `password.txt`
2. Digest the password
   ```sh
   caddy hash-password < ./password.txt
   ```
3. Put the username and digest in an ENV file \
   `caddy.env`:
   ```
   BASIC_AUTH_USER='apitoken'
   BASIC_USER_AUTH='$2a$14$sI1j0RbhzKHMZ4cHU8otHOkB3Dgl9egF2D.CXB6C0/Qk5dtaMHS/u'
   ```
4. Create a `Caddyfile` with basic auth using the ENVs
   ```Caddyfile
   api.example.com {
       handle /* {
           basicauth {
               {env.BASIC_AUTH_USERNAME} {env.BASIC_AUTH_DIGEST}
           }
           reverse_proxy localhost:11434
       }
   }
   ```
5. Run caddy
   ```sh
   caddy run --config ./Caddyfile --envfile ./caddy.env
   ```

And if you want to run it as a system service or need other details, I've got a bunch of snippets up at <https://webinstall.dev/caddy>.

**Comment by ParisNeo** [comment]
With caddy you can also do multiple users. You can create a little interface to add users and serve it with the tool. That makes using ollama much safer

**Comment by DimIsaev** [comment]
Why is the authorization mechanism not built into the Ollama server ?

**Comment by ParisNeo** [comment]
If you are interested, I have built a proxy server for ollama:
https://github.com/ParisNeo/ollama_proxy_server

It allows those features:
1 - Authentication with user:key Bearer
2 - Adding new users
3 - Logging access to the service (useful for statictics). By default the proxy doesn't log your requests, it only logs that you requested generation which is useful for statistics and for dimensionning the network.
4 - Routing to multiple ollama instances. For example you can have multiple ollama servers and use a single endpoint that will take care of dispatching the generation requests to the different servers . Each server has its own generation queue and the proxy will always forward the request to the server with the least number of requests in the queue. This makes it possible to serve simultaniously multiple clients while garanteeing a minimum latency.

Ollama is a very powerful and fast generation tool. But I think with the new proxy, it takes the potential to a new level.

**Comment by alx-xlx** [comment]
@coolaj86 Hey I tried to use your steps, I am running it on macos, but I get this error

```
Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authentication': provision http.handlers.authentication: loading authentication providers: module name 'http_basic': provision http.authentication.providers.http_basic: account 0: username and password are required
```

HERE is my config

```
BASIC_AUTH_USER='apitoken'
BASIC_USER_AUTH='$2a$14$Z7jW916wS4WAmpUBBuuEreMu51s09pC1I/exwdaHtPENtsxAhuniK'
```

```
api-ollama.example.org {
    tls {
        dns cloudflare _Q*************************-VP
    }
    handle /* {
        basicauth {
            {env.BASIC_AUTH_USERNAME} {env.BASIC_AUTH_DIGEST}
        }
        reverse_proxy localhost:11434
    }
}
```

**Comment by tandriamil** [comment]
The environment variables do not match in this example. Try replacing `env.BASIC_AUTH_USERNAME` by `env.BASIC_AUTH_USER` and `env.BASIC_AUTH_DIGEST` by `BASIC_USER_AUTH`. 😉

**Comment by alx-xlx** [comment]
I am using this configuration and it does prompt me to enter username and password, however when I do so it gives `ERROR : 403`

```
api-ollama.example.org {
    tls {
        dns cloudflare _QRi******************5u-VP
    }
    handle /* {
        basicauth {
            {env.BASIC_AUTH_USER} {env.BASIC_USER_AUTH}
        }
        reverse_proxy localhost:11434
    }
    log {
        output file /Users/USERNAME/Server/data/customcaddy/api-ollama.log {
            roll_size 100mb
            roll_keep 5
            roll_keep_for 720h
        }
    }
}
```

Logs when I enter the username and password 

```
2024/05/31 09: 36: 37.104	error	http.log.access.log0	handled request	{
    "request": {
        "remote_ip": "192.168.0.122",
        "remote_port": "62601",
        "client_ip": "192.168.0.122",
        "proto": "HTTP/2.0",
        "method": "GET",
        "host": "api-ollama.example.org",
        "uri": "/",
        "headers": {
            "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
            ],
            "Sec-Fetch-User": [
                "?1"
            ],
            "Sec-Fetch-Dest": [
                "document"
            ],
            "Sec-Ch-Ua-Mobile": [
                "?0"
            ],
            "Sec-Ch-Ua": [
                "\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""
            ],
            "Sec-Fetch-Mode": [
                "navigate"
            ],
            "Accept-Encoding": [
                "gzip, deflate, br, zstd"
            ],
            "Save-Data": [
                "on"
            ],
            "Authorization": [],
            "Accept-Language": [
                "en-US,en;q=0.9,hi;q=0.8"
            ],
            "Priority": [
                "u=0, i"
            ],
            "Sec-Ch-Ua-Platform": [
                "\"Windows\""
            ],
            "Upgrade-Insecure-Requests": [
                "1"
            ],
            "Accept": [
                "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
            ],
            "Sec-Fetch-Site": [
                "none"
            ],
            "Cache-Control": [
                "max-age=0"
            ]
        },
        "tls": {
            "resumed": false,
            "version": 772,
            "cipher_suite": 4865,
            "proto": "h2",
            "server_name": "api-ollama.example.org"
        }
    },
    "bytes_read": 0,
    "user_id": "admin",
    "duration": 0.994463625,
    "size": 0,
    "status": 403,
    "resp_headers": {
        "Date": [
            "Fri, 31 May 2024 09:36:37 GMT"
        ],
        "Content-Length": [
            "0"
        ],
        "Server": [
            "Caddy"
        ],
        "Alt-Svc": [
            "h3=\":443\"; ma=2592000"
        ]
    }
}
```

**Comment by dheavy** [comment]
Sorry, this isn't solving the precise issue discussed on the couple of previous messages, but as an alternative solution for the subject of this thread -- I have developed a quickly deployable solution to not have to deal with nginx 

https://github.com/dheavy/ollama-secure-proxy

**Comment by bartolli** [comment]
I had trouble setting up the native api_key authentication on the Ollama Go server, so instead, I set up a Docker image with the latest Caddy server and Ollama This setup uses a Bearer header for authentication, much like the OpenAI API, making it work seamlessly with all endpoints and methods. You can check out the setup on Docker Hub and GitHub if you're interested.

Docker: https://hub.docker.com/r/bartolli497/ollama-bearer-auth
Github: https://github.com/bartolli/ollama-bearer-auth

**Comment by chigkim** [comment]
It would be great for Ollama to directly support api token with ssl!

**Comment by SomeoneSerge** [comment]
> The solution to this for the time being would be to add an authenticating proxy in front of Ollama (ex: nginx with basic auth)

Note: https://github.com/ollama/ollama/issues/739 would allow to accomplish this in a simple systemd unit, without doing anything cursed about network namespaces

**Comment by KaKi87** [comment]
Hello @mxyng,
Why is this feature discarded ?
Thank you

**Comment by frederikb96** [comment]
> Here's how you add HTTP Basic Auth with `caddy` as a reverse proxy to `localhost:11434`, and also handle HTTPS automatically:
> 
>     0. Install caddy
>        # Mac, Linux
>        curl https://webi.sh/caddy | sh
>        
>        # Windows
>        curl.exe https://webi.ms/caddy | powershell
> 
>     1. Put your password (which could be an API Token) in a `password.txt`
> 
>     2. Digest the password
>        caddy hash-password < ./password.txt
> 
>     3. Put the username and digest in an ENV file 
>        `caddy.env`:
>        ```
>        BASIC_AUTH_USER='apitoken'
>        BASIC_USER_AUTH='$2a$14$sI1j0RbhzKHMZ4cHU8otHOkB3Dgl9egF2D.CXB6C0/Qk5dtaMHS/u'
>        ```
> 
>     4. Create a `Caddyfile` with basic auth using the ENVs
>        api.example.com {
>            handle /* {
>                basicauth {
>                    {env.BASIC_AUTH_USERNAME} {env.BASIC_AUTH_DIGEST}
>                }
>                reverse_proxy localhost:11434
>            }
>        }
> 
>     5. Run caddy
>        caddy run --config ./Caddyfile --envfile ./caddy.env
> 
> 
> And if you want to run it as a system service, or _without_ HTTPS or need other details, I've got a bunch of snippets up at https://webinstall.dev/caddy.


This is deprecated by now. You can instead try this, which works for me together with API Key auth and I am able to use it with openai connectors which require API Key auth:

```
nano caddy.env
```

```
API_KEY='some-key'
```

```
nano Caddyfile
```


```
api.example.com {
	# if you have 80 and 443 open on the ollama server, you can specify tls and caddy automatically sets up SSL for you such that external connectors securely connect to your Ollama API with SSL and do not complain about certificates
	# tls somemail@mail.com
	
	@requireAuth {
		not header Authorization "Bearer {env.API_KEY}"
	}

	respond @requireAuth "Unauthorized" 401

	reverse_proxy localhost:11434
}
```

**Comment by vadimkantorov** [comment]
I agree, supporting a basic API key / basic auth would be a great feature for basic bootstrapping / testing ollama (without having to also configure/test nginx for proxy). Similar to how Jupyter Hub supports a username/password out of the box.

**Comment by hansenz42** [comment]
> > Here's how you add HTTP Basic Auth with `caddy` as a reverse proxy to `localhost:11434`, and also handle HTTPS automatically:
> > ```
> > 0. Install caddy
> >    # Mac, Linux
> >    curl https://webi.sh/caddy | sh
> >    
> >    # Windows
> >    curl.exe https://webi.ms/caddy | powershell
> > 
> > 1. Put your password (which could be an API Token) in a `password.txt`
> > 
> > 2. Digest the password
> >    caddy hash-password < ./password.txt
> > 
> > 3. Put the username and digest in an ENV file 
> >    `caddy.env`:
> >    ```
> >    BASIC_AUTH_USER='apitoken'
> >    BASIC_USER_AUTH='$2a$14$sI1j0RbhzKHMZ4cHU8otHOkB3Dgl9egF2D.CXB6C0/Qk5dtaMHS/u'
> >    ```
> > 
> > 4. Create a `Caddyfile` with basic auth using the ENVs
> >    api.example.com {
> >        handle /* {
> >            basicauth {
> >                {env.BASIC_AUTH_USERNAME} {env.BASIC_AUTH_DIGEST}
> >            }
> >            reverse_proxy localhost:11434
> >        }
> >    }
> > 
> > 5. Run caddy
> >    caddy run --config ./Caddyfile --envfile ./caddy.env
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And if you want to run it as a system service, or _without_ HTTPS or need other details, I've got a bunch of snippets up at https://webinstall.dev/caddy.
> 
> This is deprecated by now. You can instead try this, which works for me together with API Key auth and I am able to use it with openai connectors which require API Key auth:
> 
> ```
> nano caddy.env
> ```
> 
> ```
> API_KEY='some-key'
> ```
> 
> ```
> nano Caddyfile
> ```
> 
> ```
> api.example.com {
> 	# if you have 80 and 443 open on the ollama server, you can specify tls and caddy automatically sets up SSL for you such that external connectors securely connect to your Ollama API with SSL and do not complain about certificates
> 	# tls somemail@mail.com
> 	
> 	@requireAuth {
> 		not header Authorization "Bearer {env.API_KEY}"
> 	}
> 
> 	respond @requireAuth "Unauthorized" 401
> 
> 	reverse_proxy localhost:11434
> }
> ```

After testing with curl, I found that when accessing via some "api.example.com", you need to set the reverse proxy header to localhost. Otherwise, Ollama will deny the request with a 403 error.:

```
api.example.com {
	# if you have 80 and 443 open on the ollama server, you can specify tls and caddy automatically sets up SSL for you such that external connectors securely connect to your Ollama API with SSL and do not complain about certificates
	# tls somemail@mail.com
	
	@requireAuth {
		not header Authorization "Bearer {env.API_KEY}"
	}

	respond @requireAuth "Unauthorized" 401

	reverse_proxy localhost:11434 {
               header_up Host 127.0.0.1:11434
        }
}
```

**Comment by PJ-568** [comment]
<details>
<summary>
Reply
</summary>

> > > Here's how you add HTTP Basic Auth with `caddy` as a reverse proxy to `localhost:11434`, and also handle HTTPS automatically:
> > > ```
> > > 0. Install caddy
> > >    # Mac, Linux
> > >    curl https://webi.sh/caddy | sh
> > >    
> > >    # Windows
> > >    curl.exe https://webi.ms/caddy | powershell
> > > 
> > > 1. Put your password (which could be an API Token) in a `password.txt`
> > > 
> > > 2. Digest the password
> > >    caddy hash-password < ./password.txt
> > > 
> > > 3. Put the username and digest in an ENV file 
> > >    `caddy.env`:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > BASIC_AUTH_USER='apitoken'
> > > BASIC_USER_AUTH='$2a$14$sI1j0RbhzKHMZ4cHU8otHOkB3Dgl9egF2D.CXB6C0/Qk5dtaMHS/u'
> > > ```
> > > 
> > > 4. Create a `Caddyfile` with basic auth using the ENVs
> > > api.example.com {
> > >     handle /* {
> > >         basicauth {
> > >             {env.BASIC_AUTH_USERNAME} {env.BASIC_AUTH_DIGEST}
> > >         }
> > >         reverse_proxy localhost:11434
> > >     }
> > > }
> > > 
> > > 5. Run caddy
> > > caddy run --config ./Caddyfile --envfile ./caddy.env
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And if you want to run it as a system service, or _without_ HTTPS or need other details, I've got a bunch of snippets up at https://webinstall.dev/caddy.
> > 
> > 
> > This is deprecated by now. You can instead try this, which works for me together with API Key auth and I am able to use it with openai connectors which require API Key auth:
> > ```
> > nano caddy.env
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > API_KEY='some-key'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > nano Caddyfile
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > api.example.com {
> > 	# if you have 80 and 443 open on the ollama server, you can specify tls and caddy automatically sets up SSL for you such that external connectors securely connect to your Ollama API with SSL and do not complain about certificates
> > 	# tls somemail@mail.com
> > 	
> > 	@requireAuth {
> > 		not header Authorization "Bearer {env.API_KEY}"
> > 	}
> > 
> > 	respond @requireAuth "Unauthorized" 401
> > 
> > 	reverse_proxy localhost:11434
> > }
> > ```
> 
> After testing with curl, I found that when accessing via some "api.example.com", you need to set the reverse proxy header to localhost. Otherwise, Ollama will deny the request with a 403 error:
> 
> ```
> api.example.com {
> 	# if you have 80 and 443 open on the ollama server, you can specify tls and caddy automatically sets up SSL for you such that external connectors securely connect to your Ollama API with SSL and do not complain about certificates
> 	# tls somemail@mail.com
> 	
> 	@requireAuth {
> 		not header Authorization "Bearer {env.API_KEY}"
> 	}
> 
> 	respond @requireAuth "Unauthorized" 401
> 
> 	reverse_proxy localhost:11434 {
>                header_up Host 127.0.0.1:11434
>         }
> }
> ```

</details>

Yet another approach: `curl -sSL https://raw.githubusercontent.com/PJ-568/ollama-proxy/refs/heads/master/install.sh | bash`

Form [PJ-568/ollama-proxy](https://github.com/PJ-568/ollama-proxy).

**Comment by Ccocconut** [comment]
> why the authorization mechanism cannot be built into the ollama server?

It is not ollama's job. It is yours to use whatever you can, i.e. nginx or Caddy to secure your shit. It is out of scope of ollama and it adds friction and unnecessary code that may introduce bugs.

**Comment by KaKi87** [comment]
> It is not ollama's job.

When one serves content on a port, it is.

**Comment by Ccocconut** [comment]
> > It is not ollama's job.
> 
> When one serves content on a port, it is.

No. Ollama should not implement authentication. Its focus is on serving models. Security (auth, TLS) should be handled by a reverse proxy like Nginx or Caddy. This separation is standard in web architecture: application logic vs. access control.

To elaborate: serving content on a port does NOT automatically imply that it is responsible for access control or authentication. The act of binding to a port and responding to requests is a technical requirement for providing a service, but securing that service (via Basic Auth, TLS, or other mechanisms) is generally delegated to a reverse proxy or security layer. Expecting the service itself to implement authentication conflates the responsibilities of service delivery and access control, which are typically separated for maintainability and security reasons.

Expecting every service to implement access control would be absurd. What's next, fork OpenBSD for every port it opens? If listening on a port meant you needed built-in security, every daemon on Unix would come bundled with its own firewall. Spoiler: they don't, and that's how sane system architecture works. Protect the service yourself, you are responsible!

The idea that (opening) a port automatically makes a program responsible for security is as misguided as thinking a toaster should handle fire suppression.

**Comment by KaKi87** [comment]
> The act of binding to a port and responding to requests is a technical requirement for providing a service

Absolutely not.

Ever heard of [inter-process communication (IPC)](https://en.wikipedia.org/wiki/Inter-process_communication), especially [Unix domain sockets (UDS)](https://en.wikipedia.org/wiki/Unix_domain_socket), which a lot of services use, like Docker, to respond to requests from a huge variety of clients ?

**Comment by Ccocconut** [comment]
> > The act of binding to a port and responding to requests is a technical requirement for providing a service
> 
> Absolutely not.
> 
> Ever heard of [inter-process communication (IPC)](https://en.wikipedia.org/wiki/Inter-process_communication), especially [Unix domain sockets (UDS)](https://en.wikipedia.org/wiki/Unix_domain_socket), which a lot of services use, like Docker, to respond to requests from a huge variety of clients ?

Yes, I'm aware of IPC and Unix Domain Sockets. Many services, especially on Unix, indeed use UDS or other IPC mechanisms to receive requests locally without opening a network port. My point wasn't that every service must bind to a TCP port, it was that whatever mechanism a service uses to accept requests, it is not inherently responsible for authentication or access control. Whether it's a TCP port, a UDS, or another IPC channel, securing access is still the responsibility of a security layer (reverse proxy, firewall, system permissions, etc.), not the service itself.

The underlying principle remains: serving requests ≠ handling authentication.

To reiterate: Ollama serves models. Protect the service yourself, you are responsible. Ports or sockets don't confer magical security duties.

**Comment by KaKi87** [comment]
> whatever mechanism a service uses to accept requests, it is not inherently responsible for authentication or access control [...] Whether it's a TCP port, a UDS, or another IPC channel, securing access is still the responsibility of a security layer (reverse proxy, firewall, system permissions, etc.), not the service itself.

That's where I disagree.

If you use IPC, you're already protected.

If you use a port, you are responsible for protecting it.

**Comment by Ccocconut** [comment]
> > whatever mechanism a service uses to accept requests, it is not inherently responsible for authentication or access control [...] Whether it's a TCP port, a UDS, or another IPC channel, securing access is still the responsibility of a security layer (reverse proxy, firewall, system permissions, etc.), not the service itself.
> 
> That's where I disagree.
> 
> If you use IPC, you're already protected.
> 
> If you use a port, you are responsible for protecting it.

Yes, I couldn't agree more: if you use a port, you are responsible for protecting it - that's literally my point. Whether it's a TCP port, a UDS, or any other interface, the service itself doesn't enforce security - the responsibility always lies with whoever exposes it, i.e. YOU. IPC like Unix Domain Sockets may reduce exposure via OS-level permissions, but any interface has boundaries that must be consciously secured. Thinking ports make a program responsible while UDS absolves it is oversimplified. Ollama serves models - you are responsible.

**Comment by vadimkantorov** [comment]
I think, basic auth support (built-in) or via an official python wrapper is important, but not for production use - for testing and tinkering ollama in small teams, like JupyterLab does it (having some basic password protection support). So that it's a bit harder to have a footgun by default...

**Comment by kesor** [comment]
The least ollama could do is reference third party solutions, many of which were mentioned in this thread, in some kind of documentation or wiki or something. So that anyone raising this issue again can be referred to the list of existing solutions.

**Comment by Ccocconut** [comment]
> I think, basic auth support (built-in) or via an official python wrapper is important, but not for production use - for testing and tinkering ollama in small teams, like JupyterLab does it (having some basic password protection support). So that it's a bit harder to have a footgun by default...

I see where you're coming from, having lightweight password protection for local testing or small teams can make experimentation safer and reduce accidental exposure.

That said, I would still argue that this is fundamentally different from built-in authentication for production-level security. Even "lightweight" protection can give a false sense of safety / security if someone assumes it's robust. In practice, any serious deployment should rely on standard access controls - reverse proxies, TLS, OS-level permissions - rather than expecting the model server itself to handle authentication.

> The least ollama could do is reference third party solutions, many of which were mentioned in this thread, in some kind of documentation or wiki or something. So that anyone raising this issue again can be referred to the list of existing solutions.

I agree, having a section in the documentation or wiki that references third-party solutions for securing Ollama (Nginx, Caddy[1], reverse proxies, OS permissions, etc.) would be very helpful. It doesn't change the principle that Ollama itself should focus on serving models, but it would make it easier for users to find safe ways to deploy it without reinventing the wheel or misunderstanding responsibilities. I would probably add a section for various methods of doing this.

[1] Something like https://github.com/ollama/ollama/issues/849#issuecomment-1773697189, for example.

**Comment by KaKi87** [comment]
> Yes, I couldn't agree more: if you use a port, you are responsible for protecting it - that's literally my point.

I meant *you* as the developer.

**Comment by KaKi87** [comment]
> basic auth support [...] is important, but not for production use - for testing

> having lightweight password protection for local testing or small teams can make experimentation safer and reduce accidental exposure [...] this is fundamentally different from built-in authentication for production-level security. Even "lightweight" protection can give a false sense of safety / security if someone assumes it's robust

What's the difference between built-in BasicAuth and Caddy's BasicAuth ?

**Comment by ParisNeo** [comment]
I have just finished building the new version of my ollama proxy with multi servers support, multi users, multi keys and with rate limiting and a full dashboard that shows statistics and stuff.



Have fun!

**Comment by flan7** [comment]
Auth with api key is standard for every other provider and requiring a home brewed reverse proxy breaks many endpoints such as home assistant. Home assistant will never be able to add compatibility for ollama auth if every user has a different implementation.

Not adding auth to software you created requiring open ports is just contributing to a terrible greater security ecosystem. You can see this from the vast amount of open ollama instances on the internet. Basic security should not be considered out of scope

**Comment by Cranke** [comment]
"out of scope" to secure an api with authentication?
is it still 1995?
if you want to create a product and not just a toy, you will need auth.

**Comment by ParisNeo** [comment]
The new version of my ollama proxy server is ready for those who need security. it is packed with alot of functionality with an administrative ui, statistics, load balancing and more:

<img width="1898" height="893" alt="Image" src="https://github.com/user-attachments/assets/7c1aca53-ea5c-4411-a901-c6c66b9e952f" />

<img width="1916" height="905" alt="Image" src="https://github.com/user-attachments/assets/c8f14991-8f2d-41ef-a1d2-c4dc27455da0" />

It took me a long time to build, So  hope you find it useful.

[https://github.com/ParisNeo/ollama_proxy_server](https://github.com/ParisNeo/ollama_proxy_server)
