### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by youssef02** [jmorganca/ollama#850]
Is there. A possible way to have manual installation, because I want to download the model from a fast proxy or something similar, the speed for. Mistral is 160 kbit/s, and 4 GB is it hosted on a different server or is it possible to download using a torrent or something that don't limit my download speed, I have WARP to bypass Türkiye IP ban, but the speed is still causing me headache,

can someone tell me what are my options. Here.  Thanks in advance.

**Comment by mchiang0610** [comment]
@youssef02 Ollama library shouldn't limit the download speed. It uses Cloudflare to serve the models at their edge. 

Is there a VPN or some kind of tunnel that you are using?

**Comment by mchiang0610** [comment]
Hi @youssef02 just wanted to follow up on this to see if it's something we can help with

**Comment by pdevine** [comment]
We don't currently use a CDN for the models, but we just did a number of changes to the client which should improve pulling by trying to snag more chunks of the model at once.

I'll close the issue for now, but @youssef02 feel free to re-open or create a new issue if you're still having performance issues.

**Comment by youssef02** [comment]
All good, I think that solved the problem.

Thanks for upgrade.
