### ISSUE TITLE
macOS: Installing CLI from DMG should NOT require administrator privileges

### ISSUE THREAD

**Issue by coolaj86** [jmorganca/ollama#851]
As a matter of security, would you adjust the Mac installer to install to the standard user location of `~/.local/bin/` and not require administrator privileges?

I'm not that familiar with DMG installers, but I can provide shell script examples (or write whatever is needed in full) for ensuring that the executable is installed properly with the correct PATH across the various shells (sh, bash, zsh, fish, etc) without requiring admin privileges.

**Comment by mxyng** [comment]
The macOS app requires superuser privileges once to install a symlink to `/usr/local/bin` which is in the PATH on macOS. `~/.local/bin` isn't in the PATH so it'll require additional configurations to use make ollama work out of the box.

**Comment by gardner** [comment]
I definitely don't want to give administrator access to a random binary that was downloaded off the internet. There are other options for installing a command line tool. I manually symlinked the binary to an appropriate place. Now I can't get passed this screen:

<img width="399" alt="image" src="https://github.com/jmorganca/ollama/assets/787026/34dc8ba8-b026-49de-a2d9-45368047e606">

I understand wanting to make it easy for the LCD but having a way to bypass the screen without giving admin privileges could be a good compromise.

**Comment by BernieCr** [comment]
I also wasn't gonna give give an app administrator privileges that has no good reason to request them.

To get rid of the install screen, you can add the following to `~/Library/Application Support/Ollama/config.json`:
`"first-time-run": true`

But then the app actually has no UI, it just sits in the menu bar. 

I'm curious why you guys needed to implement this whole overhead with an Electron app for this? AFAIK this is just a CLI tool?

**Comment by gardner** [comment]
If you arrived here hoping to be able to install ollama without granting admin privileges then please check out the homebrew package: https://formulae.brew.sh/formula/ollama

**Comment by zberkes** [comment]
It's ridiculous that it needs admin rights. I only want to run it from a command line under my user.

**Comment by iwinux** [comment]
The `ollama` binary for macOS is just 52MB. Bundled with Electron: 400MB+. So much for a menu bar icon 🤣
