### ISSUE TITLE
Use GoReleaser for automated releases?

### ISSUE THREAD

**Issue by coolaj86** [jmorganca/ollama#853]
I am willing to help with this.

I don't see any `.goreleaser.yaml` or `.github/workflows` or any other sort of release automation in the repo.

Most Go projects use GoReleaser and I'm definitely not a hype man, but I'm definitely on the GoReleaser bus, and I'm familiar with the process for setting API tokens in GitHub Actions and could help do something like have a release created when a tag is pushed.

Would you be interested in anything like that?

Even if you don't fully automate it with release-on-tag, using GoReleaser can relieve some of the management burden.

It's also easy to have support for **x86 and ARM macOS builds**.

I have no-nonsense guide on GoReleaser here: https://webinstall.dev/goreleaser

**Comment by mxyng** [comment]
The build for this project is more involved than normal goreleaser project. While it's possible to implement a goreleaser configuration and workflows, the project is changing quickly enough where that will become a hindrance. 

It's a possibility for the future but I'm going to close this issue for now
