### ISSUE TITLE
Manually download and upload models

### ISSUE THREAD

**Issue by dawnpatrol04** [jmorganca/ollama#857]
hey guys.  Having issues getting with this part a work with corporate proxy: docker exec -it ollama ollama run llama2.  

2 issues.  

1) When I set a proxy something breaks.  

2) model  url / cert not allowed / blocked.  To work around this I will need to manually download model files upload to the container.

Can we manually download and upload model files?  Where do I put the model files after I have download them?

**Comment by mxyng** [comment]
You can set `HTTP_PROXY` or `HTTPS_PROXY` when starting the ollama docker container.

```
docker run -d -e HTTP_PROXY -e HTTPS_PROXY ollama/ollama
```

You can also set it globally for all docker contains. See https://docs.docker.com/network/proxy/

**Comment by jmorganca** [comment]
Hi @dawnpatrol04, as @mxyng mentioned this may be from not configuring Ollama to use your http or https proxy. If this doesn't fix the issue please feel free to re-open!

**Comment by reactivetype** [comment]
@dawnpatrol04 @jmorganca  this issue is still not solved. There many open issues about proxy and it'd be great if you provide a way and documentation to download the models manually.

**Comment by nmstoker** [comment]
I second reactivetype's comment. Can this be reopened?

It would be wise to park the proxy point completely and just **confirm if there's a way to download the models manually** as this is often necessary in corporate networks, some of which will have areas where there is literally no internet access allowed.

**Comment by nmstoker** [comment]
I'm guessing the answer may involve putting files in the location here:

https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

I'll see if I can figure it out from common sense and a bit of tinkering

**Comment by dhirajsuvarna** [comment]
did someone figure this out?

**Comment by sven700c** [comment]
> I second reactivetype's comment. Can this be reopened?
> 
> It would be wise to park the proxy point completely and just **confirm if there's a way to download the models manually** as this is often necessary in corporate networks, some of which will have areas where there is literally no internet access allowed.

Exactly this! There is not Internet access allowed at all on the machine I'm trying to run this and other machines only get https access thru a web browser, so setting https_proxy env var for the command line won't help.

**Comment by nmstoker** [comment]
@jmorganca any chance this could be re-opened & looked at again purely in regard to manual downloading of models for the reasons given above?

**Comment by Seedmanc** [comment]
I'm not even in a corporative network and pulling model doesn't work at all. I wish someone made a torrent of a working Ollama installation so I would at least have something to start with, driven by example. Starting from scratch is too hard, not a single model comes with the installer itself.

**Comment by MattFriedman** [comment]
I too and behind a corporate proxy. I've set the http mentioned above env vars and have no luck getting ollama to use my proxy. On the other hand, I can use curl with my proxy to communicate the the external endpoints so for certain the proxy works perfectly. I've tried running in docker, running from the cli and running from the source code. Constantly getting a bad gateway error. 

I would like to download the model manually and put it in the right location if someone knows how to do that.

**Comment by usathyan** [comment]
it downloads the files as manifests and blobs. not easy to do manually. this is a great useless product unfortunately for corporate uses.

**Comment by amirrezaDev1378** [comment]
If anyone did not find a solution for their problem, I've created this simple app that will give you links to download and model in any size you want from the Ollama registry:

https://github.com/amirrezaDev1378/ollama-model-direct-download
