### ISSUE TITLE
Recreating the models pushed on ollama model registry

### ISSUE THREAD

**Issue by avinish1** [jmorganca/ollama#858]
This issue is to understand about the process carried out for creating currently quantized models on the ollama registry like
https://ollama.ai/library/llama2 with any tag,

I have been trying to quantize a llama7b text generation model(https://huggingface.co/meta-llama/Llama-2-7b) from hugging face to have similiar performance to the one currently in ollama model registry.

Issue is the performance of quantized model from hugging face is not anywhere near the one which is in the ollama registry.

I have checked the following things:-

1. Size of both the quantized models is same.
2. I am using the same Modelfile to load the quantized model, this was by using the "Show" command for the llama2:latest model after pulling it.

Are there some more steps involved here to get the quantized model work same/similiar to the one currently already pushed to the registry(llama2:latest).

**Comment by jmorganca** [comment]
Hi @avinish1, these steps are used: https://github.com/jmorganca/ollama/blob/main/docs/import.md. There isn't anything additional – what kind of performance difference are you seeing? Just to confirm, make sure you're using `q4_0` (4 bit quantization) – that's what the default or `latest` tags use (e.g. `ollama run llama2`)

I'll close this for now but feel free to re-open if this doesn't help :)

**Comment by avinish1** [comment]
Thanks @jmorganca , have tried q4_0, let me come up with some examples on this and will reopen if needed.
