### ISSUE TITLE
bug: the `-v` for `--version` should be capital `-V`

### ISSUE THREAD

**Issue by coolaj86** [jmorganca/ollama#860]
I just noticed that there's a typo in the shorthand of the `--version` flag.

big `-V` is for `--version` (little `-v` is for `--verbose`)

**Comment by jmorganca** [comment]
Hi @coolaj86. Thanks for creating an issue! `--verbose` doesn't have a shorthand in this case – and so `-v` is meant to be the shorthand for `--version

**Comment by coolaj86** [comment]
It's not about conflict. It's just that `-V` is the standard - it's what people expect when they use command line tools.

```sh
grep -V
curl -V
ffmpeg -V
python -V
psql -V
shellcheck -V
mysql -V
jq -V
sd -V
fd -V
rg -V
lsd -V
```
