### ISSUE TITLE
ollama downloading something in the background

### ISSUE THREAD

**Issue by abulka** [jmorganca/ollama#866]
Why is ollama downloading? I just did an update and still its downloading something.  Ollama is supposed to be offline - not using up my mobile data.

I can't even figure out which version of ollama I have, there is no CLI command to report the version.
```
M2-Air ~ % ollama   
Large language model runner

Usage:
  ollama [command]

Available Commands:
  serve       Start ollama
  create      Create a model from a Modelfile
  run         Run a model
  pull        Pull a model from a registry
  push        Push a model to a registry
  list        List models
  cp          Copy a model
  rm          Remove a model
  help        Help about any command

Flags:
  -h, --help   help for ollama
```

<img width="651" alt="image" src="https://github.com/jmorganca/ollama/assets/11467530/1fa1756b-9bd1-4b01-b2a4-e016b54d9bc0">

**Comment by jmorganca** [comment]
Hi @abulka. Thanks for the issue (and sorry you encountered this)

The Ollama macOS app will download automatic updates when available. These updates are to add support for new models or bug fixes reported by the community here.

You can manually download the latest version [here](https://ollama.ai/download) to stop it from downloading an update. Recent versions of `ollama` have an `ollama -v` command that will show you which version is running.

Every release also includes a "binary-only" `ollama-darwin` version that doesn't auto update (if this is of interest for any reason). The Mac app is easiest to set up and stay up to date, but it's entirely up to you!

Hope this helps. I'll close this issue for now, but please re-open if you have any more concerns!

**Comment by abulka** [comment]
Thanks for the response.

The background download finally finished and has settled down.  And my `ollama` now has the `ollama -v` feature, as you say, which is good.  A preferences dialog would be handy where I can temporarily stop background updates.

P.S. I just blew my months quota of 50gb mobile data due to Sonoma downloading gb's of scenic flyover screensavers in the background. So I'm on slow data whilst on the road, for the rest of the month - so am a bit sensitive to my internet usage at the moment!
