### ISSUE TITLE
ollama API not responding

### ISSUE THREAD

**Issue by abulka** [jmorganca/ollama#867]
ollama isn't reponding to 
```
curl http://localhost:11434/api/show --json '{"name": "codellama:7b-instruct"}'
404 page not found
```
and I didn't configure ollama to start on a particular port, just a default install.  

I have the models:
```
% ollama list
NAME                    	SIZE  	MODIFIED     
codellama:7b-instruct   	3.8 GB	7 weeks ago 	
llama2:latest           	3.8 GB	2 months ago	
llama2-uncensored:latest	3.8 GB	2 months ago
```

Is there a way of checking what port ollama is running on to verify this?

This API issue is stopping me using `oterm`:
https://github.com/ggozad/oterm/issues/2

**Comment by jmorganca** [comment]
Hi @abulka, I think you may be on an old version of Ollama. Would it be possible to download the [latest version](https://ollama.ai/download)? Will close this issue, but if this is still a problem after updating please don't hesitate to re-open the issue.

**Comment by abulka** [comment]
Yep, latest `ollama` now responds correctly to API calls. Thanks!
