### ISSUE TITLE
API documentation link in the Homepage is broken

### ISSUE THREAD

**Issue by kumarana** [jmorganca/ollama#869]
It shd be https://github.com/jmorganca/ollama/blob/main/docs/api.md

**Comment by jmorganca** [comment]
Thanks for the issue. This is fixed on `main`

**Comment by kumarana** [comment]
Thank you


Kumaran (குமரன்),

CTO, Tiny Magiq

PMP, CITA-D,Chennai

Phone :+91 - 9884016038

[Image]



What is CITA-P?Click here<http://iasaglobal.org/certifications/>

Why CITA-P?Click here<http://certmag.com/five-year-mission-overcoming-challenges-in-pursuit-of-cita-p-certification/>



________________________________
