### ISSUE TITLE
Add flag `--web-root` for serving UI (w/ code example)

### ISSUE THREAD

**Issue by coolaj86** [jmorganca/ollama#874]
```sh
ollama serve --web-root ./ollama-webui/
```

1. Serve `/api/*` to the API
2. For all other requests, return results from the web server
3. If the `--web-root` flag is given, serve that directory for static files (index.html, etc)
4. If `--web-root` is not given, serve an embedded filesystem (i.e. ollama-webui or ollama-ui) \
   See also: https://github.com/ollama-webui/ollama-webui/pull/10.

Here's a tested, working example:

```sh
# serves ./webui/
go run main.go

# serves ./customui/
go run main.go --web-root ./customui/
```

```text
main.go
webui/index.html
customui/index.html
```

```go
package main

import (
	"embed"
	"flag"
	"fmt"
	"io/fs"
	"net/http"
	"os"
)

//go:embed webui/*
var defaultWebRoot embed.FS

func main() {
	var webRoot string
	flag.StringVar(&webRoot, "web-root", "", "serve the given GPT API Web Client")
	flag.Parse()

	mux := http.NewServeMux()

	apiHandler := func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "This is the API route.")
	}

	mux.HandleFunc("/api/", apiHandler)

	var webRootHandler http.Handler
	if len(webRoot) > 0 {
		webRootFs := http.Dir(webRoot)
		webRootHandler = http.FileServer(webRootFs)
	} else {
		webRootFs, err := fs.Sub(defaultWebRoot, "webui")
		if err != nil {
			// panic only because this should be impossible
			panic(err)
		}
		webRootHttpFs := http.FS(webRootFs)
		webRootHandler = http.FileServer(webRootHttpFs)
	}
	mux.Handle("/", webRootHandler)

	port := os.Getenv("PORT")
	if len(port) == 0 {
		port = "8080"
	}
	addr := "0.0.0.0:" + port

	fmt.Println("Serving on ", addr)
	http.ListenAndServe(addr, mux)
}
```

**Comment by coolaj86** [comment]
This would be added right around here:
https://github.com/jmorganca/ollama/blob/ccff9ca09c1fb6709ba4456f0285b97bd5db9599/server/routes.go#L644

The best approach would probably be to change routes.go to return an http-compatible router, and handle the non-API related boilerplate up in the cmd.go rather that sending the TCP listener down into layers that really don't need to be aware of TCP.

**Comment by coolaj86** [comment]
@jmorganca if I create the PR for this will you accept it?

**Comment by coolaj86** [comment]
@mchiang0610 ^^

**Comment by mxyng** [comment]
We're not currently planning on embedding a UI into the project. There are plenty of community projects that add a UI which can be integrated into ollama quickly and easily. See https://github.com/jmorganca/ollama#community-integrations

**Comment by coolaj86** [comment]
@mxyng I think you got this confused with another issue.

This is issue is NOT about embedding a UI.

This is about exposing the existing file server so that an alternative directory can be user-selected as the default page.

Could you please reopen for discussion on this topic?

**Comment by mxyng** [comment]
Sorry if I misunderstood but I'm not sure what "existing Go file server" you're referring to. There's no such server I'm aware of. Moreover, serving user defined files isn't what ollama is designed for and implementing this feature will be counter to ollama's core goals. 

For these reasons, I'm going to keep this issue closed.

**Comment by jmorganca** [comment]
Hi @coolaj86! Thanks so much for this issue. To add to @mxyng's comment, it would be really hard to support all configurations of file servers (e.g. headers, routing etc) to support all the different UIs built on Ollama. Are there changes to the API or `ollama serve` command that could help solve any compatibility issues with UIs (or make them easier to run/deploy together)?

**Comment by coolaj86** [comment]
@jmorganca literally just using the default built-in Go webserver with the existing Gin router is enough.

All of those other things can be left to web proxies and whatnot.

I'm just saying to make it accessible so that anyone can just plop in an index.html and start playing around - without needing to co figure CORS or reverse proxy or start a system service or orchestration layer.

Sure, some people will want to develop things that are very complex and won't work that way -, but I just want to be able to show this off without someone feeling like they have to be a docker expert just to get a page up with a prompt and have that "wow, this can run on my computer - I can build something with this" experience.

As you've probably notice here and in other repos' issues, it's a huge barrier to entry for inexperienced devs that has no technical requirement to be there.
