### ISSUE TITLE
404 page not found when pushing a model with UPPERcase letters

### ISSUE THREAD

**Issue by technovangelist** [jmorganca/ollama#889]
if you create a model, say mattw/HornyEchidna-13b-v0.1 that has uppercase letters in it, then you cannot push it to the registry. The error is:

```
ollama push mattw/HornyEchidna-13b-v0.1
retrieving manifest
pushing c9244955e935...   0% |                                                                                                                      | ( 0 B/7.4 GB) [0s:0s]Error: on upload registry responded with code 404: 404 page not found
```

The problem is that we don't accept a name with uppercase letters, but the error just says the page cannot be found. Super Cryptic!!

**Comment by jmorganca** [comment]
Closing for #336
