### ISSUE TITLE
permissions error on `ollama create` on Linux

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#892]
On Linux, Ollama runs as another `ollama` user. This causes permission errors on `ollama create`.

A fix is in progress, tracked here: https://github.com/jmorganca/ollama/issues/891

In the meantime, current workaround is to add `ollama` to the user's group so Ollama can access group-accessible files:

```
usermod -a -G $(id -gn $USER) ollama
```

Then re-start the `ollama` service

```
sudo systemctl restart ollama
```

**Comment by ClaudiuCeia** [comment]
#613 is reporting the same issue but was closed following a PR to add ollama to user group with apparently no effect. 
The fix suggested in this post doesn't work for me either, only managed to get it working by copying the model to the `/tmp` directory. 

`Linux fedora-laptop 6.5.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 11 04:07:58 UTC 2023 x86_64 GNU/Linux`

**Comment by iplayfast** [comment]
Ongoing bug with fresh install Nov 11
