### ISSUE TITLE
Support more params when ollama run

### ISSUE THREAD

**Issue by UICJohn** [jmorganca/ollama#902]
Hi there,

Thanks for all you have done.

Just wonder if there is any plan to support more params/options for running ollama model? 
For example, --rope-freq-scale 
So that we can run like this 
`ollama run xxxx --rope-freq-scale 0.125`
I can see there is an Options map in api.GenerateRequest but it is not used when running generation

**Comment by mchiang0610** [comment]
Thanks @UICJohn for submitting this. I believe @pdevine is working on improving the command line options within Ollama. He'll have a better take on what it'll exactly look like as the improvements take place.

**Comment by mxyng** [comment]
@pdevine added `/set parameter` in the repl which produces the same results
