### ISSUE TITLE
centos8 use gpu 

### ISSUE THREAD

**Issue by tuoxin126** [jmorganca/ollama#904]
How to make my Centos8 system call GPU. Currently, Ollama can be used, but it calls the CPU. Running olama run llama2 chinese: 13b chat fp16 can directly reply. There is no process for selecting a GPU. I couldn't find the corresponding parameter by looking at the help.
From langchain.llms import Ollama
Llm=Ollama (model="llama2 chinese: 13b chat fp16")
While True:
#Receive user input
Input_ Text=input ("Please enter text (enter 'exit' to exit):")
#Check if you want to exit the loop
If input_ Text. lower()=='exit ':
Break
#Using the predict() method to generate text
Res=llm. predict (input_text)
#Print generated text
Print (res)
Using Python code for testing without selecting the location of the GPU, who knows how to call the GPU
. thanks

**Comment by tuoxin126** [comment]
> @tuoxin126 may I ask what are your system specs to help us look into this?

CentOS Linux release 8.5.2111
Cuda compilation tools, release 11.7, V11.7.64
ollama version 0.1.3

Other algorithm models can call GPU

**Comment by tuoxin126** [comment]
> Ollama

Is it necessary to use Ollama in Docker to use GPU?
No matter how configured, it cannot run on GPU directly under Linux, right？
I hope to dispel doubts. Hard work

**Comment by technovangelist** [comment]
No requirement for docker on Linux. Some just choose to use docker. What gpu do you have?

**Comment by tuoxin126** [comment]
> No requirement for docker on Linux. Some just choose to use docker. What gpu do you have?

NVIDIA A100-SXM

**Comment by tuoxin126** [comment]
> No requirement for docker on Linux. Some just choose to use docker. What gpu do you have?



> No requirement for docker on Linux. Some just choose to use docker. What gpu do you have?

Thank you for your clarification

**Comment by jmorganca** [comment]
Hi @tuoxin126 . Ollama should use the GPU by default. Here's a few things you can try:

* Make sure nvidia drivers are installed. Running `nvidia-smi` should work.
* Try running `ollama run <model>`. Does this use the GPU?

The Linux installer script will install Nvidia drivers if they aren't installed yet:

```
curl https://ollama.ai/install.sh | sh
```

If not it may be something we can look into further to help debug 😊 . I'll close this issue for now but please re-open if above doesn't help

**Comment by tuoxin126** [comment]
> Hi @tuoxin126 . Ollama should use the GPU by default. Here's a few things you can try:
> 
> * Make sure nvidia drivers are installed. Running `nvidia-smi` should work.
> * Try running `ollama run <model>`. Does this use the GPU?
> 
> The Linux installer script will install Nvidia drivers if they aren't installed yet:
> 
> ```
> curl https://ollama.ai/install.sh | sh
> ```
> 
> If not it may be something we can look into further to help debug 😊 . I'll close this issue for now but please re-open if above doesn't help

GPU can be used through curl. Thank you for your reply
