### ISSUE TITLE
Modelfile invalid version

### ISSUE THREAD

**Issue by eduardofarina** [jmorganca/ollama#913]
I've finetuned a llama2 model and applied this step here https://github.com/jmorganca/ollama/blob/main/docs/import.md#step-2-convert-and-quantize-to-a-bin-file-optional-for-pytorch-and-safetensors to generate de q4_0.bin file However my Modelfile that contains `FROM ./q4_0.bin
TEMPLATE "[INST] {{ .Prompt }} [/INST]"` when I run ` ollama create llama_ft -f Modelfile` appear `parsing modelfile
looking for model
⠋ creating model layer  Error: invalid version`

**Comment by mxyng** [comment]
This is likely because the bin file is ggufv3 which is incompatible with ollama version v0.1.3 and earlier. Can you update ollama to the latest version and retry?

**Comment by eduardofarina** [comment]
Thanks, it worked. Only installed it again `curl https://ollama.ai/install.sh | sh`
