### ISSUE TITLE
Cannot download models behind a proxy

### ISSUE THREAD

**Issue by beettlle** [jmorganca/ollama#915]
Seems like #769 doesn't catch all the corner cases when users are behind a proxy. Both @reactivetype and I can reproduce in `0.1.3` and `0.1.5`.

```
$ ollama -v
ollama version 0.1.5
$ ollama pull llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai on xxx.xxx.xxx.xxx:53: read udp xxx.xxx.xxx.xxx:49613->xxxx.xxx.xxx.xxx:53: i/o timeout
$ curl https://registry.ollama.ai/v2/library/llama2/manifests/latest
{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
```

**Comment by mxyng** [comment]
Without divulging private information, can you describe your proxy configurations? e.g. what kind of proxy, how it's set, authentication, etc. It will help immensely with fixing this issue

**Comment by beettlle** [comment]
Sadly I don't know either, it's a black box managed by IT. I do have to set `http_proxy` and `https_proxy` in my shell to get connectivity. My Go is very poor so I could be wrong but I don't see anything in [client.go](https://github.com/jmorganca/ollama/blob/6d283882b16673e42dbe3c068f65271df010de77/api/client.go#L42) where these environment variables are taken into account. 

If that's not valid maybe I see that UDP is mentioned in the error message. I can't quite find why UDP is being used, but I have a feeling that all UDP traffic is blocked.

**Comment by mxyng** [comment]
Thanks for the response. client.go does use HTTP_PROXY and HTTPS_PROXY environment variables through [`http.ProxyFromEnvironment`](https://github.com/jmorganca/ollama/blob/6d283882b16673e42dbe3c068f65271df010de77/api/client.go#L80) and sets the proxy URL in the [`http.Client.Transport`](https://github.com/jmorganca/ollama/blob/6d283882b16673e42dbe3c068f65271df010de77/api/client.go#L87)

**Comment by beettlle** [comment]
Good to know. Mine were in lowercase so I added the uppercase version but it still doesn't work.  

In case it helps I changed the values of the IP to show when they are the same and when they are different.  

```
$ ollama pull llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai on xxx.xxx.xxx.xxx:53: read udp yyy.yyy.yyy.yyy:58915->xxx.xxx.xxx.xxx:53: i/o timeout
$ env | grep -i http
https_proxy=http://zzz.zzz.zzz.zzz:3128
HTTPS_PROXY=http://zzz.zzz.zzz.zzz:3128
HTTP_PROXY=http://zzz.zzz.zzz.zzz:3128
http_proxy=http://zzz.zzz.zzz.zzz:3128
```

**Comment by daaniyaan** [comment]
same thing #689 #676

**Comment by mxyng** [comment]
> Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai on xxx.xxx.xxx.xxx:53: read udp yyy.yyy.yyy.yyy:58915->xxx.xxx.xxx.xxx:53: i/o timeout

Does the proxy server have DNS and can it resolve registry.ollama.ai? A local test using mitmproxy works mostly as expected with just setting `https_proxy` or `HTTPS_PROXY`. I ran into similar errors messages when the mitmproxy container had bad networking configurations and couldn't resolve the ollama.ai hostname.

**Comment by beettlle** [comment]
Interestingly, while `dig` doesn't resolve the domain, I can get to `registry.ollama.ai` with cURL but I'm still getting the error with the ollama CLI. Do you know if the GoLang library you are using doesn't something different than cURL?

```
$ dig registry.ollama.ai
;; communications error to 172.31.160.1#53: timed out
$ curl -I https://registry.ollama.ai
HTTP/1.1 200 Connection established

HTTP/2 404 
content-type: text/plain; charset=utf-8
date: Thu, 02 Nov 2023 15:07:14 GMT
content-length: 9
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
$ curl -s https://registry.ollama.ai | grep -i '<title>'
    <title>Ollama</title>
$ ollama pull llama2
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/latest": dial tcp: lookup registry.ollama.ai on 172.31.160.1:53: read udp 172.31.167.180:35379->172.31.160.1:53: i/o timeout
```

**Comment by dezoito** [comment]
Having the same proxy issues after installing locally.
I suspect the dockerized container had issues  behind the corporate proxy, but it only displayed a generic error message.

It would be cool if the `ollama run` and `ollama pull` commands read `http_proxy` (and related vars) from the environment, or if the proxy could be set via CLI arg or a config file.

**Comment by bblease** [comment]
I am also having this issue. It's specifically HTTP_PROXY. If it's set, I get a "Something went wrong, please see the ollama server logs for more information"

**Comment by dezoito** [comment]
Rebooting my VM and running the install script again solved the problem for some reason.

**Comment by bblease** [comment]
I'm running it a docker container, with no luck. It works with the regular install script. However, I need it in Docker.

**Comment by mxyng** [comment]
Ollama works with forward proxies when configured with `*_PROXY`. Here's the FAQ on how to set it up: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-do-i-use-ollama-behind-a-proxy

**Comment by lfoppiano** [comment]
Following the FAQ and other information and it seems there are some troubles when being behind a proxy: 

```
luca@wanda:~$ HTTPS_PROXY=http://proxyout.nims.go.jp:8888 ollama pull llama2:70b-chat
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama2/manifests/70b-chat": read tcp 144.213.176.192:39158->34.120.132.20:443: read: connection reset by peer
```

I'm not sure where to start to investigating this 😭

**Comment by applepieiris** [comment]
Please refer to this link: [issues1859](https://github.com/ollama/ollama/issues/1859#issuecomment-1989375455)
I solved this in my server(company network which should set proxy to download modles)
