### ISSUE TITLE
Unable to push

### ISSUE THREAD

**Issue by hemanth** [jmorganca/ollama#926]
<img width="1349" alt="image" src="https://github.com/jmorganca/ollama/assets/18315/41f9c107-c2a2-4b1b-a9e3-3e4aa70ddcf0">

I have copied the pub keys to my profile, maybe it is a firewall issue?

**Comment by technovangelist** [comment]
Just commented in the discord. Rename the model to namespace/model. Ollama cp model namespace/model

**Comment by technovangelist** [comment]
This is resolved directly on discord.

**Comment by hemanth** [comment]
Thank you! 

The below worked:

```
ollama create hemanth/booksummarizer -f hemanth/booksummarizer 

ollama push hemanth/booksummarizer
```
