### ISSUE TITLE
FR: Increase prompt size limit on UI

### ISSUE THREAD

**Issue by hemanth** [jmorganca/ollama#929]
<img width="378" alt="image" src="https://github.com/jmorganca/ollama/assets/18315/2bee7056-b101-4430-a0c1-400cff494405">

This is limited to 255 chars only.

**Comment by technovangelist** [comment]
That field is intended to be a high level summary and the full content goes into the larger text box. But we can look into making that a bigger field.

**Comment by technovangelist** [comment]
It looks like that page does not indicate that a full description can also be entered. So unless you know it makes sense to think you need to stuff everything in to 255 chars

**Comment by hemanth** [comment]
<img width="497" alt="image" src="https://github.com/jmorganca/ollama/assets/18315/0591612b-76a7-4c10-b1f5-a47bd6c2a73e">

Ah, it looks like I am not able to edit it in the larger text box too?

**Comment by technovangelist** [comment]
This last comment was resolved in discord but the earlier point still stands

**Comment by jmorganca** [comment]
Hi @hemanth thanks for the issue. Yes, currently summaries are limited to 256 characters just to keep them short and sweet. The overview page has no such limit however and so feel free to add more details there! Please let me know if you have more feedback as well on using ollama.ai 😊
