### ISSUE TITLE
Failed to parse available VRAM: strconv.ParseInt: parsing "[Insufficient Permissions]"

### ISSUE THREAD

**Issue by domWinter** [jmorganca/ollama#932]
Hi,

I am trying to run ollama in a docker container with the nvidia runtime on a system with a Nvidia A100 and MIG enabled.
When starting the ollama server I get the following error:

`2023/10/27 09:16:05 routes.go:682: Warning: GPU support may not enabled, check you have installed install GPU drivers: failed to parse available VRAM: strconv.ParseInt: parsing "[Insufficient Permissions]": invalid syntax`

The ollama server is running as root user.

However, when running nvidia-smi inside the container I see the passed through GPU and MIG device and I am also able to allocate the GPU with e.g. pytorch in the same container.

Cuda Version: 12.2
Nvidia Driver Version: 535.104.12
Docker version 24.0.6, build ed223bc
ollama version 0.1.3

Any help is appreciated!

**Comment by domWinter** [comment]
Seems like the problematic call is:

nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits

Which returns [Insufficient Permissions]

**Comment by BruceMacD** [comment]
Thanks for opening the issue. Looks like the container might need some host level permissions it does not currently have. When you run ollama as the root user in the container it will have sudo permissions in the container, but not externally.

Another workaround is to manually set the `num_gpu` in a modelfile.
