### ISSUE TITLE
Request: Include Embedding Models

### ISSUE THREAD

**Issue by MarcellM01** [jmorganca/ollama#933]
It would be great to have some embedding models as part of the Ollama model collection (such as "all-MiniLM-L6-v2"). Mistral and the others (I have tried) are unfortunately slow to handle embedding tasks for QA retrieval applications.

**Comment by mchiang0610** [comment]
Yes, this is a major pain when working with open source models / tooling today.

**Comment by MarcellM01** [comment]
Do you maybe know if this slowness is universal across all (or most) embedding models that currently run locally? I have limited experience in this field :D.

**Comment by technovangelist** [comment]
Thanks so much for adding this issue. Good small embedding models are definitely an important thing for us to support but there is a duplicate issue #327 that also covers this. So I will go ahead and close this one to make it a bit easier to track. Thanks for being part of this great community.
