### ISSUE TITLE
Low memory systems with a lot of VRAM hit a memory issue

### ISSUE THREAD

**Issue by jmorganca** [jmorganca/ollama#939]
When creating a small instance with <4GB of RAM, `ollama` hits an error when loading the memory into VRAM

**Comment by morandalex** [comment]
I had the same strange issue as informed here https://github.com/jmorganca/ollama/issues/1853

**Comment by jmorganca** [comment]
This should be fixed as of https://github.com/jmorganca/ollama/releases/tag/v0.1.19 with further improvements to CUDA reliability + memory allocation coming. Will close for now, but can re-open if it's persisting
