### ISSUE TITLE
create Sentence Transformer models 

### ISSUE THREAD

**Issue by antonio-castellon** [jmorganca/ollama#963]
Hi Everyone,

Download  and create  a model from Hugginface works like a charm, but the problem is when we are trying to create a transformer model like: **jinaai/jina-embeddings-v2-base-en** or **all-MiniLM-L6-v2.bin**, we are not able to create  amodel to be used for example in langchain like:

```
  ollama = OllamaEmbeddings(base_url=ollama_url,
                              model="jina-embeddings-v2-base-en",
                              temperature=0.0)
```

How we can include new Sentence Transformer model to be used by ollama when embeddings?

Many thanks
Antonio

**Comment by flavioVitoriano** [comment]
Up
