### ISSUE TITLE
problem on last release

### ISSUE THREAD

**Issue by francescoagati** [jmorganca/ollama#970]
hello,
i have notice a big change with last release.
many models in a simple task of summarize become crazy and generate or random words or enter in an infinite loop.
i have do rollback to an old version of ollama

**Comment by jmorganca** [comment]
Hi @francescoagati, I'm sorry you hit this – may I ask:

- Are you on macOS or Linux (or WSL?)
- Which model did you run
- What are your hardware specs?

Thanks – we'll get this fixed

**Comment by jmorganca** [comment]
@francescoagati ok thank you – which langchain integration are you using? Ollama or ChatOllama?

**Comment by francescoagati** [comment]
this is an example of code

`def summarize(llm,docs):

    print("summarize")

    map_custom_prompt='''
        Summarize the following text in a clear and concise way:
        TEXT:`{text}`
        Brief Summary:
    '''
    print("summarize 2")

    map_prompt_template = PromptTemplate (
        input_variables=['text'],
        template=map_custom_prompt
    )

    

    combine_custom_prompt='''
        Generate a summary of the following text that includes the following elements:

        * A title that accurately reflects the content of the text.
        * An introduction paragraph that provides an overview of the topic.
        * Bullet points that list the key points of the text.
        * A conclusion paragraph that summarizes the main points of the text.

        Text:`{text}`
        '''

    combine_prompt_template = PromptTemplate(
        template=combine_custom_prompt,
        input_variables=['text']
    )


    print("load summarize chain")

    chain = load_summarize_chain(llm, 
                                 chain_type='map_reduce',
                                 map_prompt=map_prompt_template,
                                 combine_prompt=combine_prompt_template,
                                 verbose=False
                                 )
    result = chain.run(docs)
    return result

`

**Comment by francescoagati** [comment]
actually i i use 0.0.19 because this script with 0.17 isnt usable

**Comment by jmorganca** [comment]
Hi @francescoagati would it be possible to upgrade to the latest version 0.1.8 and try there? This issue should be fixed. If it’s not feel free to re-open!

**Comment by francescoagati** [comment]
yes now work 
thanks. i close this issue
