### ISSUE TITLE
connect: can't assign requested address & $HOME variable not defined

### ISSUE THREAD

**Issue by tyhallcsu** [jmorganca/ollama#977]
```
% ollama run llama2
Error: Head "http://127.0.0.1:11434/": dial tcp 127.0.0.1:11434: connect: can't assign requested address
```

`/opt/homebrew/var/log/ollama.log`
Log file states:
```
Error: $HOME is not defined
Error: Head "http://127.0.0.1:11434/": dial tcp 127.0.0.1:11434: connect: can't assign requested address
```

But when I run echo $HOME i get 
```
% echo $HOME
/Users/myusername
```

So what do I need to do to fix this? I even checked that the home variable was accessible from CPP enviornment using this script:
```
#include <cstdlib>
#include <iostream>

int main() {
    const char* homeDir = getenv("HOME");
    if (homeDir) {
        std::cout << "The HOME directory is: " << homeDir << std::endl;
    } else {
        std::cout << "The HOME environment variable is not set." << std::endl;
    }
    return 0;
}
```

and it returned my $HOME variable just fine

**Comment by tyhallcsu** [comment]
UPDATE:
I think the issue is that I had the brew version and the .app version installed concurrently and that caused collisions

**Comment by tyhallcsu** [comment]
> UPDATE: I think the issue is that I had the brew version and the .app version installed concurrently and that caused collisions

Nope. Still broken lol

**Comment by igorschlum** [comment]
Hello tyhallcsu,
When I type in terminal (MacOS) 
% ollama run llama2
I get the normal >>>  prompt.
and when I type "http://127.0.0.1:11434/" in Safari, I have the message : Ollama is running
I cannot reproduce the issue you describe.

**Comment by tyhallcsu** [comment]
> Hello tyhallcsu, When I type in terminal (MacOS) % ollama run llama2 I get the normal >>> prompt. and when I type "http://127.0.0.1:11434/* " in Safari, I have the message : Ollama is running I cannot reproduce the issue you describe.

The error log just has "Error: $HOME is not defined"
Is there any reason ollama isnt able to read my env variables?

**Comment by tyhallcsu** [comment]
**Update, I fixed it using this command:**

`sudo ifconfig lo0 alias 127.0.0.1/8`

It was running on 0.0.0.0 only, but not accessible because I didnt have a loopback alias for 127.0.0.1
