### ISSUE TITLE
Uninstall ollama from linux

### ISSUE THREAD

**Issue by sheecegardezi** [jmorganca/ollama#986]
Here's a general guideline on how to uninstall it:

1. Delete the Ollama binary:
   Use the `rm` command to remove the Ollama binary. For example:
   ```
   sudo rm /usr/local/bin/ollama
   ```

2. If the script created a systemd service, disable and remove it:
   If the script created a systemd service for Ollama, you should disable and remove it using the following commands:
   ```
   sudo systemctl stop ollama
   sudo systemctl disable ollama
   sudo rm /etc/systemd/system/ollama.service
   sudo systemctl daemon-reload
   ```

3. Remove any created user and group (if applicable):
   The script might have created a user and group named "ollama." You can remove them using the following commands:
   ```
   sudo userdel ollama
   sudo groupdel ollama
   ```

**Comment by BruceMacD** [comment]
Hi @sheecegardezi, thanks for helping to document this. It's also in our [linux.md](https://github.com/jmorganca/ollama/blob/main/docs/linux.md#uninstall) doc, down at the bottom. 

Resolving this issue now as there is no further work to be done, but it should be useful for other people to see this when they search our issues in the future.

**Comment by Wang-Mer** [comment]
Uninstall ollama from Windows？ @sheecegardezi @BruceMacD

**Comment by BruceMacD** [comment]
@Wang-Mer Ollama can be uninstalled on Windows from the [Programs and Features](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98#:~:text=In%20the%20search%20box%20on,select%20Uninstall%20or%20Uninstall%2FChange.) settings.

**Comment by Wang-Mer** [comment]
> @Wang-Mer Ollama can be uninstalled on Windows from the [Programs and Features](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98#:~:text=In%20the%20search%20box%20on,select%20Uninstall%20or%20Uninstall%2FChange.) settings.

Is there any problem of unclean deletion?

**Comment by BiRo96** [comment]
> Who would want to remove something so great like ollama 😁?

Me, who just solved to make ollama and open-webui in one YAML file, so I can launch it all-in-one with docker-compose and transfer it with it's files to my other computers if I want. But unfortunatelly I installed it directly to my linux computer, without dockerising it :P
That's my reason to remove ollama from my PC's main OS.

**Comment by robmenas** [comment]
> Uninstall ollama from Windows？ @sheecegardezi @BruceMacD

I haven't tested it because I haven't needed to, but wouldn't `winget uninstall --id Ollama.Ollama` be enough?

**Comment by Wang-Mer** [comment]
> > 从 Windows 卸载 ollama？
> 
> @Wang-Mer 我没有测试过，因为我不需要，但这还不够`winget uninstall --id Ollama.Ollama`吗？

I installed it using exe

**Comment by satheshshiva** [comment]
You may need to remove the downloaded models on `/usr/share/ollama`

**Comment by yhw-miracle** [comment]
```bash
#!/bin/bash

sudo rm -v /usr/local/bin/ollama
sudo rm -rv /usr/local/lib/ollama

sudo systemctl stop ollama
sudo systemctl disable ollama
sudo rm -v /etc/systemd/system/ollama.service
sudo systemctl daemon-reload

sudo userdel ollama
sudo groupdel ollama

sudo rm -rv /usr/share/ollama
```

**Comment by disarticulate** [comment]
are we should this is all accurate. I moved ollama into a docker service, after running it on the bare metal linux, and keep seeing it start up even though I replaced the service file et al.

**Comment by ocgg** [comment]
I had to add:
```
rm -rv ~/.ollama
```

> Who would want to remove something so great like ollama 😁?

Especially anyone who wants Vulkan support... https://github.com/ollama/ollama/pull/5059

**Comment by ocgg** [comment]
I had to add:
```
rm -rv ~/.ollama
```

>    Who would want to remove something so great like ollama 😁?

Especially anyone who wants Vulkan support
(oops, I initally mentioned the PR 5059 and saw I uselessly polluted its thread. I deleted my original post but the mention remains. Didn't mean it...)

**Comment by ForwardFeed** [comment]
My installation of ollama probably was made a bit differently
So, i'll show what I had to delete
Unsure if I did not forget anything
```
sudo rm -rv /usr/lib/ollama/
sudo rm -rv /usr/local/lib/ollama

rm -rv .ollama/
```
I also deleted rocm which iirc was needed with AMD chips.
In total this freed 20G from my main partition which I need to keep slim.

**Comment by yuwash** [comment]
Small note: the documentation file has been renamed to [linux.mdx](https://github.com/ollama/ollama/blob/main/docs/linux.mdx#uninstall) but it largely describes the same steps as described above
