### ISSUE TITLE
CLI clear command

### ISSUE THREAD

**Issue by tommyneu** [jmorganca/ollama#989]
The terminal gets a bit cluttered when asking questions. It would be nice if I could clear the terminal with a command. Something like `/clear` to clear the terminal so my next output is a little easier to read or I can clear the output when I'm done asking questions for now.

**Comment by aashish2057** [comment]
Hi I would like to take this on

**Comment by mxyng** [comment]
This is already supported. If you use Ctrl+L, it'll clear the screen. This is a common shortcut for `/clear`

**Comment by tommyneu** [comment]
Ctrl+L is not a shortcut to clear the terminal in all scenarios and it would help more novice terminal users when they see the list of command from `/?`
